'use client';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Gamepad2,X} from 'lucide-react';
import {PognaliArena} from '../crm/PognaliArena';
import './games.css';
type Game='pognali'|'util';
export function GameButton({game,children}:{game:Game;children:React.ReactNode}){
 const [open,setOpen]=useState(false),frame=useRef<HTMLIFrameElement>(null),button=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.focus();const siblings=Array.from(document.body.children).filter((node):node is HTMLElement=>node instanceof HTMLElement&&node!==panel.current),inert=siblings.map(node=>node.inert);siblings.forEach(node=>node.inert=true);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};
 const receive=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow)return;if(game==='util'){if(e.data?.game!=='util-v1')return;if(e.data.type==='exit')setOpen(false);try{if(e.data.type==='ready')frame.current?.contentWindow?.postMessage({game:'util-v1',type:'best',score:Number(localStorage.getItem('avtocena:util-best'))||0},'*');if(e.data.type==='best'&&Number.isSafeInteger(e.data.score)&&e.data.score>=0)localStorage.setItem('avtocena:util-best',String(e.data.score));}catch{}return;}if(e.data?.game!=='pognali-v1')return;const send=(data:object)=>frame.current?.contentWindow?.postMessage({game:'pognali-v1',...data},'*');if(e.data.type==='ready')send({type:'user',user:{name:'Игрок'}});if(e.data.type==='start')send({type:'started',id:crypto.randomUUID()});if(e.data.type==='finish')send({type:'saved',score:Math.floor(e.data.distance)+e.data.coins*25+e.data.kills*500,guest:true});if(e.data.type==='exit')setOpen(false);};
 window.addEventListener('keydown',key);window.addEventListener('message',receive);return()=>{document.body.style.overflow=previous;siblings.forEach((node,i)=>node.inert=inert[i]);window.removeEventListener('keydown',key);window.removeEventListener('message',receive);button.current?.focus();};},[open,game]);
 return <><button ref={button} type="button" className="ac-game-button" onClick={()=>setOpen(true)}><Gamepad2 size={20}/>{children}</button>{open&&createPortal(<div ref={panel} tabIndex={-1} className={`ac-game-overlay ${game==='pognali'?'is-race':'is-util'}`} role="dialog" aria-modal="true" aria-label={game==='pognali'?'Погнали':'Утильсбор'}><div className="ac-game-stage"><iframe ref={frame} src={`/games/${game==='pognali'?'pognali':'util'}.html?v=7`} sandbox="allow-scripts" title={game==='pognali'?'Погнали':'Утильсбор'} referrerPolicy="no-referrer"/><button type="button" className="ac-game-close" aria-label="Закрыть игру" onClick={()=>setOpen(false)}><X/></button></div></div>,document.body)}</>;
}
export function GameButtons({afterLead=false}:{afterLead?:boolean}){return <div className="ac-game-buttons"><GameButton game="pognali">Погнали</GameButton><GameButton game="util">{afterLead?'Старт':'Утильсбор'}</GameButton></div>;}
export function LeadSuccessGames(){return <div className="ac-lead-games"><strong>Есть время сыграть!</strong><p>Пока менеджер обрабатывает заявку.</p><GameButtons afterLead/><a href="/account?mode=register" className="ac-game-account">Войти в кабинет</a></div>;}
export function GamesHub({user,userId}:{user:{name:string;avatar?:string};userId:string}){return <section className="ac-games-hub"><h2><Gamepad2/> Старт</h2><p>Выберите игру для небольшого перерыва.</p><PognaliArena user={user} userId={userId}/><div className="ac-util-cover"><h3>Утильсбор</h3><p>Тетрис автоутилизации</p><GameButton game="util">Играть</GameButton></div></section>;}
