export const user={id:'owner-test',displayName:'Тестовый руководитель',telegramUsername:'test_owner',role:'owner',status:'active'};
export const users=[user,{id:'manager-test',displayName:'Александр Константинопольский',telegramUsername:'test_manager_long',role:'manager',status:'active'}];
export const leads=Array.from({length:8},(_,i)=>({id:'test-'+i,name:'Клиент для проверки '+(i+1),phone:'+79991234567',contactMethod:'phone',car:'Toyota Corolla Cross Hybrid',budgetRub:2250000,status:'new',assignedManagerId:i%2?'manager-test':undefined,clientId:'client-'+i,createdAt:'2026-09-21T05:00:00Z',source:'offer_lead_banner',selectedOffers:[],followups:[]}));
export const getCurrentUser=async()=>user;
export const getAuthUsers=()=>users;
export const isAdminRole=(r:string)=>r==='owner'||r==='admin';
export const isCrmRole=(r:string)=>isAdminRole(r)||r==='manager';
export const readCrmUsers=async()=>users;
export const readDataJson=async(p:string,f:any)=>p==='auth/users.json'?users:p==='leads/leads.json'?leads:p==='clients/clients.json'?leads.map((l,i)=>({...l,id:'client-'+i,fio:l.name})):f;
export const readChunkedDataJson=readDataJson;
export const getActiveDirectPartnerPayout=async()=>({defaultSignedContractPayoutRub:10000});
export const money=(v:number)=>Math.round(v).toLocaleString('ru-RU');
export const markets=['japan','china','korea','uae','europe','georgia'].map((id,i)=>({id,name:['Япония','Китай','Корея','ОАЭ','Европа','Грузия'][i],effectiveVersion:{id:'test-'+id,version:1,currency:'USD',securityDepositRub:160000,topAvtoCommissionRub:90000,logisticsRub:100000}}));
export const getEffectiveMarketsWithDefaults=async()=>markets;
export const calculateCustomerParameterScenario=async()=>({totalRub:null,calculationSnapshot:{missing:['power'],warnings:[]}});
export const isOfficialCustomsCurrencyRate=()=>true;
export const resolveCatalogMarketConfig=()=>({config:{id:'fixture',version:1,currency:'USD',logisticsRub:100000},estimated:false});
export const followupText=()=>'';
export const leadReadState=()=>({seenBy:[],unread:true,eventKey:'test'});
