import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {PriceTrend} from '../../apps/web/components/catalog/PriceTrend';
import {CatalogPrice} from '../../apps/web/components/catalog/CatalogPrice';
import {ConsentCheckbox} from '../../apps/web/components/legal/ConsentCheckbox';
const japanRate={currency:'JPY',sourcePrice:700000,rateSource:'cbr_live',effectiveRate:.6,previousEffectiveRate:.598,rateDate:'2026-10-02',previousRateDate:'2026-10-01'};
const japanOffer={market:'japan',sourceId:'proauctions_japan_stat',totalRub:970371,sourceCurrency:'JPY',sourcePrice:700000,auctionGrade:'4.5',calculationSnapshot:{currencyRate:japanRate}};
function JapanExamples(){return <><section data-japan="preview" style={{width:260}}><CatalogPrice offer={{...japanOffer,japanDeliveredPreview:{totalRub:970371,currencyRate:japanRate}}} label="2017 г." dense/></section><section data-japan="saved" style={{width:260}}><CatalogPrice offer={{...japanOffer,savedCalculationPreview:{totalRub:970371}}} label="2017 г." dense/></section><section data-japan="detail"><PriceTrend offer={japanOffer} panel/></section><section data-japan="historical"><CatalogPrice offer={japanOffer} label="2017 г."/></section></>}
function App(){const [checked,setChecked]=useState(false);return <main style={{maxWidth:760,margin:'auto',padding:20}}><JapanExamples/><ConsentCheckbox checked={checked} onChange={setChecked}/>{[404125,100000].map((sourcePrice,i)=><section key={i} data-car={i} style={{padding:20,marginTop:20}}><PriceTrend panel offer={{totalRub:8811105,sourceCurrency:'CNY',sourcePrice,priceDeltaRub:i?700:-703,calculationSnapshot:{currencyRate:{currency:'CNY',rateSource:'cbr_live',effectiveRate:12.5629,previousEffectiveRate:12.5355,rateDelta:.0274,rateDate:'2026-09-29',previousRateDate:'2026-09-26'}}}}/></section>)}</main>};createRoot(document.getElementById('root')!).render(<App/>);
