import React from 'react';
import {DealerBrowsingProvider} from '../../apps/web/components/dealers/DealerBrowsingContext';
import {hydrateRoot} from 'react-dom/client';
import {renderToString} from 'react-dom/server';
import {DealerLivePreview} from '../../apps/web/components/dealers/DealerLivePreview';
import {BrandLogoRail} from '../../apps/web/components/catalog/BrandLogoRail';
import {CurrencyRatesStrip} from '../../apps/web/components/catalog/CurrencyRatesStrip';
import {PublicLegalFooter} from '../../apps/web/components/layout/PublicLegalFooter';
import {OverlayBackHistory} from '../../apps/web/components/layout/OverlayBackHistory';
import {DealerProfileContent} from '../../apps/web/components/dealers/DealerProfileContent';
import {publicDealerProfile} from '../../apps/web/lib/dealers/public-profile';
import {DealerOfferContent} from '../../apps/web/components/dealers/DealerOfferContent';
import {PublicLeadCaptureV2} from '../../apps/web/components/leads/PublicLeadCaptureV2';
import FavoritesPage from '../../apps/web/app/(public)/favorites/page';
import {SpecTile} from '../../apps/web/components/catalog/OfferSpecTile';
import {publicRail} from '../../apps/web/lib/dealers/public-rail';
import {SpecialRail} from '../../apps/web/components/dealers/SpecialRail';
import {createRoot} from 'react-dom/client';
import {DealerWorkspace} from '../../apps/web/components/dealers/DealerWorkspace';
import {DealerPlatformManager} from '../../apps/web/components/dealers/DealerPlatformManager';
import {PartnerLanding,KnowledgeBase} from '../../apps/web/components/partners/PartnerPages';
import {defaultShowcase} from '../../apps/web/lib/dealers/showcase-model';
import {DEFAULT_PROGRAM} from '../../apps/web/lib/dealers/program-model';
const q=new URLSearchParams(location.search),kind=q.get('view')||(location.pathname.startsWith('/cars/offer/')?'offer':location.pathname==='/favorites'?'favorites':'')||(location.pathname==='/knowledge'?'knowledge':'editor'),s=defaultShowcase('dealer_topavto');s.description=q.has('long')?'Подбор и доставка автомобилей из шести стран. '+('Поможем выбрать автомобиль, проверим его состояние и организуем доставку в ваш город. '.repeat(6)):'Подбор и доставка автомобилей из шести стран.';s.offices=[{id:'office',city:'Новокузнецк',address:'Пример адреса',phone:'',hours:'10:00–19:00',lat:null,lon:null,photos:[]}];
Object.assign(s,JSON.parse(sessionStorage.getItem('fixture-server')||'{}'));
const renderer=kind==='preview-hydration'?null:createRoot(document.getElementById('root')!);
const root={render:(content:React.ReactNode)=>renderer!.render(<><OverlayBackHistory/>{content}</>)};
if(kind==='preview-hydration'){
 const preview=<DealerLivePreview value={s} section="overview" verified fullAccess/>;
 const container=document.getElementById('root')!;
 container.innerHTML=renderToString(preview);
 window.addEventListener('fixture-hydrate',()=>hydrateRoot(container,preview),{once:true});
}else if(kind==='offer'){
 s.name='ТопАвто';
 const stock=q.get('stock')==='1';
 const o={id:'vehicle',status:'published' as const,availability:stock?'stock' as const:'order' as const,condition:'new' as const,officeId:'office',make:'Toyota',model:'RAV4',trim:'2026 2.0L',year:2026,productionMonth:1,engineCc:1987,powerHp:150,power30MinKw:0,fuel:'petrol' as const,transmission:'CVT',drive:'Полный',body:'SUV',color:'Чёрный',steering:'left' as const,mileageKm:0,description:'Автомобиль дилера',equipment:'Климат-контроль',photos:[{id:'p',url:'/buyers/1.jpg',caption:''},{id:'p2',url:'/buyers/2.jpg',caption:''}],priceUsd:34000,priceRub:3000000,customsIncluded:true,customsExtraRub:0,personalUseEligible:true,defaultCity:'Новосибирск',updatedAt:'2026-10-02T08:00:00Z'};
 s.pricing.usdRub=84;s.pricing.rateAt=new Date().toISOString();s.pricing.rateMode='manual';s.specialsEnabled=true;s.stockEnabled=true;s.profileEnabled=true;s.logoLight='/brands/topavto-logo-black.png';s.logoDark='/brands/topavto-logo-black.png';
 root.render(<DealerBrowsingProvider dealer={{id:s.dealerId,name:s.name,logoLight:s.logoLight,logoDark:s.logoDark,href:"/dealers/topavto",preview:false,markets:[]}}><DealerOfferContent id="special_dealer_topavto__vehicle" s={s} o={o} verified={q.get('verified')!=='0'} items={publicRail({...s,offers:[{...o,id:"another-order",availability:"order",make:"Другой",model:"автомобиль",trim:"под заказ с длинным названием комплектации и дополнительным оборудованием"},{...o,id:"another-stock",availability:"stock",make:"Другой",model:"автомобиль",trim:"в наличии",priceRub:2500000}]})} canCopy={q.get('staff')==='1'} canPdf={q.get('staff')==='1'}/><PublicLeadCaptureV2/></DealerBrowsingProvider>);
}else if(kind==='profile'){s.name='ТопАвто';s.banner='/dealers/topavto-banner-v3.webp';if(q.has('mobileBanner'))s.bannerMobile='/buyers/2.jpg';s.requisites={...s.requisites!,legalName:'ООО Тестовый дилер',inn:'7707083893',ogrn:'1027700132195',legalAddress:'Новокузнецк, Пример адреса',bank:'Скрытый банк',account:'40802810926710009905'};s.profileEnabled=true;s.logoLight='/brands/topavto-logo-black.png';s.logoDark=s.logoLight;s.buyersEnabled=true;s.buyerPhotos=Array.from({length:q.has('multi')?12:1},(_,i)=>({id:'p'+i,url:`/buyers/${i+1}.jpg`,caption:''}));if(q.has('multi'))s.extraBanners=Array.from({length:4},(_,i)=>({id:'b'+i,desktop:`/buyers/${i+3}.jpg`,mobile:`/buyers/${i+4}.jpg`}));if(q.has('empty')){s.banner='';s.bannerMobile='';s.logoLight='';s.logoDark='';s.catalogMarkets=[];s.buyerPhotos=[];s.description='';}root.render(<><DealerProfileContent s={publicDealerProfile(s)} verified={q.get('verified')!=='0'} items={q.has('interactive')?[{id:'test',href:'/cars/offer/test',image:'/buyers/1.jpg',title:'Toyota RAV4',price:2000000,city:'Томск'}]:[]} catalog={<><p>Каталог компании</p>{q.has('interactive')&&<div className="ac-catalog-page"><CurrencyRatesStrip rates={[{currency:'JPY',effectiveRate:.6,previousEffectiveRate:.59}]} /><BrandLogoRail brands={['Toyota','BMW','Audi','Honda','Mazda','Lexus','Nissan','Kia']} /><div style={{height:600}}/></div>}</>}/>{q.has('interactive')&&<PublicLegalFooter knowledgeEnabled={q.has('knowledge')}/>}</>);
}else if(kind==='favorites')root.render(<><FavoritesPage/><PublicLeadCaptureV2/></>);
else if(kind==='specs')root.render(<main className="ac-offer-page ac-dealer-offer ac-page-copy p-4"><SpecialRail heading="Спецпредложения" items={[{id:'test',href:'#',image:'/buyers/1.jpg',title:'Toyota RAV4',price:3000000,city:'Томск',heading:'Спецпредложения',subtitle:'От 5 дней — автомобиль у вас дома'}]}/><h2 className="mb-3 text-lg font-bold">Характеристики</h2><div className="grid grid-cols-2 gap-3"><SpecTile showLabel label="Год" value="2026" icon="year"/><SpecTile showLabel label="Двигатель" value="2000 см³" icon="engine"/><SpecTile showLabel label="Пробег" value="Новый" icon="mileage"/><SpecTile showLabel label="Привод" value="Полный" icon="drive"/></div></main>);
else if(kind==='partners')root.render(<PartnerLanding lang={(q.get('lang')||'ru') as any} preview={false} program={DEFAULT_PROGRAM} knowledgeEnabled partnersEnabled/>);
else if(kind==='knowledge')root.render(<KnowledgeBase lang={(q.get('lang')||'ru') as any} preview={false} knowledgeEnabled partnersEnabled initialArticle={q.get("article")||""} initialCategory={q.get("category")||""}/>);
else root.render(<main className="crm-root crm-workspace min-h-screen"><header className="crm-header"><div className="crm-header-inner"><div className="crm-topbar"><a href="/" className="crm-brand"><img src="/logo/avtocena-mark-dark.svg" className="crm-brand-mark" width="36" height="36" alt=""/><span>CRM</span></a></div><nav className="crm-navigation" aria-label="Разделы CRM">{["Обзор","Заявки","Клиенты","Команда","Рынки","Дилеры"].map(x=><a key={x} href="#" aria-current={x==="Дилеры"?"page":undefined}>{x}</a>)}</nav></div></header><div className="crm-content"><div className="crm-page-heading"><h1>{kind==='platform'?'Дилеры':'ТопАвто'}</h1></div>{kind==='platform'?<DealerPlatformManager dealers={[{id:'dealer_topavto',name:'ТопАвто',city:'Новокузнецк',status:'verified'}]} applications={[{id:'app',companyName:'Компания-пример',city:'Шанхай',contactName:'Контакт',status:'new',partnerType:'supplier'}]} initialProgram={DEFAULT_PROGRAM} initialFeatures={{version:0,affiliatesEnabled:true}}/>:<DealerWorkspace verified initial={s} features={{version:0,affiliatesEnabled:true}} owner/>}</div></main>);
