import assert from 'node:assert/strict';import fs from 'node:fs';import http from 'node:http';import {build} from 'esbuild';import postcss from 'postcss';import tailwindcss from 'tailwindcss';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const out='artifacts/games-crm';fs.mkdirSync(out,{recursive:true});
await build({entryPoints:['tests/browser/games-crm-fixture.tsx'],bundle:true,format:'esm',platform:'browser',jsx:'automatic',outfile:`${out}/fixture.js`,tsconfig:'apps/web/tsconfig.json',define:{'process.env.NODE_ENV':'"production"'}});
const css=await postcss([tailwindcss({content:['apps/web/components/**/*.tsx']})]).process('@tailwind base;@tailwind components;@tailwind utilities;',{from:undefined});
const messages=Array.from({length:35},(_,i)=>({id:String(i),text:'Проверка сообщения '+i,author:'Тестовый менеджер',createdAt:'2026-10-10T10:00:00Z'}));
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');
 if(url.pathname==='/api/crm/chat'){res.setHeader('content-type','application/json');return res.end(JSON.stringify(url.searchParams.has('thread')?{id:'lead:test',kind:'lead',title:'Тестовый клиент',canSend:true,canDiscuss:true,leadId:'test',messages,media:[],info:'Тестовые сведения'}:{userId:'staff',team:[],threads:[{id:'lead:test',kind:'lead',title:'Тестовый клиент',subtitle:'Проверка'}]}));}
 if(url.pathname==='/api/crm/discussion'){res.setHeader('content-type','application/json');return res.end(JSON.stringify({messages:[],noticeIds:[]}));}
 if(url.pathname.startsWith('/api/')){res.setHeader('content-type','application/json');return res.end('{}');}
 if(url.pathname==='/fixture.js'){res.setHeader('content-type','text/javascript');return res.end(fs.readFileSync(`${out}/fixture.js`));}
 if(['/games/util.html','/games/pognali.html'].includes(url.pathname)){res.setHeader('content-type','text/html');return res.end(fs.readFileSync('apps/web/public'+url.pathname));}
 res.setHeader('content-type','text/html');res.end(`<!doctype html><html data-theme="light"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css.css}${fs.readFileSync(`${out}/fixture.css`,'utf8')}:root{--ac-surface:#fff;--ac-surface-2:#edf0f5;--ac-text:#17243d;--ac-muted:#657080;--ac-border:#ccd0d6}body{margin:0}main{padding:12px}</style><div id="root"></div><script type="module" src="/fixture.js"></script>`);
});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||undefined,args:['--no-sandbox','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{for(const width of [390,1440]){const page=await browser.newPage({viewport:{width,height:844},isMobile:width<768,hasTouch:width<768});const errors=[],external=[];page.on('pageerror',e=>{errors.push(String(e));console.error('PAGE ERROR',e);});page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});await page.goto(base);
 assert.equal(await page.locator('iframe').count(),0);assert.equal(await page.getByRole('link',{name:'Войти в кабинет'}).getAttribute('href'),'/account?mode=register');
 await page.getByRole('button',{name:'Утильсбор',exact:true}).click();const util=page.frameLocator('iframe[title="Утильсбор"]');await util.locator('#startBtn').click();await util.locator('#startScreen').waitFor({state:'hidden'});await util.locator('#pauseBtn').click();await util.locator('#pauseScreen').waitFor({state:'visible'});await page.screenshot({path:`${out}/util-${width}.png`});await page.getByRole('button',{name:'Закрыть игру',exact:true}).click();assert.equal(await page.locator('iframe').count(),0);
 await page.getByRole('button',{name:'Погнали',exact:true}).first().click();const race=page.frameLocator('iframe[title="Погнали"]');await race.locator('#btnStart').click();await race.locator('#hud.on').waitFor();await race.locator('#stageProgress').waitFor({state:'visible'});await page.screenshot({path:`${out}/race-${width}.png`});await page.getByRole('button',{name:'Закрыть игру',exact:true}).click();
 await page.getByRole('button',{name:'Тестовый клиент Проверка'}).click();const compose=page.getByRole('textbox',{name:'Сообщение клиенту'});await compose.fill('Сохранённый черновик');
 if(width<768){await page.getByRole('dialog',{name:'Тестовый клиент'}).waitFor();await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})));});const box=await compose.boundingBox();assert.ok(box.y+box.height<=844);await page.getByRole('button',{name:'Свернуть чат'}).click();assert.equal(await page.getByRole('dialog',{name:'Тестовый клиент'}).count(),0);await page.getByRole('button',{name:'Тестовый клиент Проверка'}).click();assert.equal(await compose.inputValue(),'Сохранённый черновик');}
 await page.screenshot({path:`${out}/chat-${width}.png`});assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.close();console.log(`games/crm ${width}: passed`);
}}finally{await browser.close();server.close();}
