import React from 'react';import {createRoot} from 'react-dom/client';
import {ChatWorkspace} from '../../apps/web/components/crm/ChatWorkspace';
import {SiteControls} from '../../apps/web/components/site/SiteControls';
import {SitePageAccess} from '../../apps/web/components/site/SitePageAccess';
import {siteVisibilityCss} from '../../apps/web/lib/site-controls';
import {DealerOfferView} from '../../apps/web/components/dealers/DealerOfferView';
import {decodeShareDraft} from '../../apps/web/lib/catalog/offer-share';
import {defaultShowcase} from '../../apps/web/lib/dealers/showcase-model';
const threads=[{id:'notifications',kind:'system' as const,title:'Уведомления',subtitle:'Непрочитанных: 1',updatedAt:''},{id:'lead:test',kind:'lead' as const,title:'Иван',subtitle:'ТопАвто · Toyota',updatedAt:''},{id:'team-test',kind:'team' as const,title:'Мария',subtitle:'Команда',updatedAt:''}];
const s=defaultShowcase('dealer_topavto');s.pricing.usdRub=80;s.pricing.rateAt=new Date().toISOString();s.specialsEnabled=true;
const offer={id:'test',status:'published' as const,make:'Toyota',model:'RAV4',trim:'',year:2026,productionMonth:1,engineCc:2000,powerHp:150,power30MinKw:0,fuel:'petrol' as const,transmission:'Автомат',drive:'Полный',body:'Кроссовер',color:'Белый',steering:'left' as const,mileageKm:0,description:'',equipment:'',photos:[],priceUsd:30000,customsIncluded:true,customsExtraRub:0,personalUseEligible:true,defaultCity:'Москва',updatedAt:new Date().toISOString()};
const mode=new URLSearchParams(location.search).get('mode');
createRoot(document.getElementById('root')!).render(mode==='controls'?<SiteControls initial={{version:0,affiliatesEnabled:true}}/>:mode==='visibility'?<><style>{siteVisibilityCss({siteControls:{catalog:{desktop:true,mobile:false}}})}</style><SitePageAccess><p>Доступный каталог</p></SitePageAccess></>:mode==='offer'?<DealerOfferView id="special_dealer_topavto__test" s={s} o={offer} initialCity={new URLSearchParams(location.search).has("estimate")?decodeShareDraft(new URLSearchParams(location.search).get("estimate")||"")?.deliveryCity||"":undefined}/>:<ChatWorkspace initial={{userId:'owner',threads,team:[{id:'manager',name:'Мария'}]}}/>);
