import { cacheImageFromUrl, stableOfferId } from "./storage";
import { normalizeVehicleOfferSpecs } from "./spec-normalization";
import type { CatalogFetchResult, CatalogImage, CatalogSourceAdapter, OfferStatus, VehicleOffer } from "./types";

type Row = { id:string; url:string; title:string; make:string; model:string; year:number; price?:number; currency?:string; mileageKm?:number; engineCc?:number; powerHp?:number; fuel?:string; transmission?:string; drive?:string; bodyType?:string; color?:string; images:string[] };
const HEADERS = { accept:"text/html,application/xhtml+xml,*/*;q=0.8", "accept-language":"en-US,en;q=0.9", "cache-control":"no-cache", pragma:"no-cache", "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150.0.0.0 Safari/537.36" };
const MAKES = ["Mercedes-Benz","Land Rover","Rolls-Royce","Toyota","Lexus","Nissan","Infiniti","Honda","Mazda","Mitsubishi","Subaru","Suzuki","Hyundai","Genesis","Kia","BMW","Audi","Volkswagen","Volvo","Porsche","Ford","Chevrolet","Cadillac","Jeep","Dodge","Renault","Peugeot","Citroen","Skoda","MINI","BYD","Geely","Changan","Chery","GAC","Haval","Tesla","Jetour","RAM","GMC","Bentley","Lamborghini","Ferrari","Maserati","McLaren"].sort((a,b)=>b.length-a.length);
const BAD_IMAGE = /logo|icon|avatar|qrcode|qr-code|placeholder|banner|related|similar|people-also-viewed|dealer|tracking|pixel|calendar|calender|kilometers|share|email|heart|settings|feature_groups|social|homepage|mobile-mockup/i;
function clean(value:unknown){return String(value||"").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function abs(value:string,base:string){try{return new URL(value.replace(/&amp;/gi,"&").replace(/\\\//g,"/"),base).toString()}catch{return""}}
function integer(value:unknown){const result=Number(String(value||"").replace(/[^0-9]/g,""));return Number.isFinite(result)&&result>0?result:undefined}
async function request(url:string,referer="https://www.dubicars.com/uae/used"){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),Number(process.env.CATALOG_SOURCE_TIMEOUT_MS||35000));try{const response=await fetch(url,{headers:{...HEADERS,referer},redirect:"follow",signal:controller.signal});return{response,markup:await response.text()}}finally{clearTimeout(timer)}}
function makeModel(raw:string){const title=clean(raw).replace(/^\s*(?:19|20)\d{2}\s+/,"").replace(/^used\s+/i,"").trim();const lower=title.toLowerCase();const make=MAKES.find((item)=>lower===item.toLowerCase()||lower.startsWith(`${item.toLowerCase()} `))||"";const model=make?title.slice(make.length).replace(/^\s*[-–—|]\s*/,"").split(/\s+/).slice(0,8).join(" ").trim():"";return{make,model}}
function amount(value:string){const result=integer(value);return result&&result>=1000?result:undefined}
function price(plain:string){const token="([0-9]{1,3}(?:[, ]\\d{3})+|[0-9]{4,7})(?![0-9])";const patterns:Array<[RegExp,string,number]>=[[new RegExp(`(?:AED|د\\.?إ\\.?)\\s*${token}`,"i"),"AED",10000000],[new RegExp(`(?:USD|US\\$|\\$)\\s*${token}`,"i"),"USD",2000000],[new RegExp(`(?:SAR|ر\\.?س\\.?)\\s*${token}`,"i"),"SAR",10000000],[new RegExp(`${token}\\s*(?:AED|د\\.?إ\\.?)`,"i"),"AED",10000000],[new RegExp(`${token}\\s*(?:USD|US\\$)`,"i"),"USD",2000000]];for(const [pattern,currency,maximum] of patterns){const parsed=amount(plain.match(pattern)?.[1]||"");if(parsed&&parsed<=maximum)return{price:parsed,currency}}return{price:undefined,currency:undefined}}
function labeled(plain:string,label:string,next:string[]){const all=[label,...next].map((item)=>item.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"));const match=plain.match(new RegExp(`${all[0]}\\s*[:：]?\\s*([^|•]{1,80}?)(?=\\s+(?:${all.join("|")})\\s*[:：]?|$)`,"i"));return clean(match?.[1])}
function images(markup:string,url:string){const values:string[]=[];for(const match of markup.matchAll(/(?:data-src|data-original|data-lazy-src|src|content|poster)\s*=\s*["']([^"']+)["']/gi))values.push(match[1]);for(const match of markup.matchAll(/(?:srcset|data-srcset)\s*=\s*["']([^"']+)["']/gi))for(const part of match[1].split(","))values.push(part.trim().split(/\s+/)[0]);for(const match of markup.matchAll(/https?:\\?\/\\?\/[^"'<>\s\\]+\.(?:jpe?g|webp)(?:\?[^"'<>\s\\]*)?/gi))values.push(match[0]);const valid=[...new Set(values.map((value)=>abs(value,url)).filter((value)=>value&&!BAD_IMAGE.test(value)&&/\/images\/[a-f0-9]{6}\/(?:w_?\d+x\d+|\d+x\d+|f_?\d+x\d+)\/[^/?#]+\/[a-f0-9-]+\.(?:jpe?g|webp)(?:[?#]|$)/i.test(value)&&!/\/(?:130x76|f_500x282)\//i.test(value)))];const groups=new Map<string,string[]>();for(const value of valid){try{const parsed=new URL(value);const parts=parsed.pathname.split("/").filter(Boolean);const key=`${parsed.hostname}/${parts.slice(0,Math.max(1,parts.length-1)).join("/")}`;groups.set(key,[...(groups.get(key)||[]),value])}catch{}}const best=[...groups.values()].sort((a,b)=>b.length-a.length)[0];return(best&&best.length>=2?best:valid).slice(0,15)}
function parse(markup:string,url:string):Row|null{const plain=clean(markup);const rawTitle=clean(markup.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||markup.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)?.[1]);const title=rawTitle.replace(/\s+(?:19|20)\d{2}\s+for sale.*$/i,"").trim();const parsedName=makeModel(title);const year=Number(`${title} ${plain}`.match(/\b(?:19|20)\d{2}\b/)?.[0]);if(!parsedName.make||!parsedName.model||!year)return null;const parsedPrice=price(plain);const mileageKm=integer(plain.match(/(?:Kilometers?|Mileage)?\s*([0-9][0-9, ]+)\s*Km\b/i)?.[1]);const liters=Number(plain.match(/(?:Engine capacity|Engine)?\s*([0-9]+(?:\.[0-9]+)?)\s*L\b/i)?.[1]||0);const specs=["Fuel Type","Transmission","Drive type","Vehicle type","Color","Model year","Kilometers","Engine capacity","Horsepower"];const photos=images(markup,url);if(!photos.length)return null;return{id:url.match(/-(\d{5,})\.html/i)?.[1]||url,url,title,make:parsedName.make,model:parsedName.model,year,price:parsedPrice.price,currency:parsedPrice.currency,mileageKm,engineCc:liters?Math.round(liters*1000):integer(plain.match(/([0-9][0-9, ]+)\s*cc\b/i)?.[1]),powerHp:integer(plain.match(/(?:Horsepower)?\s*([0-9]{2,4})\s*HP\b/i)?.[1]),fuel:labeled(plain,"Fuel Type",specs),transmission:labeled(plain,"Transmission",specs),drive:labeled(plain,"Drive type",specs),bodyType:labeled(plain,"Vehicle type",specs),color:labeled(plain,"Color",specs),images:photos}}
export class DubicarsCurrentAdapter implements CatalogSourceAdapter{sourceId="dubicars_uae_exact";market="uae" as const;accessMode="public_html" as const;async fetchPage(cursor?:string|null):Promise<CatalogFetchResult>{const page=Math.max(1,Number(cursor||1));const listUrl=`https://www.dubicars.com/uae/used?page=${page}`;const listing=await request(listUrl);if(!listing.response.ok)throw new Error(`dubicars_current_http_${listing.response.status}`);const links=[...new Set([...listing.markup.matchAll(/href=["']([^"']+-\d{5,}\.html)["']/gi)].map((match)=>abs(match[1],listUrl)))].slice(0,40);const rows:Row[]=[];for(let index=0;index<links.length;index+=6){const batch=await Promise.all(links.slice(index,index+6).map(async(url)=>{const detail=await request(url,listUrl).catch(()=>null);return detail?.response.ok?parse(detail.markup,url):null}));rows.push(...batch.filter(Boolean) as Row[])}if(!rows.length)throw new Error("dubicars_current_zero");return{items:rows,nextCursor:String(page+1),finished:false,count:rows.length,health:{ok:true,message:`DubiCars page ${page}: ${rows.length}`,checkedAt:new Date().toISOString(),httpStatus:listing.response.status,contentType:listing.response.headers.get("content-type")||""}}}mapStatus():OfferStatus{return"active"}normalizeOffer(raw:unknown):VehicleOffer|null{const row=raw as Row;if(!row.id||!row.make||!row.model||!row.year||!row.images.length)return null;const now=new Date().toISOString();return normalizeVehicleOfferSpecs({id:stableOfferId(this.sourceId,row.id),sourceId:this.sourceId,sourceOfferId:row.id,market:"uae",offerType:"fixed",status:"active",make:row.make,model:row.model,trim:row.title,year:row.year,mileageKm:row.mileageKm,engineCc:row.engineCc,powerHp:row.powerHp,fuel:row.fuel,transmission:row.transmission,drive:row.drive,bodyType:row.bodyType,color:row.color,sourcePrice:row.price||null,sourceCurrency:row.price?(row.currency||"AED"):null,priceMode:row.price?"fixed":"estimated",images:[],totalRub:null,calculationStatus:row.price?"ready":"needs_data",firstSeenAt:now,updatedAt:now,operational:{sourceUrl:row.url,sourceVenueName:"DubiCars UAE",raw:row}} as VehicleOffer)}async fetchImages(offer:VehicleOffer):Promise<CatalogImage[]>{const row=offer.operational.raw as Row;const limit=Math.max(1,Number(process.env.CATALOG_MAX_IMAGES_PER_OFFER||3));const cached=await Promise.all(row.images.slice(0,limit).map((url)=>cacheImageFromUrl(url,"uae",{headers:{...HEADERS,accept:"image/avif,image/webp,image/apng,image/*,*/*;q=0.8",referer:row.url}}).catch(()=>null)));return cached.filter((image):image is CatalogImage=>Boolean(image&&image.size>8000))}async healthCheck(){return{ok:true,message:"DubiCars current detail pages with real gallery photos",checkedAt:new Date().toISOString()}}}
export const dubicarsUaeCurrentSource=new DubicarsCurrentAdapter();