import { cacheImageFromUrl, stableOfferId } from "./storage";
import { normalizeVehicleOfferSpecs } from "./spec-normalization";
import type { CatalogFetchResult, CatalogImage, CatalogSourceAdapter, OfferStatus, VehicleOffer } from "./types";

type Row = { id:string; url:string; title:string; make:string; model:string; year:number; price?:number; mileageKm?:number; engineCc?:number; powerHp?:number; fuel?:string; transmission?:string; drive?:string; bodyType?:string; images:string[] };
const H={accept:"text/html,application/xhtml+xml,*/*;q=0.8","accept-language":"en-US,en;q=0.9","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150.0.0.0 Safari/537.36"};
const MAKES=["Mercedes-Benz","Land Rover","Rolls-Royce","Toyota","Lexus","Nissan","Infiniti","Honda","Mazda","Mitsubishi","Subaru","Suzuki","Hyundai","Genesis","Kia","BMW","Audi","Volkswagen","Volvo","Porsche","Ford","Chevrolet","Cadillac","Jeep","Dodge","Renault","Peugeot","Citroen","Skoda","MINI","BYD","Geely","Changan","Chery","GAC","Haval","Tesla"].sort((a,b)=>b.length-a.length);
function clean(v:unknown){return String(v||"").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function abs(v:string,b:string){try{return new URL(v.replace(/\\\//g,"/"),b).toString()}catch{return""}}
function num(v:unknown){const n=Number(String(v||"").replace(/[^0-9]/g,""));return Number.isFinite(n)&&n>0?n:undefined}
async function html(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),35000);try{const r=await fetch(url,{headers:H,redirect:"follow",signal:c.signal});return{r,s:await r.text()}}finally{clearTimeout(t)}}
function makeModel(title:string){const lower=title.toLowerCase();const make=MAKES.find(x=>lower===x.toLowerCase()||lower.startsWith(x.toLowerCase()+" "))||"";return{make,model:make?title.slice(make.length).replace(/^\s*[-–—|]\s*/,"").split(/\s+/).slice(0,7).join(" "):""}}
function values(markup:string,label:string){const e=label.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return clean(markup.match(new RegExp(`${e}[\\s\\S]{0,120}?(?:<[^>]+>\\s*)*([^<]{1,80})`,"i"))?.[1]||"")}
function parse(markup:string,url:string):Row|null{const p=clean(markup);const title=clean(markup.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||markup.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)?.[1]);const mm=makeModel(title);const year=Number((title+" "+p).match(/\b(?:19|20)\d{2}\b/)?.[0]);if(!mm.make||!mm.model||!year)return null;const price=num(p.match(/AED\s*([0-9][0-9, ]+)/i)?.[1]);const mileageKm=num(p.match(/([0-9][0-9, ]+)\s*km\b/i)?.[1]);const liters=Number((p.match(/([0-9]+(?:\.[0-9]+)?)\s*L\b/i)?.[1]||"0"));const engineCc=liters?Math.round(liters*1000):num(p.match(/([0-9][0-9, ]+)\s*cc\b/i)?.[1]);const powerHp=num(p.match(/([0-9]{2,4})\s*(?:HP|horsepower)/i)?.[1]);const images=[...new Set([...markup.matchAll(/(?:data-src|data-original|src)=["']([^"']+\.(?:jpg|jpeg|png|webp)(?:\?[^"']*)?)["']/gi)].map(m=>abs(m[1],url)).filter(x=>x&&!/(?:logo|icon|avatar|qrcode|qr-code|placeholder|banner)/i.test(x)))].slice(0,15);if(!images.length)return null;return{id:url.match(/-(\d{5,})\.html/i)?.[1]||url,title,make:mm.make,model:mm.model,year,price,mileageKm,engineCc,powerHp,fuel:values(markup,"Fuel Type"),transmission:values(markup,"Transmission"),drive:values(markup,"Drive Type"),bodyType:values(markup,"Body Type"),images}}
export class DubicarsExactAdapter implements CatalogSourceAdapter{sourceId="dubicars_uae_exact";market="uae" as const;accessMode="public_html" as const;async fetchPage(cursor?:string|null):Promise<CatalogFetchResult>{const page=Math.max(1,Number(cursor||1));const listUrl=`https://www.dubicars.com/uae/used?page=${page}`;const l=await html(listUrl);if(!l.r.ok)throw new Error(`dubicars_http_${l.r.status}`);const links=[...new Set([...l.s.matchAll(/href=["']([^"']+-\d{5,}\.html)["']/gi)].map(m=>abs(m[1],listUrl)))].slice(0,40);const rows:Row[]=[];for(let i=0;i<links.length;i+=6){const batch=await Promise.all(links.slice(i,i+6).map(async u=>{const d=await html(u).catch(()=>null);return d?.r.ok?parse(d.s,u):null}));rows.push(...batch.filter(Boolean) as Row[])}if(!rows.length)throw new Error("dubicars_exact_zero");return{items:rows,nextCursor:String(page+1),finished:false,count:rows.length}}mapStatus():OfferStatus{return"active"}normalizeOffer(raw:unknown):VehicleOffer|null{const x=raw as Row;if(!x.id||!x.images.length)return null;const now=new Date().toISOString();return normalizeVehicleOfferSpecs({id:stableOfferId(this.sourceId,x.id),sourceId:this.sourceId,sourceOfferId:x.id,market:"uae",offerType:"fixed",status:"active",make:x.make,model:x.model,trim:x.title,year:x.year,mileageKm:x.mileageKm,engineCc:x.engineCc,powerHp:x.powerHp,fuel:x.fuel,transmission:x.transmission,drive:x.drive,bodyType:x.bodyType,sourcePrice:x.price||null,sourceCurrency:x.price?"AED":null,priceMode:x.price?"fixed":"estimated",images:[],totalRub:null,calculationStatus:x.price?"ready":"needs_data",firstSeenAt:now,updatedAt:now,operational:{sourceUrl:x.url,sourceVenueName:"DubiCars UAE",raw:x}} as VehicleOffer)}async fetchImages(o:VehicleOffer):Promise<CatalogImage[]>{const x=o.operational.raw as Row;const out:CatalogImage[]=[];for(const u of x.images.slice(0,Number(process.env.CATALOG_MAX_IMAGES_PER_OFFER||10))){const im=await cacheImageFromUrl(u,"uae",{headers:{...H,referer:x.url}}).catch(()=>null);if(im&&im.size>8000)out.push(im)}return out}async healthCheck(){return{ok:true,message:"DubiCars exact detail",checkedAt:new Date().toISOString()}}}
export const dubicarsUaeExactSource=new DubicarsExactAdapter();
