import { cacheImageFromUrl, stableOfferId } from "./storage";
import { normalizeVehicleOfferSpecs } from "./spec-normalization";
import type { CatalogFetchResult, CatalogImage, CatalogSourceAdapter, OfferStatus, VehicleOffer } from "./types";

type Row={id:string;url:string;title:string;make:string;model:string;year:number;price?:number;mileageKm?:number;engineCc?:number;fuel?:string;transmission?:string;drive?:string;bodyType?:string;color?:string;images:string[]};
const H={accept:"text/html,application/xhtml+xml,*/*;q=0.8","accept-language":"en-US,en;q=0.9,ja;q=0.8","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150.0.0.0 Safari/537.36"};
const MAKES=["MERCEDES-BENZ","LAND ROVER","ROLLS-ROYCE","TOYOTA","LEXUS","NISSAN","INFINITI","HONDA","MAZDA","MITSUBISHI","SUBARU","SUZUKI","DAIHATSU","ISUZU","BMW","AUDI","VOLKSWAGEN","PORSCHE","VOLVO","MINI","JEEP","JAGUAR","FORD","CHEVROLET","TESLA","HYUNDAI","KIA"].sort((a,b)=>b.length-a.length);
const SEARCH_MAKES=["TOYOTA","NISSAN","HONDA","MAZDA","MITSUBISHI","SUBARU","SUZUKI","DAIHATSU","LEXUS","BMW","MERCEDES_BENZ","VOLKSWAGEN","AUDI"];
function clean(v:unknown){return String(v||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function abs(v:string,b:string){try{return new URL(v.replace(/\\\//g,"/"),b).toString()}catch{return""}}
function num(v:unknown){const n=Number(String(v||"").replace(/[^0-9]/g,""));return Number.isFinite(n)&&n>0?n:undefined}
async function html(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),35000);try{const r=await fetch(url,{headers:H,redirect:"follow",signal:c.signal});return{r,s:await r.text()}}finally{clearTimeout(t)}}
function parseJsonLd(s:string){const out:any[]=[];for(const m of s.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const v=JSON.parse(m[1]);out.push(...(Array.isArray(v)?v:[v]))}catch{}}return out}
function imageValues(v:any):string[]{if(!v)return[];if(typeof v==="string")return[v];if(Array.isArray(v))return v.flatMap(imageValues);if(typeof v==="object")return imageValues(v.url||v.contentUrl||v.image||v.images);return[]}
function parse(s:string,url:string):Row|null{const p=clean(s);const ld=parseJsonLd(s);const vehicle=ld.find(x=>/vehicle|car|product/i.test(Array.isArray(x?.["@type"])?x["@type"].join(" "):String(x?.["@type"]||"")))||{};const title=clean(vehicle.name||s.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||s.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)?.[1]);const upper=title.toUpperCase();const makeRaw=clean(vehicle.brand?.name||vehicle.brand)||MAKES.find(x=>upper===x||upper.startsWith(x+" "))||"";const make=makeRaw==="MERCEDES_BENZ"?"MERCEDES-BENZ":makeRaw;const model=clean(vehicle.model||title.slice(makeRaw.length)).replace(/^[-–—| ]+/,"").split(/\s+/).slice(0,8).join(" ");const year=Number(String(vehicle.vehicleModelDate||vehicle.modelDate||title+" "+p).match(/(?:19|20)\d{2}/)?.[0]);if(!make||!model||!year)return null;const offer=vehicle.offers||{};const price=num(offer.price)||num(p.match(/(?:FOB|PRICE|US\$|USD|¥)\s*([0-9][0-9, ]+)/i)?.[1]);const mileageKm=num(String(vehicle.mileageFromOdometer?.value||vehicle.mileageFromOdometer||p.match(/([0-9][0-9, ]+)\s*km/i)?.[1]||""));const engineCc=num(String(vehicle.vehicleEngine?.engineDisplacement||p.match(/([0-9][0-9, ]+)\s*cc/i)?.[1]||""));const images=[...new Set([...ld.flatMap(x=>imageValues(x.image||x.images)),...s.matchAll(/(?:data-src|data-original)=["']([^"']+\.(?:jpg|jpeg|png|webp)(?:\?[^"']*)?)["']/gi)].flatMap((x:any)=>typeof x==="string"?[x]:[x[1]]).map(x=>abs(String(x),url)).filter(x=>x&&!/(?:logo|icon|avatar|qrcode|qr-code|placeholder|banner)/i.test(x)))].slice(0,15);if(!images.length)return null;return{id:url.match(/(?:detail\/|[-_/])(\d{6,})(?:\.html|[/?#]|$)/i)?.[1]||url,url,title,make,model,year,price,mileageKm,engineCc,fuel:clean(vehicle.fuelType||p.match(/Fuel\s*[:：]?\s*([^|•]{1,30})/i)?.[1]),transmission:clean(vehicle.vehicleTransmission||p.match(/Transmission\s*[:：]?\s*([^|•]{1,30})/i)?.[1]),drive:clean(vehicle.driveWheelConfiguration||p.match(/Drive\s*[:：]?\s*([^|•]{1,30})/i)?.[1]),bodyType:clean(vehicle.bodyType||vehicle.vehicleConfiguration),color:clean(vehicle.color),images}}
export class GoonetExactAdapter implements CatalogSourceAdapter{sourceId="goonet_japan_exact";market="japan" as const;accessMode="public_html" as const;async fetchPage(cursor?:string|null):Promise<CatalogFetchResult>{const page=Math.max(1,Number(cursor||1));const make=SEARCH_MAKES[(page-1)%SEARCH_MAKES.length];const sub=Math.floor((page-1)/SEARCH_MAKES.length)+1;const urls=[`https://www.goo-net-exchange.com/usedcars/${make}/index-${sub}.html`,`https://www.goo-net-exchange.com/usedcars/${make}/?page=${sub}`];for(const listUrl of urls){const l=await html(listUrl).catch(()=>null);if(!l?.r.ok)continue;const links=[...new Set([...l.s.matchAll(/href=["']([^"']*\/usedcars\/(?:detail\/|[^"']*\d{6,})[^"']*)["']/gi)].map(m=>abs(m[1],listUrl)))].slice(0,40);const rows:Row[]=[];for(let i=0;i<links.length;i+=6){const batch=await Promise.all(links.slice(i,i+6).map(async u=>{const d=await html(u).catch(()=>null);return d?.r.ok?parse(d.s,u):null}));rows.push(...batch.filter(Boolean) as Row[])}if(rows.length)return{items:rows,nextCursor:String(page+1),finished:false,count:rows.length}}throw new Error("goonet_exact_zero")}mapStatus():OfferStatus{return"active"}normalizeOffer(raw:unknown):VehicleOffer|null{const x=raw as Row;if(!x.id||!x.images.length)return null;const now=new Date().toISOString();return normalizeVehicleOfferSpecs({id:stableOfferId(this.sourceId,x.id),sourceId:this.sourceId,sourceOfferId:x.id,market:"japan",offerType:"fixed",status:"active",make:x.make,model:x.model,trim:x.title,year:x.year,mileageKm:x.mileageKm,engineCc:x.engineCc,fuel:x.fuel,transmission:x.transmission,drive:x.drive,bodyType:x.bodyType,color:x.color,sourcePrice:x.price||null,sourceCurrency:x.price?"USD":null,priceMode:x.price?"fixed":"estimated",images:[],totalRub:null,calculationStatus:x.price?"ready":"needs_data",firstSeenAt:now,updatedAt:now,operational:{sourceUrl:x.url,sourceVenueName:"Goo-net Exchange",raw:x}} as VehicleOffer)}async fetchImages(o:VehicleOffer):Promise<CatalogImage[]>{const x=o.operational.raw as Row;const out:CatalogImage[]=[];for(const u of x.images.slice(0,Number(process.env.CATALOG_MAX_IMAGES_PER_OFFER||10))){const im=await cacheImageFromUrl(u,"japan",{headers:{...H,referer:x.url}}).catch(()=>null);if(im&&im.size>8000)out.push(im)}return out}async healthCheck(){return{ok:true,message:"Goo-net exact detail",checkedAt:new Date().toISOString()}}}
export const goonetJapanExactSource=new GoonetExactAdapter();
