import { readChunkedDataJson } from "../data";
import type { VehicleOffer, MarketId } from "./types";
const labels: Record<string,string> = { japan:"Япония", china:"Китай", korea:"Корея", uae:"ОАЭ", europe:"Европа" };
export const marketLabel = (market:string)=> labels[market] || market;
export function getVehicleOffers(){ return readChunkedDataJson<VehicleOffer>("catalog/offers/offers.json", []).filter(isPublicOffer); }
export function getVehicleOffer(id:string){ return getVehicleOffers().find((offer)=>offer.id===id); }
export function isPublicOffer(offer:VehicleOffer){ return offer.availability === "live" && offer.importEligibility !== "blocked" && !!offer.priceLocal && !!offer.year && (!!offer.mileageKm || offer.condition === "new") && (!!offer.engineCc || !!offer.trim) && !!offer.powerHp && !!offer.coverImage && !!offer.sourceUrl && !!offer.calculationSnapshot; }
export function searchVehicleOffers(input:{budgetRub?:number; market?:string; brand?:string; model?:string; yearFrom?:number; body?:string}){
 const budget=input.budgetRub || 0; const brand=input.brand?.toLowerCase(); const model=input.model?.toLowerCase();
 return getVehicleOffers().filter(o=> !input.market||input.market==="any"||o.market===input.market).filter(o=>!brand||o.brand.toLowerCase().includes(brand)).filter(o=>!model||o.model.toLowerCase().includes(model)).filter(o=>!input.yearFrom||o.year>=input.yearFrom).filter(o=>!input.body||input.body==="any"||o.bodyType===input.body).filter(o=>!budget|| (o.calculationSnapshot?.totalRub||0)<=budget*1.18).sort((a,b)=>{ const at=a.calculationSnapshot?.totalRub||0, bt=b.calculationSnapshot?.totalRub||0; const ain=!budget||at<=budget, bin=!budget||bt<=budget; if(ain!==bin) return ain?-1:1; return (b.dataQualityScore-a.dataQualityScore)|| (new Date(b.lastCheckedAt).getTime()-new Date(a.lastCheckedAt).getTime()) || (b.calculationConfidence-a.calculationConfidence); });
}
export function toAvtocenaCase(offer:VehicleOffer){ const total=offer.calculationSnapshot?.totalRub || offer.priceLocal; return { id:offer.id, brand:offer.brand, model:offer.model, title:`${offer.brand} ${offer.model}`, market:offer.market, marketName:marketLabel(offer.market), year:offer.year, body:offer.bodyType||"auto", bodyName:offer.bodyType||"Авто", fuel:offer.fuelType||"не указано", transmission:offer.transmission||"—", drive:offer.drive||"—", powerHp:offer.powerHp||0, engineVolumeCc:offer.engineCc||undefined, mileageKm:offer.mileageKm||undefined, city:offer.location||marketLabel(offer.market), deliveryDays:"45–90", totalRub:total, currency:offer.currency, sourcePrice:offer.priceLocal, tags:[offer.sourceName, offer.availability] as string[], lines:offer.calculationSnapshot?.lines?.map(l=>({...l, kind:(l.id==="car"?"car":"service") as "car" | "service"}))||[], process:["Проверка объявления", "Расчёт", "Подтверждение менеджером"], recommendation:"Реальный пример предложения с зарубежного рынка. Объявление может быть продано. Наличие и итоговую стоимость подтверждает менеджер.", offer }; }
export function getCatalogStaticParams(){ const offers=getVehicleOffers(); return Array.from(new Set(offers.map(o=>o.market))).map(m=>({market:m as MarketId})); }
