import { cacheImageFromUrl, stableOfferId } from "./storage";
import { normalizeVehicleOfferSpecs } from "./spec-normalization";
import type { CatalogFetchResult, CatalogImage, CatalogSourceAdapter, OfferStatus, VehicleOffer } from "./types";

type Row={id:string;url:string;title:string;make:string;model:string;year:number;price?:number;mileageKm?:number;engineCc?:number;powerHp?:number;fuel?:string;transmission?:string;drive?:string;bodyType?:string;color?:string;images:string[]};
const H={accept:"text/html,application/xhtml+xml,*/*;q=0.8","accept-language":"pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150.0.0.0 Safari/537.36"};
const MAKES=["Mercedes-Benz","Land Rover","Rolls-Royce","Alfa Romeo","Aston Martin","Toyota","Lexus","Nissan","Infiniti","Honda","Mazda","Mitsubishi","Subaru","Suzuki","Hyundai","Genesis","Kia","BMW","Audi","Volkswagen","Volvo","Porsche","Ford","Chevrolet","Cadillac","Jeep","Dodge","Renault","Peugeot","Citroen","Skoda","SEAT","MINI","Opel","Fiat","Tesla","Cupra"].sort((a,b)=>b.length-a.length);
function clean(v:unknown){return String(v||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function abs(v:string,b:string){try{return new URL(v.replace(/\\\//g,"/"),b).toString()}catch{return""}}
function num(v:unknown){const n=Number(String(v||"").replace(/[^0-9]/g,""));return Number.isFinite(n)&&n>0?n:undefined}
async function html(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),35000);try{const r=await fetch(url,{headers:H,redirect:"follow",signal:c.signal});return{r,s:await r.text()}}finally{clearTimeout(t)}}
function ld(s:string){const out:any[]=[];const visit=(v:any,d=0)=>{if(v==null||d>8)return;if(Array.isArray(v))return v.forEach(x=>visit(x,d+1));if(typeof v!=="object")return;out.push(v);Object.values(v).forEach(x=>visit(x,d+1))};for(const m of s.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{visit(JSON.parse(m[1]))}catch{}}return out}
function imgs(v:any):string[]{if(!v)return[];if(typeof v==="string")return[v];if(Array.isArray(v))return v.flatMap(imgs);if(typeof v==="object")return imgs(v.url||v.contentUrl||v.image||v.images);return[]}
function parse(s:string,url:string):Row|null{const p=clean(s);const all=ld(s);const car=all.find(x=>/vehicle|car|product/i.test(Array.isArray(x?.["@type"])?x["@type"].join(" "):String(x?.["@type"]||"")))||{};const title=clean(car.name||s.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||s.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)?.[1]);const brand=clean(car.brand?.name||car.brand);const lower=title.toLowerCase();const make=brand||MAKES.find(x=>lower===x.toLowerCase()||lower.startsWith(x.toLowerCase()+" "))||"";const model=clean(car.model||title.slice(make.length)).replace(/^[-–—| ]+/,"").split(/\s+/).slice(0,8).join(" ");const year=Number(String(car.vehicleModelDate||car.modelDate||title+" "+p).match(/(?:19|20)\d{2}/)?.[0]);if(!make||!model||!year)return null;const offer=car.offers||{};const price=num(offer.price)||num(p.match(/([0-9][0-9 .]+)\s*(?:PLN|zł)/i)?.[1]);const mileageKm=num(String(car.mileageFromOdometer?.value||car.mileageFromOdometer||p.match(/([0-9][0-9 .]+)\s*km/i)?.[1]||""));const engineCc=num(String(car.vehicleEngine?.engineDisplacement||p.match(/([0-9][0-9 .]+)\s*cm3/i)?.[1]||""));const powerHp=num(String(car.vehicleEngine?.enginePower||p.match(/([0-9]{2,4})\s*KM\b/i)?.[1]||""));const images=[...new Set([...all.flatMap(x=>imgs(x.image||x.images)),...s.matchAll(/(?:data-src|data-original)=["']([^"']+\.(?:jpg|jpeg|png|webp)(?:\?[^"']*)?)["']/gi)].flatMap((x:any)=>typeof x==="string"?[x]:[x[1]]).map(x=>abs(String(x),url)).filter(x=>x&&!/(?:logo|icon|avatar|qrcode|qr-code|placeholder|banner)/i.test(x)))].slice(0,15);if(!images.length)return null;return{id:url.match(/-ID([A-Za-z0-9]+)\.html/i)?.[1]||url,url,title,make,model,year,price,mileageKm,engineCc,powerHp,fuel:clean(car.fuelType),transmission:clean(car.vehicleTransmission),drive:clean(car.driveWheelConfiguration),bodyType:clean(car.bodyType||car.vehicleConfiguration),color:clean(car.color),images}}
export class OtomotoExactAdapter implements CatalogSourceAdapter{sourceId="otomoto_europe_exact";market="europe" as const;accessMode="public_html" as const;async fetchPage(cursor?:string|null):Promise<CatalogFetchResult>{const page=Math.max(1,Number(cursor||1));const urls=[`https://www.otomoto.pl/osobowe?page=${page}`,`https://www.otomoto.pl/osobowe?search%5Border%5D=created_at_first%3Adesc&page=${page}`];for(const listUrl of urls){const l=await html(listUrl).catch(()=>null);if(!l?.r.ok)continue;const links=[...new Set([...l.s.matchAll(/href=["']([^"']*\/osobowe\/oferta\/[^"']+-ID[A-Za-z0-9]+\.html)["']/gi)].map(m=>abs(m[1],listUrl)))].slice(0,40);const rows:Row[]=[];for(let i=0;i<links.length;i+=6){const batch=await Promise.all(links.slice(i,i+6).map(async u=>{const d=await html(u).catch(()=>null);return d?.r.ok?parse(d.s,u):null}));rows.push(...batch.filter(Boolean) as Row[])}if(rows.length)return{items:rows,nextCursor:String(page+1),finished:false,count:rows.length}}throw new Error("otomoto_exact_zero")}mapStatus():OfferStatus{return"active"}normalizeOffer(raw:unknown):VehicleOffer|null{const x=raw as Row;if(!x.id||!x.images.length)return null;const now=new Date().toISOString();return normalizeVehicleOfferSpecs({id:stableOfferId(this.sourceId,x.id),sourceId:this.sourceId,sourceOfferId:x.id,market:"europe",offerType:"fixed",status:"active",make:x.make,model:x.model,trim:x.title,year:x.year,mileageKm:x.mileageKm,engineCc:x.engineCc,powerHp:x.powerHp,fuel:x.fuel,transmission:x.transmission,drive:x.drive,bodyType:x.bodyType,color:x.color,sourcePrice:x.price||null,sourceCurrency:x.price?"PLN":null,priceMode:x.price?"fixed":"estimated",images:[],totalRub:null,calculationStatus:x.price?"ready":"needs_data",firstSeenAt:now,updatedAt:now,operational:{sourceUrl:x.url,sourceVenueName:"OTOMOTO",raw:x}} as VehicleOffer)}async fetchImages(o:VehicleOffer):Promise<CatalogImage[]>{const x=o.operational.raw as Row;const out:CatalogImage[]=[];for(const u of x.images.slice(0,Number(process.env.CATALOG_MAX_IMAGES_PER_OFFER||10))){const im=await cacheImageFromUrl(u,"europe",{headers:{...H,referer:x.url}}).catch(()=>null);if(im&&im.size>8000)out.push(im)}return out}async healthCheck(){return{ok:true,message:"OTOMOTO exact detail",checkedAt:new Date().toISOString()}}}
export const otomotoEuropeExactSource=new OtomotoExactAdapter();
