import { cacheImageFromUrl, stableOfferId } from "./storage";
import { normalizeVehicleOfferSpecs } from "./spec-normalization";
import type { CatalogFetchResult, CatalogImage, CatalogSourceAdapter, OfferStatus, VehicleOffer } from "./types";

type Row = { id:string; url:string; title:string; make:string; model:string; year:number; price?:number; mileageKm?:number; engineCc?:number; powerHp?:number; fuel?:string; transmission?:string; drive?:string; bodyType?:string; color?:string; images:string[] };
const H = { accept:"text/html,application/xhtml+xml,*/*;q=0.8", "accept-language":"pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7", "cache-control":"no-cache", pragma:"no-cache", "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/150.0.0.0 Safari/537.36" };
const MAKES = ["Mercedes-Benz","Land Rover","Rolls-Royce","Alfa Romeo","Aston Martin","Toyota","Lexus","Nissan","Infiniti","Honda","Mazda","Mitsubishi","Subaru","Suzuki","Hyundai","Genesis","Kia","BMW","Audi","Volkswagen","Volvo","Porsche","Ford","Chevrolet","Cadillac","Jeep","Dodge","Renault","Peugeot","Citroen","Skoda","SEAT","MINI","Opel","Fiat","Tesla","Cupra","BYD","MG","Omoda"].sort((a,b)=>b.length-a.length);
const BAD = /(?:logo|icon|avatar|qrcode|qr-code|placeholder|banner|seller|dealer|tracking|pixel|last-slide|cta)/i;
function clean(v:unknown){return String(v||"").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function abs(v:string,b:string){try{return new URL(v.replace(/\\\//g,"/"),b).toString()}catch{return""}}
function num(v:unknown){const n=Number(String(v||"").replace(/[^0-9]/g,""));return Number.isFinite(n)&&n>0?n:undefined}
async function html(url:string,referer="https://www.otomoto.pl/osobowe"){const c=new AbortController();const t=setTimeout(()=>c.abort(),Number(process.env.CATALOG_SOURCE_TIMEOUT_MS||35000));try{const r=await fetch(url,{headers:{...H,referer},redirect:"follow",signal:c.signal});return{r,s:await r.text()}}finally{clearTimeout(t)}}
function makeModel(title:string){const normalized=clean(title).replace(/^Używany\s+/i,"");const lower=normalized.toLowerCase();const make=MAKES.find(x=>lower===x.toLowerCase()||lower.startsWith(`${x.toLowerCase()} `))||"";return{make,model:make?normalized.slice(make.length).trim().split(/\s+/).slice(0,8).join(" "):""}}
function imageUrls(markup:string,url:string){const values:string[]=[];for(const m of markup.matchAll(/(?:data-src|data-original|data-lazy-src|src)=["']([^"']+)["']/gi))values.push(m[1]);for(const m of markup.matchAll(/(?:srcset|data-srcset)=["']([^"']+)["']/gi))for(const part of m[1].split(","))values.push(part.trim().split(/\s+/)[0]);for(const m of markup.matchAll(/https?:\\?\/\\?\/[^"'\\\s<>]+?\.(?:jpe?g|png|webp)(?:\?[^"'\\\s<>]*)?/gi))values.push(m[0].replace(/\\\//g,"/"));return[...new Set(values.map(v=>abs(v,url)).filter(v=>v&&/\.(?:jpe?g|png|webp)(?:[?#]|$)/i.test(v)&&!BAD.test(v)))].slice(0,20)}
function fuel(text:string){return /Hybryda Plug-in|PHEV/i.test(text)?"phev":/Hybryda|hybrid/i.test(text)?"hybrid":/Diesel|Olej napędowy/i.test(text)?"diesel":/Elektrycz/i.test(text)?"electric":/Benzyna/i.test(text)?"petrol":""}
function transmission(text:string){return /Automatyczna/i.test(text)?"automatic":/Manualna/i.test(text)?"manual":""}
function body(text:string){return /SUV|Crossover/i.test(text)?"suv":/Kombi/i.test(text)?"wagon":/Hatchback|Auta miejskie/i.test(text)?"hatchback":/Coupe/i.test(text)?"coupe":/Kabriolet/i.test(text)?"convertible":/Sedan|Limuzyna/i.test(text)?"sedan":""}
function listRows(markup:string,listUrl:string){const anchors=[...markup.matchAll(/<a\b[^>]*href=["']([^"']*\/osobowe\/oferta\/[^"']+-ID[A-Za-z0-9]+\.html[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi)];const rows:Row[]=[];const seen=new Set<string>();for(let i=0;i<anchors.length;i++){const a=anchors[i];const url=abs(a[1],listUrl);if(!url||seen.has(url))continue;const start=Math.max(0,(a.index||0)-4500);const end=Math.min(markup.length,(a.index||0)+10000);const card=markup.slice(start,end);const title=clean(a[2])||clean(card.match(/<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>/i)?.[1])||clean(card.match(/<img[^>]+alt=["']([^"']+)/i)?.[1]);const mm=makeModel(title);const plain=clean(card);const year=Number(plain.match(/(?:year\s*)?\b((?:19|20)\d{2})\b/i)?.[1]);if(!mm.make||!mm.model||!year)continue;const id=url.match(/-ID([A-Za-z0-9]+)\.html/i)?.[1]||stableOfferId("otomoto",url);seen.add(url);rows.push({id,url,title,make:mm.make,model:mm.model,year,price:num(plain.match(/([0-9][0-9 .]{2,})\s*PLN/i)?.[1]),mileageKm:num(plain.match(/([0-9][0-9 .]{1,})\s*km/i)?.[1]),engineCc:num(plain.match(/([0-9][0-9 .]{2,})\s*cm3/i)?.[1]),powerHp:num(plain.match(/([0-9]{2,4})\s*KM\b/i)?.[1]),fuel:fuel(plain),transmission:transmission(plain),drive:/4x4|AWD|4-Matic|quattro|xDrive/i.test(plain)?"awd":"",bodyType:body(plain),images:imageUrls(card,listUrl)})}return rows}
function objects(markup:string){const all:any[]=[];const visit=(v:any,d=0)=>{if(v==null||d>9)return;if(Array.isArray(v)){v.forEach(x=>visit(x,d+1));return}if(typeof v!=="object")return;all.push(v);Object.values(v).forEach(x=>visit(x,d+1))};for(const m of markup.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{visit(JSON.parse(m[1]))}catch{}}return all}
function imageObject(v:any):string[]{if(!v)return[];if(typeof v==="string")return[v];if(Array.isArray(v))return v.flatMap(imageObject);if(typeof v==="object")return imageObject(v.url||v.contentUrl||v.image||v.images);return[]}
function detailRow(markup:string,url:string,fallback?:Row):Row|null{const plain=clean(markup);const all=objects(markup);const car=all.find(x=>/vehicle|car|product/i.test(Array.isArray(x?.["@type"])?x["@type"].join(" "):String(x?.["@type"]||"")))||{};const title=clean(car.name||markup.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||fallback?.title);const brand=clean(car.brand?.name||car.brand);const mm=makeModel(title);const make=brand||mm.make||fallback?.make||"";const model=clean(car.model)||mm.model||fallback?.model||"";const year=Number(String(car.vehicleModelDate||car.modelDate||title+" "+plain).match(/(?:19|20)\d{2}/)?.[0]||fallback?.year);if(!make||!model||!year)return fallback||null;const offer=car.offers||{};const images=[...new Set([...all.flatMap(x=>imageObject(x.image||x.images)),...imageUrls(markup,url)].map(x=>abs(String(x),url)).filter(x=>x&&!BAD.test(x)))].slice(0,20);return{id:url.match(/-ID([A-Za-z0-9]+)\.html/i)?.[1]||fallback?.id||url,url,title,make,model,year,price:num(offer.price)||num(plain.match(/([0-9][0-9 .]+)\s*(?:PLN|zł)/i)?.[1])||fallback?.price,mileageKm:num(String(car.mileageFromOdometer?.value||car.mileageFromOdometer||plain.match(/([0-9][0-9 .]+)\s*km/i)?.[1]||""))||fallback?.mileageKm,engineCc:num(String(car.vehicleEngine?.engineDisplacement||plain.match(/([0-9][0-9 .]+)\s*cm3/i)?.[1]||""))||fallback?.engineCc,powerHp:num(String(car.vehicleEngine?.enginePower||plain.match(/([0-9]{2,4})\s*KM\b/i)?.[1]||""))||fallback?.powerHp,fuel:clean(car.fuelType)||fuel(plain)||fallback?.fuel,transmission:clean(car.vehicleTransmission)||transmission(plain)||fallback?.transmission,drive:clean(car.driveWheelConfiguration)||(/4x4|AWD|4-Matic|quattro|xDrive/i.test(plain)?"awd":"")||fallback?.drive,bodyType:clean(car.bodyType||car.vehicleConfiguration)||body(plain)||fallback?.bodyType,color:clean(car.color)||fallback?.color,images:images.length?images:fallback?.images||[]}}

export class OtomotoExactAdapter implements CatalogSourceAdapter{
  sourceId="otomoto_europe_exact";market="europe" as const;accessMode="public_html" as const;
  async fetchPage(cursor?:string|null):Promise<CatalogFetchResult>{const page=Math.max(1,Number(cursor||1));const urls=[`https://www.otomoto.pl/osobowe?page=${page}`,`https://www.otomoto.pl/osobowe?search%5Border%5D=created_at_first%3Adesc&page=${page}`];for(const listUrl of urls){const l=await html(listUrl).catch(()=>null);if(!l?.r.ok)continue;const listed=listRows(l.s,listUrl).slice(0,40);if(!listed.length)continue;const rows:Row[]=[];for(let i=0;i<listed.length;i+=6){const batch=await Promise.all(listed.slice(i,i+6).map(async row=>{const d=await html(row.url,listUrl).catch(()=>null);return d?.r.ok?detailRow(d.s,row.url,row):row}));rows.push(...batch.filter(Boolean) as Row[])}if(rows.length)return{items:rows,nextCursor:String(page+1),finished:false,count:rows.length}}throw new Error("otomoto_exact_zero")}
  mapStatus():OfferStatus{return"active"}
  normalizeOffer(raw:unknown):VehicleOffer|null{const x=raw as Row;if(!x.id||!x.make||!x.model||!x.year)return null;const now=new Date().toISOString();return normalizeVehicleOfferSpecs({id:stableOfferId(this.sourceId,x.id),sourceId:this.sourceId,sourceOfferId:x.id,market:"europe",offerType:"fixed",status:"active",make:x.make,model:x.model,trim:x.title,year:x.year,mileageKm:x.mileageKm,engineCc:x.engineCc,powerHp:x.powerHp,fuel:x.fuel,transmission:x.transmission,drive:x.drive,bodyType:x.bodyType,color:x.color,sourcePrice:x.price||null,sourceCurrency:x.price?"PLN":null,priceMode:x.price?"fixed":"estimated",images:[],totalRub:null,calculationStatus:x.price?"ready":"needs_data",firstSeenAt:now,updatedAt:now,operational:{sourceUrl:x.url,sourceVenueName:"OTOMOTO",raw:x}} as VehicleOffer)}
  async fetchImages(o:VehicleOffer):Promise<CatalogImage[]>{const x=o.operational.raw as Row;let urls=x.images||[];if(urls.length<3){const d=await html(x.url,x.url).catch(()=>null);if(d?.r.ok)urls=detailRow(d.s,x.url,x)?.images||urls}const results=await Promise.all([...new Set(urls)].slice(0,Number(process.env.CATALOG_MAX_IMAGES_PER_OFFER||10)).map(u=>cacheImageFromUrl(u,"europe",{headers:{...H,referer:x.url}}).catch(()=>null)));return results.filter((im):im is CatalogImage=>Boolean(im&&im.size>8000))}
  async healthCheck(){return{ok:true,message:"OTOMOTO listing plus exact detail",checkedAt:new Date().toISOString()}}
}
export const otomotoEuropeExactSource=new OtomotoExactAdapter();
