import type { VehicleOffer } from "./types";
import { isPublicOffer } from "./index";
import { calculateOfferSnapshot } from "./calculation";
import { validatePublishableOffer } from "./validation";
export function deduplicateOffers(offers: VehicleOffer[]){ const seen=new Set<string>(); const out:VehicleOffer[]=[]; for(const o of offers){ const keys=[`${o.source}:${o.sourceListingId}`, o.sourceUrl, `${o.brand}:${o.model}:${o.year}:${o.mileageKm}:${o.priceLocal}:${o.sellerType}`].filter(Boolean); if(keys.some(k=>seen.has(k))) continue; keys.forEach(k=>seen.add(k)); out.push(o); } return out; }
export function validateOffer(offer: VehicleOffer): VehicleOffer { const reasons=[...offer.eligibilityReasons]; let availability=offer.availability; const publication=validatePublishableOffer(offer); if(!publication.ok){ availability="needs_review"; reasons.push(...publication.reasons); } if(!offer.advertisedPower && !offer.icePowerHp && !offer.systemPowerHp){ availability="needs_review"; reasons.push("Power is unknown and must not be guessed."); } if(offer.importEligibility==="blocked") availability="blocked"; return {...offer, availability, eligibilityReasons:Array.from(new Set(reasons))}; }
export function recalculateOffer(offer: VehicleOffer, asOf = new Date()): VehicleOffer { const snapshot=calculateOfferSnapshot(offer, asOf); if(!snapshot) return validateOffer({...offer, calculationSnapshot: undefined, calculationStatus:"needs_review", calculationComplete:false, calculationConfidence:"needs_review"}); const complete=snapshot.complete === true; return validateOffer({...offer, calculationSnapshot:snapshot, calculationStatus:complete ? "complete" : "estimate_incomplete", calculationComplete: complete, calculationConfidence: complete ? "medium" : "needs_review"}); }
export function publishableOffers(offers: VehicleOffer[]){ return deduplicateOffers(offers.map((offer)=>validateOffer(offer))).filter(isPublicOffer); }
export function expireStaleOffers(offers:VehicleOffer[], now=new Date(), staleDays=14){ const ms=staleDays*864e5; return offers.map(o=> now.getTime()-new Date(o.lastCheckedAt).getTime()>ms ? {...o, availability:"stale" as const, listingStatus:"stale" as const}:o); }
