import { cacheImageFromUrl, stableOfferId } from "./storage";
import { normalizeVehicleOfferSpecs } from "./spec-normalization";
import type { CatalogFetchResult, CatalogImage, CatalogMarket, CatalogSourceAdapter, OfferStatus, VehicleOffer } from "./types";

export type ScopedSourceConfig = {
  sourceId: string;
  market: CatalogMarket;
  label: string;
  baseUrl: string;
  currency: string;
  listUrls: (page: number) => string[];
  detailPattern: RegExp;
  forcedCharset?: string;
  referer?: string;
};

type Row = { id: string; detailUrl: string; title: string; year: number; make: string; model: string; price?: number; currency: string; mileageKm?: number };
const HEADERS = { accept: "text/html,application/xhtml+xml,application/json;q=0.9,image/avif,image/webp,*/*;q=0.8", "accept-language": "en-US,en;q=0.9,ru;q=0.8,zh-CN;q=0.7,ja;q=0.6", "cache-control": "no-cache", pragma: "no-cache", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36" };
const BAD_IMAGE = /(?:logo|favicon|icon|sprite|banner|placeholder|avatar|tracking|pixel|cookie|qrcode|qr-code|qr_|weixin|wechat|scan|download[-_]?app|appstore|googleplay|no[-_ ]?photo|no[-_ ]?image|loading)/i;
const NON_VEHICLE = /(?:news|article|review|blog|magazine|motorcycle|scooter|forklift|excavator|tractor|generator|spare parts|autoteile)/i;
const MAKES = ["Mercedes-Benz","Mercedes Benz","Land Rover","Range Rover","Rolls-Royce","Alfa Romeo","Aston Martin","Great Wall","Li Auto","Toyota","Lexus","Nissan","Infiniti","Honda","Acura","Mazda","Mitsubishi","Subaru","Suzuki","Daihatsu","Isuzu","Hyundai","Genesis","Kia","KGM","SsangYong","BMW","Audi","Volkswagen","Volvo","Porsche","Ford","Chevrolet","Cadillac","Jeep","Dodge","Renault","Peugeot","Citroen","Skoda","SEAT","MINI","BYD","Geely","Changan","Chery","GAC","Haval","Zeekr","Nio","XPeng","Jetour","Denza","Rox","Opel","Fiat","Tesla","Cupra","MG"].sort((a,b)=>b.length-a.length);
const CN: Array<[RegExp,string]> = [[/雷克萨斯/g,"Lexus"],[/梅赛德斯[-·]?奔驰|奔驰/g,"Mercedes-Benz"],[/宝马/g,"BMW"],[/奥迪/g,"Audi"],[/大众/g,"Volkswagen"],[/丰田/g,"Toyota"],[/本田/g,"Honda"],[/日产/g,"Nissan"],[/马自达/g,"Mazda"],[/三菱/g,"Mitsubishi"],[/斯巴鲁/g,"Subaru"],[/现代/g,"Hyundai"],[/起亚/g,"Kia"],[/沃尔沃/g,"Volvo"],[/保时捷/g,"Porsche"],[/福特/g,"Ford"],[/雪佛兰/g,"Chevrolet"],[/凯迪拉克/g,"Cadillac"],[/路虎/g,"Land Rover"],[/特斯拉/g,"Tesla"],[/比亚迪/g,"BYD"],[/吉利/g,"Geely"],[/长安/g,"Changan"],[/奇瑞/g,"Chery"],[/哈弗/g,"Haval"],[/广汽/g,"GAC"],[/理想/g,"Li Auto"],[/蔚来/g,"Nio"],[/小鹏/g,"XPeng"],[/极氪/g,"Zeekr"],[/捷途/g,"Jetour"],[/腾势/g,"Denza"],[/名爵/g,"MG"]];

function clean(value: unknown) { return String(value ?? "").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/[\u0000-\u001f]+/g," ").replace(/\s+/g," ").trim(); }
function absolute(value: unknown, base: string) { const raw=String(value||"").replace(/\\\//g,"/").replace(/&amp;/gi,"&").trim(); if(!raw||/^(?:data:|javascript:|mailto:|tel:)/i.test(raw)) return ""; try{return new URL(raw,base).toString();}catch{return "";} }
function validImage(url:string){return /^https?:/i.test(url)&&!BAD_IMAGE.test(url)&&/(?:\.(?:jpe?g|png|webp|avif)(?:[?#]|$)|\/image\/|\/images\/|\/photo\/|\/photos\/|autoimg|alicdn|cloudfront)/i.test(url);}
function integer(value:unknown){const n=Number(String(value??"").replace(/[^0-9]/g,""));return Number.isFinite(n)&&n>0?n:undefined;}
function decimal(value:unknown){const n=Number(String(value??"").replace(/[^0-9.]/g,""));return Number.isFinite(n)&&n>0?n:undefined;}
function yearOf(value:unknown){const n=Number(String(value||"").match(/(?:19|20)\d{2}/)?.[0]);return n>=1985&&n<=new Date().getFullYear()+1?n:0;}
function normalizedTitle(value:string){let t=clean(value);for(const [p,r] of CN)t=t.replace(p,`${r} `);return t.replace(/二手车|准新车|新车|在售|报价|图片|详情/g," ").replace(/\s+/g," ").trim();}
function makeModel(value:string){const title=normalizedTitle(value).replace(/^(?:used|new|gebraucht|neu|premium|promoted|featured)\s+/i,"").replace(/^(?:19|20)\d{2}\s+/,"").trim();const lower=title.toLowerCase();const found=MAKES.find(m=>lower===m.toLowerCase()||lower.startsWith(`${m.toLowerCase()} `));if(found){const make=found==="Mercedes Benz"?"Mercedes-Benz":found;const rest=title.slice(found.length).replace(/^[-–—·|\s]+/,"").trim();return{make,model:rest.split(/\s+/).slice(0,5).join(" ")||make,title};}const p=title.split(/\s+/).filter(Boolean);return{make:p[0]||"",model:p.slice(1,6).join(" ")||p[0]||"",title};}
function priceOf(value:string,currency:string){const wan=value.match(/(?:￥|¥|RMB|CNY)?\s*([0-9]+(?:[.,][0-9]+)?)\s*万(?:元)?/i);if(wan)return{price:Math.round(Number(wan[1].replace(",","."))*10000),currency:"CNY"};const patterns:Array<[RegExp,string]>=[[/\bAED\s*([0-9][0-9 ,.']{2,})/i,"AED"],[/(?:USD|US\$|\$)\s*([0-9][0-9 ,.']{2,})/i,"USD"],[/(?:EUR|€)\s*([0-9][0-9 ,.']{2,})/i,"EUR"],[/(?:JPY|JP¥|円|¥)\s*([0-9][0-9 ,.']{2,})/i,"JPY"],[/(?:CNY|RMB|CN¥|￥)\s*([0-9][0-9 ,.']{2,})/i,"CNY"]];for(const [p,c] of patterns){const n=integer(value.match(p)?.[1]);if(n)return{price:n,currency:c};}return{price:undefined,currency};}
function mileageOf(value:string){const wan=value.match(/([0-9]+(?:[.,][0-9]+)?)\s*万\s*(?:公里|km)?/i);if(wan)return Math.round(Number(wan[1].replace(",","."))*10000);return integer(value.match(/([0-9]{1,3}(?:[ ,.'][0-9]{3})+|[0-9]{2,7})\s*(?:km|公里|キロ)/i)?.[1]);}
function embedded(html:string){const out:any[]=[];const visit=(v:any,d=0)=>{if(v==null||d>10)return;if(Array.isArray(v))return v.forEach(x=>visit(x,d+1));if(typeof v!=="object")return;out.push(v);Object.values(v).forEach(x=>visit(x,d+1));};for(const m of html.matchAll(/<script[^>]*(?:type=["'](?:application\/ld\+json|application\/json)["']|id=["']__NEXT_DATA__["'])[^>]*>([\s\S]*?)<\/script>/gi)){try{visit(JSON.parse(m[1].trim()));}catch{}}return out;}
function imageValues(value:any,base:string,out:string[],depth=0){if(value==null||depth>8)return;if(typeof value==="string"){const u=absolute(value,base);if(validImage(u))out.push(u);return;}if(Array.isArray(value))return value.forEach(x=>imageValues(x,base,out,depth+1));if(typeof value==="object")for(const [k,v] of Object.entries(value))if(/image|photo|picture|gallery|media|src|url/i.test(k))imageValues(v,base,out,depth+1);}
function score(v:any){const type=String(v?.["@type"]||v?.type||"").toLowerCase();return(/vehicle|car|product|individualproduct/.test(type)?6:0)+(v?.name||v?.title?2:0)+(v?.image||v?.images||v?.photos?4:0)+(v?.vehicleModelDate||v?.modelYear||v?.year?2:0)+(v?.offers||v?.price?2:0);}
function meta(html:string,key:string){const k=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return clean(html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${k}["'][^>]+content=["']([^"']+)["']`,"i"))?.[1]||html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${k}["']`,"i"))?.[1]||"");}
function parseDetail(html:string,url:string,config:ScopedSourceConfig){const objects=embedded(html).sort((a,b)=>score(b)-score(a));const v=objects[0]||{};const plain=clean(html);const name=clean(v.name||v.title||v.vehicleName||meta(html,"og:title")||html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]);const d=makeModel(name);const brand=v.brand;const make=clean(typeof brand==="object"?brand?.name:brand)||d.make;const modelValue=v.model;const model=clean(typeof modelValue==="object"?modelValue?.name:modelValue)||clean(v.vehicleModel||v.modelName)||d.model;const year=yearOf(v.vehicleModelDate||v.modelYear||v.year||name);const offers=Array.isArray(v.offers)?v.offers[0]:v.offers||{};const detected=priceOf(`${JSON.stringify(v)} ${plain.slice(0,30000)}`,clean(offers.priceCurrency||v.priceCurrency||config.currency).toUpperCase());const price=decimal(offers.price||offers.lowPrice||v.price)||detected.price;const currency=clean(offers.priceCurrency||v.priceCurrency||detected.currency||config.currency).toUpperCase();const od=v.mileageFromOdometer;const mileageKm=decimal(typeof od==="object"?od.value:od)||decimal(v.mileage)||mileageOf(plain);const engineCc=decimal(v.engineDisplacement||v.displacement||v.engineCc)||integer(plain.match(/([0-9][0-9 ,.']{2,5})\s*(?:cc|cm3|cm³)/i)?.[1]);const powerHp=decimal(v.vehicleEngine?.enginePower?.value||v.enginePower||v.power)||integer(plain.match(/\b([0-9]{2,4})\s*(?:HP|PS|л\.с\.)\b/i)?.[1]);const fuel=clean(v.fuelType||v.vehicleEngine?.fuelType||plain.match(/\b(Petrol|Gasoline|Diesel|Hybrid|Electric|EV|PHEV|LPG|Benzin|Elektro|汽油|柴油|纯电|混合动力|增程)\b/i)?.[1]);const transmission=clean(v.vehicleTransmission||v.transmission||plain.match(/\b(Automatic|Manual|CVT|DCT|Automatik|Schaltgetriebe|自动|手动|无级变速|双离合)\b/i)?.[1]);const drive=clean(v.driveWheelConfiguration||v.drivetrain||plain.match(/\b(AWD|4WD|2WD|FWD|RWD|Allrad|Frontantrieb|Heckantrieb|四驱|前驱|后驱|两驱)\b/i)?.[1]);const bodyType=clean(v.bodyType||v.vehicleConfiguration||plain.match(/\b(SUV\/Crossover|SUV|Crossover|Sedan|Saloon|Hatchback|Coupe|Convertible|Pickup|Wagon|Estate|Kombi|Minivan|Van|轿车|跑车|两厢|三厢|旅行车|越野车|MPV|皮卡)\b/i)?.[1]);const images:string[]=[];imageValues(v.image||v.images||v.photos||v.gallery,url,images);const og=absolute(meta(html,"og:image"),url);if(validImage(og))images.push(og);return{name,make,model,year,price,currency,mileageKm,engineCc,powerHp,fuel,transmission,drive,bodyType,images:[...new Set(images)].slice(0,20)};}
function listRows(html:string,config:ScopedSourceConfig){const rows=new Map<string,Row>();for(const m of html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const detailUrl=absolute(m[1],config.baseUrl);if(!detailUrl||NON_VEHICLE.test(detailUrl))continue;let path="";try{path=new URL(detailUrl).pathname;}catch{continue;}if(!config.detailPattern.test(path))continue;const i=m.index||0;const card=html.slice(Math.max(0,i-3500),Math.min(html.length,i+7000));const candidates=[clean(m[2]),clean(card.match(/<img[^>]+alt\s*=\s*["']([^"']+)["']/i)?.[1]),clean(card.match(/<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>/i)?.[1])];const title=candidates.find(x=>x.length>=3&&x.length<=200&&!NON_VEHICLE.test(x))||"";const plain=clean(card);const d=makeModel(title);const year=yearOf(`${title} ${plain}`);if(!d.make||!d.model||!year)continue;const price=priceOf(plain,config.currency);const id=detailUrl.match(/(?:-|\/)([a-z0-9]{6,})(?:\.html|[/?#]|$)/i)?.[1]||stableOfferId(config.sourceId,detailUrl);rows.set(detailUrl,{id,detailUrl,title:d.title,year,make:d.make,model:d.model,price:price.price,currency:price.currency,mileageKm:mileageOf(plain)});}return[...rows.values()];}
async function decode(response:Response,charset?:string){const bytes=await response.arrayBuffer();if(charset)try{return new TextDecoder(charset).decode(bytes);}catch{}return new TextDecoder("utf-8").decode(bytes);}

export class ScopedSourceAdapter implements CatalogSourceAdapter {
  sourceId:string; market:CatalogMarket; accessMode="public_html" as const;
  constructor(private config:ScopedSourceConfig){this.sourceId=config.sourceId;this.market=config.market;}
  private headers(referer?:string){return{...HEADERS,referer:referer||this.config.referer||`${this.config.baseUrl}/`};}
  private async request(url:string,referer?:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),Number(process.env.CATALOG_SOURCE_TIMEOUT_MS||30000));try{const response=await fetch(url,{headers:this.headers(referer),redirect:"follow",signal:controller.signal});return{response,html:await decode(response,this.config.forcedCharset)};}finally{clearTimeout(timer);}}
  async fetchPage(cursor?:string|null):Promise<CatalogFetchResult>{const page=Math.max(1,Number(cursor||1));let status=0,bytes=0;for(const url of this.config.listUrls(page)){const result=await this.request(url).catch(()=>null);if(!result)continue;status=result.response.status;bytes=result.html.length;if(!result.response.ok)continue;const items=listRows(result.html,this.config);if(items.length)return{items,nextCursor:String(page+1),finished:false,count:items.length,health:{ok:true,message:`${this.config.label}: ${items.length} detail links`,checkedAt:new Date().toISOString(),httpStatus:status,contentType:result.response.headers.get("content-type")||""}};}throw new Error(`${this.sourceId}_scoped_zero_status_${status}_bytes_${bytes}`);}
  mapStatus():OfferStatus{return"active";}
  normalizeOffer(raw:unknown):VehicleOffer|null{const row=raw as Row;if(!row?.id||!row.detailUrl||!row.make||!row.model||!row.year)return null;const now=new Date().toISOString();return normalizeVehicleOfferSpecs({id:stableOfferId(this.sourceId,row.id),sourceId:this.sourceId,sourceOfferId:row.id,market:this.market,offerType:"fixed",status:"active",make:row.make,model:row.model,trim:row.title,year:row.year,mileageKm:row.mileageKm,sourcePrice:row.price||null,sourceCurrency:row.price?row.currency:null,priceMode:row.price?"fixed":"estimated",images:[],totalRub:null,calculationStatus:row.price?"ready":"needs_data",firstSeenAt:now,updatedAt:now,operational:{sourceUrl:row.detailUrl,sourceVenueName:this.config.label,raw:row}} as VehicleOffer);}
  async fetchImages(offer:VehicleOffer):Promise<CatalogImage[]>{const row=offer.operational.raw as Row;const result=await this.request(row.detailUrl,row.detailUrl).catch(()=>null);if(!result?.response.ok)return[];const d=parseDetail(result.html,row.detailUrl,this.config);if(!d.make||!d.model||!d.year||!d.images.length)return[];Object.assign(offer,normalizeVehicleOfferSpecs({...offer,make:d.make,model:d.model,trim:d.name||offer.trim,year:d.year,mileageKm:d.mileageKm||offer.mileageKm,engineCc:d.engineCc||offer.engineCc,powerHp:d.powerHp||offer.powerHp,fuel:d.fuel||offer.fuel,transmission:d.transmission||offer.transmission,drive:d.drive||offer.drive,bodyType:d.bodyType||offer.bodyType,sourcePrice:d.price||offer.sourcePrice,sourceCurrency:d.price?d.currency:offer.sourceCurrency,calculationStatus:d.price||offer.sourcePrice?"ready":"needs_data",operational:{...offer.operational,raw:{list:row,detail:d}}} as VehicleOffer));const limit=Math.max(1,Number(process.env.CATALOG_MAX_IMAGES_PER_OFFER||10));const cached=await Promise.all(d.images.slice(0,limit).map(url=>cacheImageFromUrl(url,offer.market,{headers:this.headers(row.detailUrl)}).catch(()=>null)));return cached.filter((image):image is CatalogImage=>Boolean(image&&image.size>4000)).slice(0,limit);}
  async healthCheck(){return{ok:true,message:`${this.config.label}: checked during import`,checkedAt:new Date().toISOString()};}
}
