/** UI vocabulary only. Model codes, measurements and source evidence are untouched. */
export const specificationVocabulary: Record<string,string> = {
 'Basic Specifications':'Основные характеристики','Basic specification':'Основные характеристики','Basic Information':'Основные сведения','General Information':'Общие сведения','Technical Data':'Технические данные','Technical specifications':'Технические характеристики','Vehicle details':'Данные автомобиля','Vehicle information':'Данные автомобиля','Additional equipment':'Дополнительное оснащение','Optional equipment':'Дополнительное оснащение','Standard equipment':'Стандартное оснащение','Comfort & Convenience':'Комфорт и удобство','Comfort and convenience':'Комфорт и удобство','Comfort':'Комфорт','Convenience':'Удобство','Safety & Security':'Безопасность и защита','Safety and security':'Безопасность и защита','Security':'Защита от угона','Interior':'Салон','Exterior':'Внешнее оснащение','Entertainment & Media':'Мультимедиа','Entertainment':'Мультимедиа','Multimedia':'Мультимедиа','Infotainment':'Мультимедиа','Audio':'Аудиосистема','Lighting':'Освещение','Chassis Steering':'Шасси и рулевое управление','Chassis and Steering':'Шасси и рулевое управление','Wheels and brakes':'Колёса и тормоза','Wheels & Tyres':'Колёса и шины','Dimensions and weight':'Размеры и масса','Performance':'Динамические характеристики','Consumption':'Расход топлива','Battery':'Тяговая батарея','Electric motor':'Электродвигатель','Charging':'Зарядка','Warranty':'Гарантия','Service history':'История обслуживания','Vehicle condition':'Состояние автомобиля','Options':'Оснащение','Other':'Прочее оснащение','Extras':'Дополнительное оснащение',
 'Model Name':'Модификация','Energy Type':'Тип топлива','Fuel Type':'Топливо','Body Type':'Тип кузова','Engine Model':'Модель двигателя','Engine Capacity':'Рабочий объём','Displacement (mL)':'Рабочий объём, см³','Displacement (L)':'Рабочий объём, л','Maximum horsepower (Ps)':'Максимальная мощность, л.с.','Maximum power (kW)':'Максимальная мощность, кВт','Maximum torque (N·m)':'Максимальный крутящий момент, Н·м','Length (mm)':'Длина, мм','Width (mm)':'Ширина, мм','Height (mm)':'Высота, мм','Wheelbase (mm)':'Колёсная база, мм','Ground clearance':'Дорожный просвет','Curb weight':'Снаряжённая масса','Gross weight':'Полная масса','Number of seats':'Число мест','Number of doors':'Число дверей','Door count':'Число дверей','Seat count':'Число мест','Drive type':'Тип привода','Drivetrain':'Привод','Drive wheels':'Ведущие колёса','Gearbox':'Коробка передач','Exterior color':'Цвет кузова','Interior color':'Цвет салона','Interior material':'Отделка салона','Color':'Цвет','Colour':'Цвет','Registration date':'Дата регистрации','First registration':'Первая регистрация','Previous owners':'Предыдущие владельцы','Owners':'Число владельцев','Condition':'Состояние','Country of origin':'Страна происхождения','Emission class':'Экологический класс','Fuel consumption':'Расход топлива','Fuel tank capacity':'Объём топливного бака','Battery capacity':'Ёмкость тяговой батареи','Range':'Запас хода','Top speed':'Максимальная скорость','Acceleration':'Разгон','Torque':'Крутящий момент','Horsepower':'Мощность, л.с.','Power':'Мощность',
 'Air conditioning':'Кондиционер','Automatic climate control':'Автоматический климат-контроль','Climate control':'Климат-контроль','Cruise control':'Круиз-контроль','Adaptive cruise control':'Адаптивный круиз-контроль','Parking sensors':'Парктроники','Rear camera':'Камера заднего вида','Rear view camera':'Камера заднего вида','Navigation system':'Навигация','Heated seats':'Подогрев сидений','Ventilated seats':'Вентиляция сидений','Leather seats':'Кожаные сиденья','Electric seats':'Электрорегулировка сидений','Power windows':'Электростеклоподъёмники','Power steering':'Усилитель руля','Sunroof':'Люк','Panoramic roof':'Панорамная крыша','Alloy wheels':'Легкосплавные диски','Airbags':'Подушки безопасности','Central locking':'Центральный замок','Keyless entry':'Бесключевой доступ','Blind spot monitor':'Контроль слепых зон','Lane assist':'Помощь удержания в полосе','Emergency braking':'Автоматическое экстренное торможение','LED headlights':'Светодиодные фары','Fog lights':'Противотуманные фары','Rain sensor':'Датчик дождя','Light sensor':'Датчик света','Heated steering wheel':'Подогрев руля','Tire pressure monitoring':'Контроль давления в шинах',
 'Fahrzeugdaten':'Данные автомобиля','Technische Daten':'Технические данные','Ausstattung':'Оснащение','Sicherheit':'Безопасность','Komfort':'Комфорт','Innenausstattung':'Оснащение салона','Außenausstattung':'Внешнее оснащение','Fahrzeugzustand':'Состояние автомобиля','Erstzulassung':'Первая регистрация','Kilometerstand':'Пробег','Kraftstoffart':'Тип топлива','Hubraum':'Рабочий объём','Leistung':'Мощность','Getriebe':'Коробка передач','Farbe':'Цвет','Anzahl Sitzplätze':'Число мест','Anzahl der Türen':'Число дверей','Schadstoffklasse':'Экологический класс','Umweltplakette':'Экологическая наклейка','Fahrzeughalter':'Владельцы','Klimatisierung':'Климатическая установка','Einparkhilfe':'Помощь при парковке',
 '基本情報':'Основные сведения','車両情報':'Данные автомобиля','装備':'Оснащение','エンジン':'Двигатель','駆動方式':'Тип привода','排気量':'Рабочий объём','走行距離':'Пробег','年式':'Год выпуска','車検':'Техосмотр','修復歴':'История восстановительного ремонта','燃料':'Топливо','乗車定員':'Число мест','ドア数':'Число дверей','ミッション':'Коробка передач','ハンドル':'Расположение руля','ボディカラー':'Цвет кузова','基本参数':'Основные характеристики','变速箱':'Коробка передач','底盘转向':'Шасси и рулевое управление','车轮制动':'Колёса и тормоза','电动机':'Электродвигатель','电池/充电':'Батарея и зарядка','干式双离合':'Сухое двойное сцепление','湿式双离合':'Мокрое двойное сцепление','电子驻车':'Электронный стояночный тормоз','电动助力':'Электроусилитель','承载式':'Несущий кузов','非承载式':'Рамный кузов','通风盘式':'Вентилируемые дисковые','盘式':'Дисковые','鼓式':'Барабанные','前排':'Передний ряд','后排':'Задний ряд','前/后':'Спереди / сзади','主/副驾驶座安全气囊':'Фронтальные подушки водителя и пассажира','前/后排侧气囊':'Боковые подушки спереди / сзади','前/后排头部气囊(气帘)':'Шторки безопасности спереди / сзади','前/后驻车雷达':'Парктроники спереди / сзади','前/后电动车窗':'Электростеклоподъёмники спереди / сзади',
 'yes':'Есть','no':'Нет','Yes':'Есть','No':'Нет','Unknown':'Не указано','Not specified':'Не указано','N/A':'Не указано','Used':'С пробегом','New':'Новый','Left':'Слева','Right':'Справа','Left hand drive':'Левый руль','Right hand drive':'Правый руль','Front wheel drive':'Передний привод','Rear wheel drive':'Задний привод','All wheel drive':'Полный привод','Four wheel drive':'Полный привод','Automatic':'Автоматическая','Manual':'Механическая','Petrol':'Бензин','Gasoline':'Бензин','Diesel':'Дизель','Hybrid':'Гибрид','Electric':'Электромобиль','Black':'Чёрный','White':'Белый','Silver':'Серебристый','Grey':'Серый','Gray':'Серый','Blue':'Синий','Red':'Красный','Green':'Зелёный','Brown':'Коричневый','Beige':'Бежевый','Leather':'Кожа','Cloth':'Ткань','Fabric':'Ткань','Full leather':'Кожа','Partial leather':'Комбинированная кожа',
};
const entries=Object.entries(specificationVocabulary).sort((a,b)=>b[0].length-a[0].length);
const exactTerms=new Map(entries.map(([source,target])=>[source.toLocaleLowerCase(),target]));
const replacements=entries.filter(([source])=>!/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/u.test(source)||source.length>=4).map(([source,target])=>{
 const escaped=source.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
 return [new RegExp(/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/u.test(source)?escaped:`(?<![\\p{L}])${escaped}(?![\\p{L}])`,'giu'),target] as const;
});
const cache=new Map<string,string>();
export function translateKnownSpecification(value:string) {
 if(cache.has(value))return cache.get(value)!;
 const exact=exactTerms.get(value.toLocaleLowerCase());
 if(exact)return exact;
 let result=value;
 for(const [pattern,target] of replacements) result=result.replace(pattern,target);
 if(cache.size>=4096)cache.clear();
 cache.set(value,result);
 return result;
}
