import crypto from "node:crypto";
import { getJsonStorage, readDataJson, writeDataJson } from "../data";
import type { CatalogImage, CatalogMarket, CatalogSearchParams, PublicVehicleOffer, VehicleOffer } from "./types";

const MARKETS: CatalogMarket[] = ["japan", "korea", "china", "uae", "europe"];
const CDN = process.env.CATALOG_IMAGE_CDN_URL || "https://img.avtocena.com";
export const CATALOG_CHUNK_SIZE = 500;
export function publicOffer(offer: VehicleOffer): PublicVehicleOffer { const { operational, vin, frameNumber, ...dto } = offer; return dto; }
export function offerPath(market: string, chunk: string) { return `catalog/offers/${market}/${chunk}.json`; }
export function chunkName(index: number) { return `chunk-${String(index).padStart(4, "0")}`; }
export async function readMarketOffers(market: string) { const manifest = await readDataJson<any>("catalog/manifest.json", { markets: {} }); const chunks: string[] = manifest.markets?.[market]?.chunks || []; const lists = await Promise.all(chunks.map((c) => readDataJson<VehicleOffer[]>(offerPath(market, c), []))); return lists.flat(); }
export async function readAllOffers() { const lists = await Promise.all(MARKETS.map(readMarketOffers)); return lists.flat(); }
function shard(value?: string | number) { return String(value || "unknown").toLowerCase().replace(/[^a-z0-9а-яё-]+/gi, "-").replace(/-+/g, "-"); }
function budgetBucket(v?: number) { if (!v) return "unknown"; return String(Math.ceil(v / 500000) * 500000); }
async function writeIndexShard(name: string, key: string, ids: string[]) { await writeDataJson(`catalog/indexes/${name}/${shard(key)}.json`, { updatedAt: new Date().toISOString(), ids }); }
export async function persistCatalogOffers(nextOffers: VehicleOffer[]) {
  const now = new Date().toISOString(); const byMarket = new Map<string, VehicleOffer[]>();
  for (const offer of nextOffers) if (offer.images.length && (offer.totalRub || offer.calculationStatus !== "ready")) byMarket.set(offer.market, [...(byMarket.get(offer.market) || []), offer]);
  const markets: any = {};
  for (const [market, offers] of byMarket) { const chunks: string[] = []; for (let i = 0; i < offers.length; i += CATALOG_CHUNK_SIZE) { const name = chunkName(chunks.length + 1); chunks.push(name); await writeDataJson(offerPath(market, name), offers.slice(i, i + CATALOG_CHUNK_SIZE)); } markets[market] = { count: offers.length, chunks, updatedAt: now }; }
  await writeDataJson("catalog/manifest.json", { version: 1, updatedAt: now, markets }); await rebuildIndexes(nextOffers);
}
export async function rebuildIndexes(offers: VehicleOffer[]) { const active = offers.filter((o) => o.status === "active" && o.images.length); const maps: Record<string, Map<string, string[]>> = { market: new Map(), make: new Map(), model: new Map(), year: new Map(), budget: new Map(), bodyType: new Map(), fuel: new Map(), drive: new Map(), updatedAt: new Map() }; for (const o of active) { const pairs = { market: o.market, make: o.make, model: `${o.make}:${o.model}`, year: o.year, budget: budgetBucket(o.totalRub), bodyType: o.bodyType, fuel: o.fuel, drive: o.drive, updatedAt: (o.updatedAt || "").slice(0,10) }; for (const [name, key] of Object.entries(pairs)) { const m = maps[name]; const k = shard(key); m.set(k, [...(m.get(k) || []), o.id]); } } await Promise.all(Object.entries(maps).flatMap(([name, map]) => [...map.entries()].map(([key, ids]) => writeIndexShard(name, key, ids)))); }
export async function getOffer(id: string) { return (await readAllOffers()).find((o) => o.id === id && o.status === "active" && o.images.length) || null; }
export async function searchOffers(params: CatalogSearchParams) { const page = Math.max(1, Number(params.page || 1)); const pageSize = Math.min(48, Math.max(1, Number(params.pageSize || 24))); const market = params.market && params.market !== "any" ? params.market : undefined; const candidate = market ? await readMarketOffers(market) : await readAllOffers(); let items = candidate.filter((o) => o.status === "active" && o.images.length && (o.totalRub || o.calculationStatus !== "ready")); items = items.filter((o) => (!params.make || o.make.toLowerCase() === params.make.toLowerCase()) && (!params.model || o.model.toLowerCase() === params.model.toLowerCase()) && (!params.budgetTo || (o.totalRub || Infinity) <= params.budgetTo) && (!params.yearFrom || o.year >= params.yearFrom) && (!params.yearTo || o.year <= params.yearTo) && (!params.mileageTo || (o.mileageKm || 0) <= params.mileageTo) && (!params.fuel || o.fuel === params.fuel) && (!params.transmission || o.transmission === params.transmission) && (!params.drive || o.drive === params.drive) && (!params.bodyType || o.bodyType === params.bodyType) && (!params.auctionGrade || o.auctionGrade === params.auctionGrade)); const sort = params.sort || "updatedAt"; items.sort((a,b) => sort === "totalRub" ? (a.totalRub || 0) - (b.totalRub || 0) : sort === "year" ? b.year - a.year : sort === "mileage" ? (a.mileageKm || 0) - (b.mileageKm || 0) : String(b.auctionDate || b.updatedAt).localeCompare(String(a.auctionDate || a.updatedAt))); const total = items.length; return { total, page, pageSize, items: items.slice((page-1)*pageSize, page*pageSize).map(publicOffer), usedIndexShards: market ? [`catalog/indexes/market/${market}.json`] : ["catalog/manifest.json"] }; }
export async function cacheImageFromUrl(url: string, market: string): Promise<CatalogImage | null> { const res = await fetch(url); if (!res.ok) return null; const mimeType = res.headers.get("content-type") || ""; if (!/^image\/(jpeg|png|webp)$/.test(mimeType)) return null; const buf = Buffer.from(await res.arrayBuffer()); if (!buf.length || buf.length > Number(process.env.CATALOG_IMAGE_MAX_BYTES || 8000000)) return null; const checksum = crypto.createHash("sha256").update(buf).digest("hex"); const ext = mimeType.includes("png") ? "png" : mimeType.includes("webp") ? "webp" : "jpg"; const objectKey = `catalog/images/${market}/${checksum}.${ext}`; const storage = getJsonStorage(); if (!(await storage.binaryExists?.(objectKey))) await storage.putBinary?.(objectKey, buf, mimeType, { ifNoneMatch: "*" }); return { id: checksum.slice(0,16), objectKey, url: `${CDN}/${objectKey}`, size: buf.length, checksum, mimeType }; }
export function stableOfferId(sourceId: string, sourceOfferId: string) { return crypto.createHash("sha256").update(`${sourceId}:${sourceOfferId}`).digest("hex").slice(0, 24); }
