import Link from "next/link";
import { notFound } from "next/navigation";
import { BrandMark } from "@/components/brand/BrandMark";
import { VehicleGallery } from "@/components/catalog/VehicleGallery";
import { getVehicleOffer, getVehicleOffers, marketLabel } from "@/lib/catalog";
import { money } from "@/lib/avtocena";

export function generateStaticParams(){ return getVehicleOffers().map((offer)=>({id:offer.id})); }
export function generateMetadata({params}:{params:{id:string}}){ const offer=getVehicleOffer(params.id); if(!offer) return { robots:{index:false,follow:false} }; return { title:`${offer.brand} ${offer.model} ${offer.year} — АвтоЦена`, description:`Предложение ${offer.brand} ${offer.model}: цена площадки ${offer.priceLocal} ${offer.currency}, расчёт под ключ уточняется менеджером.`, alternates:{canonical:`/cars/offer/${offer.id}`} }; }

function SourcePhotoPlaceholder({sourceUrl}:{sourceUrl:string}) { return <div className="flex h-full min-h-[320px] flex-col items-center justify-center gap-5 bg-[radial-gradient(circle_at_25%_18%,rgba(239,68,68,0.34),transparent_36%),linear-gradient(135deg,rgba(255,255,255,0.12),rgba(255,255,255,0.025))] p-6 text-center"><BrandMark className="h-24 w-24 opacity-40"/><div><div className="text-lg font-black">Фотографии доступны у источника</div><p className="mt-2 max-w-sm text-sm font-bold text-white/55">Площадка не подтверждена для прямого hotlink изображений. АвтоЦена не проксирует оригинальные фото.</p></div><a href={sourceUrl} target="_blank" rel="noreferrer" className="rounded-2xl bg-red-600 px-5 py-3 text-sm font-black text-white">Посмотреть фотографии у источника</a></div>; }

export default function OfferPage({params}:{params:{id:string}}){ const offer=getVehicleOffer(params.id); if(!offer) notFound(); const lines=offer.calculationSnapshot?.complete ? offer.calculationSnapshot.lines : []; const hasDirectGallery=offer.imageMode !== "source_page_only" && offer.images.length > 0; return <main className="min-h-screen px-4 py-6 md:px-8"><Link href={`/cars/${offer.market}`} className="text-sm font-bold text-red-200 underline">← {marketLabel(offer.market)}</Link><section className="mt-5 overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.045]"><div className="grid md:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)]"><div className="min-h-[320px]">{hasDirectGallery ? <VehicleGallery images={offer.images} title={`${offer.brand} ${offer.model}`}/> : <SourcePhotoPlaceholder sourceUrl={offer.sourceUrl}/>}</div><div className="p-5 md:p-7"><h1 className="text-4xl font-black tracking-[-0.04em]">{offer.year} {offer.brand} {offer.model}</h1><p className="mt-3 text-sm font-bold text-white/60">Предложение найдено на внешней площадке. Оно может быть продано или изменено. Актуальность, возможность покупки и итоговую стоимость подтверждает менеджер.</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><dt className="text-white/45">Пробег</dt><dd className="font-black">{money(offer.mileageKm||0)} км</dd><dt className="text-white/45">Двигатель</dt><dd className="font-black">{offer.engineCc} cc</dd><dt className="text-white/45">Мощность</dt><dd className="font-black">{offer.advertisedPower || offer.systemPowerHp || offer.icePowerHp || "уточняется"}</dd><dt className="text-white/45">КПП / привод</dt><dd className="font-black">{offer.transmission} / {offer.drive}</dd><dt className="text-white/45">Цена площадки</dt><dd className="font-black">{money(offer.priceLocal)} {offer.currency}</dd><dt className="text-white/45">Расчёт</dt><dd className="font-black text-yellow-100">{offer.calculationComplete && offer.calculationSnapshot ? `${money(offer.calculationSnapshot.totalRub)} ₽` : "уточняется менеджером"}</dd></dl><a href={offer.sourceUrl} target="_blank" rel="noreferrer" className="mt-5 inline-block text-red-200 underline">Источник: {offer.sourceName}</a><div className="mt-1 text-xs text-white/45">Проверено: {new Date(offer.lastCheckedAt).toLocaleString("ru-RU")}</div></div></div><div className="border-t border-white/10 p-5 md:p-7"><h2 className="text-2xl font-black">Расчёт АвтоЦена</h2>{lines.length ? <div className="mt-3 grid max-w-2xl gap-2">{lines.map((line)=><div key={line.id} className="flex justify-between gap-4 text-sm"><span className="text-white/60">{line.title}</span><b>{money(line.amountRub)} ₽</b></div>)}</div> : <p className="mt-3 rounded-2xl border border-yellow-200/20 bg-yellow-300/10 p-4 text-sm font-bold text-yellow-50/85">Расчёт под ключ уточняется менеджером. Сейчас показываем только цену площадки: {money(offer.priceLocal)} {offer.currency}.</p>}</div></section></main> }
