'use client';
import {useRef,useState} from 'react';
import {PhoneInput} from '@/components/leads/PhoneInput';
import {leadFetch} from '@/lib/lead-submit-client';
export function PrivacyRequestForm(){
 const [name,setName]=useState(''),[phone,setPhone]=useState('+7'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState('');const operation=useRef('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{operation.current||=crypto.randomUUID();const r=await leadFetch('/api/privacy-request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,phone,message,operationId:operation.current})});const data=await r.json();if(!r.ok)throw Error(data.error||'Не удалось отправить обращение.');setResult(data.id);}catch(e){setError(e instanceof Error?e.message:'Ошибка отправки.');}finally{setBusy(false);}}
 if(result)return <p role="status" className="rounded-xl border border-green-500/40 p-5">Обращение зарегистрировано: <strong className="break-all">{result}</strong>. Сохраните номер. Оператор свяжется с вами для ответа или проверки личности.</p>;
 return <form onSubmit={submit} className="grid gap-4 rounded-2xl border border-[var(--ac-border)] p-5"><label>Имя<input required maxLength={300} value={name} onChange={e=>setName(e.target.value)} className="soft-input mt-1 w-full rounded-xl p-3"/></label><label>Телефон, указанный в заявке<PhoneInput required value={phone} onChange={setPhone}/></label><label>Что нужно сделать<textarea required minLength={5} maxLength={3000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Например: отзываю согласие на обработку заявки №… и прошу удалить данные при отсутствии другого законного основания хранения." className="soft-input mt-1 min-h-36 w-full rounded-xl p-3"/></label><p className="text-sm text-[var(--ac-muted)]">Не указывайте паспортные и банковские реквизиты. Данные этой формы используются для рассмотрения требования по закону № 152-ФЗ. Новое согласие на подбор автомобиля или рекламу не требуется.</p>{error?<p role="alert" className="text-red-500">{error}</p>:null}<button disabled={busy} className="rounded-xl bg-red-600 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?'Отправляем…':'Направить обращение'}</button></form>;
}
