import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);
test('staff writes enforce capability, owner boundary and prevent granting absent capabilities',async()=>{
 const state:any={actor:{id:'a',role:'admin',displayName:'Admin',telegramUsername:'admin',permissions:{calculations:false}},users:[{id:'a',role:'admin',displayName:'Admin',telegramUsername:'admin',permissions:{calculations:false}},{id:'o',role:'owner',displayName:'Owner',telegramUsername:'owner'}]};(globalThis as any).__staffPermissions=state;
 const sources:any={'@/lib/auth':`export const getCurrentUser=async()=>globalThis.__staffPermissions.actor;export const getAuthUsers=()=>globalThis.__staffPermissions.users;export const normalizeTelegramUsername=s=>s.replace(/^@/,'').toLowerCase();export const isAdminRole=r=>['owner','admin'].includes(r);`,'@/lib/data':`export const generateId=()=>"new-staff";export const mutateDataJson=async(p,f,fn)=>{const s=globalThis.__staffPermissions;s.users=fn(s.users);return s.users;};`,'@/lib/crm-activity':`export const recordCrmActivity=async()=>{};export const activityChanges=()=>[];export const activityPerson=u=>u;`};
 const r=await build({entryPoints:['apps/web/app/(crm)/api/crm/users/route.ts'],bundle:true,platform:'node',format:'cjs',write:false,packages:'external',plugins:[{name:'staff',setup(b){b.onResolve({filter:/^@\/lib\//},a=>sources[a.path]?{path:a.path,namespace:'mock'}:undefined);b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:sources[a.path],loader:'ts',resolveDir:process.cwd()}));}}]});const m={exports:{} as any};new Function('require','module','exports',r.outputFiles[0].text)(require,m,m.exports);
 async function save(values:any,origin='https://avtocena.com'){const form=new FormData();for(const [k,v] of Object.entries({displayName:'New',telegramUsername:'newperson',role:'manager',permissionsPresent:'1',...values}))form.set(k,String(v));return m.exports.POST(new Request('https://avtocena.com/api/crm/users',{method:'POST',headers:{origin},body:form}));}
 try{assert.equal((await save({},'https://evil.example')).status,403);let response=await save({role:'owner'});assert.match(response.headers.get('location'),/state=error/);assert.equal(state.users.length,2);response=await save({permissionsPresent:'0',role:'admin'});assert.match(response.headers.get('location'),/state=error/);assert.equal(state.users.length,2);response=await save({permission_calculations:'on'});assert.match(response.headers.get('location'),/state=error/);assert.equal(state.users.length,2);response=await save({userId:'o',telegramUsername:'owner'});assert.match(response.headers.get('location'),/state=error/);response=await save({permission_editClients:'on'});assert.match(response.headers.get('location'),/state=saved/);assert.equal(state.users[0].permissions.editClients,true);assert.equal(state.users[0].permissions.calculations,false);response=await save({userId:'new-staff',personalPhone:'8 (999) 123-45-67'});assert.match(response.headers.get('location'),/state=saved/);assert.equal(state.users[0].personalPhone,'+79991234567');
 response=await save({userId:'new-staff'});assert.equal(state.users[0].personalPhone,'+79991234567','older form preserves the phone');
 response=await save({userId:'new-staff',personalPhone:'invalid'});assert.match(response.headers.get('location'),/state=error/);assert.equal(state.users[0].personalPhone,'+79991234567');
 response=await save({userId:'new-staff',personalPhone:''});assert.equal(state.users[0].personalPhone,'','phone can be cleared');
 response=await save({userId:'new-staff',workplacesPresent:'1',workAddresses:JSON.stringify([' Офис 1 ','Офис 2','Офис 1']),remoteWork:'on'});assert.match(response.headers.get('location'),/state=saved/);assert.deepEqual(state.users[0].workAddresses,['Офис 1','Офис 2']);assert.equal(state.users[0].remoteWork,true);
 response=await save({userId:'new-staff'});assert.deepEqual(state.users[0].workAddresses,['Офис 1','Офис 2'],'older forms preserve workplaces');
 response=await save({userId:'new-staff',workplacesPresent:'1',workAddresses:'broken'});assert.match(response.headers.get('location'),/state=error/);assert.deepEqual(state.users[0].workAddresses,['Офис 1','Офис 2']);
 response=await save({userId:'new-staff',workplacesPresent:'1',workAddresses:'[]'});assert.deepEqual(state.users[0].workAddresses,[]);assert.equal(state.users[0].remoteWork,false);

 assert.equal(state.users[0].offerCopyEnabled,false,'new employees start without the flower button');
 response=await save({userId:'new-staff',offerCopyPresent:'1',offerCopyEnabled:'on'});assert.match(response.headers.get('location'),/state=error/);assert.equal(state.users[0].offerCopyEnabled,false,'admin cannot enable the button');
 state.actor.permissions.deleteReviews=true;response=await save({userId:'new-staff',permission_deleteReviews:'on'});assert.match(response.headers.get('location'),/state=error/);assert.notEqual(state.users[0].permissions.deleteReviews,true,'delegates cannot grant moderation');
 state.actor={...state.actor,role:'owner'};
 const previousVersion=state.users[0].sessionVersion||0;
 response=await save({userId:'new-staff',permission_chat:'on',permission_analytics:'on'});assert.match(response.headers.get('location'),/state=saved/);assert.equal(state.users[0].permissions.chat,true);assert.equal(state.users[0].permissions.analytics,true);assert.equal(state.users[0].sessionVersion,previousVersion+1);
 response=await save({userId:'new-staff',permission_site:'on'});assert.equal(state.users[0].permissions.site,false,'manager cannot receive site administration');assert.equal(state.users[0].permissions.chat,false,'unchecked chat is revoked');
 response=await save({userId:'new-staff',offerCopyPresent:'1',offerCopyEnabled:'on'});assert.match(response.headers.get('location'),/state=saved/);assert.equal(state.users[0].offerCopyEnabled,true);
 state.actor={...state.actor,role:'admin'};
 response=await save({userId:'new-staff'});assert.match(response.headers.get('location'),/state=saved/);assert.equal(state.users[0].offerCopyEnabled,true,'admin saving other fields preserves owner setting');
 response=await save({userId:'new-staff',offerCopyPresent:'1'});assert.match(response.headers.get('location'),/state=error/);assert.equal(state.users[0].offerCopyEnabled,true,'admin cannot disable the button');
 state.actor={...state.actor,role:'owner'};
 response=await save({userId:'new-staff',offerCopyPresent:'1'});assert.match(response.headers.get('location'),/state=saved/);assert.equal(state.users[0].offerCopyEnabled,false);
 state.actor={...state.actor,role:'admin'};
 state.actor={...state.actor,permissions:{staff:false}};response=await save({telegramUsername:'another'});assert.match(response.headers.get('location'),/auth_required/);assert.equal(state.users.length,3);}finally{delete (globalThis as any).__staffPermissions;}
});
