import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {createRequire} from 'node:module';import {discussionHref,discussionMessages} from '../apps/web/lib/crm-discussion';const require=createRequire(import.meta.url);
test('discussion links identify the entity and message, and legacy notes remain visible',()=>{assert.equal(discussionHref('lead','l','n'),'/crm/leads?id=l&message=n#discussion-lead-l');assert.equal(discussionHref('client','c'),'/crm/clients/c#discussion-client-c');assert.equal(discussionMessages({internalNotes:[{text:'Old note',createdByName:'Manager'}]})[0].text,'Old note');});
test('chat preserves assignment/status, appends replies once and notifies only permitted colleagues',async()=>{
 const state:any={users:[{id:'owner',role:'owner',displayName:'Owner',companyId:'one'},{id:'m',role:'manager',displayName:'Manager',companyId:'one'},{id:'other',role:'manager',displayName:'Other',companyId:'one'},{id:'foreign',role:'owner',displayName:'Foreign',companyId:'two'}],leads:[{id:'l',name:'Игорь',car:'RAV4',assignedManagerId:'m',status:'contacted',internalNotes:[{id:'old',text:'Prior note',createdByUserId:'owner'}]}],clients:[{id:'c',fio:'Client',assignedManagerId:'m'}],events:[],notices:[]};(globalThis as any).__chat=state;
 const sources:any={'./auth':`export const isCrmRole=r=>['owner','admin','manager'].includes(r);`,'./crm-users':`export const readCrmUsers=async()=>globalThis.__chat.users;`,'./data':`const s=globalThis.__chat;export const readChunkedDataJson=async p=>p.startsWith('leads')?s.leads:s.clients;export const updateChunkedDataJson=async(p,id,fn)=>{const rows=p.startsWith('leads')?s.leads:s.clients;const i=rows.findIndex(x=>x.id===id);if(i<0)return null;return rows[i]=fn(rows[i]);};`,'./crm-activity':`export const recordCrmActivity=async(u,e)=>globalThis.__chat.events.push(e);`,'./crm-notification-store':`export const notifyTeam=async n=>globalThis.__chat.notices.push(n);`};
 const output=await build({entryPoints:['apps/web/lib/crm-discussion-store.ts'],bundle:true,platform:'node',format:'cjs',packages:'external',write:false,plugins:[{name:'chat',setup(b){b.onResolve({filter:/^\.\//},a=>sources[a.path]?{path:a.path,namespace:'mock'}:undefined);b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:sources[a.path],loader:'ts'}));}}]});const m={exports:{} as any};new Function('require','module','exports',output.outputFiles[0].text)(require,m,m.exports);const api=m.exports;
 try{const user=state.users[1],message={text:'Answer',operationId:'operation-123',replyTo:'old'};await assert.rejects(api.readDiscussion(state.users[2],'lead','l'),/forbidden/);await assert.rejects(api.addDiscussionMessage({...user,permissions:{editLeads:false}},'lead','l',message),/forbidden/);await assert.rejects(api.addDiscussionMessage(user,'lead','l',{...message,replyTo:'missing'}),/invalid_reply/);
 const result=await api.addDiscussionMessage(user,'lead','l',message);assert.equal(result.messages.length,2);assert.equal(result.messages[1].replyTo,'old');assert.equal(state.leads[0].assignedManagerId,'m');assert.equal(state.leads[0].status,'contacted');assert.equal(state.notices.length,1);assert.deepEqual(state.notices[0].recipientIds,['owner']);assert.match(state.notices[0].title,/Игорь.*RAV4/);assert.match(state.notices[0].href,/#discussion-lead-l/);
 await api.addDiscussionMessage(user,'lead','l',message);assert.equal(state.leads[0].internalNotes.length,2);assert.equal(state.notices.length,1);assert.equal(state.events.length,1);await assert.rejects(api.addDiscussionMessage(user,'lead','l',{...message,text:'different'}),/message_conflict/);
 await api.addDiscussionMessage(user,'client','c',{text:'Client note',operationId:'operation-client'});assert.equal(state.clients[0].internalNotes[0].text,'Client note');state.leads[0].assignedManagerId='other';await assert.rejects(api.addDiscussionMessage(user,'lead','l',{text:'No access',operationId:'operation-denied'}),/forbidden/);
 }finally{delete (globalThis as any).__chat;}
});
