import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {build} from 'esbuild';
import {emptyDealerSubscriptions,updateSubscription,subscriptionState} from '../apps/web/lib/dealers/subscription-model';
test('subscription count is idempotent, preserves date and removes only selected subscriber',()=>{let s=emptyDealerSubscriptions();s=updateSubscription(s,'a',true,'date1');s=updateSubscription(s,'a',true,'date2');assert.deepEqual(subscriptionState(s,'a'),{count:1,subscribed:true});assert.equal(s.subscribers.a.createdAt,'date1');s=updateSubscription(s,'b',true);s=updateSubscription(s,'a',false);assert.deepEqual(subscriptionState(s,'a'),{count:1,subscribed:false});assert.equal(subscriptionState(s,'b').subscribed,true);});
test('public subscription endpoint owns identity cookie, denies hidden/cross-origin writes and returns only aggregate',async()=>{const out=path.resolve('artifacts/subscription-route.cjs');fs.mkdirSync(path.dirname(out),{recursive:true});await build({entryPoints:['apps/web/app/(public)/api/dealers/[id]/subscription/route.ts'],outfile:out,bundle:true,platform:'node',format:'cjs',packages:'external',plugins:[{name:'store',setup(b){const modules:Record<string,string>={
'@/lib/data':`const state={};export async function readDataJson(k,f){return state[k]||f}export async function mutateDataJson(k,f,fn){return state[k]=await fn(state[k]||f)}`,
'@/lib/dealers/showcase-store':`export function validDealerId(id){return /^[a-z0-9_]+$/.test(id)}export async function readShowcase(id){return id==='missing'?null:{profileEnabled:id!=='hidden'}}`,
'@/lib/dealers/program-store':`export async function availableShowcase(s){return s}`,
'@/lib/dealers/access':`export async function canManageDealer(){return false}`,
'@/lib/auth':`export async function getCurrentUser(){return null}`};b.onResolve({filter:/^@\/lib\//},args=>modules[args.path]?{path:args.path,namespace:'mock'}:undefined);b.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:modules[args.path]}));}}]});const api=createRequire(import.meta.url)(out);const ctx=(id='dealer_a')=>({params:Promise.resolve({id})});const req=(method='GET',cookie='',body?:unknown,origin='https://avtocena.com')=>new Request('https://avtocena.com/api/dealers/dealer_a/subscription',{method,headers:{origin,cookie,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});let r=await api.GET(req(),ctx());const cookie=r.headers.get('set-cookie')!.split(';')[0];assert.match(cookie,/ac_dealer_subscriber=[a-f0-9]{64}$/);assert.match(r.headers.get('set-cookie')!,/HttpOnly/i);assert.deepEqual(await r.json(),{count:0,subscribed:false});for(let i=0;i<2;i++){r=await api.PUT(req('PUT',cookie,{subscribed:true}),ctx());assert.deepEqual(await r.json(),{count:1,subscribed:true});}assert.equal((await api.PUT(req('PUT',cookie,{subscribed:true},'https://evil.example'),ctx())).status,403);assert.equal((await api.GET(req(),ctx('hidden'))).status,404);assert.equal((await api.PUT(req('PUT',cookie,{subscribed:'yes'}),ctx())).status,400);r=await api.PUT(req('PUT',cookie,{subscribed:false}),ctx());assert.deepEqual(await r.json(),{count:0,subscribed:false});});
