import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';import {build} from 'esbuild';
import {minor,monthKey,dueDate,vatIncluded,commissionMinor,basis,eligibleProviderPayment,BILLING_POLICY} from '../apps/web/lib/dealers/billing/model';
import {EMPTY_MEMBERSHIP} from '../apps/web/lib/dealers/program-model';
const require=createRequire(import.meta.url);
test('money stays in kopecks, dates follow Krasnoyarsk, taxes and bases are explicit',()=>{
 assert.equal(minor('150 000,01'),15000001);for(const v of ['',-1,'1.001','1e3',NaN])assert.throws(()=>minor(v));
 assert.equal(commissionMinor(minor('150000'),10),1500000);assert.equal(commissionMinor(minor('150000'),15),2250000);assert.throws(()=>commissionMinor(-1,10));
 assert.equal(monthKey('2026-10-31T17:00:00Z'),'2026-11');assert.equal(monthKey('2026-10-31T16:59:59Z'),'2026-10');assert.equal(dueDate('2026-12'),'2027-01-01');
 assert.equal(vatIncluded(12200,22),2200);assert.equal(vatIncluded(12200,null),null);assert.equal(vatIncluded(12200,'none'),0);
 const s:any={depositMinor:10000,commissionMinor:15000,otherMinor:100,excludedMinor:10000};assert.throws(()=>basis(s));assert.equal(basis({...s,exclusionApprovedBy:'owner'}),15100);assert.throws(()=>basis({...s,depositMinor:-1}));
});
test('provider confirmation must match merchant, amount, currency, mode and order',()=>{
 const o:any={providerId:'p',id:'o',amountMinor:1000000};const p={id:'p',status:'succeeded',paid:true,test:false,amount:{value:'10000.00',currency:'RUB'},metadata:{orderId:'o'},recipient:{account_id:'shop'}};
 assert.ok(eligibleProviderPayment(o,p,'shop',false));for(const patch of [{test:true},{paid:false},{id:'another'},{status:'pending'},{amount:{value:'1.00',currency:'RUB'}},{amount:{value:'10000.00',currency:'USD'}},{metadata:{orderId:'another'}},{recipient:{account_id:'another'}}])assert.equal(eligibleProviderPayment(o,{...p,...patch},'shop',false),false);
});
test('scoped ledger: signed-deal snapshots, deduplication, taxes, invoices, payment retry and access',async()=>{
 const cwd=process.cwd(),env={...process.env},fetch=globalThis.fetch,tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ac-billing-'));const out=path.resolve('artifacts/billing-tests');fs.mkdirSync(out,{recursive:true});const modules:any={};
 for(const [name,entry] of Object.entries({store:'apps/web/lib/dealers/billing/store.ts',payments:'apps/web/lib/dealers/billing/payments.ts',access:'apps/web/lib/dealers/billing/access.ts',api:'apps/web/app/api/dealers/billing/route.ts',pdf:'apps/web/lib/dealers/billing/pdf.ts'})){
 const file=path.join(out,name+'.cjs');await build({entryPoints:[entry],outfile:file,bundle:true,platform:'node',format:'cjs',packages:'external',logLevel:'silent',plugins:[{name:'auth',setup(b){b.onResolve({filter:/^@\/lib\/auth$/},()=>({path:'auth',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export async function getCurrentUser(){return globalThis.__billingActor||null}'}));}}]});modules[name]=require(file);}
 const put=(p:string,v:any)=>{const f=path.join(tmp,'data',p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v));};const get=(p:string)=>JSON.parse(fs.readFileSync(path.join(tmp,'data',p),'utf8'));
 const a={version:BILLING_POLICY,text:'terms',digest:'accepted',actorId:'d',representative:'Director',authority:'Charter',legalName:'Dealer',inn:'1234567890',ogrn:'1234567890123',address:'Address',submittedAt:'2026-10-01',approvedAt:'2026-10-01'};
 const lead={id:'l',clientId:'c',requestedDealerId:'external',assignedManagerId:'d',dealerContactResult:'contacted',platformTerms:{percent:10,agreementDigest:a.digest,agreementVersion:BILLING_POLICY}};
 const client:any={id:'c',documents:[{id:'doc',name:'Contract',customerVisible:true}],portalContracts:{}};
 put('dealers/dealers.json',[{id:'external',name:'Dealer',status:'verified'},{id:'other',name:'Other',status:'verified'}]);put('dealers/memberships/external.json',{...EMPTY_MEMBERSHIP,agreement:a});put('leads/leads.json',[lead]);put('dealers/external/clients.json',[client]);process.chdir(tmp);process.env.JSON_STORAGE_DRIVER='local';
 const s=modules.store;try{
 const dealer={id:'d',companyId:'external',role:'dealer',dealerApproved:true},owner={id:'o',companyId:'dealer_topavto',role:'owner'};
 await assert.rejects(()=>modules.access.billingDealer(null,'external'));await assert.rejects(()=>modules.access.billingDealer(dealer,'other'));assert.equal(await modules.access.billingDealer(dealer),'external');assert.equal(await modules.access.billingDealer(owner,'other'),'other');
 (globalThis as any).__billingActor=dealer;const req=(b:any)=>new Request('https://avtocena.com/api/dealers/billing',{method:'POST',headers:{origin:'https://avtocena.com','Content-Type':'application/json'},body:JSON.stringify(b)});
 assert.equal((await modules.api.POST(req({action:'tax',version:0,tax:'none',taxBasis:'test'}))).status,400);assert.equal((await modules.api.GET(new Request('https://avtocena.com/api/dealers/billing?dealer=other'))).status,403);
 const input={leadId:'l',documentId:'doc',contractNumber:'A-1',car:'Haval Jolion',year:2026,total:'2000000',deposit:'50000',commission:'150000',other:'0',excluded:'50000',exclusionReason:'Возвратное обеспечение, пункт 3 договора',version:0};
 await s.saveSpec('external',input,'d');await assert.rejects(()=>s.saveSpec('external',input,'d'));await assert.rejects(()=>s.requireSpec('external',lead,'doc',true));await s.approveExclusion('external','l',1,'o');const spec=await s.requireSpec('external',lead,'doc',true);assert.ok(spec.lockedAt);await assert.rejects(()=>s.saveSpec('external',{...input,version:1},'d'));
 await s.saveBillingConfig({version:0,tax:22,taxBasis:'Подтверждённая ставка'},'o');client.portalContracts.l={documentId:'doc',confirmedBy:'d',confirmedAt:'2026-10-07',requiresCustomerConfirmation:true,customerConfirmedAt:'2026-10-07',financialDigest:spec.digest};put('dealers/external/clients.json',[client]);
 await s.captureSignedDeal('external','l');await s.captureSignedDeal('external','l');let book=await s.readBook('external');assert.equal(book.charges.length,1);assert.equal(book.charges[0].amountMinor,1500000);assert.equal(book.charges[0].tax,22);
 await s.saveBillingConfig({version:1,tax:'none',taxBasis:'Другой период'},'o');await s.closePeriods('external',new Date('2026-11-02'));await s.closePeriods('external',new Date('2026-11-02'));book=await s.readBook('external');assert.equal(book.invoices.length,1);assert.equal(book.invoices[0].tax,22);assert.equal(book.invoices[0].dueDate,'2026-11-01');const invoice=book.invoices[0];
 await s.recordBankPayment('external',invoice.id,'5000','Bank-1','o');await assert.rejects(()=>s.recordBankPayment('external',invoice.id,'5000','Bank-1','o'));await assert.rejects(()=>s.recordBankPayment('external',invoice.id,'10001','Bank-2','o'));
 const order=await s.newOrder('external',{kind:'invoice',invoiceId:invoice.id,email:'dealer@example.com'});assert.equal(order.amountMinor,1000000);assert.equal((await s.newOrder('external',{kind:'invoice',invoiceId:invoice.id,email:'dealer@example.com'})).id,order.id);await assert.rejects(()=>s.recordBankPayment('external',invoice.id,'1','Bank-2','o'));
 Object.assign(process.env,{DEALER_PAYMENTS_ENABLED:'1',DEALER_PAYMENTS_MODE:'live',DEALER_YOOKASSA_SHOP_ID:'shop',DEALER_YOOKASSA_SECRET:'test-key',DEALER_RECEIPTS_CONFIRMED:'1',DEALER_FISCAL_FLOW_CONFIRMED:'1'});
 const provider={id:'11111111-1111-1111-1111-111111111111',status:'succeeded',paid:true,test:false,amount:{currency:'RUB',value:'10000.00'},metadata:{dealerId:'external',orderId:order.id},recipient:{account_id:'shop'},captured_at:'2026-11-01T01:00:00Z'};
 globalThis.fetch=async()=>Response.json(provider);await s.mutateBook('external',(b:any)=>({...b,orders:b.orders.map((o:any)=>o.id===order.id?{...o,providerId:provider.id,status:'pending'}:o)}));
 await modules.payments.checkPayment('external',order.id);await modules.payments.checkPayment('external',order.id);book=await s.readBook('external');assert.equal(book.receipts.filter((r:any)=>r.providerId===provider.id).length,1);assert.equal(book.receipts.reduce((n:number,r:any)=>n+r.amountMinor,0),1500000);
 const subscription=await s.newOrder('external',{kind:'subscription',months:1,invoiceId:invoice.id,email:'dealer@example.com'});assert.equal(subscription.invoiceId,undefined);provider.metadata.orderId=subscription.id;provider.id='22222222-2222-2222-2222-222222222222';await s.mutateBook('external',(b:any)=>({...b,orders:b.orders.map((o:any)=>o.id===subscription.id?{...o,providerId:provider.id,status:'pending'}:o)}));
 await modules.payments.checkPayment('external',subscription.id);const paid=get('dealers/memberships/external.json').paidUntil;await modules.payments.checkPayment('external',subscription.id);assert.equal(get('dealers/memberships/external.json').paidUntil,paid);assert.equal(get('dealers/memberships/external.json').history.length,1);
 const trialOrder=await s.newOrder('external',{kind:'subscription',months:1,email:'dealer@example.com'});provider.metadata.orderId=trialOrder.id;provider.id='33333333-3333-3333-3333-333333333333';provider.test=true;process.env.DEALER_PAYMENTS_MODE='test';await s.mutateBook('external',(b:any)=>({...b,orders:b.orders.map((o:any)=>o.id===trialOrder.id?{...o,providerId:provider.id,status:'pending'}:o)}));
 assert.equal(await modules.payments.checkPayment('external',trialOrder.id),'test_succeeded');assert.equal(get('dealers/memberships/external.json').history.length,1);assert.equal((await s.readBook('external')).receipts.length,2);
 await s.reverseCharge('external','deal_l','Подтверждённая отмена','o');await s.reverseCharge('external','deal_l','Подтверждённая отмена','o');book=await s.readBook('external');assert.equal(book.charges.length,2);assert.equal(book.charges.reduce((n:number,c:any)=>n+c.amountMinor,0),0);
 process.chdir(cwd);const pdf=await modules.pdf.billingPdf(invoice,book,true);assert.ok(pdf.subarray(0,4).toString()==='%PDF');assert.ok(pdf.length>1000);fs.writeFileSync(path.join(out,'act.pdf'),pdf);
 }finally{globalThis.fetch=fetch;delete(globalThis as any).__billingActor;process.chdir(cwd);for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);fs.rmSync(tmp,{recursive:true,force:true});}
});
