import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {canReadRegisteredCustomers,registeredCustomersPage,registeredCustomerHref} from '../apps/web/lib/account/crm-accounts';
import {accountPath,phoneAccountId} from '../apps/web/lib/account/auth';
import {writeDataJson,resetJsonStorageForTests} from '../apps/web/lib/data';
test('registered accounts remain platform-scoped and old accounts are discoverable without a new registration event',async()=>{
 const user:any={id:'staff',role:'owner',companyId:'dealer_topavto'};assert.equal(canReadRegisteredCustomers(user),true);assert.equal(canReadRegisteredCustomers({...user,companyId:'dealer_other'}),false);assert.equal(canReadRegisteredCustomers({...user,status:'disabled'}),false);assert.equal(canReadRegisteredCustomers({...user,role:'manager',permissions:{viewAll:false}}),false);
 const cwd=process.cwd(),driver=process.env.JSON_STORAGE_DRIVER,secret=process.env.AUTH_SECRET,temp=fs.mkdtempSync(path.join(os.tmpdir(),'registered-customers-'));fs.mkdirSync(path.join(temp,'data'));process.chdir(temp);process.env.JSON_STORAGE_DRIVER='local';process.env.AUTH_SECRET='registered-list-test';resetJsonStorageForTests();
 try{for(let i=0;i<43;i++){const phone='+7999000'+String(i).padStart(4,'0'),id=phoneAccountId(phone);await writeDataJson(accountPath(id),{id,phone,name:'Test',createdAt:new Date(2026,0,1+i).toISOString(),passwordHash:'private'});}await writeDataJson('accounts/telegram-challenges.json',[]);const p=await registeredCustomersPage('',1),p2=await registeredCustomersPage('',2);assert.equal(p.total,43);assert.equal(p.accounts.length,40);assert.equal(p2.accounts.length,3);assert.equal(new Set([...p.accounts,...p2.accounts].map(a=>a.id)).size,43);const found=await registeredCustomersPage('8 (999) 000-00-42',1);assert.equal(found.accounts.length,1);assert.match(registeredCustomerHref(found.accounts[0].id),/^\/crm\/clients\/registered\/[a-f0-9]{64}$/);assert.deepEqual(await registeredCustomersPage('invalid',1),{accounts:[],total:0});}
 finally{process.chdir(cwd);for(const [k,v] of Object.entries({JSON_STORAGE_DRIVER:driver,AUTH_SECRET:secret})){if(v===undefined)delete process.env[k];else process.env[k]=v;}resetJsonStorageForTests();fs.rmSync(temp,{recursive:true,force:true});}
});
