import {randomUUID} from 'node:crypto';
import {currentAccount,accountRateLimit} from '@/lib/account/auth';
import {linkedClient,clientsPath} from '@/lib/account/portal';
import {getJsonStorage,updateChunkedDataJson} from '@/lib/data';
import {documentKey,encryptClientDocument,prepareClientDocument,readDocumentForm,MAX_CLIENT_DOCUMENTS,type ClientDocument} from '@/lib/client-documents';
import {isCalculationOriginAllowed} from '@/lib/catalog/calculation-request-origin';
export async function POST(request:Request){if(!isCalculationOriginAllowed(request))return new Response(null,{status:403});const a=await currentAccount();if(!a)return new Response(null,{status:401});let key='',stored=false;const storage=getJsonStorage();try{
 const {link,client}=await linkedClient(a,new URL(request.url).searchParams.get('client')||'');if((client.documents||[]).length>=MAX_CLIENT_DOCUMENTS)throw Error('Достигнут лимит документов.');if(!await accountRateLimit('upload:'+a.id,10,3600000)||!await accountRateLimit('upload-ip:'+(request.headers.get('x-forwarded-for')||'unknown').split(',')[0],30,3600000))return Response.json({error:'Слишком много загрузок. Повторите позже.'},{status:429});const form=await readDocumentForm(request),file=form.get('file');if(!(file instanceof File))throw Error('Выберите файл.');const p=await prepareClientDocument(file);const doc:ClientDocument&{customerVisible:boolean}={id:randomUUID(),name:p.name,mime:p.mime,size:file.size,createdAt:new Date().toISOString(),createdBy:a.id,hasThumbnail:!!p.thumbnail,customerVisible:true};key=documentKey(client.id,doc.id);if(!storage.putBinary)throw Error('Хранилище недоступно.');await storage.putBinary(key,encryptClientDocument(Buffer.from(JSON.stringify({data:p.data.toString('base64'),thumbnail:p.thumbnail?.toString('base64')})),key),'application/octet-stream');stored=true;
 const updated=await updateChunkedDataJson<any>(clientsPath(link.companyId),client.id,c=>{if(c.portalAccountId!==a.id||c.deletedAt)throw Error('Нет доступа.');if((c.documents||[]).length>=MAX_CLIENT_DOCUMENTS)throw Error('Достигнут лимит документов.');return {...c,documents:[...(c.documents||[]),doc],documentsUpdatedAt:doc.createdAt};});if(!updated)throw Error('Нет доступа.');stored=false;return Response.json({ok:true,document:{id:doc.id,name:doc.name,size:doc.size,createdAt:doc.createdAt}},{headers:{'Cache-Control':'no-store'}});
 }catch(e){if(stored)await storage.deleteBinary?.(key).catch(()=>{});const message=e instanceof Error?e.message:'';return Response.json({error:message==='size'?'Файл должен быть не больше 5 МБ.':message==='format'?'Поддерживаются изображения, PDF, DOC, DOCX, XLSX.':message||'Не удалось загрузить файл.'},{status:400});}}
