import { NextResponse } from "next/server";
import { appendChunkedDataJson, generateId, readChunkedDataJson } from "@/lib/data";
import { getCurrentUser, isCrmRole } from "@/lib/auth";
import { errorResponse, updateClientRecord } from "@/lib/crm-server";

function clean(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function numberOrNull(value: unknown) { const num = Number(String(value || "").replace(/[^0-9]/g, "")); return Number.isFinite(num) && num > 0 ? num : null; }
export async function GET() { const user = await getCurrentUser(); if (!user || !isCrmRole(user.role)) return NextResponse.json({ ok: false, error: "auth_required" }, { status: 401 }); const clients = await readChunkedDataJson<any>("clients/clients.json", []); return NextResponse.json({ ok: true, clients }); }
export async function POST(request: Request) { const user = await getCurrentUser(); if (!user || !isCrmRole(user.role)) return NextResponse.json({ ok: false, error: "auth_required" }, { status: 401 }); const body = await request.json().catch(() => ({})); const fio = clean(body.fio); const phone = clean(body.phone); const telegram = clean(body.telegram); const comment = clean(body.comment); if (!fio && !phone && !telegram) return NextResponse.json({ ok: false, error: "client_contact_required" }, { status: 400 }); const createdAt = new Date().toISOString(); const operationId = clean(body.operationId) || generateId("operation"); try { const clients = await readChunkedDataJson<any>("clients/clients.json", []); const leads = await readChunkedDataJson<any>("leads/leads.json", []); const events = await readChunkedDataJson<any>("activity/feed.json", []); let client = clients.find((item) => item.operationId === operationId); let lead = leads.find((item) => item.operationId === operationId); let event = events.find((item) => item.operationId === operationId); const clientId = `client_${operationId}`; if (!client) client = await appendChunkedDataJson("clients/clients.json", { id: clientId, operationId, createdAt, updatedAt: createdAt, fio, phone, telegram, city: clean(body.city), comment, comments: comment, status: "active", interestedCar: clean(body.car), market: clean(body.market), budgetRub: numberOrNull(body.budgetRub), phones: phone ? [phone] : [], passport: clean(body.passport), address: clean(body.address), birthDate: clean(body.birthDate), documents: [], contracts: [], history: [{ at: createdAt, by: user.id, type: "client_created", title: "Клиент создан", operationId }], createdByManagerId: user.id, assignedManagerId: clean(body.assignedManagerId) || user.id, source: clean(body.source) || "manual" }); if (!lead) lead = await appendChunkedDataJson("leads/leads.json", { id: `lead_${operationId}`, operationId, createdAt, updatedAt: createdAt, clientId, status: "new", name: fio, phone, telegram, comment, car: clean(body.car), brand: clean(body.brand), model: clean(body.model), market: clean(body.market), budgetRub: numberOrNull(body.budgetRub), totalRub: numberOrNull(body.totalRub), source: clean(body.source) || "manual", partnerRef: clean(body.partnerRef), createdByManagerId: user.id, assignedManagerId: clean(body.assignedManagerId) || user.id }); if (!event) event = await appendChunkedDataJson("activity/feed.json", { id: `event_${operationId}`, operationId, createdAt, type: "client_created", title: "Добавлен клиент", managerId: user.id, managerName: user.displayName, clientId, leadId: lead.id, text: fio || phone || telegram || "Новый клиент", car: clean(body.car) }); return NextResponse.json({ ok: true, client, lead, event, operationId }); } catch { return NextResponse.json({ ok: false, error: "storage_write_failed" }, { status: 500 }); } }
export async function PUT(request: Request) { try { const body = await request.json().catch(() => ({})); const result = await updateClientRecord(body); return NextResponse.json({ ok: true, ...result }); } catch (error) { const { message, status } = errorResponse(error); return NextResponse.json({ ok: false, error: message }, { status }); } }
