'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Monitor,Smartphone,ArrowUpRight,ChevronDown} from 'lucide-react';
import {SITE_SECTIONS,siteRule} from '@/lib/site-controls';
import type {PublicFeatures} from '@/lib/dealers/showcase-store';
import './site-controls.css';
import {AccountAppearanceEditor} from './AccountAppearanceEditor';
export function SiteControls({initial}:{initial:PublicFeatures}){
 const [value,setValue]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [uploadBusy,setUploadBusy]=useState(false);
 const change=(id:typeof SITE_SECTIONS[number]['id'],patch:any)=>setValue(v=>{const section=SITE_SECTIONS.find(s=>s.id===id)!;const rule={...siteRule(v,id),...patch};return {...v,...('legacy'in section?{[section.legacy]:rule.desktop||rule.mobile}:{}),siteControls:{...v.siteControls,[id]:rule}};});
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/crm/public-features',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await r.json();if(!r.ok)throw Error(data.error);setValue(data);setMessage('Настройки сайта сохранены');}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <div className="site-controls"><p className="text-sm text-[var(--ac-muted)]">Отдельно управляйте показом на компьютере и телефоне. Изменения применяются после сохранения.</p>
 <details className="site-settings-fold"><summary>Вход и регистрация <ChevronDown size={18}/></summary><AccountAppearanceEditor value={value.accountAppearance||{}} onChange={accountAppearance=>setValue(current=>({...current,accountAppearance}))} onBusyChange={setUploadBusy}/></details>
 <details className="site-settings-fold" open><summary>Разделы сайта <ChevronDown size={18}/></summary><div className="site-visibility-scroll"><table className="site-visibility"><thead><tr><th scope="col">Раздел</th><th scope="col"><span><Monitor size={18}/>Компьютер</span></th><th scope="col"><span><Smartphone size={18}/>Телефон</span></th><th scope="col">Действия</th></tr></thead><tbody>{SITE_SECTIONS.map(s=>{const r=siteRule(value,s.id);return <tr key={s.id}><td><h2>{s.label}</h2><p>{s.description}</p>{['partners','knowledge'].includes(s.id)&&<details className="mt-3"><summary className="cursor-pointer text-sm font-bold">Заголовок страницы</summary><label className="mt-3 grid gap-2 text-sm">Заголовок<input maxLength={120} value={r.title} onChange={e=>change(s.id,{title:e.target.value})} className="soft-input rounded-xl p-3" placeholder="Стандартный заголовок"/></label><label className="mt-3 grid gap-2 text-sm">Вступление<textarea maxLength={600} value={r.description} onChange={e=>change(s.id,{description:e.target.value})} className="soft-input rounded-xl p-3" placeholder="Стандартное вступление"/></label></details>}</td>{(['desktop','mobile'] as const).map(device=><td key={device} className="site-switch-cell"><button type="button" role="switch" aria-checked={r[device]} aria-label={`${s.label} · ${device==='desktop'?'Компьютер':'Телефон'}`} title={`${s.label} · ${device==='desktop'?'Компьютер':'Телефон'}`} className="site-visibility-switch" onClick={()=>change(s.id,{[device]:!r[device]})}><span/></button></td>)}<td><div className="site-section-links"><Link className="underline" href={s.href} target="_blank">Открыть <ArrowUpRight size={14} className="inline"/></Link>{'edit'in s&&<Link className="underline" href={s.edit}>Редактировать</Link>}</div></td></tr>})}</tbody></table></div></details>
 <div className="site-save-actions"><p role="status" className="text-sm">{message}</p><button disabled={busy||uploadBusy} onClick={()=>void save()} className="rounded-xl bg-red-500 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?'Сохраняем…':'Сохранить настройки'}</button></div></div>;
}
