'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Monitor,Smartphone,ArrowUpRight,ChevronDown} from 'lucide-react';
import {SITE_SECTIONS,siteRule} from '@/lib/site-controls';
import type {PublicFeatures} from '@/lib/dealers/showcase-store';
import {Toggle} from '@/components/dealers/DealerEditorFields';
export function SiteControls({initial}:{initial:PublicFeatures}){
 const [value,setValue]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const change=(id:typeof SITE_SECTIONS[number]['id'],patch:any)=>setValue(v=>{const section=SITE_SECTIONS.find(s=>s.id===id)!;const rule={...siteRule(v,id),...patch};return {...v,...('legacy'in section?{[section.legacy]:rule.desktop||rule.mobile}:{}),siteControls:{...v.siteControls,[id]:rule}};});
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/crm/public-features',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await r.json();if(!r.ok)throw Error(data.error);setValue(data);setMessage('Настройки сайта сохранены');}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <div className="space-y-4"><p className="text-sm text-[var(--ac-muted)]">Отдельно управляйте показом на компьютере и телефоне. Изменения применяются после сохранения.</p>{SITE_SECTIONS.map(s=>{const r=siteRule(value,s.id);return <section key={s.id} className="border-b border-[var(--ac-border)] py-5"><div className="flex flex-wrap items-start justify-between gap-5"><div><h2 className="text-xl font-bold">{s.label}</h2><p className="mt-1 text-sm text-[var(--ac-muted)]">{s.description}</p><div className="mt-3 flex gap-5 text-sm"><Link className="underline" href={s.href} target="_blank">Открыть <ArrowUpRight size={14} className="inline"/></Link>{'edit'in s&&<Link className="underline" href={s.edit}>Редактировать</Link>}</div></div><div className="flex flex-wrap gap-4"><div><Monitor size={18} className="mb-2"/><Toggle label={`${s.label} · Компьютер`} value={r.desktop} onChange={desktop=>change(s.id,{desktop})}/></div><div><Smartphone size={18} className="mb-2"/><Toggle label={`${s.label} · Телефон`} value={r.mobile} onChange={mobile=>change(s.id,{mobile})}/></div></div></div>{['partners','knowledge'].includes(s.id)&&<details className="mt-4"><summary className="cursor-pointer font-bold">Заголовок страницы <ChevronDown size={16} className="inline"/></summary><label className="mt-3 grid gap-2 text-sm">Заголовок<input maxLength={120} value={r.title} onChange={e=>change(s.id,{title:e.target.value})} className="soft-input rounded-xl p-3" placeholder="Стандартный заголовок"/></label><label className="mt-3 grid gap-2 text-sm">Вступление<textarea maxLength={600} value={r.description} onChange={e=>change(s.id,{description:e.target.value})} className="soft-input rounded-xl p-3" placeholder="Стандартное вступление"/></label></details>}</section>})}<div className="sticky bottom-3 flex flex-wrap items-center gap-4 rounded-2xl bg-[var(--ac-surface)] p-4 shadow-lg"><button disabled={busy} onClick={()=>void save()} className="rounded-xl bg-red-500 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?'Сохраняем…':'Сохранить настройки'}</button><p role="status" className="text-sm">{message}</p></div></div>;
}
