'use client';
import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {previewBlocks,previewParts} from '@/lib/contracts/preview';
import {crmDateKey,crmDateTime} from '@/lib/crm-time';
import {defaultManagerAvatar} from '@/lib/default-avatars';
import {Trash2,RotateCcw} from 'lucide-react';
import {CrmDateInput} from '../CrmDateInput';
import {sampleFields,fieldGroups,dateKeys,formatDate,markets,money,type ContractRecord,type ContractTemplate,type TemplateId} from '@/lib/contracts/model';
import './contracts.css';
const PdfPreview=lazy(()=>import('../../catalog/OfferPdfPreview'));
type Client={id:string;name:string;phone:string;city:string};
type ListItem={id:string;revision:number;number:string;client:string;car:string;createdAt:string;createdBy:string;updatedAt:string;versions:number;market:string;templateId:TemplateId;archivedAt?:string};
type Manager={id:string;name:string;avatar?:string};
const flags:Record<string,string>={japan:'🇯🇵',china:'🇨🇳',korea:'🇰🇷',uae:'🇦🇪',georgia:'🇬🇪',europe:'🇪🇺'};
async function api(body:unknown){const res=await fetch('/api/crm/contracts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error||'Не удалось сохранить.');return data;}
async function read(query=''){const res=await fetch('/api/crm/contracts'+query,{cache:'no-store'});const data=await res.json();if(!res.ok)throw Error(data.error||'Не удалось загрузить.');return data;}
function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
export function ContractWorkspace({owner,clients,managers=[]}:{owner:boolean;clients:Client[];managers?:Manager[]}){
 const [tab,setTab]=useState<'contracts'|'archive'>('contracts'),[list,setList]=useState<ListItem[]>([]),[q,setQ]=useState(''),[r,setR]=useState<ContractRecord|null>(null),[editingTemplate,setEditingTemplate]=useState<ContractTemplate|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[mobile,setMobile]=useState('fields'),[pdf,setPdf]=useState<{blob:Blob;name:string}|null>(null),[shareFile,setShareFile]=useState<File|null>(null);
 const [selectedMarket,setSelectedMarket]=useState('japan'),[managerFilter,setManagerFilter]=useState(''),[dateFilter,setDateFilter]=useState(''),[activeField,setActiveField]=useState('');
 const workspace=useRef<HTMLDivElement>(null),paper=useRef<HTMLDivElement>(null),templateDirty=useRef(false);
 const current=useRef(r),dirty=useRef(false),pending=useRef<Promise<ContractRecord|null>|null>(null);current.current=r;
 function apply(next:ContractRecord|null){current.current=next;setR(next);}
 function edit(next:ContractRecord){dirty.current=true;apply(next);setNote('Есть несохранённые изменения');}
 function field(k:string,v:string){const x=current.current;if(x)edit({...x,fields:{...x.fields,[k]:v}});}
 async function save():Promise<ContractRecord|null>{if(pending.current){await pending.current;return dirty.current?save():current.current;}const captured=current.current;if(!captured||!dirty.current)return captured;const promise=(async()=>{const data=await api({action:'save',id:captured.id,revision:captured.revision,fields:captured.fields,clientId:captured.clientId,template:captured.template});if(current.current===captured){dirty.current=false;apply(data.record);setNote('Черновик сохранён');}else if(current.current?.id===captured.id){apply({...current.current,revision:data.record.revision,updatedAt:data.record.updatedAt,calculation:null});}return current.current;})();pending.current=promise;try{await promise;}finally{pending.current=null;}return dirty.current?save():current.current;}
 useEffect(()=>{read().then(d=>setList(d.records)).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!dirty.current)return;const timer=setTimeout(()=>{save().catch(e=>setError(e.message));},1400);return()=>clearTimeout(timer);},[r]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current||templateDirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить действие.');}finally{setBusy(false);}}
 async function listView(){if(templateDirty.current&&!window.confirm('Закрыть шаблон без сохранения изменений?'))return;templateDirty.current=false;await save();apply(null);setEditingTemplate(null);const data=await read();setList(data.records);setNote('');}
 async function create(id:TemplateId){await save();const data=await api({action:'create',templateId:id,id:crypto.randomUUID()});dirty.current=false;apply(data.record);if(data.record.fields.market!==selectedMarket)edit({...data.record,fields:{...data.record.fields,market:selectedMarket}});setEditingTemplate(null);setMobile('fields');setNote('Черновик создан');}
 async function act(action:string){const saved=await save();if(!saved)return;const data=await api({action,id:saved.id,revision:saved.revision});dirty.current=false;apply(data.record);setNote(data.warning||({import:'Параметры и расчёт загружены',manual:'Ручной расчёт сохранён',finalize:'Готовая версия сохранена'} as Record<string,string>)[action]||'Сохранено');}
 async function output(mode:'preview'|'download'|'share'|'print',version?:number,templateId?:TemplateId){let query:string,name:string;if(templateId){query=`?template=${templateId}&pdf=1`;name=`Образец договора — ${templateId==='japan'?'Япония':'остальные рынки'}.pdf`;}else{const saved=await save();if(!saved)return;query=`?id=${saved.id}&pdf=1${version?`&version=${version}`:''}`;name=`Договор ${saved.number.replace('/','-')}${version?` — версия ${version}`:' — черновик'}.pdf`;}
 const response=await fetch('/api/crm/contracts'+query,{cache:'no-store'});if(!response.ok){const data=await response.json();throw Error(data.error||'Не удалось сформировать PDF.');}const blob=await response.blob();if(mode==='preview'){setPdf({blob,name});return;}if(mode==='download'){download(blob,name);return;}if(mode==='share'){const file=new File([blob],name,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){setShareFile(file);setNote('Файл подготовлен. Нажмите «Выбрать, куда отправить».');}else{download(blob,name);setNote('PDF скачан — прикрепите его в нужном чате.');}return;}
 const url=URL.createObjectURL(blob);const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:1px;height:1px;bottom:0;right:0;border:0';frame.src=url;frame.onload=()=>{try{frame.contentWindow?.focus();frame.contentWindow?.print();setNote('Если диалог печати не открылся, скачайте PDF и выберите «Печать».');}catch{download(blob,name);setNote('Откройте скачанный PDF и выберите «Печать».');}};document.body.appendChild(frame);setTimeout(()=>{frame.remove();URL.revokeObjectURL(url);},120000);
 }
 async function attach(version:number){const saved=await save();if(!saved)return;await api({action:'attach',id:saved.id,version});setNote('Договор прикреплён к клиенту');}
 const templateId:TemplateId=selectedMarket==='japan'?'japan':'other';
 function focusEditor(key:string){
  setActiveField(key);setMobile('fields');
  requestAnimationFrame(()=>{
   const label=workspace.current?.querySelector<HTMLElement>(`[data-editor-field="${key}"]`);
   if(!label)return;
   let parent=label.parentElement;while(parent){if(parent instanceof HTMLDetailsElement)parent.open=true;parent=parent.parentElement;}
   const control=label.matches('input,textarea,select')?label:label.querySelector<HTMLElement>('input,textarea,select');
   control?.focus({preventScroll:true});label.scrollIntoView({block:'nearest',behavior:'smooth'});
  });
 }
 function focusPreview(key:string){
  setActiveField(key);
  const node=Array.from(paper.current?.querySelectorAll<HTMLElement>('[data-preview-fields]')||[]).find(n=>n.dataset.previewFields?.split('|').includes(key));
  if(node&&paper.current)paper.current.scrollTo({top:paper.current.scrollTop+node.getBoundingClientRect().top-paper.current.getBoundingClientRect().top-50,behavior:'smooth'});
 }
 useEffect(()=>{
  const shell=workspace.current?.querySelector<HTMLElement>('.contract-edit-shell');if(!shell)return;
  const measure=()=>shell.style.setProperty('--contract-editor-height',`${Math.max(400,window.innerHeight-shell.getBoundingClientRect().top-18)}px`);
  measure();window.addEventListener('resize',measure);return()=>window.removeEventListener('resize',measure);
 },[Boolean(r),Boolean(editingTemplate),error,note]);
 async function changeState(item:ListItem,action:'archive'|'restore'|'purge'){
  const message=action==='archive'?`Переместить договор № ${item.number} в архив? Его можно восстановить.`:action==='restore'?`Восстановить договор № ${item.number}?`:`Удалить договор № ${item.number} и все его версии навсегда? Прикреплённые к клиенту копии останутся. Отменить удаление нельзя.`;
  if(!window.confirm(message))return;
  await api({action,id:item.id,revision:item.revision,confirm:true});setList((await read()).records);
  setNote(action==='archive'?'Договор в архиве':action==='restore'?'Договор восстановлен':'Договор удалён');
 }
 const changeTemplate=(next:ContractTemplate)=>{templateDirty.current=true;setEditingTemplate(next);};
 const textEditor=(template:ContractTemplate,onChange:(t:ContractTemplate)=>void)=><div className="contract-text-editor"><p className="contract-muted">Подстановки в двойных скобках сохраняйте без изменений.</p><label data-editor-field="template.agent">Данные исполнителя<textarea value={template.agent} rows={5} onChange={e=>onChange({...template,agent:e.target.value})}/></label>{template.sections.map((s,i)=><details key={i}><summary>{s.title}</summary><label data-editor-field={`template.sections.${i}.title`}>Заголовок<input value={s.title} onChange={e=>onChange({...template,sections:template.sections.map((x,j)=>i===j?{...x,title:e.target.value}:x)})}/></label><label data-editor-field={`template.sections.${i}.text`}>Текст раздела<textarea aria-label={s.title} value={s.text} rows={12} onChange={e=>onChange({...template,sections:template.sections.map((x,j)=>i===j?{...x,text:e.target.value}:x)})}/></label></details>)}<label data-editor-field="template.requisites">Реквизиты исполнителя<textarea rows={8} value={template.requisites} onChange={e=>onChange({...template,requisites:e.target.value})}/></label></div>;
 const snapshot=r?{version:0,createdAt:r.updatedAt,createdBy:r.createdBy,fields:r.fields,template:r.template,calculation:r.calculation}:editingTemplate?{version:0,createdAt:'',createdBy:'',fields:{...sampleFields(editingTemplate.id),market:selectedMarket},template:editingTemplate,calculation:null}:null;
 const preview=snapshot?<section className="contract-panel contract-preview"><div className="contract-preview-heading"><h2>Предпросмотр</h2>{r&&<button disabled={busy} onClick={()=>run(()=>output('preview'))}>Открыть PDF</button>}</div><div ref={paper} className="contract-paper"><small>{r?'ЧЕРНОВИК':'ОБРАЗЕЦ'}</small>{previewBlocks(snapshot,r?.number||'ОБРАЗЕЦ').map((block,i)=>{
  const keys=[...(r?block.fields:[]),...(block.editor?[block.editor]:[])];const key=r?(block.fields[0]||block.editor):block.editor;
  const active=keys.includes(activeField);const Tag=block.heading?'h4':'p';
  return <Tag key={i} data-preview-fields={keys.join('|')} className={active?'contract-highlight':undefined} tabIndex={key?0:undefined} role={key?'button':undefined} title={key?'Открыть поле для редактирования':undefined} onClick={()=>key&&focusEditor(key)} onKeyDown={e=>{if(key&&(e.key==='Enter'||e.key===' ')){e.preventDefault();focusEditor(key);}}}>{previewParts(block,snapshot.fields).map((part,j)=>part.field&&r?<span key={j} className={activeField===part.field?'contract-value-active':'contract-value'} onClick={e=>{e.stopPropagation();focusEditor(part.field!);}}>{part.text}</span>:<span key={j}>{part.text}</span>)}</Tag>;
 })}</div></section>:null;
 const editorFocus=(event:React.FocusEvent<HTMLElement>)=>{const label=(event.target as HTMLElement).closest<HTMLElement>('[data-editor-field]');if(label)focusPreview(label.dataset.editorField!);};
 const filtered=list.filter(x=>Boolean(x.archivedAt)===(tab==='archive')&&[x.client,x.car,x.number].join(' ').toLowerCase().includes(q.toLowerCase())&&(!managerFilter||x.createdBy===managerFilter)&&(!dateFilter||crmDateKey(x.createdAt)===dateFilter));
 return <div ref={workspace} className="contract-workspace">
 {error&&<p className="contract-error" role="alert">{error}</p>}{note&&<p className="contract-muted contract-status" role="status">{note}</p>}
 {!r&&!editingTemplate&&<>
 <div className="contract-start"><div className="contract-actions"><button className="primary" disabled={busy} onClick={()=>run(()=>create(templateId))}>Создать договор</button><button disabled={busy} onClick={()=>run(()=>output('preview',undefined,templateId))}>Образец</button>{owner&&<button disabled={busy} onClick={()=>run(async()=>{templateDirty.current=false;setEditingTemplate((await read(`?template=${templateId}`)).template);setMobile('fields');})}>Редактировать шаблон</button>}</div><label className="contract-country"><span className="sr-only">Страна договора</span><select aria-label="Страна договора" value={selectedMarket} onChange={e=>setSelectedMarket(e.target.value)}>{Object.entries(markets).map(([id,name])=><option value={id} key={id}>{flags[id]} {name}</option>)}</select></label></div>
 <div className="contract-tabs"><button className={tab==='contracts'?'selected':''} onClick={()=>setTab('contracts')}>Договоры</button><button className={tab==='archive'?'selected':''} onClick={()=>setTab('archive')}>Архив</button></div>
 <div className="contract-filters"><label>Поиск договоров<input type="search" placeholder="Клиент, автомобиль или номер" value={q} onChange={e=>setQ(e.target.value)}/></label><label>Менеджер<select value={managerFilter} onChange={e=>setManagerFilter(e.target.value)}><option value="">Все менеджеры</option>{managers.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Дата создания · Новокузнецк<CrmDateInput name="contract-date" value={dateFilter} onChange={setDateFilter}/></label>{(dateFilter||managerFilter||q)&&<button onClick={()=>{setQ('');setDateFilter('');setManagerFilter('');}}>Сбросить</button>}</div>
 <div className="contract-list">{filtered.map(x=>{const manager=managers.find(m=>m.id===x.createdBy);return <article key={x.id} className="contract-panel contract-list-row"><button className="contract-list-item" disabled={busy} onClick={()=>run(async()=>{dirty.current=false;apply((await read(`?id=${x.id}`)).record);setMobile('fields');})}><strong>№ {x.number} · {x.client}</strong><span>{x.car||'Автомобиль не выбран'}</span><small><img src={manager?.avatar||defaultManagerAvatar(x.createdBy)} alt="" width={24} height={24}/>{manager?.name||'Менеджер'} · {crmDateTime(x.createdAt)} · {x.versions?`Версий: ${x.versions}`:'Черновик'}</small></button><div className="contract-row-tools"><span title={markets[x.market]||'Остальные рынки'} aria-label={markets[x.market]||'Остальные рынки'}>{flags[x.market]||(x.templateId==='japan'?flags.japan:'🌐')}</span>{x.archivedAt&&<button aria-label={`Восстановить договор ${x.number}`} title="Восстановить" disabled={busy} onClick={()=>run(()=>changeState(x,'restore'))}><RotateCcw size={18}/></button>}<button aria-label={`${x.archivedAt?'Удалить навсегда':'В архив'} договор ${x.number}`} title={x.archivedAt?'Удалить навсегда':'В архив'} disabled={busy} onClick={()=>run(()=>changeState(x,x.archivedAt?'purge':'archive'))}><Trash2 size={18}/></button></div></article>;})}{!filtered.length&&<p className="contract-muted">{tab==='archive'?'Архив пуст или нет совпадений.':'Договоры не найдены.'}</p>}</div></>}
 {(r||editingTemplate)&&<>
 <div className="contract-mobile-tabs"><button className={mobile==='fields'?'selected':''} onClick={()=>setMobile('fields')}>Заполнение</button><button className={mobile==='preview'?'selected':''} onClick={()=>setMobile('preview')}>Предпросмотр</button></div>
 <div className={`contract-edit-shell show-${mobile}`}><div className="contract-toolbar"><div><h2>{r?`Договор № ${r.number}`:`Шаблон: ${editingTemplate?.name}`}</h2><span className="contract-muted">{r?.archivedAt?'В архиве':r?'Изменения сохраняются автоматически':'Образец и редактирование шаблона'}</span></div><div className="contract-actions">{r&&!r.archivedAt&&<><button disabled={busy} onClick={()=>run(async()=>{await save();setNote('Черновик сохранён');})}>Сохранить</button><button className="primary" disabled={busy} onClick={()=>run(()=>act('finalize'))}>Готовая версия</button><button disabled={busy} onClick={()=>run(()=>output('download'))}>Скачать</button></>}{editingTemplate&&<button className="primary" disabled={busy} onClick={()=>run(async()=>{const d=await api({action:'template',template:editingTemplate,revision:editingTemplate.revision});setEditingTemplate(d.template);templateDirty.current=false;setNote('Шаблон сохранён для новых договоров');})}>Сохранить шаблон</button>}<button disabled={busy} onClick={()=>run(listView)}>← К списку</button></div></div>
 <div className="contract-editor-layout"><section className="contract-panel contract-fields" onFocusCapture={editorFocus}><fieldset disabled={busy||Boolean(r?.archivedAt)}>
 {editingTemplate?textEditor(editingTemplate,changeTemplate):r?<>
 <label>Клиент из CRM<select value={r.clientId} onChange={e=>{const c=clients.find(c=>c.id===e.target.value);edit({...r,clientId:e.target.value,fields:{...r.fields,...(c?{fio:c.name,phone:c.phone,deliveryCity:c.city}:{})}});}}><option value="">Ввести вручную / выбрать позже</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name} · {c.phone}</option>)}</select></label>
 <label data-editor-field="market">Рынок<select value={r.fields.market} onChange={e=>field('market',e.target.value)}>{r.template.id==='other'&&<option value="">Выберите рынок</option>}{Object.entries(markets).filter(([id])=>(id==='japan')===(r.template.id==='japan')).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 <label data-editor-field="offerUrl">Ссылка на автомобиль<input type="url" placeholder="https://avtocena.com/cars/offer/…" value={r.fields.offerUrl||''} onChange={e=>field('offerUrl',e.target.value)}/></label><button type="button" onClick={()=>run(()=>act('import'))}>Подставить автомобиль и обновить расчёт</button>
 {fieldGroups.map(g=><details key={g.title} open={g.title==='Клиент'}><summary>{g.title}</summary><div className="contract-form-grid">{g.fields.map(([key,label])=><label data-editor-field={key} key={key} className={['address','passportIssued','car'].includes(key)?'wide':''}>{label}{['fio','birthDate','passportSeries','passportNumber','passportIssued','passportDate','passportCode','address','phone','date','deliveryCity','deliveryDays','car'].includes(key)&&<em> *</em>}{dateKeys.has(key)?<CrmDateInput name={key} value={r.fields[key]||''} onChange={v=>field(key,v)}/>:<input value={r.fields[key]||''} onChange={e=>field(key,e.target.value)} maxLength={2000}/>}</label>)}</div></details>)}
 <details><summary>Расчёт вручную</summary><p className="contract-muted">Для автомобиля вне каталога или согласованного расчёта.</p><div className="contract-form-grid">{[['manualTotal','Итого под ключ, ₽'],['manualCommission','Комиссия, ₽'],['manualDeposit','Обеспечительный платёж, ₽'],['manualRate','Курс (например, 1 USD = 95 ₽)'],['manualRateDate','Дата курса'],['manualExpenses','Расшифровка расходов']].map(([key,label])=><label data-editor-field={key} key={key}>{label}{dateKeys.has(key)?<CrmDateInput name={key} value={r.fields[key]||''} onChange={v=>field(key,v)}/>:<input value={r.fields[key]||''} onChange={e=>field(key,e.target.value)}/>}</label>)}</div><button type="button" onClick={()=>run(()=>act('manual'))}>Сохранить ручной расчёт</button></details>
 <details><summary>Текст этого договора</summary>{textEditor(r.template,template=>edit({...r,template}))}</details> </>:null}</fieldset>
 {r&&r.versions.length>0&&<details className="contract-versions"><summary>Готовые версии · {r.versions.length}</summary>{r.versions.slice().reverse().map(v=><article className="contract-version" key={v.version}><strong>Версия {v.version} · {formatDate(v.fields.date)}</strong><div className="contract-actions"><button disabled={busy} onClick={()=>run(()=>output('preview',v.version))}>Открыть</button><button disabled={busy} onClick={()=>run(()=>output('download',v.version))}>Скачать</button><button disabled={busy} onClick={()=>run(()=>output('share',v.version))}>Отправить</button><button disabled={busy} onClick={()=>run(()=>output('print',v.version))}>Печать</button><button disabled={busy||!r.clientId||Boolean(r.archivedAt)} onClick={()=>run(()=>attach(v.version))}>Прикрепить к клиенту</button></div></article>)}</details>}
 </section>{preview}</div></div></>}
 {shareFile&&<div className="contract-actions"><button onClick={()=>{navigator.share({files:[shareFile],title:shareFile.name}).then(()=>setShareFile(null)).catch(e=>{if(e.name!=='AbortError')setError('Не удалось открыть отправку. Скачайте PDF и прикрепите его в чате.');});}}>Выбрать, куда отправить</button><button onClick={()=>setShareFile(null)}>Отмена</button></div>}
 {pdf&&<Suspense fallback={<p>Открываем PDF…</p>}><PdfPreview blob={pdf.blob} filename={pdf.name} onClose={()=>setPdf(null)}/></Suspense>}
 </div>;
}
