'use client';
import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {CrmDateInput} from '../CrmDateInput';
import {documentBlocks,fieldGroups,dateKeys,formatDate,markets,money,type ContractRecord,type ContractTemplate,type TemplateId} from '@/lib/contracts/model';
import './contracts.css';
const PdfPreview=lazy(()=>import('../../catalog/OfferPdfPreview'));
type Client={id:string;name:string;phone:string;city:string};
type ListItem={id:string;number:string;client:string;car:string;updatedAt:string;versions:number};
async function api(body:unknown){const res=await fetch('/api/crm/contracts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.error||'Не удалось сохранить.');return data;}
async function read(query=''){const res=await fetch('/api/crm/contracts'+query,{cache:'no-store'});const data=await res.json();if(!res.ok)throw Error(data.error||'Не удалось загрузить.');return data;}
function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
export function ContractWorkspace({owner,clients}:{owner:boolean;clients:Client[]}){
 const [tab,setTab]=useState<'contracts'|'templates'>('contracts'),[list,setList]=useState<ListItem[]>([]),[q,setQ]=useState(''),[r,setR]=useState<ContractRecord|null>(null),[editingTemplate,setEditingTemplate]=useState<ContractTemplate|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[mobile,setMobile]=useState('fields'),[pdf,setPdf]=useState<{blob:Blob;name:string}|null>(null),[shareFile,setShareFile]=useState<File|null>(null);
 const current=useRef(r),dirty=useRef(false),pending=useRef<Promise<ContractRecord|null>|null>(null);current.current=r;
 function apply(next:ContractRecord|null){current.current=next;setR(next);}
 function edit(next:ContractRecord){dirty.current=true;apply(next);setNote('Есть несохранённые изменения');}
 function field(k:string,v:string){const x=current.current;if(x)edit({...x,fields:{...x.fields,[k]:v}});}
 async function save():Promise<ContractRecord|null>{if(pending.current){await pending.current;return dirty.current?save():current.current;}const captured=current.current;if(!captured||!dirty.current)return captured;const promise=(async()=>{const data=await api({action:'save',id:captured.id,revision:captured.revision,fields:captured.fields,clientId:captured.clientId,template:captured.template});if(current.current===captured){dirty.current=false;apply(data.record);setNote('Черновик сохранён');}else if(current.current?.id===captured.id){apply({...current.current,revision:data.record.revision,updatedAt:data.record.updatedAt,calculation:null});}return current.current;})();pending.current=promise;try{await promise;}finally{pending.current=null;}return dirty.current?save():current.current;}
 useEffect(()=>{read().then(d=>setList(d.records)).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!dirty.current)return;const timer=setTimeout(()=>{save().catch(e=>setError(e.message));},1400);return()=>clearTimeout(timer);},[r]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить действие.');}finally{setBusy(false);}}
 async function listView(){await save();apply(null);setEditingTemplate(null);const data=await read();setList(data.records);setNote('');}
 async function create(id:TemplateId){await save();const data=await api({action:'create',templateId:id,id:crypto.randomUUID()});dirty.current=false;apply(data.record);setEditingTemplate(null);setMobile('fields');setNote('Черновик создан');}
 async function act(action:string){const saved=await save();if(!saved)return;const data=await api({action,id:saved.id,revision:saved.revision});dirty.current=false;apply(data.record);setNote(data.warning||({import:'Параметры и расчёт загружены',manual:'Ручной расчёт сохранён',finalize:'Готовая версия сохранена'} as Record<string,string>)[action]||'Сохранено');}
 async function output(mode:'preview'|'download'|'share'|'print',version?:number,templateId?:TemplateId){let query:string,name:string;if(templateId){query=`?template=${templateId}&pdf=1`;name=`Образец договора — ${templateId==='japan'?'Япония':'остальные рынки'}.pdf`;}else{const saved=await save();if(!saved)return;query=`?id=${saved.id}&pdf=1${version?`&version=${version}`:''}`;name=`Договор ${saved.number.replace('/','-')}${version?` — версия ${version}`:' — черновик'}.pdf`;}
 const response=await fetch('/api/crm/contracts'+query,{cache:'no-store'});if(!response.ok){const data=await response.json();throw Error(data.error||'Не удалось сформировать PDF.');}const blob=await response.blob();if(mode==='preview'){setPdf({blob,name});return;}if(mode==='download'){download(blob,name);return;}if(mode==='share'){const file=new File([blob],name,{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){setShareFile(file);setNote('Файл подготовлен. Нажмите «Выбрать, куда отправить».');}else{download(blob,name);setNote('PDF скачан — прикрепите его в нужном чате.');}return;}
 const url=URL.createObjectURL(blob);const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:1px;height:1px;bottom:0;right:0;border:0';frame.src=url;frame.onload=()=>{try{frame.contentWindow?.focus();frame.contentWindow?.print();setNote('Если диалог печати не открылся, скачайте PDF и выберите «Печать».');}catch{download(blob,name);setNote('Откройте скачанный PDF и выберите «Печать».');}};document.body.appendChild(frame);setTimeout(()=>{frame.remove();URL.revokeObjectURL(url);},120000);
 }
 async function attach(version:number){const saved=await save();if(!saved)return;await api({action:'attach',id:saved.id,version});setNote('Договор прикреплён к клиенту');}
 const t=editingTemplate||r?.template;
 const textEditor=(template:ContractTemplate,onChange:(t:ContractTemplate)=>void)=><div className="contract-text-editor"><p className="contract-muted">Меняйте только нужные формулировки. Подстановки в двойных скобках оставляйте без изменений.</p><label>Данные исполнителя<textarea value={template.agent} rows={5} onChange={e=>onChange({...template,agent:e.target.value})}/></label>{template.sections.map((s,i)=><details key={i}><summary>{s.title}</summary><label>Заголовок<input value={s.title} onChange={e=>onChange({...template,sections:template.sections.map((x,j)=>i===j?{...x,title:e.target.value}:x)})}/></label><textarea aria-label={s.title} value={s.text} rows={12} onChange={e=>onChange({...template,sections:template.sections.map((x,j)=>i===j?{...x,text:e.target.value}:x)})}/></details>)}<label>Реквизиты исполнителя<textarea rows={8} value={template.requisites} onChange={e=>onChange({...template,requisites:e.target.value})}/></label></div>;
 return <div className="contract-workspace">
 <div className="contract-tabs"><button type="button" className={tab==='contracts'?'selected':''} disabled={busy} onClick={()=>run(async()=>{await listView();setTab('contracts');})}>Договоры</button><button type="button" className={tab==='templates'?'selected':''} disabled={busy} onClick={()=>run(async()=>{await listView();setTab('templates');})}>Шаблоны</button></div>
 {error&&<p className="contract-error" role="alert">{error}</p>}{note&&<p className="contract-muted" role="status">{note}</p>}
 {!r&&!editingTemplate&&<><div className="contract-template-grid">{(['japan','other'] as const).map(id=><article className="contract-panel" key={id}><h2>{id==='japan'?'Япония':'Остальные рынки'}</h2><div className="contract-actions"><button className="primary" disabled={busy} onClick={()=>run(()=>create(id))}>Создать договор</button><button disabled={busy} onClick={()=>run(()=>output('preview',undefined,id))}>Образец</button><button disabled={busy} onClick={()=>run(()=>output('download',undefined,id))}>Скачать образец</button>{owner&&tab==='templates'&&<button disabled={busy} onClick={()=>run(async()=>setEditingTemplate((await read(`?template=${id}`)).template))}>Редактировать шаблон</button>}</div></article>)}</div>{tab==='contracts'&&<><label className="contract-search">Поиск договоров<input type="search" placeholder="Клиент, автомобиль или номер" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="contract-list">{list.filter(x=>[x.client,x.car,x.number].join(' ').toLowerCase().includes(q.toLowerCase())).map(x=><button key={x.id} className="contract-panel contract-list-item" disabled={busy} onClick={()=>run(async()=>{dirty.current=false;apply((await read(`?id=${x.id}`)).record);setMobile('fields');})}><strong>№ {x.number} · {x.client}</strong><span>{x.car||'Автомобиль не выбран'}</span><small>{x.versions?`Готовых версий: ${x.versions}`:'Черновик'} · {new Date(x.updatedAt).toLocaleDateString('ru-RU')}</small></button>)}{!list.length&&<p className="contract-muted">Пока нет договоров. Выберите шаблон выше.</p>}</div></>}</>}
 {editingTemplate&&<section className="contract-panel"><h2>Шаблон: {editingTemplate.name}</h2><fieldset disabled={busy}>{textEditor(editingTemplate,setEditingTemplate)}</fieldset><div className="contract-actions"><button className="primary" disabled={busy} onClick={()=>run(async()=>{const d=await api({action:'template',template:editingTemplate,revision:editingTemplate.revision});setEditingTemplate(d.template);setNote('Шаблон сохранён. Изменения действуют только для новых договоров.');})}>Сохранить шаблон</button><button disabled={busy} onClick={()=>{setEditingTemplate(null);setNote('');}}>Закрыть</button></div></section>}
 {r&&<><div className="contract-toolbar"><div><h2>Договор № {r.number}</h2><span className="contract-muted">{r.template.name} · черновик</span></div><div className="contract-actions"><button disabled={busy} onClick={()=>run(async()=>{await save();setNote('Черновик сохранён');})}>Сохранить</button><button disabled={busy} onClick={()=>run(listView)}>← К списку</button></div></div>
 <div className="contract-mobile-tabs"><button className={mobile==='fields'?'selected':''} onClick={()=>setMobile('fields')}>Заполнение</button><button className={mobile==='preview'?'selected':''} onClick={()=>setMobile('preview')}>Предпросмотр</button></div>
 <div className={`contract-editor-layout show-${mobile}`}><section className="contract-panel contract-fields"><fieldset disabled={busy}>
 <label>Клиент из CRM<select value={r.clientId} onChange={e=>{const c=clients.find(c=>c.id===e.target.value);edit({...r,clientId:e.target.value,fields:{...r.fields,...(c?{fio:c.name,phone:c.phone,deliveryCity:c.city}:{})}});}}><option value="">Ввести вручную / выбрать позже</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name} · {c.phone}</option>)}</select></label>
 <label>Рынок<select value={r.fields.market} onChange={e=>field('market',e.target.value)}>{r.template.id==='other'&&<option value="">Выберите рынок</option>}{Object.entries(markets).filter(([id])=>(id==='japan')===(r.template.id==='japan')).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 <label>Ссылка на автомобиль<input type="url" placeholder="https://avtocena.com/cars/offer/…" value={r.fields.offerUrl||''} onChange={e=>field('offerUrl',e.target.value)}/></label><button type="button" onClick={()=>run(()=>act('import'))}>Подставить автомобиль и обновить расчёт</button>
 {fieldGroups.map(g=><details key={g.title} open={g.title!=='Автомобиль'}><summary>{g.title}</summary><div className="contract-form-grid">{g.fields.map(([key,label])=><label key={key} className={['address','passportIssued','car'].includes(key)?'wide':''}>{label}{['fio','birthDate','passportSeries','passportNumber','passportIssued','passportDate','passportCode','address','phone','date','deliveryCity','deliveryDays','car'].includes(key)&&<em> *</em>}{dateKeys.has(key)?<CrmDateInput name={key} value={r.fields[key]||''} onChange={v=>field(key,v)}/>:<input value={r.fields[key]||''} onChange={e=>field(key,e.target.value)} maxLength={2000}/>}</label>)}</div></details>)}
 <details><summary>Расчёт вручную</summary><p className="contract-muted">Для автомобиля вне каталога или согласованного расчёта.</p><div className="contract-form-grid">{[['manualTotal','Итого под ключ, ₽'],['manualCommission','Комиссия, ₽'],['manualDeposit','Обеспечительный платёж, ₽'],['manualRate','Курс (например, 1 USD = 95 ₽)'],['manualRateDate','Дата курса'],['manualExpenses','Расшифровка расходов']].map(([key,label])=><label key={key}>{label}{dateKeys.has(key)?<CrmDateInput name={key} value={r.fields[key]||''} onChange={v=>field(key,v)}/>:<input value={r.fields[key]||''} onChange={e=>field(key,e.target.value)}/>}</label>)}</div><button type="button" onClick={()=>run(()=>act('manual'))}>Сохранить ручной расчёт</button></details>
 <details><summary>Текст этого договора</summary>{textEditor(r.template,template=>edit({...r,template}))}</details></fieldset></section>
 <section className="contract-panel contract-preview"><div className="contract-preview-heading"><h2>Предпросмотр</h2><button disabled={busy} onClick={()=>run(()=>output('preview'))}>Открыть PDF</button></div><div className="contract-paper"><small>ЧЕРНОВИК</small>{documentBlocks({version:0,createdAt:r.updatedAt,createdBy:r.createdBy,fields:r.fields,template:r.template,calculation:r.calculation},r.number).map((block,i)=>block.heading?<h4 key={i}>{block.text}</h4>:<p key={i}>{block.text}</p>)}</div></section></div>
 <div className="contract-panel"><div className="contract-actions"><button className="primary" disabled={busy} onClick={()=>run(()=>act('finalize'))}>Сохранить готовую версию</button><button disabled={busy} onClick={()=>run(()=>output('download'))}>Скачать черновик</button></div>{r.versions.length>0&&<h3>Готовые версии</h3>}{r.versions.slice().reverse().map(v=><article className="contract-version" key={v.version}><strong>Версия {v.version} · {formatDate(v.fields.date)}</strong><div className="contract-actions"><button disabled={busy} onClick={()=>run(()=>output('preview',v.version))}>Открыть</button><button disabled={busy} onClick={()=>run(()=>output('download',v.version))}>Скачать</button><button disabled={busy} onClick={()=>run(()=>output('share',v.version))}>Отправить</button><button disabled={busy} onClick={()=>run(()=>output('print',v.version))}>Распечатать</button><button disabled={busy||!r.clientId} onClick={()=>run(()=>attach(v.version))}>Прикрепить к клиенту</button></div></article>)}{r.clientId&&<a href={`/crm/clients/${r.clientId}`}>Открыть клиента / загрузить подписанный экземпляр →</a>}</div></>}
 {shareFile&&<div className="contract-panel contract-actions"><button onClick={()=>{navigator.share({files:[shareFile],title:shareFile.name}).then(()=>setShareFile(null)).catch(e=>{if(e.name!=='AbortError')setError('Не удалось открыть отправку. Скачайте PDF и прикрепите его в чате.');});}}>Выбрать, куда отправить</button><button onClick={()=>setShareFile(null)}>Отмена</button></div>}
 {pdf&&<Suspense fallback={<p>Открываем PDF…</p>}><PdfPreview blob={pdf.blob} filename={pdf.name} onClose={()=>setPdf(null)}/></Suspense>}
 </div>;
}
