'use client';
import {PublicSheet} from '../ui/PublicSheet';
import {ChevronDown} from 'lucide-react';
import {crmChatStyles} from './ChatStyles';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Bell,Info,Search,Send,MessageCircle,X,Users,Plus,Smile,MoreHorizontal,Check} from 'lucide-react';
import {NotificationReply} from './NotificationReply';
import {ChatDialog} from './ChatDialog';
import {CHAT_EMOJI} from '@/lib/chat-emoji';
import {TeamDiscussion} from './TeamDiscussion';
import type {ChatThread,ChatMessage} from '@/lib/crm-chat';
type Index={userId:string;threads:ChatThread[];team:{id:string;name:string;avatar?:string}[]};
type Detail={connection?:{accountId:string;name:string;phone:string};id:string;kind:string;title:string;canSend:boolean;canDiscuss?:boolean;leadId?:string;messages:ChatMessage[];info:string;media:{url:string;title:string}[];href?:string;reason?:string;members?:Index["team"];canManage?:boolean;version?:number;creatorId?:string};
const tone=(value:string)=>Array.from(value).reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,0)%6;
const time=(at:string)=>{const d=new Date(at);return Number.isFinite(+d)?d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'';};
export function ChatWorkspace({initial,initialThread=''}:{initial:Index;initialThread?:string}){
 const [index,setIndex]=useState(initial),[selected,setSelected]=useState(initialThread),[detail,setDetail]=useState<Detail|null>(null),[query,setQuery]=useState(''),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState<'customer'|'team'>('customer'),[info,setInfo]=useState(false);
 const [popup,setPopup]=useState<{kind:'room'|'members'|'emoji'|'reaction'|'actions'|'forward'|'delete';message?:ChatMessage}|null>(null),[roomTitle,setRoomTitle]=useState(''),[members,setMembers]=useState<string[]>([]),[editing,setEditing]=useState<ChatMessage|null>(null),[reply,setReply]=useState<ChatMessage|null>(null),[feedback,setFeedback]=useState('');
 const [teamDraft,setTeamDraft]=useState({text:'',replyTo:''});
 const [mobile,setMobile]=useState(false),[sheetOpen,setSheetOpen]=useState(Boolean(initialThread)),[viewport,setViewport]=useState(0);
 useEffect(()=>{const media=matchMedia('(max-width:767px)'),update=()=>{setMobile(media.matches);setViewport(window.visualViewport?.height||innerHeight);};update();media.addEventListener('change',update);window.visualViewport?.addEventListener('resize',update);return()=>{media.removeEventListener('change',update);window.visualViewport?.removeEventListener('resize',update);};},[]);
 const composer=useRef<HTMLTextAreaElement>(null),roomOperation=useRef(''),membershipVersion=useRef(0),mutation=useRef(0),posting=useRef(false);
 const selection=useRef(selected),operation=useRef(''),bottom=useRef<HTMLDivElement>(null),list=useRef<HTMLDivElement>(null),follow=useRef(true);
 function choose(id:string){setSheetOpen(Boolean(id));if(id===selected){setInfo(false);return;}setTeamDraft({text:'',replyTo:''});selection.current=id;setSelected(id);setDetail(null);setMode('customer');setInfo(false);setError('');setText('');setEditing(null);setReply(null);setPopup(null);setFeedback('');operation.current='';follow.current=true;history.replaceState(null,'',id?`/crm/chat?thread=${encodeURIComponent(id)}`:'/crm/chat');}
 useEffect(()=>{let active=true,loading=false;const controller=new AbortController();async function refresh(){if(loading||posting.current||document.visibilityState!=='visible')return;loading=true;const epoch=mutation.current;try{const [r,d]=await Promise.all([fetch('/api/crm/chat',{cache:'no-store',signal:controller.signal}),selected?fetch(`/api/crm/chat?thread=${encodeURIComponent(selected)}`,{cache:'no-store',signal:controller.signal}):Promise.resolve(null)]);const i=await r.json();if(!r.ok)throw Error(i.error);let data:Detail|null=null;if(d){data=await d.json();if(!d.ok)throw Error((data as any)?.error);}if(!active||posting.current||epoch!==mutation.current)return;setIndex(i);setDetail(data);setError('');}catch(e){if(active&&!controller.signal.aborted&&!posting.current&&epoch===mutation.current){setDetail(null);setError((e as Error).message||'Не удалось обновить чат');}}finally{loading=false;}}refresh();const timer=setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);return()=>{active=false;controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[selected]);
 useEffect(()=>{if(follow.current)bottom.current?.scrollIntoView({block:'nearest'});},[detail?.messages,sheetOpen,mobile]);
 async function post(body:any){posting.current=true;mutation.current++;try{const r=await fetch('/api/crm/chat',{method:'POST',signal:AbortSignal.timeout(20000),headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}catch(e){if(e instanceof Error&&['TimeoutError','AbortError','TypeError'].includes(e.name))throw Error('Не удалось связаться с сервером. Проверьте соединение и повторите.');throw e;}finally{posting.current=false;mutation.current++;}}
 async function start(recipientId:string){if(!recipientId||busy)return;setBusy(true);setError('');try{const d=await post({action:'create',recipientId});choose(d.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function send(){if(!text.trim()||busy||!detail?.canSend)return;const id=selected;operation.current||=crypto.randomUUID();setBusy(true);setError('');try{const d=await post({action:editing?'edit':undefined,thread:id,text,operationId:operation.current,messageId:editing?.id,version:editing?.version||0,replyToId:reply?.id});if(selection.current===id){setDetail(d);setText('');setEditing(null);setReply(null);operation.current='';follow.current=true;}}catch(e){if(selection.current===id)setError((e as Error).message);}finally{setBusy(false);}}
 async function action(body:any){if(busy)return;const id=selected;setBusy(true);setError('');try{const d=await post(body);if(selection.current===id&&d.id===id)setDetail(d);return d;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function openRoom(){setRoomTitle('');setMembers([]);roomOperation.current=crypto.randomUUID();setError('');setPopup({kind:'room'});}
 async function saveRoom(){const d=await action(popup?.kind==='members'?{action:'room-update',thread:selected,version:membershipVersion.current,participants:members}:{action:'room-create',title:roomTitle,participants:members,operationId:roomOperation.current});if(d){if(popup?.kind==='room')choose(d.id);setPopup(null);}}
 function insertEmoji(emoji:string){const el=composer.current,start=el?.selectionStart??text.length,end=el?.selectionEnd??text.length;const next=text.slice(0,start)+emoji+text.slice(end);if(next.length>3000)return;setText(next);operation.current='';setPopup(null);requestAnimationFrame(()=>{el?.focus();el?.setSelectionRange(start+emoji.length,start+emoji.length);});}
 async function react(message:ChatMessage,emoji:string){const d=await action({action:'react',thread:selected,messageId:message.id,emoji,active:!message.reactions?.find(r=>r.emoji===emoji)?.mine});if(d)setPopup(null);}
 async function forward(target:string){const d=await action({action:'forward',thread:target,sourceThread:selected,messageId:popup?.message?.id,operationId:roomOperation.current});if(d){choose(d.id);setDetail(d);}}
 function edit(message:ChatMessage){setEditing(message);setReply(null);setText(message.text);operation.current='';setPopup(null);requestAnimationFrame(()=>composer.current?.focus());}
 async function copy(message:ChatMessage){try{await navigator.clipboard.writeText(message.text);setFeedback('Текст скопирован');setPopup(null);}catch{setError('Не удалось скопировать. Выделите текст сообщения и скопируйте его.');}}
 async function markRead(){const ids=detail?.messages.filter(m=>m.unread).map(m=>m.id)||[];try{const r=await fetch('/api/crm/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});if(!r.ok)throw Error();setDetail(d=>d?{...d,messages:d.messages.map(m=>({...m,unread:false}))}:d);window.dispatchEvent(new Event('avtocena:crm-change'));}catch{setError('Не удалось отметить уведомления прочитанными');}}
 const threads=index.threads.filter(t=>`${t.title} ${t.subtitle}`.toLowerCase().includes(query.toLowerCase()));
 const conversation=<>
  <section className="ac-chat-conversation"><header className="ac-chat-toolbar"><button className="ac-chat-back" aria-label={mobile?"Свернуть чат":"К списку чатов"} onClick={()=>mobile?setSheetOpen(false):choose('')}>{mobile?<ChevronDown size={21}/>:<ArrowLeft size={21}/>}</button><strong>{detail?.title||'Выберите переписку'}</strong>{selected&&<button aria-label="Информация и медиа" onClick={()=>setInfo(true)}><Info size={21}/></button>}</header>
   {detail?.kind==='lead'&&<div className="ac-chat-modes"><button aria-pressed={mode==='customer'} onClick={()=>setMode('customer')}>Клиент · Личный кабинет</button><button aria-pressed={mode==='team'} onClick={()=>setMode('team')}>Обсуждение команды</button></div>}
   {feedback&&<p role="status" className="ac-chat-feedback">{feedback}</p>}{error&&<p role="alert" className="ac-chat-error">{error}</p>}
   {detail?.kind==='lead'&&mode==='team'?<div className="ac-chat-discussion"><TeamDiscussion key={detail.id} type="lead" entityId={detail.leadId!} label={detail.title} userId={index.userId} canReply={!!detail.canDiscuss} draft={teamDraft} onDraftChange={setTeamDraft}/></div>:<><div ref={list} className="ac-chat-messages" onScroll={()=>{const l=list.current;if(l)follow.current=l.scrollHeight-l.scrollTop-l.clientHeight<100;}}>{!selected?<div className="ac-chat-empty"><MessageCircle size={40}/><p>Откройте чат слева или выберите сотрудника.</p></div>:!detail&&!error?<p>Загружаем переписку…</p>:detail&&!detail.messages.length?<p className="ac-chat-empty">Здесь пока нет сообщений.</p>:detail?.messages.map(m=><article key={m.id} data-tone={tone(m.authorId||m.author)} className={`ac-chat-message ${`${m.mine?'is-mine':''} ${m.deleted?'is-deleted':''}`}`}><div className="ac-chat-message-head"><strong>{m.author}{m.unread?' · новое':''}</strong>{detail.kind!=='system'&&!m.deleted&&<button aria-label={`Действия с сообщением ${m.id}`} onClick={()=>{setError('');setPopup({kind:'actions',message:m});}}><MoreHorizontal size={19}/></button>}</div>{m.forwarded&&<div className="ac-chat-quote">Переслано · {m.forwarded.author} · {m.forwarded.from}</div>}{m.replyTo&&<div className="ac-chat-quote"><strong>{m.replyTo.author}</strong><p>{m.replyTo.text}</p></div>}<p>{m.text}</p>{!m.deleted&&detail.kind!=='system'&&!!m.reactions?.length&&<div className="ac-chat-reactions">{m.reactions?.map(r=><button key={r.emoji} aria-label={`Реакция ${r.emoji}: ${r.count}`} aria-pressed={r.mine} title={r.names.join(', ')} disabled={busy} onClick={()=>react(m,r.emoji)}>{r.emoji} {r.count}</button>)}</div>}{m.replyTarget&&<NotificationReply target={m.replyTarget} title={m.author} text={m.text}/ >}{m.href&&<a href={m.href}>Открыть →</a>}<small>{m.editedAt&&!m.deleted?'изменено · ':''}{time(m.createdAt)}{m.status?` · ${{sent:'Отправлено',pending:'В очереди',cancelled:'Отменено',saved:'Сохранено'}[m.status]||'Ожидает отправки'}`:''}</small></article>)}<div ref={bottom}/></div>
   {detail?.kind==='system'?<button className="ac-chat-read" onClick={markRead} disabled={!detail.messages.some(m=>m.unread)}>Отметить прочитанными</button>:detail?.canSend?<><div className="ac-chat-draft-context">{(editing||reply)&&<><span>{editing?'Редактирование':`Ответ · ${reply?.author}`}<small>{(editing||reply)?.text.slice(0,120)}</small></span><button aria-label="Отменить редактирование или ответ" onClick={()=>{setEditing(null);setReply(null);setText('');operation.current='';}}><X size={18}/></button></>}</div><form className="ac-chat-compose" onSubmit={e=>{e.preventDefault();send();}}><button type="button" className="ac-chat-emoji-button" aria-label="Выбрать смайлик" disabled={busy} onClick={()=>setPopup({kind:'emoji'})}><Smile size={22}/></button><textarea ref={composer} aria-label={detail.kind==='lead'?'Сообщение клиенту':detail.kind==='room'?'Сообщение в чат':'Сообщение сотруднику'} placeholder={detail.kind==='lead'?'Сообщение в кабинет клиента…':'Написать сообщение…'} value={text} maxLength={3000} disabled={busy} onChange={e=>{setText(e.target.value);operation.current='';}} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();send();}}}/><button aria-label={editing?"Сохранить изменения":"Отправить сообщение"} disabled={busy||!text.trim()}>{editing?<Check size={20}/>:<Send size={20}/>}</button></form></>:detail&&<div className="ac-chat-reason"><p>{detail.reason}</p>{detail.connection&&<button type="button" className="ac-chat-primary" disabled={busy} onClick={()=>{if(confirm(`Подключить кабинет ${detail.connection!.name} (${detail.connection!.phone})? Подтверждаю, что проверил личность клиента. Ему откроются переписка и документы этой карточки, отмеченные как доступные клиенту.`))void action({action:'connect-customer',thread:selected,accountId:detail.connection!.accountId,confirmed:true});}}>Подключить зарегистрированный кабинет</button>}</div>}</>}
  </section>
  <aside className="ac-chat-info"><div className="ac-chat-toolbar"><strong>Информация и медиа</strong><button aria-label="Назад к переписке" onClick={()=>setInfo(false)}><X size={20}/></button></div>{detail?<><h2>{detail.title}</h2><p>{detail.info||'Дополнительных сведений пока нет.'}</p>{detail.href&&<a className="ac-chat-record" href={detail.href}>Открыть заявку →</a>}{detail.members&&<><h3>Участники · {detail.members.length}</h3><div className="ac-chat-members">{detail.members.map(u=><div key={u.id}>{u.avatar&&<img src={u.avatar} alt=""/>}<span>{u.name}{u.id===index.userId?' · вы':''}</span></div>)}</div>{detail.canManage&&<button className="ac-chat-manage" onClick={()=>{setMembers(detail.members!.map(u=>u.id));membershipVersion.current=detail.version||0;setError('');setPopup({kind:'members'});}}>Управлять участниками</button>}</>}<h3>Медиа</h3>{detail.media.length?<div className="ac-chat-media">{detail.media.map((m,i)=><a key={i} href={m.url} target="_blank" rel="noreferrer"><img src={m.url} alt={m.title} loading="lazy"/></a>)}</div>:<p>В этой переписке пока нет медиа.</p>}</>:<p>Выберите чат, чтобы посмотреть сведения.</p>}</aside>
</>;
 return <div className="ac-chat" data-chat-screen={mobile?'list':!selected?'list':info?'info':'conversation'}>
  <aside className="ac-chat-list"><div className="ac-chat-toolbar"><strong>Переписки</strong><button aria-label="Создать комнату" onClick={openRoom}><Plus size={20}/></button></div><label className="ac-chat-search"><Search size={17}/><input aria-label="Поиск переписок" placeholder="Найти чат" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Написать сотруднику" value="" disabled={busy} onChange={e=>start(e.target.value)}><option value="">Написать сотруднику…</option>{index.team.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><div className="ac-chat-threads">{threads.map(t=><button key={t.id} title={t.title} onClick={()=>choose(t.id)} className={`ac-chat-thread ${selected===t.id?'is-active':''}`}><span className="ac-chat-avatar">{t.kind==='system'?<Bell size={20}/>:t.kind==='room'?<Users size={20}/>:t.avatar?<img src={t.avatar} alt=""/>:t.title.slice(0,2).toUpperCase()}</span><span><strong>{t.title}</strong><small>{t.subtitle}</small></span></button>)}{!threads.length&&<p className="p-4 text-sm">Переписки не найдены</p>}</div></aside>
  {mobile?sheetOpen&&selected&&<PublicSheet title={detail?.title||'Переписка'} showHeader={false} fitVisualViewport className="crm-chat-sheet" onClose={()=>setSheetOpen(false)}><div className="ac-chat crm-chat-mobile" data-chat-screen={info?'info':'conversation'} style={{height:Math.floor(viewport*.92)}}>{conversation}</div></PublicSheet>:conversation}
  {popup&&<ChatDialog key={popup.kind} title={{room:'Создать комнату',members:'Участники комнаты',emoji:'Смайлики',reaction:'Реакция на сообщение',actions:'Действия с сообщением',forward:'Переслать в чат',delete:'Удалить сообщение?'}[popup.kind]} onClose={()=>{if(!busy)setPopup(null);}}>
   {error&&<p role="alert" className="ac-chat-error">{error}</p>}
   {(popup.kind==='room'||popup.kind==='members')&&<form onSubmit={e=>{e.preventDefault();saveRoom();}}>{popup.kind==='room'&&<label className="ac-chat-room-name">Название комнаты<input autoFocus maxLength={80} value={roomTitle} required onChange={e=>{setRoomTitle(e.target.value);roomOperation.current=crypto.randomUUID();}}/></label>}<p className="ac-chat-dialog-note">Участники увидят всю историю комнаты.</p><div className="ac-chat-member-picker">{[{id:index.userId,name:'Вы'},...index.team].map(u=><label key={u.id}><input type="checkbox" checked={u.id===index.userId||members.includes(u.id)} disabled={busy||u.id===index.userId||u.id===detail?.creatorId&&popup.kind==='members'} onChange={e=>{const checked=e.target.checked;setMembers(v=>checked?[...v,u.id]:v.filter(id=>id!==u.id));roomOperation.current=crypto.randomUUID();}}/>{u.name}</label>)}</div><button className="ac-chat-primary" disabled={busy||(popup.kind==='room'&&!roomTitle.trim())}>{busy?'Сохраняем…':popup.kind==='room'?'Создать комнату':'Сохранить участников'}</button></form>}
   {(popup.kind==='emoji'||popup.kind==='reaction')&&<>{popup.kind==='reaction'&&detail?.kind==='lead'&&<p className="ac-chat-dialog-note">Эти реакции видны команде в CRM.</p>}<div className="ac-chat-emoji-grid">{CHAT_EMOJI.map(emoji=><button key={emoji} aria-label={emoji} disabled={busy} onClick={()=>popup.kind==='emoji'?insertEmoji(emoji):react(popup.message!,emoji)}>{emoji}</button>)}</div></>}
   {popup.kind==='actions'&&<div className="ac-chat-actions">{detail?.canSend&&<button onClick={()=>{setReply(popup.message!);setEditing(null);setPopup(null);requestAnimationFrame(()=>composer.current?.focus());}}>Ответить</button>}<button onClick={()=>copy(popup.message!)}>Копировать текст</button><button onClick={()=>{roomOperation.current=crypto.randomUUID();setPopup({...popup,kind:'forward'});}}>Переслать</button><button onClick={()=>setPopup({...popup,kind:'reaction'})}>Добавить реакцию</button>{popup.message?.mine&&detail?.kind!=='lead'&&<><button onClick={()=>edit(popup.message!)}>Редактировать</button><button className="ac-chat-danger" onClick={()=>setPopup({...popup,kind:'delete'})}>Удалить</button></>}{detail?.kind==='lead'&&<p className="ac-chat-dialog-note">Редактирование и удаление отправленных сообщений клиенту пока недоступны.</p>}</div>}
   {popup.kind==='forward'&&<div className="ac-chat-actions"><p className="ac-chat-dialog-note">Сообщение станет доступно участникам выбранной переписки.</p>{index.threads.filter(t=>t.kind==='team'||t.kind==='room').map(t=><button key={t.id} disabled={busy} onClick={()=>forward(t.id)}>{t.title}</button>)}</div>}
   {popup.kind==='delete'&&<><p className="ac-chat-dialog-note">Текст будет удалён у всех участников этой переписки.</p><button className="ac-chat-primary ac-chat-danger" disabled={busy} onClick={async()=>{if(await action({action:'delete',thread:selected,messageId:popup.message!.id,version:popup.message!.version||0}))setPopup(null);}}>Удалить у всех</button></>}
  </ChatDialog>}
  <style>{crmChatStyles}</style>
 </div>;
}
