"use client";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";
import { DarkSelect } from "./DarkSelect";
const types: Record<string,string>={passport:"Паспорт",driver_license:"Водительское удостоверение",contract:"Договор",power_of_attorney:"Доверенность",payment:"Платёжный документ",other:"Произвольный документ"};
export function ClientDocuments({ client }: { client: any }) { const router=useRouter(); const op=useRef(crypto.randomUUID()); const [documentType,setType]=useState("passport"); const [description,setDescription]=useState(""); const [file,setFile]=useState<File|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function upload(){ if(!file){setError("Выберите файл");return;} setLoading(true);setError(""); try{const fd=new FormData(); fd.set("file",file); fd.set("documentType",documentType); fd.set("description",description); fd.set("operationId",op.current); const res=await fetch(`/api/crm/documents/${client.id}`,{method:"POST",body:fd}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error||"upload_failed"); op.current=crypto.randomUUID(); setFile(null); setDescription(""); router.refresh();}catch(e){setError(e instanceof Error?e.message:"upload_failed");}finally{setLoading(false);}}
 async function remove(doc:any){ const id=doc.id; if(!confirm("Удалить документ?")) return; setLoading(true); try{const res=await fetch(`/api/crm/documents/${client.id}/${id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({operationId:doc.deletingOperationId||crypto.randomUUID()})}); if(!res.ok) throw new Error("delete_failed"); router.refresh();}catch(e){setError(e instanceof Error?e.message:"delete_failed");}finally{setLoading(false);}}
 return <section className="glass rounded-[2rem] p-6"><h2 className="text-xl font-black">Документы</h2><div className="mt-4 grid gap-3"><DarkSelect label="Тип документа" name="documentType" value={documentType} onChange={setType} options={Object.entries(types).map(([value,label])=>({value,label}))}/><input type="file" onChange={(e)=>setFile(e.target.files?.[0]||null)} className="soft-input rounded-2xl px-4 py-3 text-sm font-bold"/><input value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="Комментарий" className="soft-input rounded-2xl px-4 py-3 text-sm font-bold"/><button disabled={loading} onClick={upload} className="avto-button rounded-2xl px-4 py-3 font-black disabled:opacity-60">{loading?"Загрузка...":"Загрузить документ"}</button>{error&&<div className="rounded-2xl bg-red-500/15 px-4 py-3 text-sm font-bold text-red-100">{error}</div>}</div><div className="mt-5 space-y-3">{(client.documents||[]).map((d:any)=><div key={d.id} className="rounded-2xl bg-white/7 p-3 text-sm font-bold"><div>{types[d.documentType]||d.documentType} · {d.originalName||d.fileName}</div><div className="mt-1 text-xs text-white/45">{d.status==="deleting"?"Удаление не завершено":`SHA-256 ${String(d.checksum||"").slice(0,16)}… · ${d.size} байт`}</div><div className="mt-3 flex gap-2">{d.status!=="deleting"&&<a className="rounded-xl bg-white/10 px-3 py-2 text-white" href={`/api/crm/documents/${client.id}/${d.id}`}>Скачать</a>}<button onClick={()=>remove(d)} className="rounded-xl bg-red-500/20 px-3 py-2 text-red-100">{d.status==="deleting"?"Повторить удаление":"Удалить"}</button></div></div>)}{!(client.documents||[]).length&&<p className="text-sm font-bold text-white/50">Документы ещё не загружены.</p>}</div></section> }
