"use client";
import { useRouter } from "next/navigation";
import { useRef, useState } from "react";

const fields = [["fio","ФИО"],["phone","Телефон"],["telegram","Telegram"],["city","Город"],["birthDate","Дата рождения"],["passport","Паспортные данные"],["address","Адрес"],["interestedCar","Интересующий автомобиль"],["market","Рынок"],["budgetRub","Бюджет"],["source","Источник"]] as const;
export function ClientEditor({ client, managers }: { client: any; managers: any[] }) {
  const router = useRouter(); const op = useRef(crypto.randomUUID()); const [form,setForm]=useState<any>({...client}); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [saved,setSaved]=useState(false);
  const update=(key:string,value:string)=>setForm((f:any)=>({...f,[key]:value}));
  async function save(extra:any={}) { setLoading(true); setError(""); setSaved(false); try { const res=await fetch("/api/crm/clients",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:client.id,operationId:op.current,...form,...extra})}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error||"save_failed"); setSaved(true); op.current=crypto.randomUUID(); router.refresh(); } catch(e){ setError(e instanceof Error ? e.message : "save_failed"); } finally { setLoading(false); } }
  return <section className="glass rounded-[2rem] p-6"><h2 className="text-2xl font-black">Данные клиента</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{fields.map(([k,p])=><input key={k} value={form[k] ?? ""} onChange={(e)=>update(k,e.target.value)} placeholder={p} className="soft-input rounded-2xl px-4 py-3 text-sm font-bold" />)}<select value={form.assignedManagerId||""} onChange={(e)=>update("assignedManagerId",e.target.value)} className="soft-input rounded-2xl bg-zinc-950 px-4 py-3 text-sm font-bold text-white">{managers.map((m)=><option key={m.id} value={m.id}>{m.displayName}</option>)}</select><textarea value={form.comments||form.comment||""} onChange={(e)=>update("comments",e.target.value)} placeholder="Комментарии" className="soft-input resize-none rounded-2xl px-4 py-3 text-sm font-bold md:col-span-2" rows={4}/></div>{error&&<div className="mt-4 rounded-2xl bg-red-500/15 px-4 py-3 text-sm font-bold text-red-100">{error}</div>}{saved&&<div className="mt-4 rounded-2xl bg-emerald-500/15 px-4 py-3 text-sm font-bold text-emerald-100">Изменения сохранены</div>}<div className="mt-5 flex flex-wrap gap-3"><button disabled={loading} onClick={()=>save()} className="avto-button rounded-2xl px-5 py-3 font-black disabled:opacity-60">{loading?"Сохраняем...":"Сохранить"}</button>{client.status==="archived"?<button disabled={loading} onClick={()=>save({restore:true})} className="rounded-2xl bg-emerald-500/20 px-5 py-3 font-black text-emerald-100">Восстановить</button>:<button disabled={loading} onClick={()=>confirm("Архивировать клиента?")&&save({archive:true})} className="rounded-2xl bg-white/10 px-5 py-3 font-black text-white">В архив</button>}</div></section>
}
