'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
export function DeleteCrmRecord({kind,id}:{kind:'client'|'lead';id:string}){
 const router=useRouter(),dialog=useRef<HTMLDialogElement>(null);
 const [preview,setPreview]=useState<{label:string;revision:string;blockers:string[];requiresTestConfirmation?:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[testConfirmed,setTestConfirmed]=useState(false);
 const url=`/api/crm/delete/${kind}/${encodeURIComponent(id)}`,label=kind==='client'?'клиента':'заявку';
 async function open(){setBusy(true);setError('');setConfirmed(false);setTestConfirmed(false);try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error();setPreview(await r.json());dialog.current?.showModal();}catch{setError('Не удалось проверить запись. Обновите страницу и повторите.');}finally{setBusy(false);}}
 async function remove(){if(!preview||!confirmed||(preview.requiresTestConfirmation&&!testConfirmed))return;setBusy(true);setError('');try{const r=await fetch(url,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({confirm:id,revision:preview.revision,confirmTestRecord:testConfirmed})});if(!r.ok){const result=await r.json();throw Error(result.error);}dialog.current?.close();router.push(kind==='client'?'/crm/clients':'/crm/leads');router.refresh();}catch(e){setError(e instanceof Error&&['delete_conflict','delete_linked'].includes(e.message)?'Запись изменилась или появились связанные данные. Закройте окно и проверьте её заново.':'Удалить не удалось. Обновите страницу и повторите.');}finally{setBusy(false);}}
 return <div className="my-3"><button type="button" disabled={busy} onClick={open} className="rounded-xl border border-red-500/40 px-4 py-2 text-sm font-bold text-red-500">Удалить {label}</button><dialog ref={dialog} onCancel={e=>{if(busy)e.preventDefault();}} className="m-auto w-[calc(100%_-_24px)] max-w-lg rounded-2xl border border-[var(--ac-border)] bg-[var(--ac-surface,#202836)] p-6 text-[var(--ac-text)] backdrop:bg-black/70"><h2 className="text-xl font-black">Удалить {label}?</h2><p className="my-3 break-words font-semibold">{preview?.label}</p>{preview?.blockers.length?<ul className="my-4 list-disc space-y-2 pl-5 text-sm">{preview.blockers.map(b=><li key={b}>{b}</li>)}</ul>:<><p className="my-3 text-sm leading-6">{kind==='lead'?'Заявка и её дополнения исчезнут из CRM. Карточка клиента останется.':'Карточка клиента и её комментарии исчезнут из CRM.'} Восстановить запись через интерфейс нельзя.</p>{preview?.requiresTestConfirmation?<label className="my-4 flex items-start gap-3 text-sm"><input type="checkbox" checked={testConfirmed} onChange={e=>setTestConfirmed(e.target.checked)} className="mt-1 h-5 w-5"/>Это тестовая заявка. Статусы договора или оплаты выставлены для проверки, реального договора и оплаты не было.</label>:null}<label className="my-4 flex items-start gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 h-5 w-5"/>Подтверждаю удаление этой записи</label></>}{error?<p role="alert" className="my-3 text-sm text-red-500">{error}</p>:null}<div className="mt-5 flex flex-wrap justify-end gap-3"><button autoFocus type="button" disabled={busy} onClick={()=>dialog.current?.close()} className="rounded-xl border border-[var(--ac-border)] px-5 py-3 font-bold">Отмена</button>{!preview?.blockers.length?<button type="button" disabled={busy||!confirmed||Boolean(preview?.requiresTestConfirmation&&!testConfirmed)} onClick={remove} className="rounded-xl bg-red-600 px-5 py-3 font-bold text-white disabled:opacity-40">{busy?'Удаляем…':'Удалить'}</button>:null}</div></dialog>{error&&!dialog.current?.open?<p role="alert" className="mt-2 text-sm text-red-500">{error}</p>:null}</div>;
}
