'use client';
import {useEffect,useState} from 'react';
import {Bell,Check,X} from 'lucide-react';
import type {CrmReminder} from '../../lib/crm-reminders';
import {crmDateTime} from '../../lib/crm-time';
const changed=()=>{window.dispatchEvent(new Event('avtocena:reminders'));window.dispatchEvent(new Event('avtocena:crm-change'));};
async function done(id:string){const r=await fetch('/api/crm/reminders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'done',id})});if(!r.ok)throw Error('Не удалось отметить выполнение.');changed();}
function ReminderRows({rows,onChange}:{rows:CrmReminder[];onChange:()=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState('');return <>{rows.map(row=><div key={row.id} className="crm-reminder-row"><a href={row.entityType==='client'?`/crm/clients/${encodeURIComponent(row.entityId)}`:`/crm/leads?id=${encodeURIComponent(row.entityId)}`}><strong>{row.entityLabel}</strong><span>{row.text}</span><time>{crmDateTime(row.dueAt)}</time></a><button type="button" aria-label="Напоминание выполнено" disabled={busy===row.id} onClick={async()=>{setBusy(row.id);setError('');try{await done(row.id);onChange();}catch(e){setError((e as Error).message);}finally{setBusy('');}}}><Check size={20}/></button></div>)}{error?<p role="alert">{error}</p>:null}</>;}
export function ReminderButton({entityType,entityId}:{entityType:'client'|'lead';entityId:string}){
 const [open,setOpen]=useState(false),[text,setText]=useState(''),[date,setDate]=useState(''),[rows,setRows]=useState<CrmReminder[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){try{const r=await fetch(`/api/crm/reminders?entityId=${encodeURIComponent(entityId)}`,{cache:'no-store'});if(!r.ok)throw Error();setRows((await r.json()).reminders||[]);}catch{setError('Не удалось загрузить напоминания.');}}
 useEffect(()=>{if(open)void refresh();},[open,entityId]);
 return <section className="crm-reminder-editor my-4"><button type="button" className="soft-input inline-flex min-h-11 items-center gap-2 rounded-xl px-4" aria-expanded={open} onClick={()=>setOpen(!open)}><Bell size={18}/>Напоминание</button>{open?<div className="mt-3 rounded-2xl border border-[var(--ac-border)] p-4"><p className="mb-3 text-sm text-[var(--ac-muted)]">Личное напоминание · время Новокузнецка. Колокольчик загорится при наступлении срока; пропущенные напоминания останутся до выполнения.</p><form className="grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/crm/reminders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entityType,entityId,text,dueAt:new Date(`${date}:00+07:00`).toISOString()})});const d=await r.json();if(!r.ok)throw Error(d.error);setText('');setDate('');changed();await refresh();}catch(e){setError((e as Error).message||'Не удалось сохранить.');}finally{setBusy(false);}}}><label className="grid gap-2 text-sm">Дата и время<input type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)} className="soft-input min-w-0 rounded-xl p-3"/></label><label className="grid gap-2 text-sm">Что сделать<input required maxLength={1000} value={text} onChange={e=>setText(e.target.value)} placeholder="Позвонить и уточнить решение" className="soft-input min-w-0 rounded-xl p-3"/></label><button disabled={busy} className="avto-button min-h-11 rounded-xl px-4 sm:col-span-2">{busy?'Сохраняем…':'Добавить напоминание'}</button></form>{error?<p role="alert" className="mt-3 text-sm">{error}</p>:null}<ReminderRows rows={rows} onChange={()=>void refresh()}/></div>:null}</section>;
}
export function RemindersBell(){
 const [rows,setRows]=useState<CrmReminder[]>([]),[open,setOpen]=useState(false);
 useEffect(()=>{let active=true,busy=false;const refresh=async()=>{if(busy||document.visibilityState!=='visible')return;busy=true;try{const r=await fetch('/api/crm/reminders?due=1',{cache:'no-store'});if(r.status===401||r.status===403){if(active)setRows([]);return;}if(r.ok&&active)setRows((await r.json()).reminders||[]);}catch{}finally{busy=false;}};void refresh();const timer=setInterval(refresh,30_000);window.addEventListener('avtocena:reminders',refresh);document.addEventListener('visibilitychange',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('avtocena:reminders',refresh);document.removeEventListener('visibilitychange',refresh);};},[]);
 return <div className="crm-reminder-bell"><button type="button" className={`ac-staff-account ${rows.length?'crm-reminder-due':''}`} aria-label={`Напоминания: ${rows.length}`} aria-expanded={open} onClick={()=>setOpen(!open)}><Bell size={19}/>{rows.length?<span className="ac-staff-badge">{rows.length}</span>:null}</button>{open?<div className="crm-reminder-popover"><div className="flex items-center justify-between gap-2"><strong>Пора связаться</strong><button type="button" onClick={()=>setOpen(false)} aria-label="Закрыть напоминания"><X size={20}/></button></div>{rows.length?<ReminderRows rows={rows} onChange={()=>changed()}/>:<p className="mt-3 text-sm">Просроченных напоминаний нет.</p>}</div>:null}</div>;
}
