'use client';
import {useEffect,useState,useRef} from 'react';
import {AlarmClock,Check} from 'lucide-react';
import type {CrmReminder} from '../../lib/crm-reminders';
import {crmDateTime} from '../../lib/crm-time';
export const remindersChanged=()=>{window.dispatchEvent(new Event('avtocena:reminders'));window.dispatchEvent(new Event('avtocena:crm-change'));};
export function ReminderRows({rows,onChange}:{rows:CrmReminder[];onChange:()=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState('');return <>{rows.map(row=><div id={`reminder-${row.id}`} key={row.id} className="crm-reminder-row"><div className="crm-reminder-copy">{row.canOpen!==false?<a href={row.entityType==='client'?`/crm/clients/${encodeURIComponent(row.entityId)}#reminders-client-${encodeURIComponent(row.entityId)}`:`/crm/leads?id=${encodeURIComponent(row.entityId)}#reminders-lead-${encodeURIComponent(row.entityId)}`}><strong>{row.entityLabel}</strong></a>:<strong>{row.entityLabel}</strong>}<span>{row.text}</span><time>{crmDateTime(row.dueAt)}</time><small>Создал: {row.ownerName||'Сотрудник'}</small></div><button type="button" aria-label="Напоминание выполнено" title="Отметить выполненным" disabled={busy===row.id} onClick={async()=>{setBusy(row.id);setError('');try{const r=await fetch('/api/crm/reminders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'done',id:row.id})});if(!r.ok)throw Error('Не удалось отметить выполнение.');remindersChanged();onChange();}catch(e){setError((e as Error).message);}finally{setBusy('');}}}><Check size={20}/></button></div>)}{error?<p role="alert">{error}</p>:null}</>;}
export function ReminderButton({entityType,entityId}:{entityType:'client'|'lead';entityId:string}){
 const root=useRef<HTMLElement>(null);
 const anchor=`reminders-${entityType}-${entityId}`;
 const [open,setOpen]=useState(false),[text,setText]=useState(''),[date,setDate]=useState(''),[rows,setRows]=useState<CrmReminder[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const reveal=()=>{let hash='';try{hash=decodeURIComponent(location.hash.slice(1));}catch{}if(hash===anchor){const details=root.current?.closest('details');if(details)details.open=true;setOpen(true);requestAnimationFrame(()=>root.current?.scrollIntoView({block:'start'}));}};reveal();window.addEventListener('hashchange',reveal);return()=>window.removeEventListener('hashchange',reveal);},[anchor]);
 async function refresh(){try{const r=await fetch(`/api/crm/reminders?entityId=${encodeURIComponent(entityId)}`,{cache:'no-store'});if(!r.ok)throw Error();setRows((await r.json()).reminders||[]);}catch{setError('Не удалось загрузить напоминания.');}}
 useEffect(()=>{if(open)void refresh();},[open,entityId]);
 return <section ref={root} id={anchor} className="crm-reminder-editor my-4"><button type="button" className="soft-input inline-flex min-h-11 items-center gap-2 rounded-xl px-4" aria-expanded={open} onClick={()=>setOpen(!open)}><AlarmClock size={18}/>Напоминание</button>{open?<div className="mt-3 rounded-2xl border border-[var(--ac-border)] p-4"><p className="mb-3 text-sm text-[var(--ac-muted)]">Видно всей команде · время Новокузнецка</p><form className="crm-reminder-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/crm/reminders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entityType,entityId,text,dueAt:new Date(`${date}:00+07:00`).toISOString()})});const d=await r.json();if(!r.ok)throw Error(d.error);setText('');setDate('');remindersChanged();await refresh();}catch(e){setError((e as Error).message||'Не удалось сохранить.');}finally{setBusy(false);}}}>
 <label className="crm-reminder-text">Что сделать<textarea required rows={3} maxLength={1000} value={text} onChange={e=>setText(e.target.value)} placeholder="Позвонить и уточнить решение" className="soft-input rounded-xl p-3"/></label>
 <label className="crm-reminder-date">Дата и время<input type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)} className="crm-reminder-datetime soft-input rounded-xl" aria-label="Дата и время напоминания"/></label>
 <button disabled={busy} className="avto-button crm-reminder-save rounded-xl px-4">{busy?'Сохраняем…':'Добавить напоминание'}</button></form>{error?<p role="alert" className="mt-3 text-sm">{error}</p>:null}<ReminderRows rows={rows} onChange={()=>void refresh()}/></div>:null}</section>;
}
