'use client';
import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {FileText,Upload,Eye,Download,Trash2,X} from 'lucide-react';
import type {ClientDocument} from '../../lib/client-documents';
import {crmDateTime} from '../../lib/crm-time';
const PdfPreview=lazy(()=>import('../catalog/OfferPdfPreview'));
function Preview({document,url,onClose}:{document:ClientDocument;url:string;onClose:()=>void}){const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();},[]);return <dialog ref={dialog} className="crm-staff-document-preview" onClose={onClose}><header><strong>{document.name}</strong><button type="button" aria-label="Закрыть документ" onClick={onClose}><X size={22}/></button></header>{document.mime.startsWith('image/')?<img src={url} alt={document.name}/>:<iframe title={document.name} src={url}/>}</dialog>;}
export function StaffDocuments({userId,canManage}:{userId:string;canManage:boolean}){
 const [documents,setDocuments]=useState<ClientDocument[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<ClientDocument|null>(null),[loaded,setLoaded]=useState(false),[pdf,setPdf]=useState<{blob:Blob;name:string}|null>(null);const base=`/api/crm/users/${encodeURIComponent(userId)}/documents`;
 async function refresh(){const r=await fetch(base,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setDocuments(d.documents);setLoaded(true);}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[userId]);
 return <section id="staff-documents" className="glass mt-5 rounded-3xl p-5"><div className="crm-staff-documents-heading"><h2 className="text-xl font-bold">Документы сотрудника</h2>{canManage?<label className="avto-button inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm"><Upload size={17}/>{busy?'Загружаем…':'Добавить документ'}<input type="file" className="sr-only" disabled={busy} accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.xlsx" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);const r=await fetch(base,{method:'POST',body:form}),d=await r.json();if(!r.ok)throw Error(d.error);await refresh();window.dispatchEvent(new Event('avtocena:crm-change'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label>:null}</div><p className="mt-2 text-sm text-[var(--ac-muted)]">Скан паспорта и документы для оформления · до 5 МБ на файл. Доступ: сотрудник и руководители с правом управления командой.</p>
 {error?<p role="alert" className="mt-3">{error}</p>:null}{loaded&&!documents.length?<p className="mt-4 text-sm text-[var(--ac-muted)]">Документов пока нет.</p>:null}
 <div className="crm-staff-document-list">{documents.map(doc=><article key={doc.id}><FileText size={22}/><div><strong>{doc.name}</strong><small>{crmDateTime(doc.createdAt)} · {Math.ceil(doc.size/1024)} КБ</small></div><div className="crm-staff-document-actions">{doc.mime.startsWith('image/')||doc.mime==='application/pdf'?<button type="button" aria-label={`Просмотреть ${doc.name}`} title="Просмотреть" onClick={async()=>{if(!window.confirm(`Открыть документ «${doc.name}»?`))return;if(doc.mime!=='application/pdf'){setPreview(doc);return;}setBusy(true);setError('');try{const r=await fetch(`${base}/${doc.id}?confirmed=1`,{cache:'no-store'});if(!r.ok)throw Error('Не удалось открыть документ.');setPdf({blob:await r.blob(),name:doc.name});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Eye size={18}/></button>:null}<a href={`${base}/${doc.id}?confirmed=1&download=1`} aria-label={`Скачать ${doc.name}`} title="Скачать" onClick={e=>{if(!window.confirm(`Скачать документ «${doc.name}» на это устройство?`))e.preventDefault();}}><Download size={18}/></a>{canManage?<button type="button" disabled={busy} aria-label={`Удалить ${doc.name}`} title="Удалить" onClick={async()=>{if(!window.confirm(`Удалить документ «${doc.name}» без возможности восстановления?`))return;setBusy(true);setError('');try{const r=await fetch(`${base}/${doc.id}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({confirmed:true})});if(!r.ok)throw Error((await r.json()).error);await refresh();window.dispatchEvent(new Event('avtocena:crm-change'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Trash2 size={18}/></button>:null}</div></article>)}</div>
 {pdf?<Suspense fallback={<p role="status">Открываем PDF…</p>}><PdfPreview confirmDownload blob={pdf.blob} filename={pdf.name} onClose={()=>setPdf(null)}/></Suspense>:null}{preview?<Preview document={preview} url={`${base}/${preview.id}?confirmed=1`} onClose={()=>setPreview(null)}/>:null}</section>;
}
