'use client';
import {useState} from 'react';
import {CRM_PERMISSIONS,CRM_PERMISSION_GROUPS,hasCrmPermission,isAdministrativeCrmPermission,permissionDefaults,ROLE_DETAILS,type CrmPermission,type CrmPermissions} from '../../lib/crm-permissions';
import type {AuthUser} from '../../lib/auth';
export function StaffPermissions({role:initial='manager',permissions={},owner=false}:{role?:string;permissions?:CrmPermissions;owner?:boolean}){
 const [role,setRole]=useState(initial),[values,setValues]=useState(()=>Object.fromEntries((Object.keys(CRM_PERMISSIONS) as CrmPermission[]).map(key=>[key,hasCrmPermission({role:initial,permissions} as AuthUser,key)])) as Record<CrmPermission,boolean>);
 return <><label className="grid gap-2 text-xs font-black normal-case tracking-normal text-[var(--ac-muted)]">Роль<select aria-label="Роль" name="role" value={role} onChange={e=>{setRole(e.target.value);setValues(permissionDefaults(e.target.value));}} className="soft-input rounded-xl px-4 py-3 text-sm font-black normal-case tracking-normal"><option value="dealer">Дилер — только свой кабинет</option><option value="manager">Менеджер</option><option value="admin">Администратор</option>{owner||initial==='owner'?<option value="owner">Владелец</option>:null}</select></label>
 {role!=="dealer"&&<fieldset className="crm-permissions md:col-span-2"><legend className="font-bold">Права сотрудника</legend><p className="my-3 text-sm text-[var(--ac-muted)]">{ROLE_DETAILS[role]}</p><p className="mb-4 text-sm text-[var(--ac-muted)]">Отключённые разделы скрываются, переход по прямой ссылке также закрыт. Реклама и Метрика доступны только владельцу.</p><input type="hidden" name="permissionsPresent" value="1"/>{CRM_PERMISSION_GROUPS.map(group=><section key={group.label} className="mt-5"><h3 className="mb-3 font-bold">{group.label}</h3><div className="grid gap-3 sm:grid-cols-2">{group.keys.map(key=>{const disabled=role==='owner'||(role==='manager'&&isAdministrativeCrmPermission(key));const checked=role==='owner'||(!disabled&&values[key]);return <label key={key} className="crm-permission"><span><strong>{CRM_PERMISSIONS[key].label}</strong><small>{CRM_PERMISSIONS[key].description}</small></span><input type="checkbox" role="switch" name={`permission_${key}`} checked={checked} disabled={disabled} onChange={e=>setValues(v=>({...v,[key]:e.target.checked}))}/></label>;})}</div></section>)}</fieldset>}</>;
}
