"use client";
import {useEffect,useState} from 'react';
import {defaultManagerAvatar} from '../../lib/default-avatars';
export function StaffHeartbeat(){
 useEffect(()=>{let busy=false;const ping=async()=>{if(busy||document.visibilityState!=='visible')return;busy=true;try{await fetch('/api/crm/presence',{method:'POST'});}catch{}finally{busy=false;}};void ping();const timer=setInterval(()=>void ping(),60_000);document.addEventListener('visibilitychange',ping);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',ping);};},[]);return null;
}
type Person={id:string;displayName:string;avatarUrl?:string;lastSeenAt?:string;lastLoginAt?:string;online:boolean};
export function StaffPresence(){
 const [team,setTeam]=useState<Person[]>([]),[loaded,setLoaded]=useState(false);
 useEffect(()=>{let active=true;const refresh=async()=>{if(document.visibilityState!=='visible')return;try{const r=await fetch('/api/crm/presence',{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(active){setTeam(d.team||[]);setLoaded(true);}}catch{}};void refresh();const timer=setInterval(()=>void refresh(),60_000);document.addEventListener('visibilitychange',refresh);return()=>{active=false;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[]);
 return <section className="glass mt-5 rounded-3xl p-5" aria-label="Активность сотрудников"><h2 className="text-xl font-black">Команда в сети</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{team.map(person=><a href={`/crm/managers/${encodeURIComponent(person.id)}`} key={person.id} className="crm-presence-card flex items-center gap-3 rounded-2xl p-3"><img src={person.avatarUrl||defaultManagerAvatar(person.id)} width={44} height={44} alt="" className="h-11 w-11 rounded-full object-cover"/><div><p className="font-bold">{person.displayName}</p><p className="flex items-center gap-2 text-xs text-[var(--ac-muted)]" title={person.online?'Активность в последние 2 минуты':undefined}><span className={`h-2 w-2 rounded-full ${person.online?'bg-emerald-500':'bg-slate-500'}`}/>{person.online?'В сети':person.lastSeenAt||person.lastLoginAt?`Был(а) ${new Date((person.lastSeenAt||person.lastLoginAt)!).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Novokuznetsk'})}`:'Ещё не заходил(а)'}</p></div></a>)}</div>{!loaded?<p className="mt-3 text-sm text-[var(--ac-muted)]">Загружаем активность…</p>:null}</section>;
}
