'use client';
import {useEffect,useRef,useState} from 'react';
import {prepareIdeaScreenshot} from '@/lib/idea-photo-upload';
import {IdeaText} from './IdeaText';
import './team-ideas.css';
type Idea={id:string;title:string;description:string;authorName:string;createdAt:string;progress:number;voteCount:number;voted:boolean;screenshots:string[]};
export function TeamIdeas({owner}:{owner:boolean}){
 const [rows,setRows]=useState<Idea[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[formOpen,setFormOpen]=useState(false),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[files,setFiles]=useState<File[]>([]),[drafts,setDrafts]=useState<Record<string,number>>({}),[filter,setFilter]=useState('all'),[sort,setSort]=useState('new'),[notice,setNotice]=useState('');
 const editor=useRef<HTMLTextAreaElement>(null),form=useRef<HTMLFormElement>(null);
 async function refresh(){const r=await fetch('/api/crm/ideas',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Не удалось загрузить идеи.');setRows(data.ideas);}
 useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function send(body:FormData|Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const multipart=body instanceof FormData;const r=await fetch('/api/crm/ideas',{method:'POST',headers:multipart?undefined:{'Content-Type':'application/json'},body:multipart?body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Не удалось сохранить.');return true;}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить.');return false;}finally{setBusy(false);}}
 async function reload(){try{await refresh();}catch{setError('Изменение сохранено, но таблицу не удалось обновить. Нажмите «Обновить».');}}
 function wrap(start:string,end=start){const field=editor.current;if(!field)return;const a=field.selectionStart,b=field.selectionEnd;const chosen=description.slice(a,b)||'текст';setDescription(description.slice(0,a)+start+chosen+end+description.slice(b));requestAnimationFrame(()=>{field.focus();field.setSelectionRange(a+start.length,a+start.length+chosen.length);});}
 const visible=rows.filter(r=>filter==='all'||(filter==='done'?r.progress===100:r.progress<100)).sort((a,b)=>sort==='votes'?b.voteCount-a.voteCount||b.createdAt.localeCompare(a.createdAt):b.createdAt.localeCompare(a.createdAt));
 return <div className="team-ideas">
  <div className="ideas-actions"><button type="button" className="ideas-primary" onClick={()=>setFormOpen(!formOpen)}>{formOpen?'Закрыть форму':'Добавить идею'}</button><button type="button" disabled={busy} onClick={()=>{setError('');reload();}}>Обновить</button><label>Показать <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все идеи</option><option value="open">В работе и новые</option><option value="done">Выполненные</option></select></label><label>Порядок <select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Сначала новые</option><option value="votes">По голосам</option></select></label></div>
  {error&&<p role="alert" className="ideas-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {formOpen&&<form ref={form} className="ideas-form" onSubmit={async e=>{e.preventDefault();const body=new FormData();body.set('title',title);body.set('description',description);try{setBusy(true);for(const f of files)body.append('screenshots',await prepareIdeaScreenshot(f));}catch(e){setError(e instanceof Error?e.message:'Не удалось подготовить скриншоты.');setBusy(false);return;}if(await send(body)){setTitle('');setDescription('');setFiles([]);form.current?.reset();setFormOpen(false);setNotice('Идея добавлена.');await reload();}}}>
   <label>Заголовок *<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Что хотите улучшить?"/></label>
   <label htmlFor="idea-description">Описание *</label><div className="ideas-toolbar" aria-label="Оформление описания"><button type="button" onClick={()=>wrap('**')} title="Жирный"><strong>Жирный</strong></button><button type="button" onClick={()=>wrap('*')}><em>Курсив</em></button><button type="button" onClick={()=>wrap('[u]','[/u]')}><u>Подчеркнуть</u></button><button type="button" onClick={()=>wrap('[mark]','[/mark]')}>Выделить</button><label>Цвет <select defaultValue="" onChange={e=>{if(e.target.value)wrap(`[color=${e.target.value}]`,'[/color]');e.target.value='';}}><option value="">Выбрать</option><option value="red">Красный</option><option value="blue">Синий</option><option value="green">Зелёный</option></select></label></div>
   <textarea ref={editor} id="idea-description" required maxLength={12000} rows={6} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Опишите идею. Ссылки с https:// станут активными."/>
   {description&&<details open><summary>Предпросмотр</summary><div className="ideas-description"><IdeaText text={description}/></div></details>}
   <label>Скриншоты<input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{const next=Array.from(e.target.files||[]);if(next.length>5||next.some(f=>f.size>5*1024*1024)){setError('До 5 скриншотов, каждый до 5 МБ.');e.target.value='';setFiles([]);return;}setFiles(next);setError('');}}/></label><small>PNG, JPG, WebP — до 5 файлов, каждый до 5 МБ.</small>{files.length>0&&<ul>{files.map((f,i)=><li key={i}>{f.name} <button type="button" aria-label={`Убрать ${f.name}`} onClick={()=>setFiles(files.filter((_,n)=>n!==i))}>Убрать</button></li>)}</ul>}
   <button className="ideas-primary" disabled={busy} type="submit">{busy?'Сохраняем…':'Добавить идею'}</button>
  </form>}
  {loading?<p role="status">Загружаем идеи…</p>:!visible.length?<p>Пока нет идей в этом списке. Предложите первую!</p>:<div className="ideas-table-scroll"><table><thead><tr><th>Идея</th><th>Предложил</th><th>Голоса</th><th>Готовность</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><details><summary><strong>{row.title}</strong></summary><div className="ideas-description"><IdeaText text={row.description}/></div><div className="ideas-screenshots">{row.screenshots.map((key,i)=><a key={key} href={`/api/crm/ideas/media/${key}`} target="_blank" rel="noopener noreferrer"><img src={`/api/crm/ideas/media/${key}`} alt={`Скриншот ${i+1} к идее «${row.title}»`} loading="lazy"/></a>)}</div></details></td><td>{row.authorName}<small className="ideas-date">{new Date(row.createdAt).toLocaleDateString('ru-RU',{timeZone:'Asia/Krasnoyarsk'})}</small></td><td><button type="button" aria-pressed={row.voted} disabled={busy} title={row.voted?'Снять голос':'Поддержать идею'} onClick={async()=>{if(await send({id:row.id,action:'vote',value:!row.voted}))await reload();}}>👍 {row.voteCount}<span className="ideas-vote-label">{row.voted?' Вы поддержали':' Поддержать'}</span></button></td><td><strong>{drafts[row.id]??row.progress}%</strong>{owner?<><input aria-label={`Готовность: ${row.title}`} type="range" min={0} max={100} step={1} value={drafts[row.id]??row.progress} disabled={busy} onChange={e=>setDrafts({...drafts,[row.id]:Number(e.target.value)})}/>{drafts[row.id]!==undefined&&drafts[row.id]!==row.progress&&<button type="button" disabled={busy} onClick={async()=>{if(await send({id:row.id,action:'progress',value:drafts[row.id]})){setDrafts(current=>{const copy={...current};delete copy[row.id];return copy;});await reload();}}}>Сохранить</button>}</>:<progress max={100} value={row.progress} aria-label={`Готовность ${row.progress}%`}/>}<small>{row.progress===100?'Выполнено':row.progress>0?'В работе':'Новая идея'}</small></td></tr>)}</tbody></table></div>}
 </div>;
}
