'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Cake,X,Plus} from 'lucide-react';
import type {Shift} from '../../lib/crm-team';
type Person={id:string;name:string;avatarUrl?:string;birthday:string};
const today=()=>new Date(Date.now()+7*3600000).toISOString().slice(0,10);
const add=(date:string,n:number)=>new Date(Date.parse(`${date}T12:00:00Z`)+n*86400000).toISOString().slice(0,10);
const monday=(date:string)=>add(date,-((new Date(`${date}T12:00:00Z`).getUTCDay()+6)%7));
export function TeamSchedule({initialMonth,initialDate,focusUserId}:{initialMonth?:string;initialDate?:string;focusUserId?:string}){
 const [week,setWeek]=useState(()=>monday(initialDate&&/^\d{4}-\d{2}-\d{2}$/.test(initialDate)&&Number.isFinite(Date.parse(initialDate))?initialDate:initialMonth&&/^\d{4}-(0[1-9]|1[0-2])$/.test(initialMonth)?`${initialMonth}-01`:today())),[people,setPeople]=useState<Person[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const [edit,setEdit]=useState<{person:Person;date:string;previous?:Shift}|null>(null),[start,setStart]=useState('10:00'),[end,setEnd]=useState('20:00'),[off,setOff]=useState(false),[note,setNote]=useState('');
 const days=Array.from({length:7},(_,i)=>add(week,i));
 async function refresh(){const months=[...new Set([week.slice(0,7),add(week,6).slice(0,7)])];const data=await Promise.all(months.map(async month=>{const r=await fetch(`/api/crm/team/schedule?month=${month}`,{cache:'no-store'});if(!r.ok)throw Error('Не удалось загрузить график.');return r.json();}));setPeople(data[0].people);setShifts(data.flatMap(d=>d.shifts));setLoaded(true);}
 useEffect(()=>{setLoaded(false);setError('');void refresh().catch(e=>setError(e.message));},[week]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!edit)void refresh().catch(()=>{});},30000);return()=>clearInterval(timer);},[week,edit]);
 function choose(person:Person,date:string){const previous=shifts.find(s=>s.userId===person.id&&s.date===date);setEdit({person,date,previous});setStart(previous?.start||'10:00');setEnd(previous?.end||'20:00');setOff(Boolean(previous&&!previous.start));setNote(previous?.note||'');setError('');}
 return <section id="team-schedule" className="crm-team-schedule glass rounded-3xl p-5">
 <div className="crm-schedule-heading"><h2><CalendarDays size={22}/>Рабочий график</h2><div className="crm-schedule-navigation"><button type="button" aria-label="Предыдущая неделя" onClick={()=>{setWeek(add(week,-7));setEdit(null);}}><ChevronLeft size={18}/></button><label><span className="sr-only">Неделя графика</span><input aria-label="Неделя графика" type="date" value={week} onChange={e=>{if(e.target.value){setWeek(monday(e.target.value));setEdit(null);}}}/></label><button type="button" aria-label="Следующая неделя" onClick={()=>{setWeek(add(week,7));setEdit(null);}}><ChevronRight size={18}/></button><button type="button" onClick={()=>{setWeek(monday(today()));setEdit(null);}}>Сегодня</button></div></div>
 <p className="mt-2 text-sm text-[var(--ac-muted)]">Нажмите на день сотрудника, чтобы изменить смену. Время Новокузнецка.</p>
 {!loaded?<p className="mt-3" role="status">{error||'Загружаем график…'}</p>:<div className="crm-schedule-scroll"><table><thead><tr><th>Сотрудник</th>{days.map(d=><th key={d} className={d===today()?'is-today':''}><span>{new Date(`${d}T12:00:00Z`).toLocaleDateString('ru-RU',{weekday:'short',timeZone:'UTC'})}</span>{d.slice(8)}.{d.slice(5,7)}</th>)}</tr></thead><tbody>{people.filter(p=>!focusUserId||p.id===focusUserId).map(p=><tr key={p.id}><th>{p.avatarUrl?<img src={p.avatarUrl} alt=""/>:null}<span>{p.name}</span></th>{days.map(d=>{const shift=shifts.find(s=>s.userId===p.id&&s.date===d),birthday=p.birthday.slice(5)===d.slice(5);return <td key={d} className={d===today()?'is-today':''}><button type="button" className={shift?.start?'is-working':''} aria-label={`${p.name}, ${d}, ${shift?.start?`${shift.start}–${shift.end}`:shift?'Выходной':'Не указано'}`} onClick={()=>choose(p,d)}>{birthday?<Cake size={17} aria-label="День рождения"/>:null}<span>{shift?.start?<>{shift.start}<br/>{shift.end}</>:shift?'Выходной':<Plus size={16}/>}</span>{shift?.note?<small title={shift.note}>Заметка</small>:null}</button></td>;})}</tr>)}</tbody></table></div>}
 {edit?<form className="crm-shift-editor" onSubmit={async e=>{e.preventDefault();if(!window.confirm(`Изменить график ${edit.person.name} на ${edit.date.split('-').reverse().join('.')}? ${off?'Выходной':`${start}–${end}`}. Сотрудник получит уведомление.`))return;setBusy(true);setError('');try{const r=await fetch('/api/crm/team/schedule',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:edit.person.id,date:edit.date,start,end,off,note,expectedUpdatedAt:edit.previous?.updatedAt||'',confirmed:true})});const d=await r.json();if(!r.ok)throw Error(d.error);setEdit(null);await refresh();window.dispatchEvent(new Event('avtocena:crm-change'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <div className="crm-shift-title"><strong>{edit.person.name} · {edit.date.split('-').reverse().join('.')}</strong><button type="button" aria-label="Закрыть изменение смены" onClick={()=>setEdit(null)}><X size={20}/></button></div>
 <label className="crm-shift-off"><input type="checkbox" checked={off} onChange={e=>setOff(e.target.checked)}/>Выходной</label><label>Начало<input type="time" required={!off} disabled={off} value={start} onChange={e=>setStart(e.target.value)}/></label><label>Конец<input type="time" required={!off} disabled={off} value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="crm-shift-note">Комментарий<input maxLength={300} value={note} onChange={e=>setNote(e.target.value)} placeholder="Например: офис в Планете"/></label><button className="avto-button" disabled={busy}>{busy?'Сохраняем…':'Сохранить смену'}</button></form>:null}
 {error&&loaded?<p role="alert" className="mt-3 text-sm">{error}</p>:null}
 {people.some(p=>p.birthday&&p.birthday.slice(0,7)===week.slice(0,7))?<div className="crm-birthday-list"><strong><Cake size={17}/>Дни рождения в этом месяце</strong>{people.filter(p=>p.birthday&&p.birthday.slice(0,7)===week.slice(0,7)).sort((a,b)=>a.birthday.localeCompare(b.birthday)).map(p=><span key={p.id}>{p.birthday.slice(8)}.{p.birthday.slice(5,7)} — {p.name}</span>)}</div>:null}
 </section>;
}
