'use client';
import {useEffect,useRef,useState} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Cake,X,Plus,Check} from 'lucide-react';
import {workOptions} from '../../lib/staff-workplaces';
import type {Shift} from '../../lib/crm-team';
import {calendarToday,monthDays,patternDates,defaultScheduleStart,schedulePattern,shiftKind,shiftLabel,shiftKinds,type ShiftKind} from '../../lib/crm-schedule-calendar';
type Person={id:string;name:string;avatarUrl?:string;birthday:string;workAddresses?:string[];remoteWork?:boolean};
type Schedule={people:Person[];shifts:Shift[]};
const weekdays=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const dateLabel=(date:string,options:Intl.DateTimeFormatOptions={day:'numeric',month:'long'})=>new Date(`${date}T12:00:00Z`).toLocaleDateString('ru-RU',{...options,timeZone:'UTC'});
function initialDay(date?:string,month?:string){if(date&&/^\d{4}-(0[1-9]|1[0-2])-\d{2}$/.test(date)&&date>='2020-01-01'&&date<='2100-12-31'&&monthDays(date.slice(0,7)).includes(date))return date;return month&&/^\d{4}-(0[1-9]|1[0-2])$/.test(month)&&month>='2020-01'&&month<='2100-12'?`${month}-01`:calendarToday();}
function Avatar({person}:{person:Person}){return person.avatarUrl?<img src={person.avatarUrl} alt=""/>:<span className="crm-calendar-avatar">{person.name.slice(0,1)}</span>;}
export function TeamSchedule({initialMonth,initialDate,focusUserId}:{initialMonth?:string;initialDate?:string;focusUserId?:string}){
 const [day,setDay]=useState(()=>initialDay(initialDate,initialMonth)),[personId,setPersonId]=useState(focusUserId||''),[data,setData]=useState<Schedule>({people:[],shifts:[]}),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[retry,setRetry]=useState(0);
 const [editor,setEditor]=useState<{person:Person;dates:string[];snapshot:Shift[]}|null>(null),[kind,setKind]=useState<ShiftKind>('work'),[start,setStart]=useState('10:00'),[end,setEnd]=useState('20:00'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[editError,setEditError]=useState('');
 const [mode,setMode]=useState<'manual'|'cycle'|'weekdays'>('manual'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[anchor,setAnchor]=useState(''),[workDays,setWorkDays]=useState(2),[restDays,setRestDays]=useState(2);
 const [showAvatars,setShowAvatars]=useState(false),[workplace,setWorkplace]=useState('');
 const section=useRef<HTMLElement>(null);
 useEffect(()=>{try{setShowAvatars(localStorage.getItem('avtocena_schedule_avatars')==='1');}catch{}},[]);
 const dialog=useRef<HTMLDialogElement>(null),requestId=useRef(0),month=day.slice(0,7),days=monthDays(month),offset=(new Date(`${month}-01T12:00:00Z`).getUTCDay()+6)%7;
 const visiblePeople=data.people.filter(p=>!personId||p.id===personId),birthdays=data.people.filter(p=>(!personId||p.id===personId)&&p.birthday?.slice(0,7)===month).sort((a,b)=>a.birthday.localeCompare(b.birthday));
 useEffect(()=>{
  const controller=new AbortController();let active=true;
  async function refresh(){const id=++requestId.current;try{const r=await fetch(`/api/crm/team/schedule?month=${month}`,{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('Не удалось загрузить график.');const result=await r.json();if(active&&id===requestId.current){setData(result);setLoaded(true);setError('');}}catch(e){if(active&&(e as Error).name!=='AbortError')setError((e as Error).message);}}
  setLoaded(false);void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible'&&Boolean(section.current?.getClientRects().length)&&!dialog.current?.open)void refresh();},30000);
  return()=>{active=false;controller.abort();clearInterval(timer);};
 },[month,retry]);
 useEffect(()=>{if(!editor)return;const el=dialog.current;if(!el)return;el.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=overflow;};},[Boolean(editor)]);
 function moveMonth(delta:number){const d=new Date(`${month}-01T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+delta);const value=d.toISOString().slice(0,10);if(value>='2020-01-01'&&value<='2100-12-31'){setDay(value);setSuccess('');}}
 function open(person:Person,date=day,repeat=false){setMode(repeat?'cycle':'manual');setFrom(date);setTo(days[days.length-1]);setAnchor(date);setWorkDays(2);setRestDays(2);const previous=data.shifts.find(s=>s.userId===person.id&&s.date===date);setWorkplace(!repeat&&previous?.workplace?previous.workplace:workOptions(person).length===1?workOptions(person)[0]:'');setKind(repeat?'work':shiftKind(previous)||'work');setStart(previous?.start||'10:00');setEnd(previous?.end||'20:00');setNote(repeat?'':previous?.note||'');setEditError('');setEditor({person,dates:[date],snapshot:data.shifts});}
 function selectDates(dates:string[]){setEditor(e=>e?{...e,dates:dates.sort()}:e);}
 const pattern=mode==='manual'?[]:schedulePattern({from,to,anchor,workDays,restDays,mode});
 const selectedDates=mode==='manual'?(editor?.dates||[]):pattern.map(d=>d.date);
 async function save(clear=false){if(!editor||busy)return;setBusy(true);setEditError('');const dates=selectedDates;if(!dates.length){setBusy(false);return;}
  try{const r=await fetch('/api/crm/team/schedule',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:editor.person.id,dates,kind:mode==='manual'?kind:'work',dayKinds:mode==='manual'?undefined:Object.fromEntries(pattern.map(d=>[d.date,d.kind])),start,end,note,workplace,clear,confirmed:true,expectedUpdates:Object.fromEntries(dates.map(date=>[date,editor.snapshot.find(s=>s.userId===editor.person.id&&s.date===date)?.updatedAt||'']))})});const result=await r.json();if(!r.ok)throw Error(result.error||'Не удалось сохранить график.');
   ++requestId.current;setData(d=>({...d,shifts:[...d.shifts.filter(s=>s.userId!==editor.person.id||!dates.includes(s.date)),...(result.shifts||[])]}));setSuccess(`${editor.person.name}: ${clear?'отметки удалены':'график сохранён'} · дат: ${dates.length}`);setEditor(null);window.dispatchEvent(new Event('avtocena:crm-change'));
  }catch(e){setEditError((e as Error).message);}finally{setBusy(false);}
 }
 const overwritten=editor?.snapshot.filter(s=>s.userId===editor.person.id&&selectedDates.includes(s.date)).length||0;
 return <section ref={section} id="team-schedule" className="crm-team-schedule crm-calendar glass rounded-3xl p-5">
  <div className="crm-schedule-heading"><div><h2><CalendarDays size={22}/>Рабочий график</h2><p className="crm-calendar-muted">Смены, выходные и важные даты · время Новокузнецка</p></div><button className="avto-button crm-calendar-add" disabled={!loaded||!visiblePeople.length} onClick={()=>open(visiblePeople[0],defaultScheduleStart(month),true)}><Plus size={17}/>Заполнить график</button></div>
  <div className="crm-calendar-toolbar"><div className="crm-calendar-month"><button aria-label="Предыдущий месяц" disabled={month==='2020-01'} onClick={()=>moveMonth(-1)}><ChevronLeft size={20}/></button><label><span className="sr-only">Месяц графика</span><span aria-hidden="true">{dateLabel(`${month}-01`,{month:'long',year:'numeric'})}</span><input type="month" aria-label="Месяц графика" value={month} min="2020-01" max="2100-12" onChange={e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)&&e.target.value>='2020-01'&&e.target.value<='2100-12')setDay(`${e.target.value}-01`);}}/></label><button aria-label="Следующий месяц" disabled={month==='2100-12'} onClick={()=>moveMonth(1)}><ChevronRight size={20}/></button></div><button className="crm-calendar-today" onClick={()=>setDay(calendarToday())}>Сегодня</button><label className="crm-calendar-avatar-toggle"><input type="checkbox" checked={showAvatars} onChange={e=>{setShowAvatars(e.target.checked);try{localStorage.setItem('avtocena_schedule_avatars',e.target.checked?'1':'0');}catch{}}}/>Аватары на календаре</label>{!focusUserId?<label className="crm-calendar-person"><span className="sr-only">Сотрудник в календаре</span><select aria-label="Сотрудник в календаре" value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Вся команда</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>:null}</div>
  {error?<div className="crm-calendar-error" role="alert">{error} <button onClick={()=>setRetry(n=>n+1)}>Повторить загрузку</button></div>:null}
  {success?<p className="crm-calendar-success" role="status"><Check size={16}/>{success}</p>:null}
  {!loaded?<p role="status" className="crm-calendar-muted">{error?'График недоступен.':'Загружаем календарь…'}</p>:<>
   <div className="crm-calendar-layout"><div><div className="crm-calendar-weekdays">{weekdays.map(d=><span key={d}>{d}</span>)}</div><div className="crm-calendar-grid" aria-label="Календарь месяца">{Array.from({length:offset},(_,i)=><span key={`empty-${i}`} className="crm-calendar-empty"/>)}{days.map(date=>{const rows=data.shifts.filter(s=>s.date===date&&visiblePeople.some(p=>p.id===s.userId)),birthday=birthdays.filter(p=>p.birthday===date),working=rows.filter(s=>shiftKind(s)==='work').length;return <button key={date} className={`crm-calendar-day ${date===day?'is-selected':''} ${date===calendarToday()?'is-today':''}`} aria-pressed={date===day} aria-label={`${dateLabel(date,{day:'numeric',month:'long',year:'numeric'})}, ${personId?shiftLabel(rows[0]):`работают: ${working}, отметок: ${rows.length}`}${birthday.length?', день рождения':''}`} onClick={()=>{setDay(date);setSuccess('');}}><span className="crm-calendar-day-number">{Number(date.slice(8))}{birthday.length?<Cake size={13}/>:null}</span>{personId&&rows[0]?<span className={`crm-calendar-day-label kind-${shiftKind(rows[0])}`}>{shiftLabel(rows[0])}</span>:rows.length?<span className="crm-calendar-day-label">{working?`${working} на смене`:'Отметки'}</span>:null}{showAvatars&&rows.length?<span className="crm-calendar-avatars">{rows.slice(0,3).map(row=>{const p=visiblePeople.find(p=>p.id===row.userId)!;return <span key={p.id} className={`crm-calendar-mini kind-${shiftKind(row)}`} title={`${p.name} · ${shiftLabel(row)}${row.workplace?' · '+row.workplace:''}`}><Avatar person={p}/></span>;})}{rows.length>3?<small title={rows.slice(3).map(row=>visiblePeople.find(p=>p.id===row.userId)?.name).join(', ')}>+{rows.length-3}</small>:null}</span>:null}<span className="crm-calendar-dots">{[...new Set(rows.map(s=>shiftKind(s)))].map(k=><i key={k} className={`kind-${k}`}/>)}</span></button>;})}</div><div className="crm-calendar-legend">{Object.entries(shiftKinds).map(([k,label])=><span key={k}><i className={`kind-${k}`}/>{label}</span>)}</div></div>
   <aside className="crm-calendar-agenda" aria-label="График выбранного дня"><div className="crm-calendar-agenda-title"><strong>{dateLabel(day,{day:'numeric',month:'long'})}</strong><span>{dateLabel(day,{weekday:'long'})}{day===calendarToday()?' · сегодня':''}</span></div>{visiblePeople.length?visiblePeople.map(p=>{const row=data.shifts.find(s=>s.date===day&&s.userId===p.id);return <button key={p.id} className="crm-calendar-person-row" onClick={()=>open(p)} aria-label={`Изменить график: ${p.name}, ${day}`}><Avatar person={p}/><span><strong>{p.name}</strong><span className={`crm-calendar-status kind-${shiftKind(row)||'empty'}`}>{shiftLabel(row)}</span>{row?.workplace?<small className="crm-calendar-location">{row.workplace}</small>:null}{row?.note?<small>{row.note}</small>:null}{p.birthday===day?<small className="crm-calendar-birthday"><Cake size={14}/>День рождения</small>:null}</span><ChevronRight size={16}/></button>;}):<p className="crm-calendar-muted">Нет сотрудников для отображения.</p>}<p className="crm-calendar-muted">Нажмите на сотрудника, чтобы изменить этот день или выбрать несколько дат.</p></aside></div>
   {birthdays.length?<div className="crm-birthday-list"><strong><Cake size={17}/>Дни рождения</strong>{birthdays.map(p=><button key={p.id} onClick={()=>setDay(p.birthday)}>{p.birthday.slice(8)}.{p.birthday.slice(5,7)} — {p.name}</button>)}</div>:null}
  </>}
  {editor?<dialog ref={dialog} className="crm-calendar-dialog" aria-labelledby="crm-calendar-editor-title" onCancel={e=>{e.preventDefault();if(!busy)setEditor(null);}}><form onSubmit={e=>{e.preventDefault();void save();}}>
   <header><div><h3 id="crm-calendar-editor-title">Настроить график</h3><p>{dateLabel(`${month}-01`,{month:'long',year:'numeric'})}</p></div><button type="button" disabled={busy} aria-label="Закрыть редактор графика" onClick={()=>setEditor(null)}><X size={22}/></button></header>
   <fieldset disabled={busy} className="crm-calendar-editor-body">
    <label>Сотрудник<select aria-label="Сотрудник" value={editor.person.id} disabled={Boolean(focusUserId)} onChange={e=>{const person=data.people.find(p=>p.id===e.target.value);if(person){setEditor({...editor,person});setNote('');setKind('work');setWorkplace(workOptions(person).length===1?workOptions(person)[0]:'');}}}>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <label>Как заполнить<select aria-label="Как заполнить" value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="manual">Отдельные даты</option><option value="cycle">Рабочие и выходные по циклу</option><option value="weekdays">Понедельник–пятница, выходные сб–вс</option></select></label>
    {mode!=='manual'?<>
     <div className="crm-calendar-time"><label>Заполнить с<input type="date" aria-label="Заполнить с" required min={days[0]} max={days[days.length-1]} value={from} onChange={e=>{setFrom(e.target.value);setAnchor(e.target.value);}}/></label><label>По<input type="date" aria-label="Заполнить по" required min={from||days[0]} max={days[days.length-1]} value={to} onChange={e=>setTo(e.target.value)}/></label></div>
     <p className="crm-calendar-muted">Заполняем выбранный период в этом месяце. Остальные даты не изменятся.</p>
     {mode==='cycle'?<><div className="crm-calendar-presets">{[[2,2],[3,3],[1,2],[5,2]].map(([work,rest])=><button type="button" key={`${work}/${rest}`} aria-pressed={work===workDays&&rest===restDays} onClick={()=>{setWorkDays(work);setRestDays(rest);}}>{work}/{rest}</button>)}</div><div className="crm-calendar-time"><label>Рабочих дней подряд<input aria-label="Рабочих дней подряд" type="number" min="1" max="31" required value={workDays||''} onChange={e=>setWorkDays(Number(e.target.value))}/></label><label>Выходных подряд<input aria-label="Выходных подряд" type="number" min="1" max="31" required value={restDays||''} onChange={e=>setRestDays(Number(e.target.value))}/></label></div><label>Первый рабочий день цикла<input aria-label="Первый рабочий день цикла" type="date" required min="2020-01-01" max="2100-12-31" value={anchor} onChange={e=>setAnchor(e.target.value)}/></label><p className="crm-calendar-muted">С указанной даты: {workDays||'…'} дн. работа, затем {restDays||'…'} дн. отдых — и так по кругу. Для продолжения графика укажите начало уже действующего цикла.</p></>:<p className="crm-calendar-muted">Понедельник–пятница — работа, суббота и воскресенье — отдых.</p>}
    </>:<div className="crm-calendar-presets"><button type="button" onClick={()=>selectDates(patternDates(month,'weekdays',day))}>Пн–Пт</button><button type="button" onClick={()=>selectDates(days)}>Весь месяц</button><button type="button" onClick={()=>selectDates([])}>Снять выбор</button></div>}
    <div className="crm-calendar-date-heading"><strong>{mode==='manual'?'Выберите даты':'Так будет выглядеть график'}</strong><span>{selectedDates.length} дн.</span></div>
    <div className="crm-calendar-weekdays">{weekdays.map(d=><span key={d}>{d}</span>)}</div><div className="crm-calendar-picker">{Array.from({length:offset},(_,i)=><span key={i}/>)}{days.map(date=>{const planned=pattern.find(p=>p.date===date);return mode==='manual'?<button type="button" key={date} aria-label={`Выбрать ${date}`} aria-pressed={editor.dates.includes(date)} className={editor.dates.includes(date)?'is-selected':''} onClick={()=>selectDates(editor.dates.includes(date)?editor.dates.filter(d=>d!==date):[...editor.dates,date])}>{Number(date.slice(8))}</button>:<span key={date} className={`crm-calendar-preview-day ${planned?'preview-'+planned.kind:''}`} aria-label={`${date}: ${planned?(planned.kind==='work'?'Рабочий день':'Выходной'):'Без изменений'}`}>{Number(date.slice(8))}{planned?<small>{planned.kind==='work'?'Р':'В'}</small>:null}</span>;})}</div>
    {mode!=='manual'?<div className="crm-calendar-pattern-summary" aria-live="polite"><span>Р — работа: {pattern.filter(d=>d.kind==='work').length}</span><span>В — отдых: {pattern.filter(d=>d.kind==='off').length}</span>{!pattern.length?<p role="alert">Проверьте период и начало цикла.</p>:null}</div>:<label>Тип дня<select aria-label="Тип дня" value={kind} onChange={e=>setKind(e.target.value as ShiftKind)}>{Object.entries(shiftKinds).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}
    {mode!=='manual'||kind==='work'?<div className="crm-calendar-time"><label>Начало<input type="time" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Конец<input type="time" required value={end} onChange={e=>setEnd(e.target.value)}/></label></div>:null}
    {(mode!=='manual'||kind==='work')?<label>Место работы<select aria-label="Место работы" value={workplace} onChange={e=>setWorkplace(e.target.value)}><option value="">Не указано</option>{workOptions(editor.person).map(address=><option value={address} key={address}>{address}</option>)}{workplace&&!workOptions(editor.person).includes(workplace)?<option value={workplace}>{workplace} (ранее указано)</option>:null}</select>{!workOptions(editor.person).length?<small className="crm-calendar-muted">Адреса офисов и удалённая работа задаются в карточке сотрудника.</small>:null}</label>:null}
    <label>{mode==='manual'&&kind==='note'?'Текст отметки':'Заметка'}<textarea maxLength={300} required={mode==='manual'&&kind==='note'} value={note} onChange={e=>setNote(e.target.value)} placeholder="Например: встреча, обучение или смена в Планете" rows={2}/></label>
   </fieldset>
   <footer><p>{editor.person.name} · дат: {selectedDates.length}{overwritten?` · дней с прежними отметками: ${overwritten}`:''}. Прежние отметки выбранных дней будут заменены. Об изменении графика другого сотрудника ему придёт уведомление.</p>{editError?<div role="alert" className="crm-calendar-error">{editError}{editError.includes('уже изменён')?<button type="button" onClick={()=>{setEditor(null);setRetry(n=>n+1);}}>Обновить календарь</button>:null}</div>:null}<div><button type="button" className="crm-calendar-clear" disabled={busy||!selectedDates.length||!overwritten} onClick={()=>void save(true)}>Очистить даты</button><button className="avto-button" disabled={busy||!selectedDates.length}>{busy?'Сохраняем…':`Сохранить · ${selectedDates.length}`}</button></div></footer>
  </form></dialog>:null}
 </section>;
}
