import {offerRouteId,offerPath} from '../catalog/offer-url';
import {getOfferForPage} from '../catalog/offer-page-data';
import {getOfferFromCurrentShard} from '../catalog/storage';
import {getSavedOfferCalculation} from '../catalog/saved-offer-calculation';
import {validateCustomerParameters} from '../catalog/customer-parameters';
import {calculateOfferWithCustomerParametersDetailed} from '../catalog/customs-pricing';
import {today,type ContractFields,type ContractCalculation,type TemplateId} from './model';
export function extractOfferId(input:string){let u:URL;try{u=new URL(input,'https://avtocena.com');}catch{throw Error('Вставьте ссылку на автомобиль с АвтоЦены.');}if(!['avtocena.com','www.avtocena.com'].includes(u.hostname)||!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port)throw Error('Нужна ссылка на автомобиль с АвтоЦены.');const match=u.pathname.match(/^\/cars\/offer\/([^/]+)\/?$/);if(!match)throw Error('Нужна ссылка на карточку автомобиля.');const id=offerRouteId(decodeURIComponent(match[1]));if(!id||id.length>300||/[\\/\x00-\x1f]/.test(id)||id==='.'||id==='..')throw Error('Некорректная ссылка.');return id;}
const text=(v:unknown)=>v==null?'':String(v);
export async function importContractOffer(url:string,fields:ContractFields,templateId:TemplateId){const id=extractOfferId(url);const offer=await getOfferForPage(id)||await getOfferFromCurrentShard(id);if(!offer)throw Error('Автомобиль не найден. Заполните данные вручную.');if((offer.market==='japan')!==(templateId==='japan'))throw Error('Для этого автомобиля выберите другой шаблон договора.');const saved=await getSavedOfferCalculation(offer);const parameters=saved?validateCustomerParameters(saved.draft):{productionDate:offer.productionDate};const vehicle={...offer,...parameters};const fuel:Record<string,string>={petrol:'Бензин',diesel:'Дизель',hybrid:'Гибрид',electric:'Электрический',lpg:'Газ',cng:'Газ'};
 const loaded:ContractFields={...fields,market:offer.market,offerUrl:`https://avtocena.com${offerPath(offer)}`,car:[offer.make,offer.model,offer.trim].filter(Boolean).join(' '),year:text(vehicle.year),color:text(offer.color),engine:fuel[vehicle.fuel||'']||text(vehicle.engineType),engineCc:text(vehicle.engineCc),powerHp:text(vehicle.powerHp),transmission:({AT:'Автомат',MT:'Механика',CVT:'Вариатор',DCT:'Робот'} as Record<string,string>)[offer.transmission||'']||text(offer.transmission),drive:({FWD:'Передний',RWD:'Задний',AWD:'Полный','4WD':'Полный'} as Record<string,string>)[offer.drive||'']||text(offer.drive),mileage:text(offer.mileageKm),grade:text(offer.auctionGrade),vin:offer.vin||offer.frameNumber||'',deliveryCity:fields.deliveryCity||vehicle.deliveryCity||''};
 const result=await calculateOfferWithCustomerParametersDetailed(offer,{...parameters,deliveryCity:loaded.deliveryCity,customsCalculationDate:today()});
 if(!result.ok)return {fields:loaded,calculation:null,warning:result.error||'Не хватает данных для расчёта. Уточните их в карточке автомобиля или заполните расчёт вручную.'};
 const c=result.calculation;const lines=(c.breakdown||[]).map((l:any)=>({label:String(l.title||l.label||l.id),amount:Number(l.amountRub)})).filter((l:any)=>Number.isFinite(l.amount));
 const commission=Number(c.paymentPlan?.commissionRub??(c.breakdown||[]).find((l:any)=>l.id==='topavto-commission')?.amountRub??0),deposit=Number(c.paymentPlan?.securityDepositRub||0);
 const calculation:ContractCalculation={calculatedAt:new Date().toISOString(),offerId:id,source:'site',rate:c.currencyRate?`1 ${c.currencyRate.currency} = ${c.currencyRate.effectiveRate} ₽`:'',rateDate:text(c.rateDate),total:Number(c.totalRub),commission,deposit,lines,warnings:c.warnings||[]};
 return {fields:{...loaded,budget:text(c.totalRub)},calculation,warning:''};
}
export function manualCalculation(f:ContractFields):ContractCalculation{const number=(k:string)=>{if(!f[k]?.trim())throw Error('Заполните сумму расчёта.');const n=Number(f[k].replace(/\s/g,'').replace(',','.'));if(!Number.isFinite(n)||n<0||n>1e10)throw Error('Проверьте суммы расчёта.');return n;};const total=number('manualTotal'),commission=number('manualCommission'),deposit=number('manualDeposit');if(total<=0||commission+deposit>total)throw Error('Первоначальный платёж не может превышать итоговую стоимость.');if(!f.manualRate||!f.manualRateDate)throw Error('Укажите курс и дату его актуальности.');return {calculatedAt:new Date().toISOString(),source:'manual',total,commission,deposit,rate:f.manualRate,rateDate:f.manualRateDate,lines:f.manualExpenses?[{label:f.manualExpenses,amount:total}]:[],warnings:[]};}
