export type TemplateId='japan'|'other';
export type ContractTemplate={id:TemplateId;name:string;revision:number;agent:string;requisites:string;sections:{title:string;text:string}[]};
export type ContractFields=Record<string,string>;
export type ContractCalculation={calculatedAt:string;offerId?:string;source:'site'|'manual';rate:string;rateDate:string;total:number;commission:number;deposit:number;lines:{label:string;amount:number}[];warnings:string[]};
export type ContractSnapshot={version:number;createdAt:string;createdBy:string;fields:ContractFields;template:ContractTemplate;calculation:ContractCalculation|null};
export type ContractRecord={id:string;revision:number;number:string;createdAt:string;updatedAt:string;createdBy:string;clientId:string;fields:ContractFields;template:ContractTemplate;calculation:ContractCalculation|null;versions:ContractSnapshot[];archivedAt?:string;archivedBy?:string};
export const markets:Record<string,string>={japan:'Япония',china:'Китай',korea:'Корея',uae:'ОАЭ',europe:'Европа',georgia:'Грузия'};
export const fieldGroups=[
 {title:'Клиент',fields:[['fio','ФИО'],['birthDate','Дата рождения'],['passportSeries','Серия паспорта'],['passportNumber','Номер паспорта'],['passportIssued','Кем выдан'],['passportDate','Дата выдачи'],['passportCode','Код подразделения'],['address','Адрес регистрации'],['phone','Телефон'],['email','Электронная почта']]},
 {title:'Договор',fields:[['date','Дата договора'],['deliveryCity','Место передачи автомобиля'],['deliveryDays','Срок доставки, суток']]},
 {title:'Автомобиль',fields:[['car','Марка, модель, комплектация'],['year','Год выпуска'],['color','Цвет'],['engine','Тип двигателя'],['engineCc','Объём, см³'],['powerHp','Мощность, л.с.'],['transmission','Коробка передач'],['drive','Привод'],['mileage','Пробег, км'],['grade','Аукционная оценка'],['vin','VIN / номер кузова'],['budget','Бюджет, ₽']]}
];
export const allowedFields=new Set([...fieldGroups.flatMap(g=>g.fields.map(f=>f[0])),'market','offerUrl','manualTotal','manualCommission','manualDeposit','manualRate','manualRateDate','manualExpenses']);
export const dateKeys=new Set(['birthDate','passportDate','date','manualRateDate']);
export const money=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n);
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Novokuznetsk',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const formatDate=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('.'):s;
export function initialFields(id:TemplateId):ContractFields{return {date:today(),market:id==='japan'?'japan':'',deliveryDays:id==='japan'?'90':'30'};}
export function sampleFields(id:TemplateId):ContractFields{return {...initialFields(id),fio:'Иванов Иван Иванович',birthDate:'1990-01-01',passportSeries:'00 00',passportNumber:'000000',passportIssued:'________________________________',passportDate:'2010-01-01',passportCode:'000-000',address:'________________________________',phone:'+7 ___ ___-__-__',deliveryCity:'________________',car:'________________',color:'________________',engine:'________________',engineCc:'____',transmission:'________________',drive:'________________',budget:'________________',mileage:'________________',grade:'____'};}
export function cleanFields(input:unknown):ContractFields{if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Неверные поля договора.');return Object.fromEntries(Object.entries(input).filter(([k])=>allowedFields.has(k)).map(([k,v])=>{if(typeof v!=='string'||v.length>2000)throw Error('Слишком длинное значение поля.');return [k,v.trim()];}));}
export function validateTemplate(t:ContractTemplate){if(!t||!['japan','other'].includes(t.id)||!Array.isArray(t.sections)||t.sections.length<1||t.sections.length>30||typeof t.agent!=='string'||typeof t.requisites!=='string'||t.agent.length>5000||t.requisites.length>5000)throw Error('Проверьте шаблон.');for(const s of t.sections)if(typeof s.title!=='string'||typeof s.text!=='string'||s.title.length>300||s.text.length>15000)throw Error('Проверьте текст раздела.');const tokens=[t.agent,t.requisites,...t.sections.flatMap(s=>[s.title,s.text])].join('\n').matchAll(/\{\{([^}]+)\}\}/g);for(const [,key]of tokens)if(!['deliveryCity','deliveryDays','commission','deposit','countryPrep','countryAcc','countryFrom'].includes(key))throw Error(`Неизвестная подстановка: ${key}`);}
export function requiredMissing(r:Pick<ContractRecord,'fields'|'calculation'|'template'>){const f=r.fields;const keys=['fio','birthDate','passportSeries','passportNumber','passportIssued','passportDate','passportCode','address','phone','date','deliveryCity','deliveryDays','car'];const names=Object.fromEntries(fieldGroups.flatMap(g=>g.fields));const errors=keys.filter(k=>!f[k]).map(k=>names[k]);for(const k of ['date','birthDate','passportDate'])if(f[k]&&(!/^\d{4}-\d{2}-\d{2}$/.test(f[k])||!Number.isFinite(Date.parse(f[k]))||new Date(f[k]).toISOString().slice(0,10)!==f[k]))errors.push(names[k]);if(!markets[f.market]||(r.template.id==='japan')!==(f.market==='japan'))errors.push('Шаблон и рынок должны совпадать');if(!/^\d{1,3}$/.test(f.deliveryDays||'')||Number(f.deliveryDays)<1)errors.push('Срок доставки');if(!r.calculation||!Number.isFinite(r.calculation.total)||r.calculation.total<=0)errors.push('Расчёт стоимости');if(r.calculation&&(!r.calculation.rate||!r.calculation.rateDate))errors.push('Курс и дата курса');if(r.calculation&&(!Number.isFinite(r.calculation.commission)||!Number.isFinite(r.calculation.deposit)||r.calculation.commission<0||r.calculation.deposit<0||r.calculation.commission+r.calculation.deposit>r.calculation.total))errors.push('Первоначальный платёж');if(r.calculation&&new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Novokuznetsk',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(r.calculation.calculatedAt))!==f.date)errors.push('Дата договора должна совпадать с датой сохранённого расчёта');return [...new Set(errors)];}
export function contractSections(template:ContractTemplate,fields:ContractFields,calculation:ContractCalculation|null){const country:Record<string,[string,string]>={japan:['Японии','Японию'],china:['Китае','Китай'],korea:['Корее','Корею'],uae:['ОАЭ','ОАЭ'],europe:['Европе','Европу'],georgia:['Грузии','Грузию']};const c=country[fields.market]||['________','________'];const values:Record<string,string>={deliveryCity:fields.deliveryCity||'________',deliveryDays:fields.deliveryDays||'____',commission:calculation?money(calculation.commission):'________',deposit:calculation?money(calculation.deposit):'________',countryPrep:c[0],countryAcc:c[1],countryFrom:({japan:'Японии',china:'Китая',korea:'Кореи',uae:'ОАЭ',europe:'Европы',georgia:'Грузии'} as Record<string,string>)[fields.market]||'________'};return template.sections.map(s=>({title:s.title,text:s.text.replace(/\{\{([^}]+)\}\}/g,(_,k)=>values[k]||'________')}));}
export function principal(f:ContractFields){const v=(k:string)=>f[k]||'________________';return `Гр. ${v('fio')}, ${formatDate(v('birthDate'))} г.р., паспорт: серия ${v('passportSeries')}, номер ${v('passportNumber')}, выдан: ${v('passportIssued')}, ${formatDate(v('passportDate'))}, код подразделения: ${v('passportCode')}, зарегистрирован по месту жительства по адресу: ${v('address')}`;}
export type ContractBlock={text:string;heading?:boolean;pageBreak?:boolean};
export function documentBlocks(s:ContractSnapshot,number:string):ContractBlock[]{const {fields:f,template:t,calculation:c}=s;const blocks:ContractBlock[]=[{text:`АГЕНТСКИЙ ДОГОВОР № ${number}`,heading:true},{text:`г. Новокузнецк                                      ${formatDate(f.date)} г.`},{text:`${principal(f)}, именуемый в дальнейшем «Принципал» (Заказчик), и ${t.agent}, именуемый в дальнейшем «Агент» (Исполнитель), совместно именуемые Стороны, заключили настоящий Договор о нижеследующем:`}];for(const section of contractSections(t,f,c)){blocks.push({text:section.title,heading:true},...section.text.split(/\n\s*\n/).map(text=>({text})));}blocks.push({text:`${t.id==='japan'?'13':'12'}. РЕКВИЗИТЫ СТОРОН`,heading:true,pageBreak:true},{text:'Агент:',heading:true},{text:t.requisites},{text:'Принципал:',heading:true},{text:`${principal(f)}\nТелефон: ${f.phone||'________________'}\nЭлектронная почта: ${f.email||'________________'}`},{text:t.id==='japan'?'ЗАЯВКА НА ПРИОБРЕТЕНИЕ АВТОМОБИЛЯ':'ЗАЯВКА НА ПРИОБРЕТЕНИЕ АВТОМОБИЛЯ (Спецификация)',heading:true,pageBreak:true},{text:`К агентскому договору № ${number} от ${formatDate(f.date)}\nг. Новокузнецк`},{text:`Гр. ${f.fio||'________________'} поручает Исполнителю — ИП Молодых Антону Владимировичу найти, приобрести и доставить автомобиль в пункт назначения.`});const specs:[string,string][]=[['Марка, модель',[f.car,f.year].filter(Boolean).join(', ')],['Цвет кузова',f.color],['Тип двигателя',f.engine],['Рабочий объём двигателя, куб. см., мощность',[f.engineCc,f.powerHp?`${f.powerHp} л.с.`:''].filter(Boolean).join(', ')],['Коробка',f.transmission]];if(t.id==='japan')specs.push(['Пробег',f.mileage],['Оценка',f.grade],['Бюджет',f.budget?`${f.budget} ₽`:'']);specs.push(['Привод',f.drive]);if(f.vin)specs.push(['VIN / номер кузова',f.vin]);specs.forEach(([label,value],i)=>blocks.push({text:`${i+1}. ${label}: ${value||'________________'}`}));if(c){blocks.push({text:'Расчёт на дату составления',heading:true},{text:`${markets[f.market]||''} · ${formatDate(f.date)}\n${c.rate}. Курс на ${formatDate(c.rateDate)}.`},...c.lines.map(l=>({text:`${l.label}: ${money(l.amount)} ₽`})),{text:`Итого: ${money(c.total)} ₽`,heading:true},{text:`Первоначальный платёж: ${money(c.commission+c.deposit)} ₽, в том числе комиссия ${money(c.commission)} ₽ и обеспечительный платёж ${money(c.deposit)} ₽. Засчитывается в расчётах, повторно не прибавляется к итоговой стоимости.`});}return blocks;}
