import PDFDocument from 'pdfkit';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {documentBlocks,type ContractSnapshot} from './model';
export async function renderContractPdf(snapshot:ContractSnapshot,number:string,watermark:'ОБРАЗЕЦ'|'ЧЕРНОВИК'|null=null){const {fields:f,template:t,calculation:c}=snapshot;const pub=existsSync(path.join(process.cwd(),'public/fonts/DejaVuSans.ttf'))?path.join(process.cwd(),'public'):path.join(process.cwd(),'apps/web/public');const doc=new PDFDocument({size:'A4',margins:{top:65,bottom:65,left:48,right:48},bufferPages:true,font:path.join(pub,'fonts/DejaVuSans.ttf'),info:{Title:`Агентский договор № ${number}`,Author:'TOP AVTO'}});doc.registerFont('normal',path.join(pub,'fonts/DejaVuSans.ttf'));doc.registerFont('bold',path.join(pub,'fonts/DejaVuSans-Bold.ttf'));const chunks:Buffer[]=[];const done=new Promise<Buffer>((resolve,reject)=>{doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);});const width=499;
 const paragraph=(s:string,bold=false,size=9.5)=>{doc.font(bold?'bold':'normal').fontSize(size).fillColor('#111111');const h=doc.heightOfString(s,{width,lineGap:2});if(doc.y+h>766&&h<690)doc.addPage();doc.text(s,{width,lineGap:2,align:'justify'});doc.moveDown(.65);};
 const heading=(s:string)=>{if(doc.y>690)doc.addPage();paragraph(s,true,11);};
 for(const block of documentBlocks(snapshot,number)){if(block.pageBreak)doc.addPage();if(block.heading)heading(block.text);else paragraph(block.text);}
 const pages=doc.bufferedPageRange();for(let i=0;i<pages.count;i++){doc.switchToPage(i);doc.page.margins.bottom=0;doc.save();const logo=path.join(pub,'brands/topavto-logo-black.png');if(existsSync(logo))doc.image(logo,433,24,{fit:[113,29]});doc.font('normal').fontSize(8).fillColor('#333').text(`Исполнитель __________________       Заказчик __________________`,48,789,{width:450,lineBreak:false});doc.fontSize(7).text(`${i+1} / ${pages.count}`,510,807,{lineBreak:false});if(watermark){doc.save().opacity(.13).rotate(-35,{origin:[298,421]}).font('bold').fontSize(55).fillColor('#777').text(watermark,50,385,{width:500,align:'center',lineBreak:false});doc.restore();}doc.restore();}doc.end();return done;}
