"use client";
import {useEffect,useRef,useState,type ReactNode,type SyntheticEvent} from 'react';
import {createPortal} from 'react-dom';
import {X} from 'lucide-react';
/** Shared public drawer: the currency sheet's placement, grip, scrolling and dismissal. */
export function PublicSheet({title,onClose,children,ownerDocument,showHeader=true,maxWidth=760,className=''}:{title:string;onClose:()=>void;children:ReactNode;ownerDocument?:Document;showHeader?:boolean;maxWidth?:number;className?:string}){
 const doc=ownerDocument||document,close=useRef(onClose),panel=useRef<HTMLElement>(null),drag=useRef<{id:number;y:number;at:number}|null>(null),[offset,setOffset]=useState(0);close.current=onClose;
 useEffect(()=>{const root=doc.documentElement,body=doc.body,previous=[root.style.overflow,body.style.overflow],focus=doc.activeElement as HTMLElement|null;root.style.overflow='hidden';body.style.overflow='hidden';panel.current?.focus({preventScroll:true});const key=(e:KeyboardEvent)=>{if(doc.querySelector('dialog[open]')||Array.from(doc.querySelectorAll('[role=dialog][aria-modal=true]')).at(-1)!==panel.current)return;if(e.key==='Escape'){close.current();}if(e.key==='Tab'){const nodes=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input,select,textarea,[tabindex="0"]')||[]).filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&doc.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&doc.activeElement===last){e.preventDefault();first?.focus();}}};doc.defaultView?.addEventListener('keydown',key);return()=>{root.style.overflow=previous[0];body.style.overflow=previous[1];doc.defaultView?.removeEventListener('keydown',key);focus?.focus({preventScroll:true});};},[doc]);
 const dismissBackdrop=(e:SyntheticEvent)=>{if(e.target!==e.currentTarget)return;e.preventDefault();e.stopPropagation();onClose();};
 const stopSheetEvent=(e:SyntheticEvent)=>e.stopPropagation();
 return createPortal(<div className="ac-public-sheet-backdrop fixed inset-0 z-[14000] flex items-end justify-center overflow-hidden bg-black/65 backdrop-blur-md md:items-center md:p-6" onTouchEnd={dismissBackdrop} onClick={dismissBackdrop}><div onTouchEnd={stopSheetEvent} onClick={stopSheetEvent} className="ac-public-sheet-wrap relative w-full" style={{maxWidth,transform:offset?`translateY(${offset}px)`:undefined,transition:drag.current?'none':'transform 200ms ease-out'}}><div className="absolute -top-8 left-1/2 z-20 flex h-8 w-24 -translate-x-1/2 touch-none cursor-grab items-center justify-center md:hidden" aria-label="Потяните вниз, чтобы закрыть" onPointerDown={e=>{drag.current={id:e.pointerId,y:e.clientY,at:performance.now()};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current?.id===e.pointerId)setOffset(Math.max(0,e.clientY-drag.current.y));}} onPointerUp={e=>{const d=drag.current;drag.current=null;if(d&&((e.clientY-d.y)>95||(e.clientY-d.y)/Math.max(1,performance.now()-d.at)>.65))onClose();else setOffset(0);}} onPointerCancel={()=>{drag.current=null;setOffset(0);}}><span className="block h-1.5 w-12 rounded-full bg-white/70"/></div><section ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={`ac-public-sheet ac-hide-scrollbar max-h-[92dvh] w-full overflow-y-auto overscroll-contain rounded-t-[30px] bg-[var(--ac-surface)] text-[var(--ac-text)] shadow-[0_-24px_80px_rgba(0,0,0,.38)] outline-none md:rounded-[30px] ${className}`}>{showHeader&&<header className="sticky top-0 z-10 flex items-center justify-between gap-4 border-b border-[var(--ac-border)] bg-[var(--ac-surface)] px-5 py-4"><h2 className="text-xl font-black">{title}</h2><button type="button" aria-label={`Закрыть ${title.toLocaleLowerCase('ru')}`} className="flex h-11 w-11 items-center justify-center rounded-full bg-[var(--ac-surface-2)]" onClick={onClose}><X size={22}/></button></header>}{children}</section></div><style>{`@keyframes acPublicSheetIn{from{translate:0 28px;opacity:0}to{translate:0 0;opacity:1}}.ac-public-sheet-wrap{animation:acPublicSheetIn .2s ease-out}@media(prefers-reduced-motion:reduce){.ac-public-sheet-wrap{animation:none!important;transition:none!important}}`}</style></div>,doc.body);
}
