import { notFound } from "next/navigation";
import { CrmShell } from "@/components/crm/CrmShell";
import { getAuthUsers } from "@/lib/auth";
import { readChunkedDataJson } from "@/lib/data";
import { isBlockedManager } from "@/lib/crm";
import { ManagerActions } from "@/components/crm/ManagerActions";
export const dynamic="force-dynamic"; const dt=(v?:string)=>v?new Date(v).toLocaleString("ru-RU"):"—";
export default async function ManagerPage({params}:{params:{id:string}}){const managers=(await getAuthUsers()); const manager=managers.find((m)=>m.id===params.id) as any; if(!manager) notFound(); const clients=await readChunkedDataJson<any>("clients/clients.json",[]); const leads=await readChunkedDataJson<any>("leads/leads.json",[]); const deals=await readChunkedDataJson<any>("deals/deals.json",[]); const count=(arr:any[])=>arr.filter((x)=>x.assignedManagerId===manager.id||x.createdByManagerId===manager.id).length;
return <CrmShell activeHref="/crm/managers" title={manager.displayName} subtitle="Профиль менеджера, доступ, приглашения и статистика."><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="glass rounded-[2rem] p-6"><div className="flex items-center gap-4"><div className="grid h-20 w-20 place-items-center rounded-full bg-white text-3xl font-black text-black">{manager.displayName.slice(0,1).toUpperCase()}</div><div><h2 className="text-2xl font-black">{manager.displayName}</h2><p className="text-sm font-bold text-white/50">@{manager.telegramUsername} · {manager.telegramId || "Telegram ID не привязан"}</p></div></div><div className="mt-6 grid gap-3 md:grid-cols-2 text-sm font-bold text-white/65">{[["Роль",manager.role],["Статус",isBlockedManager(manager)?"Заблокирован":"Активен"],["Дата добавления",dt(manager.createdAt)],["Кто пригласил",manager.invitedBy||"—"],["Последний вход",dt(manager.lastLoginAt)],["Клиентов",count(clients)],["Лидов",count(leads)],["Сделок",count(deals)]].map(([k,v])=><div className="rounded-2xl bg-white/7 p-4" key={k}><div className="text-white/38">{k}</div><div className="mt-1 text-white">{v}</div></div>)}</div></section><aside className="glass rounded-[2rem] p-6"><h2 className="text-xl font-black">Управление owner/admin</h2><ManagerActions manager={manager}/><p className="mt-4 text-sm font-bold text-white/58">Одноразовые приглашения и приватные аватары подготовлены архитектурно, но UI создания приглашения и загрузки аватара не включён в этот draft без полного workflow.</p></aside></div></CrmShell>}
