import { notFound } from "next/navigation";
import { CrmShell } from "@/components/crm/CrmShell";
import { readChunkedDataJson } from "@/lib/data";
import { getAuthUsers } from "@/lib/auth";
import { money } from "@/lib/avtocena";
import { dealProgress } from "@/lib/crm";
import { DealEditor } from "@/components/crm/DealEditor";
export const dynamic="force-dynamic"; const dt=(v?:string)=>v?new Date(v).toLocaleString("ru-RU"):"—";
export default async function DealPage({params}:{params:{id:string}}){const deals=await readChunkedDataJson<any>("deals/deals.json",[]); const deal=deals.find((d)=>d.id===params.id); if(!deal) notFound(); const clients=await readChunkedDataJson<any>("clients/clients.json",[]); const client=clients.find((c)=>c.id===deal.clientId); const managers=(await getAuthUsers()); const manager=managers.find((m)=>m.id===deal.assignedManagerId); const p=dealProgress(deal.stageIndex||0,deal.completedAtByStage,deal.stagesSnapshot||deal.marketStages||deal.stages);
return <CrmShell activeHref="/crm/deals" title={`Сделка ${deal.number||deal.id}`} subtitle={`${p.currentStage} — этап ${p.stageNumber} из ${p.totalStages} — ${p.percent}%`}><div className="grid gap-5 lg:grid-cols-[1fr_380px]"><section className="glass rounded-[2rem] p-6"><h2 className="text-2xl font-black">Карточка сделки</h2><div className="mt-5 grid gap-3 md:grid-cols-2 text-sm font-bold text-white/65">{[["Клиент",client?.fio||deal.client],["Автомобиль",deal.car||deal.vehicle],["VIN",deal.vin],["Рынок",deal.market],["Менеджер",manager?.displayName],["Создана",dt(deal.createdAt)],["Дата подписания",dt(deal.signedAt)],["Сумма",`${money(Number(deal.totalRub||deal.amountRub||0))} ₽`],["Текущий этап",p.currentStage],["Статус",deal.status||"В работе"],["Комментарии",deal.comments||"—"]].map(([k,v])=><div className="rounded-2xl bg-white/7 p-4" key={k}><div className="text-white/38">{k}</div><div className="mt-1 text-white">{v||"—"}</div></div>)}</div></section><aside className="glass rounded-[2rem] p-6"><h2 className="text-xl font-black">Договоры и документы</h2><p className="mt-3 text-sm font-bold text-white/60">Договор формируется в карточке клиента, где выбирается шаблон и сделка; здесь отображаются данные сделки и рабочее управление этапами.</p></aside></div><div className="mt-5"><DealEditor deal={deal} managers={managers} progress={p}/></div><section className="glass mt-5 rounded-[2rem] p-6"><h2 className="text-xl font-black">Прогресс сделки</h2><div className="mt-5 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-red-500" style={{width:`${p.percent}%`}} /></div><div className="mt-4 grid gap-3 md:grid-cols-4">{p.stages.map((s)=><div key={s.title} className={`rounded-2xl p-4 text-sm font-bold ${s.done?"bg-emerald-500/15 text-emerald-100":"bg-white/7 text-white/45"}`}><div>{s.index+1}. {s.title}</div><div className="mt-1 text-xs">{s.completedAt?dt(s.completedAt):s.future?"Будущий этап":"Пройден"}</div></div>)}</div></section></CrmShell>}
