import Link from "next/link";
import { notFound } from "next/navigation";
import { CrmShell } from "@/components/crm/CrmShell";
import { readChunkedDataJson, readDataJson } from "@/lib/data";
import { getAuthUsers } from "@/lib/auth";
import { money } from "@/lib/avtocena";

export const dynamic = "force-dynamic";
function dt(v?: string) { return v ? new Date(v).toLocaleString("ru-RU") : "—"; }
function mn(ms:any[], id?:string){ return ms.find((m)=>m.id===id)?.displayName || "Не назначен"; }
export default async function ClientCard({ params }: { params: { id: string } }) {
 const clients=await readChunkedDataJson<any>("clients/clients.json",[]); const client=clients.find((c)=>c.id===params.id); if(!client) notFound();
 const leads=(await readChunkedDataJson<any>("leads/leads.json",[])).filter((l)=>l.clientId===client.id); const deals=(await readChunkedDataJson<any>("deals/deals.json",[])).filter((d)=>d.clientId===client.id); const templates=await readDataJson<any[]>("contracts/templates.json",[]); const managers=getAuthUsers();
 return <CrmShell activeHref="/crm/clients" title={client.fio || "Карточка клиента"} subtitle="Редактирование без дублей, документы, договоры и история действий.">
  <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="glass rounded-[2rem] p-6"><h2 className="text-2xl font-black">Данные клиента</h2><form action="/api/crm/clients" method="post" className="mt-5 grid gap-3 md:grid-cols-2">
   {[["fio","ФИО"],["phone","Телефон"],["telegram","Telegram"],["city","Город"],["birthDate","Дата рождения"],["passport","Паспортные данные"],["address","Адрес"],["interestedCar","Интересующий автомобиль"],["market","Рынок"],["budgetRub","Бюджет"],["source","Источник"]].map(([k,p])=><input key={k} name={k} defaultValue={client[k]||""} placeholder={p} className="soft-input rounded-2xl px-4 py-3 text-sm font-bold" />)}
   <select name="assignedManagerId" defaultValue={client.assignedManagerId||""} className="soft-input rounded-2xl bg-zinc-950 px-4 py-3 text-sm font-bold text-white">{managers.map((m)=><option key={m.id} value={m.id}>{m.displayName}</option>)}</select><textarea name="comments" defaultValue={client.comments||client.comment||""} placeholder="Комментарии" className="soft-input resize-none rounded-2xl px-4 py-3 text-sm font-bold md:col-span-2" rows={4}/>
   <div className="md:col-span-2 rounded-2xl bg-white/7 p-4 text-sm font-bold text-white/60">Создан: {dt(client.createdAt)} · Последнее изменение: {dt(client.updatedAt)} · Статус: {client.status||"active"}</div>
  </form></section><aside className="space-y-5"><div className="glass rounded-[2rem] p-6"><h3 className="text-xl font-black">Договор</h3><div className="mt-3 grid gap-3 text-sm font-bold text-white/62"><select className="soft-input rounded-2xl bg-zinc-950 px-4 py-3 text-white"><option>Выберите шаблон</option>{templates.map((t)=><option key={t.id}>{t.name}</option>)}</select><select className="soft-input rounded-2xl bg-zinc-950 px-4 py-3 text-white"><option>Выберите сделку</option>{deals.map((d)=><option key={d.id}>{d.number||d.id}</option>)}</select><button className="avto-button rounded-2xl px-4 py-3">Сформировать договор</button><p>PNG-подпись директора вставляется как изображение и не является электронной подписью. DOCX сохраняется в приватное Object Storage, версии остаются в истории.</p></div></div></aside></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-3"><section className="glass rounded-[2rem] p-6"><h2 className="text-xl font-black">Связанные лиды</h2>{leads.map((l)=><Link className="mt-3 block rounded-2xl bg-white/7 p-3 text-sm font-bold hover:bg-white/10" href="/crm/leads" key={l.id}>{l.car||"Заявка"} · {l.status}</Link>)}</section><section className="glass rounded-[2rem] p-6"><h2 className="text-xl font-black">Сделки</h2>{deals.map((d)=><Link className="mt-3 block rounded-2xl bg-white/7 p-3 text-sm font-bold hover:bg-white/10" href={`/crm/deals/${d.id}`} key={d.id}>{d.number||d.id} · {d.amountRub?money(d.amountRub):"—"} ₽</Link>)}</section><section className="glass rounded-[2rem] p-6"><h2 className="text-xl font-black">Документы</h2><p className="mt-3 text-sm font-bold text-white/60">Паспорт, водительское удостоверение, договор, доверенность, платёжный и произвольный документ скачиваются только через защищённый CRM API для owner/admin или назначенного менеджера.</p>{(client.documents||[]).map((d:any)=><div className="mt-3 rounded-2xl bg-white/7 p-3 text-sm font-bold" key={d.objectKey}>{d.fileName} · SHA-256 {String(d.checksum||"").slice(0,12)}…</div>)}</section></div>
  <section className="glass mt-5 rounded-[2rem] p-6"><h2 className="text-xl font-black">История действий</h2><div className="mt-4 space-y-2">{(client.history||[]).map((h:any,i:number)=><div className="rounded-2xl bg-white/7 px-4 py-3 text-sm font-bold text-white/62" key={i}>{dt(h.at)} · {h.type} · {h.operationId}</div>)}</div></section>
 </CrmShell>;
}
