import fs from 'node:fs';
import path from 'node:path';
const OFFERS='data/catalog/offers/offers.json'; const INDEX='data/catalog/offers/offers-index.json'; const MAX=500;
export function readJson(file, fallback=[]){ try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback} }
export function atomicWrite(file, value){ fs.mkdirSync(path.dirname(file),{recursive:true}); const tmp=`${file}.${process.pid}.${Date.now()}.tmp`; fs.writeFileSync(tmp, JSON.stringify(value,null,2)); fs.renameSync(tmp,file); }
export function parseInput(file){ const raw=fs.readFileSync(file,'utf8'); if(file.endsWith('.json')) return JSON.parse(raw); const [head,...lines]=raw.trim().split(/\r?\n/); const keys=head.split(',').map(k=>k.trim()); return lines.filter(Boolean).map(line=>Object.fromEntries(line.split(',').map((v,i)=>[keys[i],v.trim()]))); }
export function isDemo(o){ return /^demo-/i.test(o.sourceListingId||''); }
export function isSpecificUrl(u=''){ try{ const p=new URL(u); return p.pathname.length>8 && !/\/($|usedcars\/?$|used\/?$|search|list\/|car\/?$)/i.test(p.pathname+p.search);}catch{return false} }
export function isPlaceholderImage(u=''){ try{ return ['images.unsplash.com','unsplash.com','placehold.co','placeholder.com','picsum.photos'].includes(new URL(String(u).split('#')[0]).hostname.replace(/^www\./,'')); }catch{return true} }
export function hasProvenance(o){ const p=o.provenance||{}; return ['priceLocal','year','mileageKm','images'].every(k=>Array.isArray(p[k])&&p[k].length); }
export function getRate(currency, asOf=new Date()){ if(currency==='RUB') return {id:'rub-1',currency:'RUB',rateRub:1,source:'RUB base',checkedAt:asOf.toISOString(),effectiveFrom:asOf.toISOString()}; const rates=readJson('data/catalog/exchange-rates.json',[]).filter(r=>r.currency===currency && new Date(r.effectiveFrom)<=asOf).sort((a,b)=>new Date(b.effectiveFrom)-new Date(a.effectiveFrom)); const rate=rates[0]; if(!rate) return null; if((asOf-new Date(rate.checkedAt))/864e5>7) return null; return rate; }
function marketVersion(market){ const markets=readJson('data/markets/markets.json',[]); const row=markets.find(m=>m.id===market); const versions=(row?.versions||[]).filter(v=>!['draft','archived'].includes(v.status||'')); return versions.sort((a,b)=>new Date(b.effectiveFrom||0)-new Date(a.effectiveFrom||0))[0] || null; }
export function calculate(o, asOf=new Date()){ const rate=getRate(o.currency,asOf), ver=marketVersion(o.market); if(!rate||!ver) return {...o, calculationSnapshot:undefined, calculationConfidence:'needs_review', availability:'needs_review'}; const sourcePriceRub=Math.round(Number(o.priceLocal)*(rate.rateRubPerUnit ?? rate.rateRub)); const fixed=['securityDepositRub','topAvtoCommissionRub','exportExpensesRub','logisticsRub','brokerRub','svhRub','laboratoryRub','sbktsRub','eptsRub','rfDeliveryRub','otherFixedExpensesRub'].reduce((s,k)=>s+Number(ver[k]||0),0); const reserve=Math.round(sourcePriceRub*Number(ver.exchangeRateReservePercent||0)/100); const lines=[{id:'car',title:'Стоимость автомобиля',amountRub:sourcePriceRub},{id:'exchange-reserve',title:'Резерв на изменение курса',amountRub:reserve}].filter(l=>l.amountRub>0); const total=sourcePriceRub+fixed+reserve; return {...o, calculationConfidence:'medium', calculationSnapshot:{settingsVersion:ver.id,marketConfigVersion:ver.id,calculatedAt:asOf.toISOString(),exchangeRate:(rate.rateRubPerUnit ?? rate.rateRub),exchangeRateVersion:(rate.id ?? `${rate.currency}-${rate.effectiveFrom}`),exchangeRateSource:rate.source,sourcePriceLocal:Number(o.priceLocal),sourcePriceRub,totalRub:total,complete:false,lines}}; }
export function validate(o){ const rejected=[]; if(isDemo(o)) rejected.push('demo sourceListingId'); if(!isSpecificUrl(o.sourceUrl)) rejected.push('not a concrete listing URL'); if(!o.images?.length || o.images.some(isPlaceholderImage) || isPlaceholderImage(o.coverImage)) rejected.push('placeholder/missing image'); if(!hasProvenance(o)) rejected.push('missing provenance'); if(!o.calculationSnapshot?.exchangeRateVersion) rejected.push('missing confirmed exchange rate'); if(!o.powerHp) rejected.push('missing power'); return rejected; }
export function normalize(row){ return {...row, priceLocal:Number(row.priceLocal), year:Number(row.year), mileageKm: row.mileageKm===''?null:Number(row.mileageKm), engineCc: row.engineCc?Number(row.engineCc):null, powerHp: row.powerHp?Number(row.powerHp):null, powerKw: row.powerKw?Number(row.powerKw):null, images:Array.isArray(row.images)?row.images:String(row.images||row.coverImage||'').split('|').filter(Boolean), eligibilityReasons:Array.isArray(row.eligibilityReasons)?row.eligibilityReasons:[], dataQualityScore:Number(row.dataQualityScore||0.7), calculationConfidence:row.calculationConfidence||'needs_review', availability:row.availability||'unverified', importEligibility:row.importEligibility||'unknown'}; }
export function dedupe(list){ const seen=new Set(); return list.filter(o=>{ const key=`${o.source}:${o.sourceListingId}`; if(seen.has(key)||seen.has(o.sourceUrl)) return false; seen.add(key); seen.add(o.sourceUrl); return true; }); }
export function buildChunks(list){ fs.mkdirSync('data/catalog/offers',{recursive:true}); const chunks=[]; for(let i=0;i<Math.max(1,Math.ceil(list.length/MAX));i++){ const part=list.slice(i*MAX,(i+1)*MAX); const file=i===0?'offers.json':`offers-${String(i+1).padStart(4,'0')}.json`; atomicWrite(`data/catalog/offers/${file}`,part); chunks.push({file,count:part.length,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}); } atomicWrite(INDEX,{version:1,collection:'offers',maxRecordsPerChunk:MAX,total:list.length,updatedAt:new Date().toISOString(),chunks}); }
export function readOffers(){ return readJson(OFFERS,[]); }
