import fs from "node:fs";
import { catalogMarkets, readAllMarketOffers, writeAllMarketOffers, writeFeaturedOffers } from "../apps/web/lib/catalog/storage";
import { recalculateOffer, expireStaleOffers, deduplicateOffers } from "../apps/web/lib/catalog/pipeline";
import { validatePublishableOffer } from "../apps/web/lib/catalog/validation";
import { getSourceAdapters, sourceRegistry } from "../apps/web/lib/catalog/adapters/registry";
import type { VehicleOffer } from "../apps/web/lib/catalog/types";

function parseInput(file: string) { const raw=fs.readFileSync(file,"utf8"); if (file.endsWith(".json")) return JSON.parse(raw); const [head,...lines]=raw.trim().split(/\r?\n/); const keys=head.split(",").map((key)=>key.trim()); return lines.filter(Boolean).map((line)=>Object.fromEntries(line.split(",").map((value,index)=>[keys[index], value.trim()]))); }
function normalize(row: any): VehicleOffer { return { ...row, priceLocal:Number(row.priceLocal), year:Number(row.year || row.advertisedModelYear || row.manufactureYear), advertisedModelYear: row.advertisedModelYear ? Number(row.advertisedModelYear) : row.year ? Number(row.year) : null, manufactureYear: row.manufactureYear ? Number(row.manufactureYear) : null, mileageKm: row.mileageKm === "" ? null : Number(row.mileageKm), engineCc: row.engineCc ? Number(row.engineCc) : null, powerHp: row.powerHp ? Number(row.powerHp) : null, powerKw: row.powerKw ? Number(row.powerKw) : null, images:Array.isArray(row.images) ? row.images : String(row.images || "").split("|").filter(Boolean), eligibilityReasons:Array.isArray(row.eligibilityReasons) ? row.eligibilityReasons : [], dataQualityScore:Number(row.dataQualityScore || 0.7), calculationConfidence: row.calculationConfidence || "needs_review", calculationStatus: row.calculationStatus || "needs_review", calculationComplete: row.calculationComplete === true, listingStatus: row.listingStatus || row.availability || "unverified", listingConfidence: row.listingConfidence || "needs_review", availability: row.availability || "unverified", importEligibility: row.importEligibility || "unknown" } as VehicleOffer; }
async function importFile(file: string) { const current=readAllMarketOffers(); const byId=new Map(current.map((offer)=>[offer.id, offer])); const report={added:0,updated:0,rejected:0,needs_review:0,rejections:[] as unknown[]}; for (const row of parseInput(file)) { const calculated=recalculateOffer(normalize(row)); const errors=validatePublishableOffer(calculated).reasons; if (errors.some((error)=>/demo|concrete|direct image/.test(error))) { report.rejected++; report.rejections.push({ id: calculated.id, errors }); continue; } if (errors.length || calculated.calculationStatus !== "complete") report.needs_review++; if (byId.has(calculated.id)) report.updated++; else report.added++; byId.set(calculated.id, calculated); } writeAllMarketOffers(deduplicateOffers([...byId.values()])); writeFeaturedOffers(); return report; }
async function importAll() { const adapters=getSourceAdapters().filter((adapter)=>adapter.config.enabled); const results=[]; for (const adapter of adapters) { const started=Date.now(); try { const health=await adapter.healthCheck(); if (!health.ok || !["operational", "operational_manual"].includes(adapter.config.status)) { results.push({ sourceId:adapter.config.id, imported:0, updated:0, rejected:0, skipped:1, error:health.message || "not operational" }); continue; } await new Promise((resolve)=>setTimeout(resolve, adapter.config.requestDelayMs)); results.push({ sourceId:adapter.config.id, imported:0, updated:0, rejected:0, skipped:1, error:"network adapters are scaffolded; use approved manual files until implemented", responseMs:Date.now()-started }); } catch (error) { results.push({ sourceId:adapter.config.id, imported:0, updated:0, rejected:0, skipped:0, error:String(error) }); } } return { sources: sourceRegistry.length, enabled: adapters.length, results }; }
async function main() { const cmd=process.argv[2]; if (cmd === "catalog:import") { const input=process.argv[3]; if (!input) throw new Error("Usage: npm run catalog:import -- file.json|file.csv"); console.log(JSON.stringify(await importFile(input), null, 2)); } else if (cmd === "catalog:import:all") console.log(JSON.stringify(await importAll(), null, 2)); else if (cmd === "catalog:validate") { const report=readAllMarketOffers().map((offer)=>({ id:offer.id, errors:validatePublishableOffer(offer).reasons })).filter((item)=>item.errors.length); console.log(JSON.stringify({ markets:catalogMarkets.length, validated:readAllMarketOffers().length, rejected:report.length, report }, null, 2)); process.exit(report.length ? 1 : 0); } else if (cmd === "catalog:recalculate") { const next=readAllMarketOffers().map((offer)=>recalculateOffer(offer)); writeAllMarketOffers(next); writeFeaturedOffers(); console.log(JSON.stringify({ recalculated:next.length }, null, 2)); } else if (cmd === "catalog:expire") { const next=expireStaleOffers(readAllMarketOffers()); writeAllMarketOffers(next); writeFeaturedOffers(); console.log(JSON.stringify({ expired:next.filter((offer)=>offer.availability === "stale").length, total:next.length }, null, 2)); } else if (cmd === "catalog:build-indexes") { const offers=readAllMarketOffers(); writeAllMarketOffers(offers); writeFeaturedOffers(); console.log(JSON.stringify({ indexed:offers.length }, null, 2)); } else throw new Error("Unknown catalog command"); }
main().catch((error)=>{ console.error(error); process.exit(1); });
