from pathlib import Path

p=Path('apps/web/lib/catalog/storage.ts')
s=p.read_text()
s=s.replace('import { hasCredibleOfferContent } from "./offer-quality";','import { hasCredibleOfferContent } from "./offer-quality";\nimport { rankedCatalogImageUrls } from "./image-quality";\nimport { catalogOfferVisibleRub } from "./public-priority";')
old='''export type CatalogSearchProjection = {\n  id: string; market: string; make: string; model: string; year: number; totalRub?: number | null; mileageKm?: number; engineCc?: number; powerHp?: number;\n  fuel?: string; bodyType?: string; transmission?: string; drive?: string; auctionGrade?: string; auctionDate?: string; updatedAt?: string; firstSeenAt?: string; sourcePublishedAt?: string;\n};'''
new='''export type CatalogSearchProjection = {\n  id: string; market: string; make: string; model: string; year: number; totalRub?: number | null; mileageKm?: number; engineCc?: number; powerHp?: number;\n  fuel?: string; bodyType?: string; transmission?: string; drive?: string; auctionGrade?: string; auctionDate?: string; updatedAt?: string; firstSeenAt?: string; sourcePublishedAt?: string;\n  trim?: string; powerKw?: number; powertrainKind?: string; power30MinKw?: number; power30MinKwByMotor?: number[]; utilizationPowerKw?: number;\n  sourcePrice?: number | null; sourceCurrency?: string | null; priceMode?: string; previousTotalRub?: number | null; priceDeltaRub?: number | null; priceChangedAt?: string;\n  calculationStatus?: string; calculationSnapshot?: { currencyRate?: any; pricingConfidence?: string } | null; publicVisibleRub?: number; cardImageUrl?: string; seriesId?: string; cardProjectionVersion?: 1;\n};'''
if old not in s: raise SystemExit('projection type block missing')
s=s.replace(old,new,1)
old='''function searchProjectionFromOffer(offer: VehicleOffer): CatalogSearchProjection {\n  return {\n    id: offer.id, market: String(offer.market || ""), make: cleanFacet(offer.make), model: cleanFacet(offer.model), year: Number(offer.year || 0),\n    totalRub: offer.totalRub, mileageKm: offer.mileageKm, engineCc: offer.engineCc, powerHp: offer.powerHp, fuel: cleanFacet(offer.fuel), bodyType: cleanFacet(offer.bodyType),\n    transmission: cleanFacet(offer.transmission), drive: cleanFacet(offer.drive), auctionGrade: cleanFacet(offer.auctionGrade), auctionDate: offer.auctionDate, updatedAt: offer.updatedAt,\n    firstSeenAt: offer.firstSeenAt, sourcePublishedAt: String((offer.operational as any)?.sourcePublishedAt || "") || undefined,\n  };\n}'''
new='''function searchProjectionFromOffer(offer: VehicleOffer): CatalogSearchProjection {\n  const visibleRub = catalogOfferVisibleRub(offer);\n  const raw: any = offer.operational?.raw || {};\n  return {\n    id: offer.id, market: String(offer.market || ""), make: cleanFacet(offer.make), model: cleanFacet(offer.model), year: Number(offer.year || 0),\n    totalRub: visibleRub || null, mileageKm: offer.mileageKm, engineCc: offer.engineCc, powerHp: offer.powerHp, fuel: cleanFacet(offer.fuel), bodyType: cleanFacet(offer.bodyType),\n    transmission: cleanFacet(offer.transmission), drive: cleanFacet(offer.drive), auctionGrade: cleanFacet(offer.auctionGrade), auctionDate: offer.auctionDate, updatedAt: offer.updatedAt,\n    firstSeenAt: offer.firstSeenAt, sourcePublishedAt: String((offer.operational as any)?.sourcePublishedAt || "") || undefined,\n    trim: cleanFacet(offer.trim), powerKw: offer.powerKw, powertrainKind: offer.powertrainKind, power30MinKw: offer.power30MinKw, power30MinKwByMotor: offer.power30MinKwByMotor, utilizationPowerKw: offer.utilizationPowerKw,\n    sourcePrice: offer.sourcePrice, sourceCurrency: offer.sourceCurrency, priceMode: offer.priceMode, previousTotalRub: visibleRub ? offer.previousTotalRub : null, priceDeltaRub: visibleRub ? offer.priceDeltaRub : null, priceChangedAt: offer.priceChangedAt,\n    calculationStatus: offer.calculationStatus, calculationSnapshot: { currencyRate: offer.calculationSnapshot?.currencyRate, pricingConfidence: offer.calculationSnapshot?.pricingConfidence },\n    publicVisibleRub: visibleRub || undefined, cardImageUrl: rankedCatalogImageUrls(offer)[0] || undefined,\n    seriesId: String(raw?.listing?.seriesId || raw?.seriesId || (offer as any)?.seriesId || "") || undefined, cardProjectionVersion: 1,\n  };\n}\nfunction projectionCanRenderCard(row: CatalogSearchProjection) {\n  return row.cardProjectionVersion === 1 && Boolean(row.id && row.market && row.make && row.model && row.year);\n}\nfunction publicOfferFromProjection(row: CatalogSearchProjection): PublicVehicleOffer {\n  const imageUrl = String(row.cardImageUrl || "");\n  return {\n    ...row, status: "active", offerType: "fixed", priceMode: (row.priceMode || "fixed") as any, calculationStatus: (row.calculationStatus || "needs_data") as any,\n    sourcePrice: row.sourcePrice ?? null, sourceCurrency: row.sourceCurrency ?? null,\n    images: imageUrl ? [{ id: "", url: imageUrl, width: undefined, height: undefined, size: 0, mimeType: "image/jpeg" }] : [],\n    firstSeenAt: row.firstSeenAt || row.updatedAt || "", updatedAt: row.updatedAt || row.firstSeenAt || "",\n  } as any;\n}'''
if old not in s: raise SystemExit('projection function block missing')
s=s.replace(old,new,1)
# correct market-only facets instead of global makes
old='''  if (!hasFilters) {\n    return {\n      ...indexed, generationId: manifest.generationId,\n      makes: uniqueText(indexed.makes || []).sort((a, b) => a.localeCompare(b, "ru")),\n      models: [], markets: [...PUBLIC_CATALOG_MARKETS],\n    };\n  }'''
new='''  if (!hasFilters) {\n    if (params.market && params.market !== "any") {\n      const projection = await readSearchProjection(manifest.generationId, String(params.market));\n      if ((projection.items || []).length) {\n        return {\n          generationId: manifest.generationId,\n          makes: uniqueText((projection.items || []).map((row) => row.make)).sort((a, b) => a.localeCompare(b, "ru")),\n          models: [], markets: [...PUBLIC_CATALOG_MARKETS],\n          bodyTypes: uniqueText((projection.items || []).map((row) => row.bodyType)).sort(),\n          fuels: uniqueText((projection.items || []).map((row) => row.fuel)).sort(),\n          transmissions: uniqueText((projection.items || []).map((row) => row.transmission)).sort(),\n          drives: uniqueText((projection.items || []).map((row) => row.drive)).sort(),\n        };\n      }\n    }\n    return {\n      ...indexed, generationId: manifest.generationId,\n      makes: uniqueText(indexed.makes || []).sort((a, b) => a.localeCompare(b, "ru")),\n      models: [], markets: [...PUBLIC_CATALOG_MARKETS],\n    };\n  }'''
if old not in s: raise SystemExit('facets fast block missing')
s=s.replace(old,new,1)
# exact make+model direct index before expensive vehicle knowledge model resolver
old='''  if (params.model) {\n    const matches = await resolveVehicleModelQuery(params.model, params.make, 100);\n    const candidates = matches.length ? matches.map((match) => `${match.make}:${match.model}`) : params.make ? [`${params.make}:${params.model}`] : [];\n    ids = intersect(ids, await unionIndexIds(manifest, "model", candidates, used));\n  }'''
new='''  if (params.model) {\n    let modelIds: string[] = [];\n    if (params.make) {\n      const directPath = `model/${cleanShard(`${params.make}:${params.model}`)}.json`;\n      const direct = await readIndex<{ ids: string[] }>(manifest.generationId, directPath, { ids: [] });\n      used.push(`catalog/generations/${manifest.generationId}/indexes/${directPath}`);\n      modelIds = direct.ids || [];\n    }\n    if (!modelIds.length) {\n      const matches = await resolveVehicleModelQuery(params.model, params.make, 100);\n      const candidates = matches.length ? matches.map((match) => `${match.make}:${match.model}`) : params.make ? [`${params.make}:${params.model}`] : [];\n      modelIds = await unionIndexIds(manifest, "model", candidates, used);\n    }\n    ids = intersect(ids, modelIds);\n  }'''
if old not in s: raise SystemExit('candidate model block missing')
s=s.replace(old,new,1)
# replace search page full-chunk stage with future projection-card fast path + safe legacy fallback
old='''  const pageSet = new Set(pageIds);\n  const chunkKeys = new Map<string, OfferLocation>();\n  for (const id of pageIds) { const loc = byId.byId[id]; if (loc) chunkKeys.set(`${loc.market}/${loc.chunk}`, loc); }\n  const chunkLocations = [...chunkKeys.values()];\n  const readConcurrency = Math.max(1, Math.min(32, Number(process.env.CATALOG_SEARCH_CHUNK_CONCURRENCY || 12)));\n  const loaded = (await mapWithConcurrency(chunkLocations, readConcurrency, (loc) => readDataJson<VehicleOffer[]>(offerPath(manifest.generationId, loc.market, loc.chunk), []))).flat();\n  let items = loaded.filter((offer) => pageSet.has(offer.id) && isPublicOffer(offer));\n  const rank = new Map(pageIds.map((id, index) => [id, index]));\n  items.sort((a,b) => (rank.get(a.id) ?? Number.MAX_SAFE_INTEGER) - (rank.get(b.id) ?? Number.MAX_SAFE_INTEGER));\n  return { generationId: manifest.generationId, total, page, pageSize, items: items.map(publicOffer), usedIndexShards: used.length ? used : [`catalog/generations/${manifest.generationId}/indexes/order-updatedAt.json`] };'''
new='''  const projectionMarkets = params.market && params.market !== "any" ? [String(params.market)] : [...new Set(pageIds.map((id) => String(byId.byId[id]?.market || "")).filter(Boolean))];\n  if (projectionMarkets.length) {\n    const projected = (await mapWithConcurrency(projectionMarkets, Math.min(7, projectionMarkets.length), async (market) => (await readSearchProjection(manifest.generationId, market)).items || [])).flat();\n    const projectedById = new Map(projected.filter(projectionCanRenderCard).map((row) => [row.id, row]));\n    if (pageIds.length && pageIds.every((id) => projectedById.has(id))) {\n      used.push(...projectionMarkets.map((market) => `catalog/generations/${manifest.generationId}/indexes/projection/${cleanShard(market)}.json`));\n      return { generationId: manifest.generationId, total, page, pageSize, items: pageIds.map((id) => publicOfferFromProjection(projectedById.get(id)!)), usedIndexShards: [...new Set(used.length ? used : [`catalog/generations/${manifest.generationId}/indexes/order-updatedAt.json`])] };\n    }\n  }\n\n  const pageSet = new Set(pageIds);\n  const chunkKeys = new Map<string, OfferLocation>();\n  for (const id of pageIds) { const loc = byId.byId[id]; if (loc) chunkKeys.set(`${loc.market}/${loc.chunk}`, loc); }\n  const chunkLocations = [...chunkKeys.values()];\n  const readConcurrency = Math.max(1, Math.min(32, Number(process.env.CATALOG_SEARCH_CHUNK_CONCURRENCY || 12)));\n  const loaded = (await mapWithConcurrency(chunkLocations, readConcurrency, (loc) => readDataJson<VehicleOffer[]>(offerPath(manifest.generationId, loc.market, loc.chunk), []))).flat();\n  let items = loaded.filter((offer) => pageSet.has(offer.id) && isPublicOffer(offer));\n  const rank = new Map(pageIds.map((id, index) => [id, index]));\n  items.sort((a,b) => (rank.get(a.id) ?? Number.MAX_SAFE_INTEGER) - (rank.get(b.id) ?? Number.MAX_SAFE_INTEGER));\n  return { generationId: manifest.generationId, total, page, pageSize, items: items.map(publicOffer), usedIndexShards: used.length ? used : [`catalog/generations/${manifest.generationId}/indexes/order-updatedAt.json`] };'''
if old not in s: raise SystemExit('search load block missing')
s=s.replace(old,new,1)
p.write_text(s)

# CatalogCard may receive compact projection with a pre-ranked source cover.
p=Path('apps/web/components/catalog/CatalogCard.tsx')
s=p.read_text()
old='''  const normalizedOffer = normalizeVehicleOfferSpecs(offer);\n  const rankedImages = rankedCatalogImageUrls(normalizedOffer);'''
new='''  const normalizedOffer = normalizeVehicleOfferSpecs(offer);\n  const projectedCover = String((offer as any)?.cardImageUrl || "").trim();\n  const rankedImages = projectedCover ? [projectedCover] : rankedCatalogImageUrls(normalizedOffer);'''
if old not in s: raise SystemExit('CatalogCard image block missing')
s=s.replace(old,new,1)
p.write_text(s)

# Allow server-generated compact projections to carry an already-gated public price.
p=Path('apps/web/lib/catalog/public-priority.ts')
s=p.read_text()
old='''export function catalogOfferVisibleRub(offer: Partial<VehicleOffer> | any) {\n  if (!completeCalculation(offer) && !preliminaryElectrifiedCalculation(offer)) return 0;\n  const totalRub = Math.round(positive(offer?.totalRub, 1_000_000_000));'''
new='''export function catalogOfferVisibleRub(offer: Partial<VehicleOffer> | any) {\n  const projectedVisibleRub = Math.round(positive(offer?.publicVisibleRub, 1_000_000_000));\n  if (projectedVisibleRub) {\n    const { absoluteMaximumRub } = publicPriceLimits();\n    return projectedVisibleRub <= absoluteMaximumRub ? projectedVisibleRub : 0;\n  }\n  if (!completeCalculation(offer) && !preliminaryElectrifiedCalculation(offer)) return 0;\n  const totalRub = Math.round(positive(offer?.totalRub, 1_000_000_000));'''
if old not in s: raise SystemExit('visible price block missing')
s=s.replace(old,new,1)
p.write_text(s)

print('catalog_card_projection_patch_ok')
