from pathlib import Path
p=Path('apps/web/lib/catalog/image-quality.ts')
s=p.read_text()
old='''function catalogImageDedupKey(image: CatalogImageLike) {\n  const sourceUrl = text(image.url);\n  // Source-URL identity must win for Mashina because source_urls_only stores\n'''
new='''function autoHomePhotoIdentity(value: unknown) {\n  const source = text(value);\n  if (!source) return "";\n  try {\n    const url = new URL(source, "https://catalog.local");\n    if (!/(?:^|\\.)autoimg\\.cn$/i.test(url.hostname)) return "";\n    const filename = decodeURIComponent(url.pathname.split("/").pop() || "")\n      .replace(/^\\d{2,4}x\\d{1,4}_c\\d+_/i, "")\n      .toLowerCase();\n    return filename.includes("autohomecar__") ? `autohome:${filename}` : "";\n  } catch { return ""; }\n}\n\nfunction catalogImageDedupKey(image: CatalogImageLike) {\n  const sourceUrl = text(image.url);\n  const autohomeIdentity = autoHomePhotoIdentity(sourceUrl);\n  if (autohomeIdentity) return autohomeIdentity;\n  // Source-URL identity must win for Mashina because source_urls_only stores\n'''
if old not in s: raise SystemExit('dedup marker missing')
s=s.replace(old,new,1)
start=s.index('export function rankedCatalogImageUrls(offer: any) {')
end=s.index('\n}',start)+2
old_block=s[start:end]
new_block='''export function rankedCatalogImageUrls(offer: any) {\n  const images: CatalogImageLike[] = Array.isArray(offer?.images) ? offer.images : [];\n  const candidates = images\n    .map((image, index) => ({\n      image, index, url: stablePublicImageUrl(image), key: catalogImageDedupKey(image), score: catalogImageScore(image),\n      sourceUrl: text(image.url),\n    }))\n    .filter((candidate) => candidate.url && candidate.score >= 0);\n\n  // AutoHome legacy public rows can contain one 900px image followed by 240px\n  // thumbnails even when a full-size exact gallery exists upstream. Do not render\n  // those tiny delivery renditions in the customer gallery. The exact-gallery\n  // refresh replaces them in storage; this display guard prevents blur meanwhile.\n  const displayCandidates = candidates.filter((candidate) =>\n    !/^https?:\\/\\/g\\.autoimg\\.cn\\/@img\\/.*\\/(?:240|300|320|360|400)x0_c\\d+_/i.test(candidate.sourceUrl));\n  const usable = displayCandidates.length ? displayCandidates : candidates;\n\n  // Preserve source gallery/cover order. For duplicate delivery renditions of the\n  // same source photo, keep the highest-quality rendition but retain the original\n  // photo's first source position. Global score sorting used to move dashboards or\n  // inspection frames ahead of a source-designated exterior cover.\n  const groups = new Map<string, { firstIndex: number; best: typeof usable[number] }>();\n  for (const candidate of usable) {\n    const renderedUrl = canonicalUrl(candidate.url);\n    const key = candidate.key || (renderedUrl ? `rendered:${renderedUrl}` : `index:${candidate.index}`);\n    const existing = groups.get(key);\n    const directAutoHome = /^https?:\\/\\/car\\d+\\.autoimg\\.cn\\/cardfs\\/product\\//i.test(candidate.sourceUrl) ? 8 : 0;\n    const existingDirect = existing && /^https?:\\/\\/car\\d+\\.autoimg\\.cn\\/cardfs\\/product\\//i.test(existing.best.sourceUrl) ? 8 : 0;\n    if (!existing) groups.set(key, { firstIndex: candidate.index, best: candidate });\n    else if (candidate.score + directAutoHome > existing.best.score + existingDirect) groups.set(key, { firstIndex: existing.firstIndex, best: candidate });\n  }\n\n  const seenUrls = new Set<string>();\n  const result: string[] = [];\n  for (const group of [...groups.values()].sort((a, b) => a.firstIndex - b.firstIndex)) {\n    const renderedUrl = canonicalUrl(group.best.url);\n    if (renderedUrl && seenUrls.has(renderedUrl)) continue;\n    if (renderedUrl) seenUrls.add(renderedUrl);\n    result.push(group.best.url);\n    if (result.length >= 30) break;\n  }\n  return result;\n}'''
s=s[:start]+new_block+s[end:]
p.write_text(s)
print('gallery_source_order_autohome_ok')
