import {getCurrentUser} from '@/lib/auth';
import {getJsonStorage,mutateDataJson} from '@/lib/data';
import {staffDocumentAccess,staffDocumentIndex,staffDocumentKey,readStaffDocuments} from '@/lib/staff-documents';
import {decryptClientDocument,type ClientDocument} from '@/lib/client-documents';
import {isCalculationOriginAllowed} from '@/lib/catalog/calculation-request-origin';
import {recordCrmActivity} from '@/lib/crm-activity';
export const runtime='nodejs';export const dynamic='force-dynamic';
const headers={'Cache-Control':'private, no-store, max-age=0'};
export async function GET(request:Request,{params}:{params:Promise<{id:string;documentId:string}>}){
 const actor=await getCurrentUser();if(!actor)return new Response(null,{status:401,headers});const q=new URL(request.url).searchParams;if(q.get('confirmed')!=='1')return Response.json({error:'Подтвердите просмотр или скачивание.'},{status:400,headers});
 try{const {id,documentId}=await params;await staffDocumentAccess(actor,id);if(!/^[a-f0-9-]{36}$/.test(documentId))return new Response(null,{status:404,headers});const doc=(await readStaffDocuments(id)).find(d=>d.id===documentId&&!d.deletedAt);if(!doc)return new Response(null,{status:404,headers});const key=staffDocumentKey(id,documentId),stored=await getJsonStorage().getBinary?.(key);if(!stored)return new Response(null,{status:404,headers});const data=Buffer.from(JSON.parse(decryptClientDocument(stored.data,key).toString()).data,'base64');const inline=q.get('download')!=='1'&&(doc.mime.startsWith('image/')||doc.mime==='application/pdf');
 return new Response(new Uint8Array(data),{headers:{...headers,'Content-Type':doc.mime,'Content-Length':String(data.length),'Content-Disposition':`${inline?'inline':'attachment'}; filename="document"; filename*=UTF-8''${encodeURIComponent(doc.name).replace(/['()*]/g,c=>`%${c.charCodeAt(0).toString(16).toUpperCase()}`)}`,'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"sandbox; default-src 'none'; frame-ancestors 'self'"}});
 }catch{return new Response(null,{status:403,headers});}
}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string;documentId:string}>}){if(!isCalculationOriginAllowed(request))return Response.json({error:'Недопустимый источник.'},{status:403});const actor=await getCurrentUser();if(!actor)return Response.json({error:'Войдите в CRM.'},{status:401});try{const body=await request.json();if(body.confirmed!==true)throw Error('Подтвердите удаление.');const {id,documentId}=await params;await staffDocumentAccess(actor,id,true);let found=false;await mutateDataJson<ClientDocument[]>(staffDocumentIndex(id),[],rows=>rows.map(d=>{if(d.id!==documentId)return d;found=true;return {...d,deletedAt:d.deletedAt||new Date().toISOString(),deletedBy:d.deletedBy||actor.id};}));if(!found)throw Error('Документ не найден.');await recordCrmActivity(actor,{type:'staff_document_deleted',title:'Удалён документ сотрудника',visibility:'management',entityType:'staff',entityId:id,href:`/crm/managers/${encodeURIComponent(id)}#staff-documents`});return Response.json({ok:true},{headers});}catch(e){return Response.json({error:e instanceof Error&&e.message!=='forbidden'?e.message:'Нет доступа к документам сотрудника.'},{status:403,headers});}}
