const people = (start:number,group:string,label:string) => Array.from({length:6},(_,i)=>({id:`character-${start+i}`,url:`/avatars/customers/character-${start+i}.svg`,label:`${label} ${i+1}`,group}));
const cars = (group:string,label:string) => Array.from({length:6},(_,i)=>({id:`${group}-${i+1}`,url:`/avatars/customers/${group}-${i+1}.svg`,label:`${label} ${i+1}`,group}));
export const CUSTOMER_AVATARS=[...people(11,'women','Женский портрет'),...people(1,'men','Мужской портрет'),...cars('city-cars','Городской автомобиль'),...cars('offroad-cars','Внедорожник')];
export const DEFAULT_CUSTOMER_AVATAR='/key-logo.png';
// Previously selected portraits remain valid even when not in the new picker.
export function customerAvatar(_seed:string,avatarId?:string){if(avatarId&&/^character-([1-9]|1[0-9]|20)$/.test(avatarId))return `/avatars/customers/${avatarId}.svg`;return CUSTOMER_AVATARS.find(a=>a.id===avatarId)?.url||DEFAULT_CUSTOMER_AVATAR;}
export function validCustomerAvatar(id:unknown){return typeof id==='string'&&(id==='key'||/^character-([1-9]|1[0-9]|20)$/.test(id)||CUSTOMER_AVATARS.some(a=>a.id===id));}

const AVATAR_BACKGROUNDS:Record<string,string>={"character-12": "#afc8f0", "offroad-cars-6": "#dce5f2", "character-16": "#f8c85d", "character-8": "#b8d7c0", "character-9": "#e2bbd3", "offroad-cars-3": "#d9e6f0", "offroad-cars-2": "#e4e0f4", "character-4": "#e2bbd3", "character-3": "#b8d7c0", "character-1": "#f8c85d", "offroad-cars-1": "#f4dce5", "city-cars-5": "#f4e9ce", "offroad-cars-5": "#f4e9ce", "character-17": "#afc8f0", "city-cars-2": "#e4e0f4", "character-10": "#d4c5f5", "character-18": "#b8d7c0", "character-13": "#b8d7c0", "character-6": "#f8c85d", "character-15": "#d4c5f5", "key": "#ffd85c", "city-cars-1": "#f4dce5", "character-19": "#e2bbd3", "character-5": "#d4c5f5", "character-20": "#d4c5f5", "character-14": "#e2bbd3", "character-7": "#afc8f0", "character-2": "#afc8f0", "city-cars-3": "#d9e6f0", "offroad-cars-4": "#e1ecdf", "character-11": "#f8c85d", "city-cars-6": "#dce5f2", "city-cars-4": "#e1ecdf"};
export function customerAvatarBackground(url:string){if(url==='/key-logo.png'||url==='/api/account/default-avatar')return '#ffc947';const id=url?.match(/^\/avatars\/customers\/([a-z0-9-]+)\.svg$/)?.[1];return id?AVATAR_BACKGROUNDS[id]:undefined;}
