import {randomUUID} from 'node:crypto';
import {getCurrentUser,isCrmRole} from '@/lib/auth';
import {isCalculationOriginAllowed} from '@/lib/catalog/calculation-request-origin';
import {getJsonStorage,updateChunkedDataJson} from '@/lib/data';
import {canSeeLead} from '@/lib/crm-visibility';
import {documentKey,encryptClientDocument,MAX_CLIENT_DOCUMENTS,MAX_CLIENT_FILE_BYTES,type ClientDocument} from '@/lib/client-documents';
import {changeContractState,accessibleClient,createContract,getContract,getTemplate,listContracts,saveTemplate,updateContract} from '@/lib/contracts/store';
import {cleanContractNumber,cleanFields,requiredMissing,sampleFields,validateTemplate,type ContractSnapshot,type TemplateId,type ContractTemplate} from '@/lib/contracts/model';
import {importContractOffer,manualCalculation} from '@/lib/contracts/calculation';
import {renderContractPdf} from '@/lib/contracts/pdf';
export const runtime='nodejs';export const dynamic='force-dynamic';
const headers={'Cache-Control':'private, no-store','X-Robots-Tag':'noindex, nofollow'};
const json=(v:unknown,status=200)=>Response.json(v,{status,headers});
const pdf=(data:Buffer)=>new Response(new Uint8Array(data),{headers:{...headers,'Content-Type':'application/pdf','Content-Disposition':'inline; filename="TOP-AVTO-contract.pdf"'}});
function snapshot(r:any):ContractSnapshot{return {number:r.number,version:0,createdAt:new Date().toISOString(),createdBy:r.createdBy,fields:r.fields,template:r.template,calculation:r.calculation};}
export async function GET(request:Request){const user=await getCurrentUser();if(!user||!isCrmRole(user.role)||user.status==='disabled')return json({error:'Войдите в CRM.'},401);try{const q=new URL(request.url).searchParams;if(q.has('template')){const t=await getTemplate(q.get('template') as TemplateId);if(q.has('pdf'))return pdf(await renderContractPdf({version:0,createdAt:new Date().toISOString(),createdBy:user.id,fields:sampleFields(t.id),template:t,calculation:null},'ОБРАЗЕЦ','ОБРАЗЕЦ'));return json({template:t});}if(q.has('id')){const r=await getContract(user,q.get('id')!);if(q.has('pdf')){const version=q.get('version');const s=version?r.versions.find(v=>v.version===Number(version)):snapshot(r);if(!s)throw Error('Версия не найдена.');return pdf(await renderContractPdf(s,s.number||r.number));}return json({record:r});}return json({records:await listContracts(user)});}catch(e){return json({error:e instanceof Error?e.message:'Не удалось открыть документ.'},400);}}
export async function POST(request:Request){if(!isCalculationOriginAllowed(request))return json({error:'Недопустимый источник запроса.'},403);const user=await getCurrentUser();if(!user||!isCrmRole(user.role)||user.status==='disabled')return json({error:'Войдите в CRM.'},401);try{if(Number(request.headers.get('content-length'))>250000)return json({error:'Слишком большой документ.'},413);const raw=await request.text();if(raw.length>250000)return json({error:'Слишком большой документ.'},413);const b=JSON.parse(raw);
 if(b.action==='create')return json({record:await createContract(user,b.templateId,String(b.clientId||''),b.id)});
 if(b.action==='template'){if(user.role!=='owner')return json({error:'Шаблоны редактирует владелец.'},403);validateTemplate(b.template);return json({template:await saveTemplate(b.template,b.revision)});}
 if(['archive','restore','purge'].includes(b.action)){if(b.confirm!==true)throw Error('Подтвердите действие.');await changeContractState(user,b.id,b.revision,b.action);return json({ok:true});}
 const r=await getContract(user,b.id);
 if(r.archivedAt)throw Error('Договор в архиве. Сначала восстановите его.');
 if(b.action==='save'){const number=b.number===undefined?r.number:cleanContractNumber(b.number);const fields=cleanFields(b.fields);const clientId=String(b.clientId||'');await accessibleClient(user,clientId);if(r.versions.length&&r.clientId&&r.clientId!==clientId)throw Error('У договора уже есть готовая версия. Для другого клиента создайте новый договор.');let template:ContractTemplate=r.template;if(b.template){validateTemplate(b.template);if(b.template.id!==r.template.id)throw Error('Нельзя заменить тип шаблона.');template={...b.template,revision:r.template.revision};}
 const priceKeys=['market','offerUrl','deliveryCity','date','car','year','engine','engineCc','powerHp','manualTotal','manualCommission','manualDeposit','manualRate','manualRateDate','manualExpenses'];const invalidate=priceKeys.some(k=>(fields[k]||'')!==(r.fields[k]||''));return json({record:await updateContract(user,r.id,b.revision,current=>({...current,number,versions:current.versions.map(v=>v.number?v:{...v,number:current.number}),fields,clientId,template,calculation:invalidate?null:current.calculation}))});}
 if(b.action==='import'){const result=await importContractOffer(r.fields.offerUrl||'',r.fields,r.template.id);return json({record:await updateContract(user,r.id,b.revision,current=>({...current,fields:result.fields,calculation:result.calculation})),warning:result.warning});}
 if(b.action==='manual'){const calculation=manualCalculation(r.fields);return json({record:await updateContract(user,r.id,b.revision,current=>({...current,calculation,fields:{...current.fields,budget:String(calculation.total)}}))});}
 if(b.action==='finalize'){const missing=requiredMissing(r);if(missing.length)throw Error(`Заполните: ${missing.join(', ')}.`);if(r.versions.length>=50)throw Error('Достигнут предел 50 версий договора.');return json({record:await updateContract(user,r.id,b.revision,current=>({...current,versions:[...current.versions,{...snapshot(current),version:current.versions.length+1,createdBy:user.id}]}))});}
 if(b.action==='attach'){if(!r.clientId)throw Error('Сначала выберите клиента.');const client=await accessibleClient(user,r.clientId);const s=r.versions.find(v=>v.version===Number(b.version));if(!s)throw Error('Сначала сохраните готовую версию.');const attachmentId=r.id.slice(0,24)+String(s.version).padStart(12,'0');const existing=(client.documents||[]).find((d:ClientDocument)=>d.id===attachmentId);if(existing?.deletedAt)throw Error('Эта версия в корзине. Восстановите её в «Архиве».');if(existing)return json({ok:true});if((client.documents||[]).length>=MAX_CLIENT_DOCUMENTS)throw Error('У клиента уже 50 документов, включая корзину.');const data=await renderContractPdf(s,s.number||r.number);if(data.length>MAX_CLIENT_FILE_BYTES)throw Error('PDF превышает 5 МБ.');const storage=getJsonStorage();const id=r.id.slice(0,24)+String(s.version).padStart(12,'0');const name=`Договор ${(s.number||r.number).replaceAll('/','-')} от ${s.fields.date}, версия ${s.version}.pdf`;const document:ClientDocument={id,name,mime:'application/pdf',size:data.length,createdAt:s.createdAt,createdBy:user.id,hasThumbnail:false};const key=documentKey(r.clientId,id);if(!storage.putBinary)throw Error('Хранилище недоступно.');await storage.putBinary(key,encryptClientDocument(Buffer.from(JSON.stringify({data:data.toString('base64')})),key),'application/octet-stream');const updated=await updateChunkedDataJson<any>('clients/clients.json',r.clientId,current=>{if(!canSeeLead(user,current))throw Error('Нет доступа к клиенту.');const docs:ClientDocument[]=current.documents||[];const existing=docs.find(d=>d.id===id);if(existing?.deletedAt)throw Error('Эта версия в корзине. Восстановите её в «Архиве».');if(existing)return current;if(docs.length>=MAX_CLIENT_DOCUMENTS)throw Error('У клиента уже 50 документов, включая корзину.');return {...current,documents:[...docs,document],documentsUpdatedAt:new Date().toISOString(),documentsUpdatedByManagerId:user.id};});if(!updated)throw Error('Клиент не найден.');return json({ok:true});}
 return json({error:'Неизвестное действие.'},400);
 }catch(e){return json({error:e instanceof Error?e.message:'Не удалось сохранить документ.'},400);}}
