export const LANGUAGES={ru:'Русский',en:'English',zh:'中文',ja:'日本語',ko:'한국어',ar:'العربية',de:'Deutsch'} as const;
export type PartnerLanguage=keyof typeof LANGUAGES;
export function partnerLanguage(v:unknown):PartnerLanguage{return typeof v==='string'&&v in LANGUAGES?v as PartnerLanguage:'ru';}
type Copy={eyebrow:string;headline:string;accent:string;intro:string;apply:string;explore:string;dealer:string;supplier:string;dealerText:string;supplierText:string;stepsTitle:string;steps:string[];stepText:string[];features:string[];featureText:string[];pricing:string;trial:string;basic:string;full:string;month:string;half:string;year:string;commission:string;sale:string;remuneration:string;billing:string;formTitle:string;formText:string;fields:string[];consent:string;privacy:string;success:string;error:string;send:string;knowledge:string;search:string;all:string;empty:string;read:string;preview:string;back:string;articles:{id:string;title:string;category:string;paragraphs:string[]}[]};
export const CONTENT:Record<PartnerLanguage,Copy>={
ru:{eyebrow:'АвтоЦена · партнёрам',headline:'Ваш бизнес.',accent:'Больше возможностей.',intro:'Дилерам в России и поставщикам автомобилей из других стран. Общий каталог, своя страница и понятное управление предложениями.',apply:'Обсудить подключение',explore:'Как это работает',dealer:'Дилер в России',supplier:'Поставщик автомобилей',dealerText:'Подбирайте автомобили из общего каталога, оформляйте страницу компании и добавляйте свои предложения.',supplierText:'Предложите автомобили из Китая, Японии, Кореи, Европы, ОАЭ или Грузии. Формат данных и условия сотрудничества согласуем после заявки.',stepsTitle:'От знакомства — к работе',steps:['Расскажите о компании','Согласуем условия','Подготовьте кабинет','Работайте с клиентами'],stepText:['Страна, направления и удобный контакт.','Проверим компанию и обсудим формат сотрудничества.','Добавьте адреса, оформление и свои автомобили.','Заявки с сайта проходят через АвтоЦену и её CRM.'],features:['Каталог без границ','Страница вашего бренда','Свои автомобили'],featureText:['Шесть направлений поиска и расчёт стоимости автомобиля.','Название, обложка, адреса на карте и фотографии выдач.','Фото, характеристики и стоимость в одном редакторе.'],pricing:'Понятные условия для дилеров',trial:'дней полного доступа после подключения',basic:'После пробного периода общий каталог остаётся доступен без подписки. Собственные автомобили и расширенное оформление — с полным доступом.',full:'Все возможности',month:'1 месяц',half:'6 месяцев',year:'1 год',commission:'Комиссия с завершённых продаж по заявкам АвтоЦены',sale:'от стоимости проданного автомобиля',remuneration:'от вознаграждения дилера',billing:'Подписка и комиссия учитываются отдельно. Условия поставщиков согласуются индивидуально. Автоматического списания оплаты на сайте нет.',formTitle:'Давайте познакомимся',formText:'Расскажите, откуда вы и какие автомобили предлагаете. Команда АвтоЦены рассмотрит заявку и свяжется по указанному контакту.',fields:['Компания','Страна','Город','Контактное лицо','Email или телефон','Telegram / другой контакт','Направления, автомобили и формат сотрудничества'],consent:'Согласен на обработку данных для рассмотрения заявки.',privacy:'Политика конфиденциальности',success:'Заявка принята. Мы свяжемся по указанному контакту.',error:'Не удалось отправить заявку. Проверьте поля и повторите.',send:'Отправить заявку',knowledge:'База знаний',search:'Поиск по инструкциям',all:'Все инструкции',empty:'Ничего не найдено. Попробуйте другое слово.',read:'Открыть инструкцию',preview:'Предпросмотр владельца · страница скрыта от посетителей',back:'На главную',articles:[
{id:'catalog',title:'Как выбрать автомобиль',category:'Покупателям',paragraphs:['Откройте каталог и выберите страну, марку, модель и бюджет. В карточке проверьте год, двигатель, мощность, пробег и фотографии.','Расчёт предварительный. Перед покупкой менеджер подтверждает наличие, характеристики и итоговую стоимость. Кнопка заявки находится в карточке автомобиля.']},
{id:'calculation',title:'Расчёт, город и доставка',category:'Покупателям',paragraphs:['В карточке автомобиля проверьте параметры расчёта и выберите нужный город доставки. Дождитесь окончания пересчёта перед отправкой ссылки.','У собственных предложений дилера базовый город задаётся компанией. Цена ТопАвто считается до Новосибирска; доставка дальше согласуется отдельно. Выбор города посетителем не меняет эту базовую цену.']},
{id:'sharing',title:'Как отправить расчёт клиенту',category:'Покупателям',paragraphs:['Нажмите «Поделиться ссылкой» после завершения расчёта. На компьютере копируется сообщение с названием, рассчитанной ценой и ссылкой — вставьте его в переписку.','На телефоне выберите приложение в меню отправки. Проверьте текст перед отправкой. Фотография в превью зависит от приложения получателя. Сохранённый клиентский расчёт может иметь собственную ссылку.']},
{id:'profile',title:'Настройка страницы дилера',category:'Дилерам',paragraphs:['После подтверждения компании войдите в «Дилер». Начните с обзора: заполните название, описание, направления каталога и адрес офиса.','В полном доступе добавьте обложку, логотипы и фотографии выдач. Предпросмотр позволяет проверить страницу до публикации. Включите показ и сохраните изменения. Телефоны компании публично не показываются; обращения проходят через АвтоЦену.']},
{id:'vehicles',title:'Добавление своих автомобилей',category:'Дилерам',paragraphs:['Откройте «Автомобили» и добавьте карточку. Можно заполнить поля вручную или импортировать доступные данные по ссылке на объявление. Проверьте найденные характеристики.','Добавьте фотографии с устройства или по ссылке, выберите обложку и порядок. Закупочную цену указывайте в USD. Таможенные платежи, мощность и применимость льгот нужно подтвердить.','В «Расчёт своих авто» задаются базовый город и затраты. Сначала сохраните черновик, проверьте расчёт и недостающие поля. Для показа выберите «Опубликован», включите предложения компании и сохраните.']},
{id:'access',title:'Пробный период и подписка',category:'Дилерам',paragraphs:['При подтверждении начинается один пробный период с полным доступом. Продолжительность и цены указаны на странице партнёров и в разделе «Мой доступ».','После окончания без оплаты остаётся базовый каталог. Собственные автомобили и галерея сохраняются, но не публикуются и не редактируются до продления. Полученную оплату подтверждает владелец АвтоЦены. Комиссия с продаж по нашим заявкам учитывается отдельно.']},
{id:'supply',title:'Как предложить автомобили из-за рубежа',category:'Поставщикам',paragraphs:['Откройте страницу партнёров и выберите «Поставщик автомобилей». Укажите страну, компанию, контакт и направления работы. Можно описать доступный каталог и имеющийся формат выгрузки.','После рассмотрения согласуем состав данных, фотографии, обновление наличия, цены и условия сотрудничества. Не отправляйте пароли и API-ключи в публичную форму.']}
]},
en:{eyebrow:'AvtoCena · partners',headline:'Your business.',accent:'More possibilities.',intro:'For dealers in Russia and vehicle suppliers abroad. A shared catalog, your company page and a clear workspace for your own vehicles.',apply:'Discuss joining',explore:'How it works',dealer:'Dealer in Russia',supplier:'Vehicle supplier',dealerText:'Use the shared catalog, build your company page and add your own vehicles.',supplierText:'Offer vehicles from China, Japan, Korea, Europe, the UAE or Georgia. We will agree data formats and commercial terms after reviewing your application.',stepsTitle:'From introduction to cooperation',steps:['Introduce your company','Agree the terms','Set up your workspace','Work with customers'],stepText:['Your country, vehicle markets and contact details.','We review your company and discuss cooperation.','Add addresses, branding and your own vehicles.','Website inquiries go through AvtoCena and its CRM.'],features:['A cross-border catalog','Your brand page','Your own vehicles'],featureText:['Six sourcing markets and vehicle cost calculations.','Company information, cover, office map and delivery photos.','Photos, specifications and prices in one editor.'],pricing:'Clear terms for dealers',trial:'days of full access after joining',basic:'After the trial, the shared catalog remains available without a subscription. Own vehicles and advanced branding require full access.',full:'Full access',month:'1 month',half:'6 months',year:'1 year',commission:'Commission on completed sales from AvtoCena inquiries',sale:'of the vehicle sale price',remuneration:'of the dealer remuneration',billing:'Subscription and commission are separate. Supplier terms are agreed individually. The website does not charge payments automatically.',formTitle:'Let’s meet',formText:'Tell us where you work and which vehicles you supply. The AvtoCena team will review your application and contact you.',fields:['Company','Country','City','Contact name','Email or phone','Telegram / other contact','Markets, vehicles and cooperation details'],consent:'I agree to data processing for reviewing this application.',privacy:'Privacy policy',success:'Application received. We will contact you using the details provided.',error:'Unable to send. Check the fields and try again.',send:'Send application',knowledge:'Knowledge base',search:'Search instructions',all:'All instructions',empty:'No results. Try another word.',read:'Read guide',preview:'Owner preview · hidden from visitors',back:'Home',articles:[
{id:'catalog',title:'Choosing a vehicle',category:'Buyers',paragraphs:['Open the catalog and choose country, make, model and budget. Check the year, engine, power, mileage and photos in the vehicle page.','Calculations are preliminary. Your manager confirms availability, specifications and final cost before purchase. Use the inquiry button on the vehicle page.']},
{id:'calculation',title:'Price, city and delivery',category:'Buyers',paragraphs:['Check the calculation inputs and destination city. Wait until recalculation is complete before sharing.','For dealer-owned offers, the company sets the base city. TopAvto prices include delivery to Novosibirsk; onward delivery is agreed separately. The visitor’s selected city does not replace this base price.']},
{id:'sharing',title:'Sharing a calculation',category:'Buyers',paragraphs:['Use the share button after calculation. On desktop it copies the vehicle name, calculated price and link; paste the message into your conversation.','On mobile select an app from the share menu and review the text. Preview photos depend on the receiving app. A saved customer calculation may have its own link.']},
{id:'profile',title:'Setting up a dealer page',category:'Dealers',paragraphs:['After approval, open the Dealer workspace. Start with company name, description, catalog markets and office address.','Full access includes cover images, logos and delivery photos. Preview the page before enabling publication and saving. Company phone numbers are not public; inquiries go through AvtoCena.']},
{id:'vehicles',title:'Adding your own vehicles',category:'Dealers',paragraphs:['Open Vehicles and add a listing. Fill it manually or import available details from a listing URL. Verify the imported specifications.','Upload photos, choose a cover and reorder them. Enter the purchase price in USD. Confirm customs payments, power and eligibility for reduced charges.','Set the base city and costs under Own vehicle calculation. Save a draft first and check missing fields. Select Published, enable company offers and save to make it public.']},
{id:'access',title:'Trial and subscription',category:'Dealers',paragraphs:['Approval starts a single full-access trial. Current duration and prices are shown on the partners page and in My access.','When access expires, the basic catalog remains available. Own listings and gallery are kept but hidden and read-only until renewal. AvtoCena’s owner confirms received payments. Sales commission is recorded separately.']},
{id:'supply',title:'Supplying vehicles from abroad',category:'Suppliers',paragraphs:['On the partners page choose Vehicle supplier. Provide country, company, contact details and markets. Describe your inventory and available export format.','After review we agree data fields, photos, availability updates, prices and cooperation terms. Do not send passwords or API keys in the public form.']}
]},
zh:{eyebrow:'AvtoCena · 合作伙伴',headline:'您的汽车业务。',accent:'更多合作可能。',intro:'面向俄罗斯经销商和海外汽车供应商。共享车辆目录、公司主页以及便捷的车辆管理。',apply:'申请合作',explore:'合作流程',dealer:'俄罗斯经销商',supplier:'汽车供应商',dealerText:'使用平台目录，创建公司主页并发布自有车辆。',supplierText:'欢迎来自中国、日本、韩国、欧洲、阿联酋和格鲁吉亚的供应商。申请审核后协商数据格式与合作条款。',stepsTitle:'从认识到合作',steps:['介绍公司','协商条款','设置工作台','服务客户'],stepText:['填写国家、经营方向与联系方式。','审核公司并讨论合作方式。','添加地址、品牌资料和车辆。','网站咨询通过 AvtoCena 及其 CRM 处理。'],features:['跨境车辆目录','品牌主页','自有车辆管理'],featureText:['六个采购市场与车辆费用计算。','公司介绍、封面、办公地址和交车照片。','在同一编辑器中管理照片、参数和价格。'],pricing:'经销商合作费用',trial:'天完整功能试用（接入后）',basic:'试用结束后仍可免费使用共享目录。发布自有车辆和高级主页功能需要订阅。',full:'完整功能',month:'1个月',half:'6个月',year:'1年',commission:'AvtoCena 客源已完成交易的佣金',sale:'按车辆成交价计算',remuneration:'按经销商服务报酬计算',billing:'订阅与佣金分别计算。供应商条件单独协商。网站不自动扣款。',formTitle:'开始了解彼此',formText:'请介绍所在地和可供应车辆。AvtoCena 团队审核后将通过您提供的联系方式联系。',fields:['公司','国家','城市','联系人','邮箱或电话','Telegram / 其他联系方式','市场、车辆及合作说明'],consent:'同意为审核本申请处理所提供的数据。',privacy:'隐私政策',success:'申请已收到，我们将与您联系。',error:'发送失败，请检查填写内容后重试。',send:'提交申请',knowledge:'使用指南',search:'搜索指南',all:'全部指南',empty:'未找到结果，请更换关键词。',read:'阅读指南',preview:'所有者预览 · 对访客隐藏',back:'首页',articles:[
{id:'catalog',title:'如何选择车辆',category:'买家',paragraphs:['打开目录，选择国家、品牌、车型及预算。在车辆页面核对年份、发动机、功率、里程和照片。','费用为初步估算。购买前由经理确认库存、参数和最终费用。可通过车辆页面的咨询按钮提交需求。']},
{id:'calculation',title:'价格、城市与运输',category:'买家',paragraphs:['核对计算参数和目的城市，等待重新计算完成后再分享。','经销商自有车辆使用公司设定的基础城市。TopAvto 报价包含运至新西伯利亚的费用，后续运输另议。访客选择的城市不会替换基础价格。']},
{id:'sharing',title:'分享计算结果',category:'买家',paragraphs:['计算完成后点击分享。电脑端会复制车辆名称、计算价格及链接，可粘贴至聊天。','手机端选择应用并检查文本。预览图片由接收应用决定。已保存的客户方案可能有独立链接。']},
{id:'profile',title:'设置经销商主页',category:'经销商',paragraphs:['审核通过后进入经销商工作台，填写公司名称、介绍、经营市场及办公地址。','完整功能支持封面、标志和交车照片。发布前可预览，启用后保存。公司电话不公开，咨询通过 AvtoCena 处理。']},
{id:'vehicles',title:'添加自有车辆',category:'经销商',paragraphs:['在车辆栏目添加信息，可手动填写或通过链接导入可用资料。请核实导入参数。','上传照片、选择封面并排序。采购价以美元填写。确认关税、功率及优惠条件。','在自有车辆计算中设置基础城市与费用。先保存草稿，补全缺失字段；选择已发布，启用公司报价并保存。']},
{id:'access',title:'试用与订阅',category:'经销商',paragraphs:['确认后开始一次完整功能试用。期限与价格见合作页面及我的权限。','到期后仍可使用基础目录。自有车辆与图库会保留，但暂停展示和编辑，续费后恢复。平台所有者确认收款，销售佣金单独记录。']},
{id:'supply',title:'海外供车合作',category:'供应商',paragraphs:['在合作页面选择汽车供应商，填写国家、公司、联系人及经营市场，并说明库存和现有数据格式。','审核后协商字段、照片、库存更新、价格与合作条件。请勿在公开表单提交密码或 API 密钥。']}
]},
ja:{eyebrow:'AvtoCena · パートナー',headline:'あなたのビジネスに。',accent:'新たな可能性を。',intro:'ロシアの販売店と海外の車両サプライヤー向け。共通カタログ、会社ページ、自社車両の管理をひとつに。',apply:'提携を相談する',explore:'ご利用の流れ',dealer:'ロシアの販売店',supplier:'車両サプライヤー',dealerText:'共通カタログを利用し、会社ページと自社車両を管理できます。',supplierText:'日本、中国、韓国、欧州、UAE、ジョージアからの車両供給。データ形式と取引条件は申請確認後に相談します。',stepsTitle:'ご相談から業務開始まで',steps:['会社の紹介','条件の確認','管理画面の設定','お客様への対応'],stepText:['国、取扱車両、連絡先を入力。','会社情報を確認し、提携方法を相談。','所在地、ブランド情報、車両を登録。','サイトからの問い合わせは AvtoCena と CRM を通じて処理。'],features:['国境を越えるカタログ','自社のブランドページ','自社車両の掲載'],featureText:['6市場の車両検索と費用計算。','会社紹介、カバー、地図、納車写真。','写真、仕様、価格を一つの編集画面で管理。'],pricing:'販売店向けの利用条件',trial:'日間のフル機能試用（接続後）',basic:'試用終了後も共通カタログを無料で利用できます。自社車両と詳細なページ設定には契約が必要です。',full:'フルアクセス',month:'1か月',half:'6か月',year:'1年',commission:'AvtoCena の問い合わせから成立した販売の手数料',sale:'車両販売価格に対して',remuneration:'販売店報酬に対して',billing:'利用料と販売手数料は別です。サプライヤー条件は個別に相談。サイトでの自動引き落としはありません。',formTitle:'まずはご紹介ください',formText:'所在地と取扱車両をご記入ください。AvtoCena が内容を確認し、ご連絡します。',fields:['会社名','国','都市','担当者名','メールまたは電話','Telegram / その他の連絡先','市場・車両・提携内容'],consent:'本申請の確認に必要なデータ処理に同意します。',privacy:'プライバシーポリシー',success:'申請を受け付けました。記載の連絡先にご連絡します。',error:'送信できません。入力内容を確認して再試行してください。',send:'申請を送信',knowledge:'ご利用ガイド',search:'ガイドを検索',all:'すべてのガイド',empty:'該当するガイドがありません。',read:'ガイドを読む',preview:'オーナープレビュー · 非公開',back:'ホーム',articles:[
{id:'catalog',title:'車両の選び方',category:'購入者',paragraphs:['カタログで国、メーカー、モデル、予算を選択。車両ページで年式、エンジン、出力、走行距離、写真を確認してください。','計算は概算です。購入前に担当者が在庫、仕様、最終費用を確認します。車両ページの問い合わせボタンをご利用ください。']},
{id:'calculation',title:'価格・都市・配送',category:'購入者',paragraphs:['計算条件と配送先を確認し、再計算の終了後に共有してください。','販売店の自社車両は会社が基準都市を設定します。TopAvto はノヴォシビルスクまでの価格で、その先の配送は別途相談。閲覧者の都市選択で基準価格は変わりません。']},
{id:'sharing',title:'見積もりの共有',category:'購入者',paragraphs:['計算後に共有ボタンを押します。PC では車名、計算価格、リンクがコピーされ、チャットに貼り付けられます。','スマートフォンでは送信先アプリを選び、文章を確認します。画像プレビューは受信アプリによります。保存した顧客向け計算には専用リンクが付く場合があります。']},
{id:'profile',title:'販売店ページの設定',category:'販売店',paragraphs:['承認後に販売店画面へ入り、会社名、紹介、対象市場、住所を入力。','フルアクセスではカバー、ロゴ、納車写真を追加できます。公開前にプレビューし、表示を有効にして保存。電話番号は公開されず、問い合わせは AvtoCena を通します。']},
{id:'vehicles',title:'自社車両の追加',category:'販売店',paragraphs:['車両欄で追加し、手入力または掲載リンクから取得できる情報を取り込みます。取得した仕様を確認してください。','写真をアップロードし、カバーと順序を設定。仕入価格は USD で入力し、関税、出力、優遇条件を確認。','自社車両の計算で基準都市と費用を設定。まず下書きを保存し、不足項目を埋め、公開状態と会社の掲載を有効にして保存します。']},
{id:'access',title:'試用期間と契約',category:'販売店',paragraphs:['承認時に一度限りのフル機能試用が始まります。期間と料金はパートナーページとアクセス画面に表示。','終了後も基本カタログは利用可能。自社車両と写真は保存されますが、更新まで非公開・編集不可になります。入金は AvtoCena のオーナーが確認し、販売手数料は別途記録します。']},
{id:'supply',title:'海外からの車両供給',category:'サプライヤー',paragraphs:['パートナーページで車両サプライヤーを選び、国、会社、連絡先、市場を入力。在庫と提供可能なデータ形式を説明してください。','確認後にデータ項目、写真、在庫更新、価格、条件を合意します。公開フォームにパスワードや API キーを入力しないでください。']}
]},
ko:{eyebrow:'AvtoCena · 파트너',headline:'당신의 비즈니스.',accent:'더 많은 가능성.',intro:'러시아 딜러와 해외 차량 공급업체를 위한 공용 카탈로그, 회사 페이지, 자체 차량 관리 공간.',apply:'제휴 상담',explore:'이용 방법',dealer:'러시아 딜러',supplier:'차량 공급업체',dealerText:'공용 카탈로그를 이용하고 회사 페이지와 자체 차량을 관리하세요.',supplierText:'한국, 중국, 일본, 유럽, UAE, 조지아의 차량을 제안하세요. 신청 검토 후 데이터 형식과 협력 조건을 협의합니다.',stepsTitle:'소개부터 협업까지',steps:['회사 소개','조건 협의','관리 공간 설정','고객 응대'],stepText:['국가, 취급 차량, 연락처를 입력합니다.','회사 확인 후 협력 방식을 논의합니다.','주소, 브랜드 정보, 자체 차량을 추가합니다.','사이트 문의는 AvtoCena와 CRM을 통해 처리됩니다.'],features:['국경을 넘는 카탈로그','브랜드 페이지','자체 차량'],featureText:['6개 시장의 차량 검색과 비용 계산.','회사 소개, 표지, 사무실 지도, 출고 사진.','사진, 사양, 가격을 한 편집기에서 관리.'],pricing:'딜러를 위한 이용 조건',trial:'일 전체 기능 체험 (연결 후)',basic:'체험 종료 후에도 공용 카탈로그는 무료입니다. 자체 차량과 고급 페이지 설정은 구독이 필요합니다.',full:'전체 기능',month:'1개월',half:'6개월',year:'1년',commission:'AvtoCena 문의를 통해 완료된 판매 수수료',sale:'차량 판매 가격 기준',remuneration:'딜러 보수 기준',billing:'구독료와 판매 수수료는 별도입니다. 공급업체 조건은 개별 협의하며 사이트에서 자동 결제하지 않습니다.',formTitle:'함께 이야기해요',formText:'소재지와 공급 차량을 알려주세요. AvtoCena 팀이 검토 후 연락드립니다.',fields:['회사','국가','도시','담당자','이메일 또는 전화','Telegram / 기타 연락처','시장, 차량 및 협력 내용'],consent:'신청 검토를 위한 개인정보 처리에 동의합니다.',privacy:'개인정보 처리방침',success:'신청이 접수되었습니다. 기재한 연락처로 연락드리겠습니다.',error:'전송하지 못했습니다. 내용을 확인하고 다시 시도하세요.',send:'신청 보내기',knowledge:'이용 안내',search:'안내 검색',all:'전체 안내',empty:'검색 결과가 없습니다.',read:'안내 읽기',preview:'소유자 미리보기 · 비공개',back:'홈',articles:[
{id:'catalog',title:'차량 선택하기',category:'구매자',paragraphs:['카탈로그에서 국가, 브랜드, 모델, 예산을 선택하세요. 차량 페이지에서 연식, 엔진, 출력, 주행거리, 사진을 확인하세요.','계산은 예상 금액입니다. 구매 전 담당자가 재고, 사양, 최종 금액을 확인합니다. 차량 페이지에서 문의를 남길 수 있습니다.']},
{id:'calculation',title:'가격, 도시, 배송',category:'구매자',paragraphs:['계산 조건과 배송 도시를 확인하고 재계산이 끝난 후 공유하세요.','딜러 자체 차량은 회사가 기준 도시를 설정합니다. TopAvto 가격은 노보시비르스크까지이며 이후 운송은 별도 협의합니다. 방문자의 도시 선택은 기준 가격을 바꾸지 않습니다.']},
{id:'sharing',title:'계산 결과 공유하기',category:'구매자',paragraphs:['계산 후 공유 버튼을 누르세요. PC에서는 차량명, 계산 가격, 링크가 복사되며 대화창에 붙여넣을 수 있습니다.','휴대폰에서는 앱을 선택하고 문구를 확인하세요. 사진 미리보기는 수신 앱에 따라 달라집니다. 저장된 고객 견적에는 별도 링크가 있을 수 있습니다.']},
{id:'profile',title:'딜러 페이지 설정',category:'딜러',paragraphs:['승인 후 딜러 공간에서 회사명, 소개, 취급 시장, 사무실 주소부터 입력하세요.','전체 기능에서는 표지, 로고, 출고 사진을 추가할 수 있습니다. 공개 전 미리보기로 확인하고 표시를 켠 후 저장하세요. 전화번호는 공개되지 않으며 문의는 AvtoCena를 통합니다.']},
{id:'vehicles',title:'자체 차량 추가',category:'딜러',paragraphs:['차량 메뉴에서 새 항목을 만들고 직접 입력하거나 매물 링크의 제공 가능한 데이터를 불러오세요. 사양을 검증하세요.','사진을 올리고 표지와 순서를 정하세요. 매입가는 USD로 입력하며 관세, 출력, 감면 조건을 확인해야 합니다.','자체 차량 계산에서 기준 도시와 비용을 설정하세요. 초안을 저장하고 누락 항목을 채운 뒤 공개 상태와 회사 매물 표시를 켜고 저장하세요.']},
{id:'access',title:'체험과 구독',category:'딜러',paragraphs:['승인 시 한 번의 전체 기능 체험이 시작됩니다. 기간과 요금은 파트너 페이지와 내 이용 권한에 표시됩니다.','종료 후에도 기본 카탈로그는 유지됩니다. 자체 매물과 사진은 보존되지만 갱신 전까지 비공개이며 수정할 수 없습니다. 입금은 플랫폼 소유자가 확인하고 판매 수수료는 별도 기록합니다.']},
{id:'supply',title:'해외 차량 공급',category:'공급업체',paragraphs:['파트너 페이지에서 차량 공급업체를 선택하고 국가, 회사, 연락처, 시장을 입력하세요. 재고와 제공 가능한 데이터 형식을 설명하세요.','검토 후 데이터 항목, 사진, 재고 갱신, 가격, 협력 조건을 협의합니다. 공개 양식에 비밀번호나 API 키를 입력하지 마세요.']}
]},
ar:{eyebrow:'AvtoCena · الشركاء',headline:'أعمالكم.',accent:'إمكانات أوسع.',intro:'للتجار في روسيا وموردي السيارات من الخارج. كتالوج مشترك وصفحة للشركة وإدارة واضحة للسيارات الخاصة بكم.',apply:'مناقشة الانضمام',explore:'كيف نعمل',dealer:'تاجر في روسيا',supplier:'مورد سيارات',dealerText:'استخدموا الكتالوج المشترك وأنشئوا صفحة شركتكم وأضيفوا سياراتكم.',supplierText:'نوفر التعاون مع موردي السيارات من الصين واليابان وكوريا وأوروبا والإمارات وجورجيا. نتفق على البيانات والشروط بعد مراجعة الطلب.',stepsTitle:'من التعارف إلى التعاون',steps:['عرّفوا بشركتكم','نتفق على الشروط','جهزوا مساحة العمل','تعاملوا مع العملاء'],stepText:['الدولة والأسواق وبيانات التواصل.','نراجع الشركة ونناقش طريقة التعاون.','أضيفوا العناوين والهوية والسيارات.','تمر استفسارات الموقع عبر AvtoCena ونظام إدارة العملاء.'],features:['كتالوج عبر الحدود','صفحة لعلامتكم','سياراتكم الخاصة'],featureText:['ستة أسواق وحساب تكلفة السيارة.','معلومات الشركة والغلاف والخريطة وصور التسليم.','الصور والمواصفات والأسعار في محرر واحد.'],pricing:'شروط واضحة للتجار',trial:'يوماً من الوصول الكامل بعد الانضمام',basic:'يبقى الكتالوج المشترك متاحاً دون اشتراك بعد التجربة. تتطلب السيارات الخاصة والتخصيص المتقدم اشتراكاً كاملاً.',full:'وصول كامل',month:'شهر واحد',half:'6 أشهر',year:'سنة واحدة',commission:'عمولة المبيعات المكتملة من استفسارات AvtoCena',sale:'من سعر بيع السيارة',remuneration:'من أتعاب التاجر',billing:'الاشتراك والعمولة منفصلان. نتفق مع الموردين على شروط فردية. لا يخصم الموقع المدفوعات تلقائياً.',formTitle:'لنتعارف',formText:'أخبرونا بموقعكم والسيارات التي توفرونها. سيراجع فريق AvtoCena الطلب ويتواصل معكم.',fields:['الشركة','الدولة','المدينة','اسم المسؤول','البريد الإلكتروني أو الهاتف','Telegram / وسيلة تواصل أخرى','الأسواق والسيارات وتفاصيل التعاون'],consent:'أوافق على معالجة البيانات لمراجعة هذا الطلب.',privacy:'سياسة الخصوصية',success:'تم استلام الطلب. سنتواصل عبر البيانات المقدمة.',error:'تعذر الإرسال. راجعوا الحقول وحاولوا مجدداً.',send:'إرسال الطلب',knowledge:'قاعدة المعرفة',search:'البحث في الأدلة',all:'جميع الأدلة',empty:'لا توجد نتائج. جربوا كلمة أخرى.',read:'قراءة الدليل',preview:'معاينة المالك · مخفية عن الزوار',back:'الرئيسية',articles:[
{id:'catalog',title:'اختيار سيارة',category:'المشترون',paragraphs:['افتحوا الكتالوج وحددوا الدولة والعلامة والطراز والميزانية. تحققوا من السنة والمحرك والقوة والمسافة والصور في صفحة السيارة.','الحساب تقديري. يؤكد المدير التوفر والمواصفات والتكلفة النهائية قبل الشراء. استخدموا زر الاستفسار في صفحة السيارة.']},
{id:'calculation',title:'السعر والمدينة والتوصيل',category:'المشترون',paragraphs:['راجعوا مدخلات الحساب ومدينة التوصيل وانتظروا انتهاء إعادة الحساب قبل المشاركة.','تحدد الشركة المدينة الأساسية لعروضها الخاصة. تشمل أسعار TopAvto النقل إلى نوفوسيبيرسك، ويُتفق على التوصيل التالي بشكل منفصل. اختيار الزائر لمدينة لا يغير السعر الأساسي.']},
{id:'sharing',title:'مشاركة الحساب',category:'المشترون',paragraphs:['اضغطوا زر المشاركة بعد الحساب. على الكمبيوتر يُنسخ اسم السيارة والسعر المحسوب والرابط للصقها في المحادثة.','على الهاتف اختاروا التطبيق وراجعوا النص. تعتمد صورة المعاينة على التطبيق المستقبِل. قد يكون للحساب المحفوظ للعميل رابط خاص.']},
{id:'profile',title:'إعداد صفحة التاجر',category:'التجار',paragraphs:['بعد الموافقة افتحوا مساحة التاجر وأدخلوا اسم الشركة ووصفها والأسواق وعنوان المكتب.','يتيح الوصول الكامل الغلاف والشعارات وصور التسليم. عاينوا الصفحة ثم فعّلوا النشر واحفظوا. أرقام الهاتف غير عامة وتمر الاستفسارات عبر AvtoCena.']},
{id:'vehicles',title:'إضافة سياراتكم',category:'التجار',paragraphs:['أضيفوا عرضاً من قسم السيارات يدوياً أو استوردوا البيانات المتاحة من رابط الإعلان. تحققوا من المواصفات المستوردة.','ارفعوا الصور واختاروا الغلاف والترتيب. أدخلوا سعر الشراء بالدولار وأكدوا الجمارك والقوة وشروط الرسوم المخفضة.','حددوا المدينة الأساسية والتكاليف في حساب السيارات الخاصة. احفظوا مسودة وأكملوا الحقول، ثم اختاروا منشور وفعّلوا عروض الشركة واحفظوا.']},
{id:'access',title:'التجربة والاشتراك',category:'التجار',paragraphs:['تبدأ تجربة واحدة بكامل الوظائف عند التأكيد. تظهر المدة والأسعار في صفحة الشركاء وقسم الوصول الخاص بكم.','بعد الانتهاء يبقى الكتالوج الأساسي. تُحفظ السيارات والصور لكنها تُخفى ويُمنع تعديلها حتى التجديد. يؤكد مالك المنصة المدفوعات المستلمة، وتُسجل عمولة البيع منفصلة.']},
{id:'supply',title:'توريد السيارات من الخارج',category:'الموردون',paragraphs:['اختاروا مورد سيارات في صفحة الشركاء وأدخلوا الدولة والشركة والتواصل والأسواق، واشرحوا المخزون وصيغة البيانات المتاحة.','بعد المراجعة نتفق على الحقول والصور وتحديث المخزون والأسعار والشروط. لا ترسلوا كلمات مرور أو مفاتيح API في النموذج العام.']}
]},
de:{eyebrow:'AvtoCena · Partner',headline:'Ihr Unternehmen.',accent:'Mehr Möglichkeiten.',intro:'Für Händler in Russland und Fahrzeuglieferanten im Ausland. Gemeinsamer Katalog, eigene Unternehmensseite und übersichtliche Fahrzeugverwaltung.',apply:'Zusammenarbeit besprechen',explore:'So funktioniert es',dealer:'Händler in Russland',supplier:'Fahrzeuglieferant',dealerText:'Nutzen Sie den gemeinsamen Katalog, gestalten Sie Ihre Unternehmensseite und ergänzen Sie eigene Fahrzeuge.',supplierText:'Fahrzeuge aus China, Japan, Korea, Europa, den VAE oder Georgien. Datenformate und Konditionen stimmen wir nach Prüfung der Anfrage ab.',stepsTitle:'Vom Kennenlernen zur Zusammenarbeit',steps:['Unternehmen vorstellen','Bedingungen abstimmen','Arbeitsbereich einrichten','Kunden betreuen'],stepText:['Land, Fahrzeugmärkte und Kontaktdaten.','Wir prüfen das Unternehmen und besprechen die Zusammenarbeit.','Adressen, Markenauftritt und eigene Fahrzeuge hinzufügen.','Website-Anfragen laufen über AvtoCena und das CRM.'],features:['Internationaler Katalog','Ihre Markenseite','Eigene Fahrzeuge'],featureText:['Sechs Beschaffungsmärkte und Fahrzeugkostenberechnung.','Unternehmensprofil, Titelbild, Bürokarte und Übergabefotos.','Fotos, technische Daten und Preise in einem Editor.'],pricing:'Klare Konditionen für Händler',trial:'Tage Vollzugriff nach Freischaltung',basic:'Nach der Testphase bleibt der gemeinsame Katalog ohne Abonnement verfügbar. Eigene Fahrzeuge und erweiterte Gestaltung benötigen Vollzugriff.',full:'Vollzugriff',month:'1 Monat',half:'6 Monate',year:'1 Jahr',commission:'Provision auf abgeschlossene Verkäufe aus AvtoCena-Anfragen',sale:'des Fahrzeugverkaufspreises',remuneration:'der Händlervergütung',billing:'Abonnement und Provision werden getrennt erfasst. Lieferantenkonditionen vereinbaren wir individuell. Es gibt keine automatische Abbuchung auf der Website.',formTitle:'Lernen wir uns kennen',formText:'Beschreiben Sie Ihren Standort und Ihr Fahrzeugangebot. Das AvtoCena-Team prüft die Anfrage und meldet sich bei Ihnen.',fields:['Unternehmen','Land','Stadt','Kontaktperson','E-Mail oder Telefon','Telegram / weiterer Kontakt','Märkte, Fahrzeuge und Zusammenarbeit'],consent:'Ich stimme der Datenverarbeitung zur Prüfung dieser Anfrage zu.',privacy:'Datenschutzerklärung',success:'Anfrage eingegangen. Wir melden uns über den angegebenen Kontakt.',error:'Senden fehlgeschlagen. Bitte Angaben prüfen und erneut versuchen.',send:'Anfrage senden',knowledge:'Wissensbasis',search:'Anleitungen durchsuchen',all:'Alle Anleitungen',empty:'Keine Ergebnisse. Versuchen Sie einen anderen Begriff.',read:'Anleitung lesen',preview:'Eigentümer-Vorschau · für Besucher verborgen',back:'Startseite',articles:[
{id:'catalog',title:'Ein Fahrzeug auswählen',category:'Käufer',paragraphs:['Wählen Sie im Katalog Land, Marke, Modell und Budget. Prüfen Sie Baujahr, Motor, Leistung, Laufleistung und Fotos auf der Fahrzeugseite.','Die Berechnung ist vorläufig. Vor dem Kauf bestätigt ein Mitarbeiter Verfügbarkeit, Daten und Endpreis. Nutzen Sie die Anfrage-Schaltfläche auf der Fahrzeugseite.']},
{id:'calculation',title:'Preis, Stadt und Lieferung',category:'Käufer',paragraphs:['Prüfen Sie Berechnungsparameter und Zielstadt. Teilen Sie den Link erst nach Abschluss der Neuberechnung.','Bei eigenen Händlerangeboten legt das Unternehmen die Basisstadt fest. TopAvto-Preise gelten bis Nowosibirsk; die Weiterlieferung wird separat vereinbart. Die Stadtauswahl des Besuchers ersetzt diesen Basispreis nicht.']},
{id:'sharing',title:'Eine Berechnung teilen',category:'Käufer',paragraphs:['Nach der Berechnung kopiert die Teilen-Schaltfläche am Computer Fahrzeugname, berechneten Preis und Link. Fügen Sie die Nachricht in Ihren Chat ein.','Wählen Sie am Smartphone eine App und prüfen Sie den Text. Vorschaubilder hängen von der empfangenden App ab. Gespeicherte Kundenberechnungen können eigene Links haben.']},
{id:'profile',title:'Händlerseite einrichten',category:'Händler',paragraphs:['Öffnen Sie nach der Freigabe den Händlerbereich. Ergänzen Sie Name, Beschreibung, Katalogmärkte und Büroadresse.','Mit Vollzugriff sind Titelbild, Logos und Übergabefotos verfügbar. Prüfen Sie die Vorschau, aktivieren Sie die Veröffentlichung und speichern Sie. Telefonnummern sind nicht öffentlich; Anfragen laufen über AvtoCena.']},
{id:'vehicles',title:'Eigene Fahrzeuge hinzufügen',category:'Händler',paragraphs:['Erstellen Sie im Bereich Fahrzeuge ein Angebot. Daten können manuell oder aus verfügbaren Inseratsdaten übernommen werden. Prüfen Sie importierte Angaben.','Laden Sie Fotos hoch, wählen Sie das Titelbild und die Reihenfolge. Der Einkaufspreis wird in USD angegeben. Zoll, Leistung und Ermäßigungsberechtigung müssen bestätigt werden.','Legen Sie Basisstadt und Kosten in der Berechnung eigener Fahrzeuge fest. Speichern Sie zunächst einen Entwurf, ergänzen Sie fehlende Felder und wählen Sie Veröffentlicht. Aktivieren Sie die Unternehmensangebote und speichern Sie.']},
{id:'access',title:'Testphase und Abonnement',category:'Händler',paragraphs:['Die Bestätigung startet eine einmalige Testphase mit Vollzugriff. Laufzeit und Preise stehen auf der Partnerseite und unter Mein Zugang.','Danach bleibt der Basiskatalog verfügbar. Eigene Angebote und Galerie bleiben gespeichert, sind aber bis zur Verlängerung verborgen und nicht bearbeitbar. Zahlungseingänge bestätigt der Plattforminhaber; Verkaufsprovisionen werden separat erfasst.']},
{id:'supply',title:'Fahrzeuge aus dem Ausland anbieten',category:'Lieferanten',paragraphs:['Wählen Sie auf der Partnerseite Fahrzeuglieferant und nennen Sie Land, Unternehmen, Kontakt und Märkte. Beschreiben Sie Bestand und verfügbares Datenformat.','Nach Prüfung vereinbaren wir Datenfelder, Fotos, Bestandsaktualisierung, Preise und Bedingungen. Senden Sie keine Passwörter oder API-Schlüssel über das öffentliche Formular.']}
]}
};
