'use client';
import {useEffect,useRef,useState} from 'react';
export function PersonAvatar({src,name}:{src?:string;name:string}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return <span className="portal-person-avatar">{src&&!failed?<img src={src} alt={name} onError={()=>setFailed(true)}/>:name.slice(0,1).toUpperCase()}</span>;}
export function CustomerChat({client,account,onSend}:{client:any;account:any;onSend:(text:string)=>Promise<any>}){
 const [text,setText]=useState(''),[pending,setPending]=useState<any>(null),[error,setError]=useState('');const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[client.messages.length,pending?.id]);
 return <><div className="portal-conversation" aria-live="polite">{[...client.messages,...(pending?[pending]:[])].map((m:any)=><article key={m.id} className={`portal-chat-row ${m.mine?'mine':''}`}><PersonAvatar src={m.mine?account.avatarUrl||'/key-logo.png':m.avatar} name={m.author}/><div className="portal-message"><small>{m.author} · {m.pending?'Отправляем…':new Date(m.createdAt).toLocaleString('ru-RU')}</small><p>{m.text}</p></div></article>)}<div ref={end}/></div>{!client.messages.length&&!pending&&<p className="account-muted mt-4">Напишите менеджеру или компании.</p>}
 <form onSubmit={async e=>{e.preventDefault();if(pending||!text.trim())return;const value=text.trim();setError('');setPending({id:'pending',text:value,author:account.name,mine:true,pending:true});setText('');try{await onSend(value);}catch(e){setText(value);setError(e instanceof Error?e.message:'Сообщение не отправлено. Попробуйте ещё раз.');}finally{setPending(null);}}}><textarea name="text" value={text} onChange={e=>setText(e.target.value)} disabled={!!pending} aria-label="Сообщение менеджеру" placeholder="Ваше сообщение…" required maxLength={4000}/>{error&&<p role="alert" className="account-error">{error}</p>}<button disabled={!!pending} className="account-primary">{pending?'Отправляем…':'Отправить'}</button></form></>;
}
