'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import './account.css';
export function CustomerAccess({clientId,documents,leads=[]}:{clientId:string;documents:any[];leads?:any[]}){const router=useRouter();const [url,setUrl]=useState(''),[error,setError]=useState(''),[messages,setMessages]=useState<any[]>([]),[linked,setLinked]=useState(false),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/crm/customer-access?clientId='+encodeURIComponent(clientId),{cache:'no-store'});if(r.ok){const d=await r.json();setMessages(d.messages);setLinked(d.linked);}}
 useEffect(()=>{void load();const t=setInterval(()=>{if(!document.hidden)void load();},30000);return()=>clearInterval(t);},[clientId]);
 async function send(body:any){setError('');setBusy(true);try{const r=await fetch('/api/crm/customer-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,...body})});const d=await r.json();if(!r.ok)throw Error(d.error||'Не удалось сохранить.');if(d.url)setUrl(d.url);await load();router.refresh();return true;}catch(e){setError(e instanceof Error?e.message:'Ошибка соединения.');return false;}finally{setBusy(false);}}
 return <section className="customer-access"><h2 className="text-xl font-bold">Кабинет клиента</h2><p className="account-muted">{linked?'Клиент подключён. Здесь — переписка, которую он видит в своём кабинете.':'Отправьте приглашение лично клиенту после проверки его личности. Ссылка действует сутки и открывает доступ к его карточке.'}</p>{!linked&&<button disabled={busy} onClick={()=>void send({action:'invite'})}>Создать приглашение</button>}{url&&<div><input readOnly value={url} aria-label="Приглашение в кабинет"/><button onClick={()=>void navigator.clipboard.writeText(url).catch(()=>setError('Скопируйте ссылку из поля.'))}>Скопировать</button></div>}<h3 className="mt-4 font-bold">Документы в кабинете</h3>{documents.filter(d=>!d.deletedAt).map(d=><label key={d.id} className="block mt-2 text-sm"><input type="checkbox" checked={d.customerVisible===true} disabled={busy} onChange={e=>void send({action:'share',documentId:d.id,visible:e.target.checked})}/> {d.name}</label>)}<p className="account-muted mt-2">Клиент видит только отмеченные файлы. Его собственные загрузки доступны сразу.</p>{linked&&<><h3 className="mt-4 font-bold">Переписка с клиентом</h3>{messages.map(m=><article className="portal-message" key={m.id}><small>{m.author} · {new Date(m.createdAt).toLocaleString('ru-RU')}</small><p>{m.text}</p></article>)}<form onSubmit={e=>{e.preventDefault();const f=e.currentTarget;void send({action:'message',text:new FormData(f).get('text')}).then(ok=>{if(ok)f.reset();});}}><textarea name="text" aria-label="Сообщение клиенту в кабинет" required maxLength={4000}/><button disabled={busy}>Отправить клиенту</button></form></>}{leads.length>0&&<details className="mt-4"><summary>Подписанный договор и право на отзыв</summary><form onSubmit={e=>{e.preventDefault();if(!confirm('Подтверждаете, что договор по этой заявке подписан клиентом и работа началась?'))return;const f=new FormData(e.currentTarget);void send({action:'confirm_contract',confirmed:true,leadId:f.get('lead'),documentId:f.get('document')});}}><select name="lead" aria-label="Заявка" required defaultValue=""><option value="" disabled>Выберите заявку</option>{leads.map(l=><option key={l.id} value={l.id}>{l.offerTitle||l.car||l.id}</option>)}</select><select name="document" aria-label="Подписанный договор" required defaultValue=""><option value="" disabled>Документ договора</option>{documents.filter(d=>d.customerVisible&&!d.deletedAt).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button disabled={busy}>Подтвердить договор</button></form></details>}{error&&<p role="alert" className="account-error">{error}</p>}</section>;
}
