'use client';
import {useEffect,useRef,useState} from 'react';
import {Send,MessageCircle,Clock3,Check} from 'lucide-react';
import {crmChatStyles} from '../crm/ChatStyles';
export function PersonAvatar({src,name}:{src?:string;name:string}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return <span className="portal-person-avatar">{src&&!failed?<img src={src} alt={name} onError={()=>setFailed(true)}/>:name.slice(0,1).toUpperCase()}</span>;}
export function CustomerChat({client,account,onSend}:{client:any;account:any;onSend:(text:string)=>Promise<any>}){
 const [text,setText]=useState(''),[pending,setPending]=useState<any>(null),[error,setError]=useState('');const list=useRef<HTMLDivElement>(null),follow=useRef(true);
 useEffect(()=>{if(list.current&&(follow.current||pending))list.current.scrollTop=list.current.scrollHeight;},[client.messages.length,pending]);
 const messages=[...client.messages,...(pending?[pending]:[])];
 return <div className="ac-chat customer-account-chat" data-chat-screen="conversation"><style>{crmChatStyles}</style><section className="ac-chat-conversation"><div className="ac-chat-toolbar"><PersonAvatar src={client.manager?.avatar} name={client.manager?.name||'Компания'}/><div><strong>{client.manager?.name||client.dealer?.name||'Чат с компанией'}</strong><small>{client.manager?'Ваш менеджер':'Переписка по вашей заявке'}</small></div></div>
 <div ref={list} className="ac-chat-messages" aria-live="polite" onScroll={()=>{const el=list.current;if(el)follow.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;}}>{!messages.length&&<div className="ac-chat-empty"><MessageCircle size={40}/><p>Напишите менеджеру или компании.</p></div>}{messages.map((m:any,i:number)=>{const date=m.createdAt?new Date(m.createdAt):new Date();const previous=messages[i-1];const showDate=!previous||date.toDateString()!==new Date(previous.createdAt||Date.now()).toDateString();return <div key={m.id}>{showDate&&<div className="customer-chat-date">{date.toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</div>}<div className={`portal-chat-row customer-chat-row ${m.mine?'mine':''}`}><PersonAvatar src={m.mine?account.avatarUrl||'/key-logo.png':m.avatar} name={m.author}/><article className={`ac-chat-message ${m.mine?'is-mine':''}`}><div className="ac-chat-message-head"><strong>{m.mine?account.name:m.author}</strong></div><p>{m.text}</p><small>{m.pending?<><Clock3 size={11}/>Отправляем…</>:<>{date.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}{m.mine&&<Check size={13} aria-label="Отправлено"/>}</>}</small></article></div></div>;})}</div>
 {error&&<p role="alert" className="ac-chat-error">{error}</p>}
 <form className="ac-chat-compose" onSubmit={async e=>{e.preventDefault();if(pending||!text.trim())return;const value=text.trim();setError('');follow.current=true;setPending({id:'pending',text:value,author:account.name,mine:true,pending:true,createdAt:new Date().toISOString()});setText('');try{await onSend(value);}catch(e){setText(value);setError(e instanceof Error?e.message:'Сообщение не отправлено. Попробуйте ещё раз.');}finally{setPending(null);}}}><textarea name="text" rows={1} value={text} onChange={e=>setText(e.target.value)} disabled={!!pending} aria-label="Сообщение менеджеру" placeholder="Сообщение…" required maxLength={4000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><button type="submit" disabled={!!pending||!text.trim()} aria-label={pending?'Отправляем…':'Отправить'} title="Отправить">{pending?<Clock3 size={21}/>:<Send size={21}/>}</button></form>
 </section></div>;
}
