'use client';
import {useEffect,useRef,useState} from 'react';
import {Send,MessageCircle,Clock3,Check,MoreHorizontal,Paperclip,ChevronDown,FileText} from 'lucide-react';
import {PublicSheet} from '../ui/PublicSheet';
import {crmChatStyles} from '../crm/ChatStyles';
export function PersonAvatar({src,name}:{src?:string;name:string}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return <span className="portal-person-avatar">{src&&!failed?<img src={src} alt={name} onError={()=>setFailed(true)}/>:name.slice(0,1).toUpperCase()}</span>;}
export function CustomerChat({client,account,onSend,onUpload}:{client:any;account:any;onSend:(text:string)=>Promise<any>;onUpload:(file:File)=>Promise<any>}){
 const [text,setText]=useState(''),[pending,setPending]=useState<any>(null),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[menu,setMenu]=useState(false),[mobile,setMobile]=useState(false),[open,setOpen]=useState(true),[viewport,setViewport]=useState<number>();
 const list=useRef<HTMLDivElement>(null),root=useRef<HTMLDivElement>(null),file=useRef<HTMLInputElement>(null),follow=useRef(true),posting=useRef(false);
 useEffect(()=>{const media=matchMedia('(max-width:767px)'),update=()=>{setMobile(media.matches);setViewport(window.visualViewport?.height||innerHeight);};update();media.addEventListener('change',update);window.visualViewport?.addEventListener('resize',update);window.addEventListener('resize',update);return()=>{media.removeEventListener('change',update);window.visualViewport?.removeEventListener('resize',update);window.removeEventListener('resize',update);};},[]);
 useEffect(()=>{if(mobile)return;const node=root.current;if(!node)return;const resize=()=>node.style.height=`${Math.max(360,innerHeight-node.getBoundingClientRect().top-16)}px`;resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[mobile]);
 useEffect(()=>{if(list.current&&(follow.current||pending))list.current.scrollTop=list.current.scrollHeight;},[client.messages.length,pending,open,mobile]);
 const messages=[...client.messages,...(pending?[pending]:[])];
 const conversation=<div ref={root} className="ac-chat customer-account-chat" data-chat-screen="conversation" style={mobile&&viewport?{height:Math.floor(viewport*.92)}:undefined}><style>{crmChatStyles}</style><section className="ac-chat-conversation"><div className="ac-chat-toolbar"><PersonAvatar src={client.manager?.avatar} name={client.manager?.name||'Компания'}/><div className="customer-chat-manager"><strong>{client.manager?.name||client.dealer?.name||'Чат с компанией'}</strong><small>{client.manager?'Ваш менеджер':'Переписка по вашей заявке'}</small></div><button type="button" aria-label="Меню чата" aria-expanded={menu} onClick={()=>setMenu(v=>!v)}><MoreHorizontal size={22}/></button>{mobile&&<button type="button" aria-label="Свернуть чат" onClick={()=>{setOpen(false);setMenu(false);}}><ChevronDown size={23}/></button>}</div>
 {menu&&<div className="customer-chat-menu"><button type="button" disabled={uploading} onClick={()=>{setMenu(false);file.current?.click();}}><Paperclip size={19}/>Прикрепить документ</button><small>До 5 МБ. Файл появится в ваших документах и карточке клиента.</small></div>}
 <input ref={file} type="file" hidden accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.xlsx" onChange={async e=>{const selected=e.target.files?.[0];e.target.value='';if(!selected||uploading)return;if(selected.size>5*1024*1024){setError('Файл должен быть не больше 5 МБ.');return;}setUploading(true);setError('');follow.current=true;try{await onUpload(selected);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить документ.');}finally{setUploading(false);}}}/>
 <div ref={list} className="ac-chat-messages" role="log" aria-live="polite" onScroll={()=>{const el=list.current;if(el)follow.current=el.scrollHeight-el.scrollTop-el.clientHeight<80;}}>{!messages.length&&<div className="ac-chat-empty"><MessageCircle size={40}/><p>Напишите менеджеру или компании.</p></div>}{messages.map((m:any,i:number)=>{const date=m.createdAt?new Date(m.createdAt):new Date();const previous=messages[i-1];const showDate=!previous||date.toDateString()!==new Date(previous.createdAt||Date.now()).toDateString();return <div key={m.id}>{showDate&&<div className="customer-chat-date">{date.toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</div>}<div className={`portal-chat-row customer-chat-row ${m.mine?'mine':''} ${m.system?'is-system':''}`}><PersonAvatar src={m.mine?account.avatarUrl||'/key-logo.png':m.avatar} name={m.author}/><article className={`ac-chat-message ${m.mine?'is-mine':''}`}><div className="ac-chat-message-head"><strong>{m.mine?account.name:m.author}</strong></div><p>{m.text}</p>{m.documentId&&<a className="customer-chat-document" href={`/api/account/documents/${encodeURIComponent(m.documentId)}?client=${encodeURIComponent(client.key)}`} target="_blank" rel="noreferrer"><FileText size={18}/>Открыть документ</a>}<small>{m.pending?<><Clock3 size={11}/>Отправляем…</>:<>{date.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}{m.mine&&<Check size={13} aria-label="Отправлено"/>}</>}</small></article></div></div>;})}</div>
 {uploading&&<p role="status" className="customer-chat-uploading">Загружаем документ…</p>}{error&&<p role="alert" className="ac-chat-error">{error}</p>}
 <form className="ac-chat-compose" onSubmit={async e=>{e.preventDefault();if(posting.current||!text.trim())return;posting.current=true;const value=text.trim();setError('');follow.current=true;setPending({id:'pending',text:value,author:account.name,mine:true,pending:true,createdAt:new Date().toISOString()});setText('');try{await onSend(value);}catch(e){setText(value);setError(e instanceof Error?e.message:'Сообщение не отправлено. Попробуйте ещё раз.');}finally{posting.current=false;setPending(null);}}}><textarea name="text" rows={1} value={text} onChange={e=>setText(e.target.value)} disabled={!!pending} aria-label="Сообщение менеджеру" placeholder="Сообщение…" required maxLength={4000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><button type="submit" disabled={!!pending||!text.trim()} aria-label={pending?'Отправляем…':'Отправить'} title="Отправить">{pending?<Clock3 size={21}/>:<Send size={21}/>}</button></form>
 </section></div>;
 if(!mobile)return conversation;
 return <><button type="button" className="customer-chat-reopen" onClick={()=>setOpen(true)}><MessageCircle size={22}/>Открыть чат{(text||uploading)&&<small>{uploading?'Загрузка документа…':'Есть черновик'}</small>}</button>{open&&<PublicSheet title="Чат с менеджером" showHeader={false} fitVisualViewport className="customer-chat-sheet" onClose={()=>{setOpen(false);setMenu(false);}}>{conversation}</PublicSheet>}</>;
}
