'use client';
import {CrmPushControl} from '../crm/CrmPushControl';
import {useEffect,useRef,useState} from 'react';
import {Bell,Volume2,VolumeX,X} from 'lucide-react';
import type {CustomerNotice} from '@/lib/account/notifications';
import './customer-header.css';
export function CustomerHeader({account:initial}:{account:any}){
 const [account,setAccount]=useState(initial),[open,setOpen]=useState(false),[items,setItems]=useState<CustomerNotice[]>([]),[seen,setSeen]=useState<string[]>([]),[sound,setSound]=useState(false),[notice,setNotice]=useState('');const known=useRef<Set<string>|null>(null),audio=useRef<AudioContext|null>(null),panel=useRef<HTMLDivElement>(null);
 const key='avtocena:customer:'+account.id;
 useEffect(()=>{const update=(e:Event)=>setAccount((e as CustomEvent).detail);window.addEventListener('avtocena:account-updated',update);try{setSeen(JSON.parse(localStorage.getItem(key+':seen')||'[]'));setSound(localStorage.getItem(key+':sound')==='1');}catch{}return()=>window.removeEventListener('avtocena:account-updated',update);},[key]);
 useEffect(()=>{let active=true;async function refresh(){try{const r=await fetch('/api/account/notifications',{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(!active)return;const fresh=(d.items as CustomerNotice[]).filter(n=>known.current&&!known.current.has(n.id));known.current=new Set(d.items.map((n:CustomerNotice)=>n.id));setItems(d.items);
 if(fresh.length&&sound&&audio.current?.state==='running'){const oscillator=audio.current.createOscillator(),gain=audio.current.createGain();oscillator.connect(gain);gain.connect(audio.current.destination);gain.gain.setValueAtTime(.06,audio.current.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.2);oscillator.frequency.value=740;oscillator.start();oscillator.stop(audio.current.currentTime+.2);}

 }catch{}}
 void refresh();const timer=setInterval(()=>void refresh(),30000);return()=>{active=false;clearInterval(timer);};},[sound,key]);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};const outside=(e:PointerEvent)=>{if(!panel.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('keydown',close);document.addEventListener('pointerdown',outside);return()=>{document.removeEventListener('keydown',close);document.removeEventListener('pointerdown',outside);};},[open]);
 useEffect(()=>{if(!sound)return;const unlock=()=>{try{const Audio=window.AudioContext||(window as any).webkitAudioContext;if(Audio){audio.current??=new Audio();void audio.current?.resume().catch(()=>{});}}catch{}};document.addEventListener('pointerdown',unlock);return()=>document.removeEventListener('pointerdown',unlock);},[sound]);
 useEffect(()=>()=>{void audio.current?.close();},[]);
 const unread=items.filter(i=>!seen.includes(i.id)).length;
 function read(){const ids=items.map(i=>i.id);setSeen(ids);try{localStorage.setItem(key+':seen',JSON.stringify(ids));}catch{}}
 return <div className="customer-header-tools" ref={panel}><button className="customer-header-icon" aria-label={`Уведомления${unread?': '+unread:''}`} aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Bell size={21}/>{unread>0&&<span>{unread}</span>}</button><a href="/account?tab=profile" aria-label="Личный кабинет"><img className={account.avatarUrl==='/key-logo.png'||account.avatarUrl==='/api/account/default-avatar'?'account-default-avatar':undefined} src={account.avatarUrl} alt="" width={40} height={40}/></a>{open&&<section className="customer-notice-panel" aria-label="Уведомления кабинета"><header><strong>Уведомления</strong><button aria-label="Закрыть уведомления" onClick={()=>setOpen(false)}><X size={20}/></button></header><div className="customer-notice-settings"><button onClick={()=>{const next=!sound;setSound(next);try{localStorage.setItem(key+':sound',next?'1':'0');if(next){audio.current??=new AudioContext();void audio.current.resume();}}catch{setNotice('Звук недоступен в этом браузере.');}}}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>} {sound?'Выключить звук':'Включить звук'}</button><CrmPushControl userId={account.id} customer/><button onClick={read}>Прочитать все</button></div>{notice&&<p role="status">{notice}</p>}<p className="customer-notice-hint">Звук на сайте включается отдельно. Push-уведомления приходят на это устройство после разрешения в браузере.</p><div className="customer-notice-list">{items.length?items.map(i=><a key={i.id} href={i.href} data-unread={!seen.includes(i.id)} onClick={()=>{const next=[...seen,i.id].slice(-100);setSeen(next);try{localStorage.setItem(key+':seen',JSON.stringify(next));}catch{}}}><strong>{i.title}</strong><p>{i.text}</p><small>{new Date(i.at).toLocaleString('ru-RU')}</small></a>):<p>Новых событий пока нет.</p>}</div><a href="/account">Открыть кабинет →</a></section>}</div>;
}
