export const dealerProfileStyles=`
.dealer-profile .dealer-customer-review{margin-top:16px}.dealer-review-author-row{display:flex;gap:12px;align-items:center}.dealer-review-author-row>strong{min-width:0;overflow-wrap:anywhere}.dealer-review-avatar{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:#ffda62;color:#17243d;overflow:hidden;flex:none;font-weight:800}.dealer-review-avatar img{width:100%;height:100%;object-fit:cover}.dealer-review-score{margin-left:auto;display:flex;align-items:center;gap:5px;color:#967000;font-size:27px;font-weight:800;flex:none}[data-theme=dark] .dealer-review-score{color:#ffda62}.dealer-profile .dealer-review-text{white-space:pre-wrap;overflow-wrap:anywhere;margin:12px 0}.dealer-review-footer{display:flex;align-items:center;flex-wrap:wrap;gap:14px;font-size:12px}.dealer-review-footer button{font-size:13px;color:#856000;text-decoration:underline;text-underline-offset:3px;padding:6px 0}[data-theme=dark] .dealer-review-footer button{color:#ffda62}.dealer-review-reply{margin-top:18px;padding:14px 0 0 16px;border-left:3px solid #ffda62}.dealer-review-reply time{font-size:11px;opacity:.7}.dealer-review-reply-form{display:grid;gap:12px;margin-top:16px}.dealer-review-reply-form label{display:grid;gap:8px;font-size:13px}.dealer-review-reply-form textarea{min-height:110px;resize:vertical;width:100%;padding:12px;border:1px solid var(--ac-border);border-radius:12px;background:var(--ac-surface);color:var(--ac-text);font-size:16px}.dealer-review-reply-form>button{justify-self:start;background:#ffda62;color:#17243d;padding:11px 16px;border-radius:12px;font-weight:700}.dealer-review-reply-form button:disabled,.dealer-review-footer button:disabled{opacity:.6}

.dealer-about-logo{margin-bottom:16px}.dealer-verification:hover>span{display:block}.dealer-verification:not([open]):not(:hover)>span{display:none}

body:has(.dealer-profile) .ac-public-footer-operator,body:has(.dealer-profile) .ac-public-footer-navigation>nav,body:has(.dealer-profile) .ac-public-footer-navigation>div>:not(.ac-public-footer-tools){display:none!important}
body:has(.dealer-profile) .ac-public-footer-navigation{display:block;padding:0!important}
body:has(.dealer-profile) .ac-public-footer-tools{max-width:320px}
body:has(.dealer-profile) .ac-public-legal-footer{margin-top:0;padding-bottom:120px}
.dealer-profile{--dealer-radius:30px;--dealer-accent:#e52b35;padding-bottom:120px;color:var(--ac-text)}
.dealer-profile button,.dealer-profile a{-webkit-tap-highlight-color:transparent}.dealer-profile button:focus-visible,.dealer-profile a:focus-visible{outline:3px solid #699de8;outline-offset:3px}.dealer-preview-note{padding:10px 16px;background:#eab30818;border:1px solid #eab30844;border-radius:14px;margin-bottom:14px;font-size:12px}
.dealer-profile-hero{position:relative;overflow:hidden;border-radius:var(--dealer-radius) var(--dealer-radius) 0 0;background:#141820}.dealer-cover{display:block;width:100%;height:clamp(260px,25vw,360px);object-fit:cover}.dealer-cover-empty{background:radial-gradient(ellipse at 75% 90%,#933737,transparent 60%),linear-gradient(120deg,#101720,#334456)}.dealer-profile-hero:after{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(#0003,transparent 40%)}.dealer-cover-label{position:absolute;z-index:1;top:22px;left:26px;color:#fff;background:#0005;border:1px solid #fff3;border-radius:100px;padding:9px 14px;font-size:12px;backdrop-filter:blur(12px)}.dealer-cover-actions{position:absolute;z-index:1;top:20px;right:24px;display:flex;gap:8px}.dealer-cover-actions button{display:grid;place-items:center;width:44px;height:44px;border-radius:50%;background:#ffffff35;backdrop-filter:blur(15px);color:#fff;border:1px solid #ffffff40}.dealer-cover-actions button[aria-pressed=true] svg{fill:#ed4d60;stroke:#fff}.dealer-share-status{position:absolute;right:24px;top:74px;padding:8px 14px;color:#fff;background:#18212edb;border-radius:12px;z-index:1;font-size:12px}
.dealer-sheet{background:var(--ac-surface);border-radius:var(--dealer-radius);min-width:0;box-shadow:0 3px 12px #0a244205}.dealer-profile-identity{position:relative;margin:-36px 0 0;padding:26px 28px 22px;z-index:2}.dealer-identity-row{display:flex;align-items:center;gap:30px}.dealer-avatar{width:124px;height:100px;flex-shrink:0;display:grid;place-items:center;border-radius:22px;background:var(--ac-page-bg);padding:4px}.dealer-avatar img{width:100%;height:100%;object-fit:contain}.dealer-avatar span{font-size:28px;font-weight:900}.dealer-identity-title{flex:1;min-width:0}.dealer-identity-title h1{font-size:28px;font-weight:850;line-height:1.2;overflow-wrap:anywhere}.dealer-address-link{font-size:13px;margin-top:7px;text-align:left;line-height:1.5}.dealer-hours{display:flex;align-items:center;gap:6px;font-size:12px;margin-top:5px;color:var(--ac-muted);text-align:left}.dealer-hours svg{width:14px;height:14px;color:#54ae77}.dealer-info-button{display:grid;place-items:center;width:36px;height:36px;flex-shrink:0;border-radius:50%;color:var(--ac-muted)}.dealer-info-button:hover{background:var(--ac-bg)}.dealer-primary{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:12px 20px;border-radius:16px;background:var(--dealer-accent);color:white!important;font-size:14px;font-weight:750;text-align:center}
.dealer-stories{border-top:1px solid var(--ac-border);margin-top:22px;padding-top:18px}.dealer-stories>section{margin:0}.dealer-stories h2{display:none}.dealer-stories .ac-buyers-rail{margin:0;gap:12px;padding:0;scrollbar-width:none}.dealer-stories .ac-buyers-rail>button{width:128px;height:128px;border-radius:23px}.dealer-intro-wrap{margin-top:18px}.dealer-intro{font-size:14px;line-height:1.6;max-width:900px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;white-space:pre-line}.dealer-intro.is-expanded{display:block}.dealer-expand{font-size:12px;font-weight:650;color:var(--ac-muted);margin-top:7px}.dealer-profile-tabs{display:flex;gap:4px;margin-top:20px;padding:4px;border-radius:100px;background:linear-gradient(100deg,#5d9ee51c,#d399c42b)}.dealer-profile-tabs button{flex:1;padding:12px 14px;border-radius:100px;font-weight:700;font-size:14px;color:var(--ac-muted);min-width:0}.dealer-profile-tabs button[aria-pressed=true]{color:var(--ac-text);background:var(--ac-surface);box-shadow:0 2px 7px #17345c0c}.dealer-profile-tabs button span{margin-left:5px;font-size:11px;opacity:.6}
.dealer-profile-body{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:20px;margin-top:18px;align-items:start}.dealer-tab-content{padding:26px;scroll-margin-top:86px}.dealer-profile-identity h2,.dealer-tab-content>h2{font-size:23px;font-weight:800;line-height:1.3}.dealer-section-heading{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-bottom:18px}.dealer-section-heading>span{font-size:11px;color:var(--ac-muted);padding:6px 10px;border-radius:50px;background:var(--ac-bg)}.dealer-eyebrow{font-size:10px;letter-spacing:normal;text-transform:none;color:var(--ac-muted);font-weight:700;margin:0 0 8px}.dealer-muted{color:var(--ac-muted);font-size:13px;line-height:1.6}.dealer-small-heading{font-size:15px;font-weight:750;margin:24px 0 12px}.dealer-about-text{white-space:pre-line;font-size:15px;line-height:1.8;margin:18px 0}.dealer-city-chips{display:flex;gap:8px;flex-wrap:wrap}.dealer-city-chips span{border-radius:100px;background:var(--ac-page-bg);padding:4px 15px;font-size:13px}.dealer-side{position:sticky;top:88px;display:grid;gap:14px}.dealer-request-card{padding:24px}.dealer-request-icon{display:grid;place-items:center;background:#e52b3512;color:var(--dealer-accent);border-radius:16px;width:48px;height:48px;margin-bottom:24px}.dealer-request-card h2{font-size:23px}.dealer-request-card p:not(.dealer-eyebrow){font-size:13px;line-height:1.7;color:var(--ac-muted);margin:16px 0 20px}.dealer-request-card .dealer-primary{width:100%}.dealer-request-card small{display:block;text-align:center;font-size:10px;color:var(--ac-muted);margin-top:13px}.dealer-office-shortcut{display:flex;align-items:center;gap:12px;text-align:left;padding:20px;font-size:12px}.dealer-office-shortcut>svg{flex-shrink:0;color:#5d90ca}.dealer-office-shortcut>span:nth-child(2){flex:1}.dealer-office-shortcut strong,.dealer-office-shortcut span span{display:block}.dealer-office-shortcut span span{color:var(--ac-muted);margin-top:5px}
.dealer-cars-grid,.dealer-catalog-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:18px}.dealer-car{overflow:hidden;background:var(--ac-bg);border-radius:20px;min-width:0}.dealer-car>img{aspect-ratio:4/3;object-fit:cover;width:100%}.dealer-car>div{padding:14px}.dealer-car h3{font-size:14px;line-height:1.4;font-weight:750;margin-bottom:8px}.dealer-car strong{font-size:19px;display:block}.dealer-car p{color:var(--ac-muted);font-size:12px;margin-top:8px}.dealer-empty{display:flex;flex-direction:column;align-items:center;text-align:center;padding:38px 12px;gap:16px}.dealer-empty>svg{width:44px;height:44px;color:#8fa9c8}.dealer-empty h3{font-size:22px;font-weight:800;max-width:360px;line-height:1.3}.dealer-empty p{max-width:450px;font-size:14px;line-height:1.7;color:var(--ac-muted)}
.dealer-market-pills{display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;padding:2px 1px 5px}.dealer-market-pills button{flex-shrink:0;display:flex;gap:7px;align-items:center;padding:10px 15px;border:1px solid transparent;border-radius:99px;background:var(--ac-bg);font-size:12px;font-weight:650}.dealer-market-pills button[aria-pressed=true]{background:var(--ac-surface);border-color:#799fc8;box-shadow:0 0 0 2px #799fc81a}.dealer-market-pills button span{font-size:18px}.dealer-catalog-search{display:flex;gap:7px;margin:16px 0 10px}.dealer-catalog-search input{width:100%;min-width:0;border:1px solid var(--ac-border);background:var(--ac-bg);color:var(--ac-text);border-radius:14px;padding:11px 14px;font-size:13px}.dealer-catalog-search button{padding:8px 14px;border-radius:14px;background:var(--ac-bg);font-size:12px;font-weight:700}.dealer-catalog-origin{font-size:11px}.dealer-pagination{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:22px;font-size:12px}.dealer-pagination button{padding:12px 14px;border-radius:13px;background:var(--ac-bg)}.dealer-pagination button:disabled{opacity:.35}.dealer-catalog-skeleton{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:18px}.dealer-catalog-skeleton>div{height:230px;border-radius:18px;background:linear-gradient(120deg,var(--ac-bg),var(--ac-border),var(--ac-bg));opacity:.45}.dealer-photo-grid .ac-buyers-rail{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px;overflow:visible}.dealer-photo-grid .ac-buyers-rail>button{width:100%;height:auto;aspect-ratio:1;border-radius:5px}.dealer-profile-offices{display:grid;gap:10px}.dealer-profile-offices button{display:flex;align-items:center;gap:12px;text-align:left;border:1px solid var(--ac-border);border-radius:18px;padding:16px}.dealer-profile-offices button>span:nth-child(2){flex:1}.dealer-profile-offices strong,.dealer-profile-offices small,.dealer-profile-offices span span{display:block;font-size:13px}.dealer-profile-offices span span,.dealer-profile-offices small{margin-top:6px;color:var(--ac-muted)}
.dealer-dock{position:fixed;z-index:45;bottom:calc(18px + env(safe-area-inset-bottom));left:50%;transform:translateX(-50%);width:min(560px,calc(100% - 32px));display:flex;gap:5px;padding:8px;background:var(--ac-surface);border:1px solid var(--ac-border);border-radius:28px;box-shadow:0 10px 45px #081c3530}.dealer-dock>a,.dealer-dock>button{flex:1;min-width:0;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:5px;min-height:54px;border-radius:20px;color:var(--ac-muted);font-size:10px;font-weight:650}.dealer-dock button[aria-pressed=true]{background:#7b9fce18;color:var(--ac-text)}.dealer-dock .dealer-dock-request{background:#e52b3510;color:var(--dealer-accent)}
.dealer-info-dialog{padding:0;border:0;border-radius:30px;width:min(560px,calc(100% - 32px));max-height:88dvh;background:var(--ac-surface);color:var(--ac-text);margin:auto;box-shadow:0 20px 100px #0005;overscroll-behavior:contain}.dealer-info-dialog::backdrop{background:#07111e8c;backdrop-filter:blur(5px)}body:has(.dealer-info-dialog[open]){overflow:hidden}.dealer-dialog-content{padding:26px}.dealer-dialog-content>header{display:flex;align-items:center;justify-content:space-between;gap:14px;padding-bottom:22px;border-bottom:1px dashed var(--ac-border)}.dealer-dialog-content h2{font-size:23px;font-weight:800}.dealer-dialog-handle{display:none}.dealer-office-select{display:flex;align-items:center;gap:12px;border:1px solid var(--ac-border);border-radius:16px;padding:12px 14px;margin-top:22px}.dealer-office-select>svg{color:#53a577;flex-shrink:0}.dealer-office-select label{font-size:10px;color:var(--ac-muted);width:100%;min-width:0}.dealer-office-select select{display:block;width:100%;font-size:13px;color:var(--ac-text);background:var(--ac-surface);padding-top:5px}.dealer-office-hours{display:flex;align-items:center;gap:12px;background:var(--ac-bg);padding:14px;border-radius:16px;margin-top:12px;font-size:14px}.dealer-office-hours small{display:block;color:var(--ac-muted);font-size:11px;margin-bottom:4px}.dealer-dialog-content .dealer-route-button{display:flex;margin-top:18px}.dealer-dialog-content section>h2{font-size:16px}.dealer-dialog-note{font-size:12px;line-height:1.6;color:var(--ac-muted);margin-top:20px}.dealer-dialog-request{display:inline-block;color:var(--dealer-accent);font-size:13px;font-weight:700;margin-top:8px}.dealer-logo-light{display:none}html[data-theme=light] .dealer-logo-light{display:block}html[data-theme=light] .dealer-logo-dark{display:none}
@media(max-width:1150px){.dealer-profile-body{grid-template-columns:minmax(0,1fr) 250px}.dealer-catalog-grid,.dealer-cars-grid,.dealer-catalog-skeleton{grid-template-columns:repeat(2,minmax(0,1fr))}.dealer-request-card{padding:20px}.dealer-desktop-request{font-size:12px;padding:10px 14px}}
@media(max-width:800px){.dealer-profile{padding:0 0 118px;--dealer-radius:30px}.dealer-preview-note{margin:10px 12px}.dealer-profile-hero{border-radius:0}.dealer-cover{height:290px;object-position:center}.dealer-cover-label{top:18px;left:18px;font-size:10px}.dealer-cover-actions{top:15px;right:16px}.dealer-cover-actions button{width:40px;height:40px}.dealer-profile-identity{margin:-32px 0 0;padding:22px 20px 20px}.dealer-identity-row>.dealer-avatar{display:none}.dealer-avatar{width:86px;height:76px;border-radius:18px;padding:2px}.dealer-identity-row{gap:20px;align-items:flex-start}.dealer-identity-title{padding-top:2px}.dealer-identity-title h1{font-size:19px}.dealer-address-link{font-size:12px;margin-top:7px}.dealer-hours{font-size:11px}.dealer-info-button{width:26px;height:26px}.dealer-info-button svg{width:20px;height:20px}.dealer-desktop-request{display:none}.dealer-stories{margin:20px -20px 0;padding:14px 0 0;border-top:1px solid var(--ac-border)}.dealer-stories .ac-buyers-rail{padding:0 20px;gap:10px}.dealer-stories .ac-buyers-rail>button{width:108px;height:110px;border-radius:23px}.dealer-intro-wrap{margin-top:16px}.dealer-intro{font-size:12px;line-height:1.55}.dealer-expand{font-size:11px}.dealer-profile-tabs{margin-top:17px}.dealer-profile-tabs button{padding:10px 3px;font-size:12px;white-space:nowrap}.dealer-profile-tabs button span{font-size:10px}.dealer-profile-body{display:block;margin-top:14px}.dealer-tab-content{padding:22px 18px}.dealer-profile-identity h2,.dealer-tab-content>h2{font-size:20px}.dealer-side{display:none}.dealer-section-heading{gap:8px;margin-bottom:16px}.dealer-section-heading>span{font-size:9px}.dealer-catalog-grid,.dealer-cars-grid{gap:10px}.dealer-car>div{padding:10px}.dealer-car h3{font-size:12px}.dealer-car strong{font-size:16px}.dealer-car p{font-size:11px}.dealer-empty{padding:25px 3px}.dealer-empty h3{font-size:20px}.dealer-empty p{font-size:12px}.dealer-about-text{font-size:13px}.dealer-market-pills{gap:7px;margin-right:-18px;padding-right:18px}.dealer-market-pills button{padding:9px 12px;font-size:11px}.dealer-catalog-search{margin-top:12px}.dealer-catalog-search input{font-size:12px}.dealer-catalog-search button{font-size:11px;padding:8px 12px}.dealer-pagination{font-size:10px}.dealer-pagination button{padding:10px}.dealer-dock{bottom:calc(12px + env(safe-area-inset-bottom));width:calc(100% - 24px);max-width:500px;padding:6px;gap:2px;border-radius:25px}.dealer-dock>a,.dealer-dock>button{min-height:52px;border-radius:19px;font-size:9px;gap:5px}.dealer-dock svg{width:23px;height:23px}.dealer-info-dialog{width:100%;max-width:none;max-height:90dvh;margin:auto 0 0;border-radius:30px 30px 0 0}.dealer-dialog-content{padding:12px 22px calc(24px + env(safe-area-inset-bottom))}.dealer-dialog-handle{display:block;height:5px;width:42px;border-radius:9px;background:var(--ac-border);margin:0 auto 20px}.dealer-dialog-content>header{padding-bottom:20px}.dealer-dialog-content h2{font-size:21px}}
@media(prefers-reduced-motion:reduce){.dealer-profile *{scroll-behavior:auto!important}}
.dealer-profile-body{display:block}.dealer-tab-content{padding:0;background:transparent;border:0;border-radius:0}.dealer-profile .dealer-shared-catalog{background:transparent!important;padding-top:0!important}.dealer-expand{display:inline-flex;align-items:center;gap:6px;min-height:40px}.dealer-city-chips>span{display:inline-flex;align-items:center;gap:8px}.dealer-dock{display:none}
@media(min-width:768px){.dealer-profile{padding-bottom:32px}body:has(.dealer-profile) .ac-public-legal-footer{padding-bottom:30px}}
@media(max-width:767px){.dealer-tab-content{padding:0 16px}.dealer-dock{display:flex;bottom:0;left:0;transform:none;width:100%;max-width:none;padding:8px 8px calc(8px + env(safe-area-inset-bottom));border-radius:24px 24px 0 0;box-shadow:none}.dealer-profile{padding-bottom:85px}}

/* Centered identity follows the supplied dealer profile reference. */
.dealer-profile-identity>.dealer-desktop-request{display:flex;width:fit-content;margin:14px auto 0}
.dealer-profile-identity{--dealer-logo-cutout:56px;padding:20px 28px 24px;margin-top:-56px;background:transparent;box-shadow:none;isolation:isolate}
/* Cut only the sheet background: the real cover remains visible around the logo. */
.dealer-profile-identity:before{content:'';position:absolute;inset:0;z-index:-1;pointer-events:none;border-radius:inherit;background:var(--ac-surface);-webkit-mask-image:radial-gradient(circle at 50% 0,transparent var(--dealer-logo-cutout),#000 calc(var(--dealer-logo-cutout) + 1px));mask-image:radial-gradient(circle at 50% 0,transparent var(--dealer-logo-cutout),#000 calc(var(--dealer-logo-cutout) + 1px))}
.dealer-identity-row{display:block;position:relative;text-align:center}
.dealer-identity-row>.dealer-avatar-centered{display:grid;position:absolute;left:50%;top:-66px;transform:translateX(-50%);width:92px;height:92px;border-radius:50%;border:3px solid var(--ac-surface);background:var(--ac-surface-2,var(--ac-surface));padding:5px;z-index:2;overflow:hidden}
.dealer-avatar-centered img{border-radius:50%;object-fit:contain}
.dealer-profile-metrics{display:grid;grid-template-columns:1fr 1fr;gap:120px;min-height:64px;max-width:620px;margin:0 auto 16px}
.dealer-profile-metrics button{display:flex;flex-wrap:wrap;justify-content:center;align-content:start;align-items:center;gap:4px 8px;min-height:52px}
.dealer-profile-metrics svg{color:#eab308}.dealer-profile-metrics button:last-child svg{color:var(--ac-muted)}
.dealer-profile-metrics strong{font-size:22px;font-weight:750;line-height:1.2}.dealer-profile-metrics span{flex-basis:100%;font-size:14px;color:var(--ac-muted)}
.dealer-identity-divider{display:flex;align-items:center;gap:16px;color:var(--ac-muted);font-size:14px;margin-bottom:10px}
.dealer-identity-divider:before,.dealer-identity-divider:after{content:'';flex:1;border-top:1px dashed var(--ac-border)}
.dealer-title-line{display:flex;justify-content:center;align-items:center;gap:8px}
.dealer-identity-info{position:absolute;right:0;bottom:0}
.dealer-identity-title h1{font-size:28px;line-height:1.3;padding:0 32px}
.dealer-intro-wrap{text-align:center;margin:10px auto 0;max-width:840px}.dealer-intro{font-size:16px;line-height:1.65;margin:0 auto}.dealer-expand{font-size:14px;min-height:40px}
.dealer-profile-tabs{max-width:740px;margin:14px auto 20px;background:var(--ac-surface);padding:7px;gap:6px}
.dealer-profile-tabs button{font-size:16px;min-height:44px;padding:10px 16px}.dealer-profile-tabs button[aria-pressed=true]{background:#d8c1c155;color:var(--ac-text)}
.dealer-profile-body{margin-top:0}.dealer-profile .dealer-stories{margin:0 0 20px;padding:0;border:0}.dealer-stories h2{display:block;font-size:18px;margin:0 0 12px}
.dealer-profile .dealer-stories .ac-buyers-rail{padding:0;gap:12px}.dealer-profile .dealer-stories .ac-buyers-rail>button{height:128px;width:128px}
.dealer-contact-sheet{padding:24px;max-width:900px;margin:0 auto}.dealer-contact-sheet .dealer-office-select{margin-top:0}.dealer-contact-sheet .dealer-office-select label,.dealer-dialog-content .dealer-office-select label{font-size:14px}.dealer-contact-sheet select,.dealer-dialog-content select{font-size:16px;padding-top:5px}
.dealer-map-link{display:flex;justify-content:center;align-items:center;gap:8px;margin:12px 0 18px;border:1px solid var(--ac-border);border-radius:16px;padding:12px;font-size:16px;font-weight:700}
.dealer-profile .dealer-office-hours small{font-size:14px}.dealer-profile .dealer-office-hours{font-size:16px}
.dealer-profile .dealer-about-text{font-size:16px}.dealer-profile .dealer-eyebrow{font-size:12px}.dealer-profile .dealer-muted{font-size:14px}
.dealer-reviews{padding:32px;text-align:center;max-width:740px;margin:0 auto}.dealer-reviews>svg{margin:0 auto 16px;color:var(--ac-muted)}.dealer-reviews h2{font-size:24px;font-weight:750}.dealer-reviews p{margin:12px auto 0;max-width:520px;line-height:1.65;font-size:16px}
.dealer-requisites{font-size:14px;line-height:1.65;overflow-wrap:anywhere}.dealer-requisites h3{font-size:16px;font-weight:700;margin:0 0 10px}.dealer-requisites p{margin-bottom:8px}.dealer-requisites dl{display:grid;gap:5px}.dealer-requisites dl>div{display:flex;gap:8px;flex-wrap:wrap}.dealer-requisites dt{color:var(--ac-muted)}.dealer-requisites dd{margin:0}
.dealer-contact-sheet>.dealer-requisites,.dealer-dialog-content>.dealer-requisites{margin-top:24px;padding-top:20px;border-top:1px dashed var(--ac-border)}
.dealer-profile-footer{margin-top:28px;padding:24px 0;border-top:1px solid var(--ac-border)}.dealer-profile-footer:has(>.dealer-requisites:empty){display:none}.dealer-profile-footer:not(:has(.dealer-requisites)){display:none}
@media(max-width:800px){
 .dealer-profile-identity>.dealer-desktop-request{display:none}
 .dealer-profile-identity{--dealer-logo-cutout:44px;padding:16px 24px 22px;margin-top:-44px}.dealer-identity-row>.dealer-avatar-centered{top:-52px;width:72px;height:72px;border-width:3px;padding:3px}
 .dealer-profile-metrics{gap:88px;margin-bottom:12px;min-height:54px}.dealer-profile-metrics strong{font-size:20px}.dealer-profile-metrics span{font-size:12px}.dealer-profile-metrics svg{width:17px;height:17px}
 .dealer-identity-title h1{font-size:22px;padding:0 24px}.dealer-identity-divider{font-size:14px;gap:14px;margin-bottom:8px}.dealer-intro{font-size:15px;line-height:1.6}.dealer-intro-wrap{margin-top:10px}.dealer-expand{font-size:14px}
 .dealer-profile-tabs{margin:12px 20px 18px;padding:5px;gap:3px}.dealer-profile-tabs button{font-size:14px;padding:10px 8px;min-height:44px}
 .dealer-profile .dealer-stories .ac-buyers-rail>button{width:108px;height:110px}.dealer-profile .dealer-stories .ac-buyers-rail{gap:10px}.dealer-stories h2{font-size:16px}
 .dealer-contact-sheet{padding:20px;border-radius:26px}.dealer-reviews{padding:28px 20px;border-radius:26px}.dealer-reviews h2{font-size:22px}.dealer-reviews p{font-size:15px}.dealer-profile-footer{margin:24px 20px 0;padding:20px 0}
}

/* Keep the cover visible around the circular avatar. */
.dealer-profile-hero picture{display:block}.dealer-cover{height:auto;aspect-ratio:4/1;object-fit:cover}
.dealer-avatar-face{display:grid;place-items:center;width:100%;height:100%;min-width:0;min-height:0}.dealer-avatar-face>img{grid-area:1/1;width:100%;height:100%;object-fit:contain}.dealer-avatar-face>span{font-size:24px}
.dealer-avatar-centered:focus-visible{filter:drop-shadow(0 0 3px #699de8)}
.dealer-title-line{display:block;text-align:center}.dealer-identity-title h1{padding:0;margin:0;text-align:center}
.dealer-profile-metrics span{white-space:nowrap}.dealer-profile-metrics{gap:120px}
.dealer-intro-wrap{position:relative;text-align:left;max-width:none;margin-top:10px}.dealer-intro-wrap.can-expand{padding-right:32px}.dealer-intro{max-width:none;text-align:left;margin:0;line-height:1.6;overflow-wrap:anywhere}.dealer-intro-wrap .dealer-expand{position:absolute;right:0;bottom:0;display:grid;place-items:center;width:32px;height:32px;min-height:32px;margin:0;border-radius:50%}.dealer-expand:hover{background:var(--ac-surface-2)}
.dealer-contact-details{display:flex;align-items:center;gap:6px;font-size:13px;color:var(--ac-muted);margin:0 0 16px auto}
.dealer-logo-dialog{border:1px solid var(--ac-border);padding:48px 28px 28px;border-radius:28px;width:min(520px,calc(100vw - 32px));max-height:90dvh;overflow:auto;margin:auto;color:var(--ac-text);background:var(--ac-surface)}.dealer-logo-dialog::backdrop{background:#07111eaa;backdrop-filter:blur(5px)}body:has(.dealer-logo-dialog[open]){overflow:hidden}.dealer-logo-close{position:absolute;right:12px;top:12px;display:grid;place-items:center;width:36px;height:36px;border-radius:50%;background:var(--ac-surface-2)}.dealer-logo-preview{display:grid;place-items:center;min-height:180px;aspect-ratio:1;max-height:55dvh}.dealer-logo-preview img{grid-area:1/1;object-fit:contain;width:100%;height:100%;min-height:0}.dealer-logo-preview>span{font-size:64px;font-weight:800}.dealer-logo-dialog h2{text-align:center;font-size:22px;font-weight:750;margin-top:16px;overflow-wrap:anywhere}.dealer-logo-verified{display:flex;justify-content:center;align-items:center;gap:8px;color:#10b981;font-size:15px;margin-top:12px}
@media(max-width:800px){.dealer-cover{height:auto;aspect-ratio:4/3}.dealer-profile-metrics{gap:88px}.dealer-intro{font-size:15px;line-height:1.6}}

/* The cover stays behind the independent profile sheet during page scroll. */
.dealer-profile{padding-top:0!important;position:relative;isolation:isolate}
.dealer-profile-hero{position:sticky;top:var(--dealer-header-height,0px);z-index:0}
.dealer-cover-open{display:block;width:100%;padding:0;border:0;text-align:inherit;cursor:zoom-in}
.dealer-profile-sheet{position:relative;z-index:2;margin-top:-56px;isolation:isolate;min-height:65vh}
.dealer-profile-sheet:before{content:'';position:absolute;inset:56px 0 0;background:var(--ac-bg,var(--ac-page-bg));z-index:-1}
.dealer-profile-sheet>.dealer-profile-identity{margin-top:0}
.dealer-default-logo{filter:grayscale(1);opacity:.5;width:70%!important;height:70%!important}
.dealer-avatar-face{background:var(--ac-surface-2)}
.dealer-intro-wrap.can-expand{padding-right:0}.dealer-profile .dealer-intro{display:block;overflow:visible;max-height:none;-webkit-line-clamp:unset}
.dealer-profile .dealer-intro .dealer-expand{position:static;display:inline-flex;width:28px;height:24px;min-height:24px;vertical-align:middle;align-items:center;justify-content:center;margin:0;padding:0;border:0;background:transparent}
.dealer-profile .dealer-photo-grid{display:block;width:100%;min-width:0}.dealer-photo-grid>section{width:100%;margin:20px 0;overflow:visible}.dealer-profile .dealer-photo-grid .ac-buyers-rail{width:100%;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;padding:0}.dealer-profile .dealer-photo-grid .ac-buyers-rail>button{width:100%;height:auto;aspect-ratio:1;min-width:0;border-radius:12px}.dealer-photo-grid h2{white-space:normal;font-size:20px;line-height:1.3}
.dealer-banner-dots{position:absolute;top:14px;left:50%;transform:translateX(-50%);display:flex;z-index:2;gap:0;padding:0 4px;border-radius:40px;background:#14202f55;backdrop-filter:blur(18px)}.dealer-banner-dots button{width:28px;height:28px;display:grid;place-items:center}.dealer-banner-dots span{width:7px;height:7px;border-radius:50%;background:#ffffff70}.dealer-banner-dots button[aria-pressed=true] span{background:#fff;width:9px;height:9px}
.dealer-banner-dialog{margin:auto;padding:48px 16px 16px;border:0;width:min(1200px,96vw);max-height:94dvh;border-radius:24px;background:var(--ac-surface);color:var(--ac-text);overflow:auto}.dealer-banner-dialog::backdrop{background:#07111eaa;backdrop-filter:blur(10px)}.dealer-banner-full{display:block;max-height:76dvh;width:100%;object-fit:contain}.dealer-banner-controls{display:flex;justify-content:center;gap:24px;align-items:center;margin-top:12px}.dealer-banner-controls button{padding:12px;border-radius:50%;background:var(--ac-surface-2)}body:has(.dealer-banner-dialog[open]){overflow:hidden}
.dealer-media-banners{position:relative;overflow:hidden;border-radius:20px;margin-top:12px}.dealer-media-cover-section{margin:24px 0}.dealer-media-cover-section h3{font-size:18px;font-weight:750}
.dealer-reviews-panel{max-width:780px;margin:0 auto;padding:28px;border-radius:28px;background:linear-gradient(135deg,#5097e52b,#b18cce26);}.dealer-reviews-panel>header{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:24px}.dealer-reviews-panel h2{font-size:24px;font-weight:800}.dealer-rating-summary{display:grid;grid-template-columns:auto auto;gap:4px 8px;align-items:center;flex-shrink:0}.dealer-rating-summary strong{font-size:30px}.dealer-rating-summary span{grid-column:1/-1;font-size:12px;color:var(--ac-muted)}.dealer-welcome-review{padding:24px;background:var(--ac-surface);border-radius:24px}.dealer-welcome-heading{display:flex;gap:12px;align-items:center;margin-bottom:20px}.dealer-welcome-heading>div{flex:1;min-width:0}.dealer-welcome-heading strong,.dealer-welcome-heading div>span{display:block}.dealer-welcome-heading div>span{font-size:12px;color:var(--ac-muted);margin-top:4px}.dealer-welcome-heading>svg{color:#10b981}.dealer-welcome-logo{display:grid;place-items:center;width:48px;height:48px;background:var(--ac-surface-2);border-radius:14px;overflow:hidden}.dealer-welcome-logo img{grid-area:1/1;width:100%;height:100%;object-fit:contain}.dealer-welcome-review h3{font-size:21px;font-weight:750;margin-bottom:8px}.dealer-welcome-review p{font-size:16px;line-height:1.65}.dealer-review-eligibility{padding:24px 0 0;text-align:center;font-size:14px;line-height:1.65;color:var(--ac-muted)}.dealer-review-eligibility>div{display:flex;justify-content:center;gap:10px;margin-bottom:16px}.dealer-review-eligibility svg{fill:#8ca3bd30;stroke:#8ca3bd70;width:30px;height:30px}
body:has(.dealer-profile) .ac-public-footer-tools{max-width:360px;gap:10px;padding:16px 0!important}body:has(.dealer-profile) .ac-public-footer-navigation{padding:0 0 16px!important}
@media(max-width:800px){.dealer-profile-sheet{margin-top:-44px}.dealer-profile-sheet:before{top:44px}.dealer-profile-tabs{gap:0;margin:12px 12px 18px}.dealer-profile-tabs button{font-size:13px;padding:10px 5px}.dealer-reviews-panel{padding:20px 16px}.dealer-reviews-panel h2{font-size:20px}.dealer-welcome-review{padding:20px}.dealer-welcome-review p{font-size:15px}.dealer-banner-dots{top:14px;left:16px;transform:none}.dealer-profile .dealer-profile-metrics svg{width:24px;height:24px}
body:has(.dealer-profile) .ac-public-header{background:color-mix(in srgb,var(--ac-surface) 72%,transparent)!important;background-color:color-mix(in srgb,var(--ac-surface) 72%,transparent)!important;-webkit-backdrop-filter:blur(18px) saturate(130%)!important;backdrop-filter:blur(18px) saturate(130%)!important}}

.dealer-profile-actions{display:grid;align-items:start;grid-template-columns:1fr 1fr;gap:12px;margin:14px auto 22px;max-width:740px}.dealer-profile-actions>button,.dealer-subscription-control>button{display:flex;width:100%;align-items:center;justify-content:center;gap:10px;min-height:48px;padding:10px 18px;border-radius:50px;background:var(--ac-surface);font-size:14px;font-weight:700}.dealer-subscription-control>button[aria-pressed=true]{color:#ed3d53;background:#ed3d5318}.dealer-subscription-control>button:disabled{opacity:.6}.dealer-subscription-control strong{font-size:12px;min-width:22px;padding:2px 6px;border-radius:20px;background:var(--ac-surface-2)}.dealer-subscription-control p,.dealer-action-status{font-size:12px;color:var(--ac-muted);text-align:center;margin-top:8px}
.dealer-identity-divider>span{display:flex;flex-direction:column;align-items:center;gap:6px}.dealer-verified-mark{color:#10b981}.dealer-profile .dealer-intro[role=button]{cursor:pointer}.dealer-profile .dealer-intro[role=button]:focus-visible{outline:2px solid #699de8;outline-offset:4px;border-radius:8px}
.dealer-main-offers{scroll-margin-top:90px}.dealer-profile-footer{margin-top:20px;padding:16px 0}.dealer-profile-sheet{min-height:0}.dealer-profile:not(.dealer-drawer-content){padding-bottom:0!important}
.dealer-drawer-content{max-width:none!important;padding:20px 20px calc(24px + env(safe-area-inset-bottom))!important;isolation:auto}.dealer-drawer-content .dealer-contact-sheet{padding:0;border-radius:0}.dealer-drawer-content .dealer-media-cover-section{margin:0 0 16px}.dealer-drawer-content .dealer-photo-grid>section{margin:16px 0}.dealer-drawer-content .dealer-reviews-panel{padding:20px 16px}.dealer-drawer-content .dealer-stories{display:none}
@media(min-width:768px){.dealer-dock{display:none;position:static;transform:none;width:min(680px,100%);margin:22px auto;box-shadow:none;border:0;padding:6px;background:var(--ac-surface)}.dealer-profile .dealer-intro-wrap{max-width:840px;margin:12px auto 0}.dealer-profile .dealer-intro{text-align:left!important}}
@media(max-width:767px){.dealer-profile-actions{margin:12px 16px 20px;gap:10px}.dealer-profile-actions>button,.dealer-subscription-control>button{font-size:13px;padding:10px 12px;gap:8px}.dealer-profile-footer{margin:16px 20px 0;padding:12px 0}.dealer-drawer-content{padding:16px 16px calc(24px + env(safe-area-inset-bottom))!important}}

.dealer-profile-metrics{margin-bottom:0;min-height:56px}
.dealer-identity-row>.dealer-avatar-centered{padding:0}
.dealer-avatar-centered .dealer-avatar-face{padding:0;overflow:hidden;border-radius:inherit}
.dealer-avatar-centered .dealer-avatar-face>img{object-fit:contain;object-position:center;min-width:0;min-height:0}
.dealer-avatar-centered .dealer-avatar-face>.dealer-default-logo{object-fit:contain;padding:10px}
@media(max-width:800px){.dealer-profile-metrics{min-height:46px;margin-bottom:0}.dealer-profile-metrics button{min-height:46px}}

.dealer-avatar-centered .dealer-avatar-face{background:var(--ac-surface)}
.dealer-identity-row>.dealer-avatar-centered{border-color:rgb(32 39 51 / .5)}
html[data-theme=light] .dealer-identity-row>.dealer-avatar-centered{border-color:rgb(255 255 255 / .5)}
html[data-theme] body .dealer-profile-actions>button{background:#00a5dc;color:#fff;-webkit-text-fill-color:#fff}
html[data-theme] body .dealer-subscription-control>button,html[data-theme] body .dealer-subscription-control>button[aria-pressed=true]{background:#ed3d5318;color:#ed233a;-webkit-text-fill-color:#ed233a}
.dealer-subscription-control strong{background:transparent}
.dealer-profile .dealer-intro,.dealer-profile .dealer-expand{transition:none!important;animation:none!important;touch-action:manipulation}
`;
