'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Building2,Inbox,CreditCard,PanelsTopLeft,Plus,Search,ArrowUpRight,BookOpen,Globe} from 'lucide-react';
import {DealerWorkspaceStyles} from './DealerWorkspaceStyles';
import {Field,Toggle,button,input} from './DealerEditorFields';
import type {PublicFeatures} from '@/lib/dealers/showcase-store';
import {dealerAccessLevel,type DealerProgram,type Membership} from '@/lib/dealers/program-model';
export async function programAction(body:unknown){const r=await fetch('/api/crm/dealer-program',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'Не удалось сохранить');return data;}
const statusLabel=(s:string)=>({verified:'Подтверждён',active:'Подключение',paused:'Приостановлен',new:'Новая',contacted:'В работе',approved:'Принята',rejected:'Отклонена'}[s]||s);
export function DealerPlatformManager({dealers,applications,initialProgram,initialFeatures}:{dealers:any[];applications:any[];initialProgram:DealerProgram;initialFeatures:PublicFeatures}){
 const [tab,setTab]=useState('companies'),[q,setQ]=useState(''),[p,setP]=useState(initialProgram),[apps,setApps]=useState(applications),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[creating,setCreating]=useState(false),[name,setName]=useState(''),[city,setCity]=useState('');
 async function act(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();setMessage('Изменения сохранены');}catch(e){setMessage(e instanceof Error?e.message:'Ошибка сохранения');}finally{setBusy(false);}}
 const rows=dealers.filter(d=>`${d.name} ${d.city}`.toLowerCase().includes(q.toLowerCase()));
 return <div className="dealer-workspace"><DealerWorkspaceStyles/><header className="dw-header"><div><p className="dw-eyebrow">Управление платформой</p><h2 className="dw-title">Партнёры АвтоЦены</h2><p className="dw-muted">Подключение партнёров и условия работы в одном разделе.</p></div><Link href="/crm/dealers/dealer_topavto" className="dw-primary">Кабинет ТопАвто <ArrowUpRight size={17}/></Link></header>
 <nav className="dw-tabs" aria-label="Управление дилерами">{[['companies','Компании',Building2],['applications','Заявки',Inbox],['program','Тарифы и доступ',CreditCard]].map(([id,label,Icon]:any)=><button key={id} aria-selected={tab===id} onClick={()=>{setTab(id);setMessage('');}}><Icon size={16} className="inline mr-2"/>{label}{id==='applications'&&apps.some(a=>a.status==='new')&&<span className="ml-2 text-red-500">{apps.filter(a=>a.status==='new').length}</span>}</button>)}<Link href="/crm/reviews" className={button}>Отзывы</Link></nav>
 {message&&<p role="status" className="mb-4 rounded-xl bg-[var(--ac-surface-2)] p-3 text-sm">{message}</p>}
 {tab==='companies'&&<><div className="flex flex-wrap gap-3 mb-5 justify-between"><label className="flex items-center gap-2"><Search size={18}/><input className="dw-input" aria-label="Поиск компании" placeholder="Компания или город" value={q} onChange={e=>setQ(e.target.value)}/></label><button className={button+' flex items-center gap-2'} onClick={()=>setCreating(!creating)}><Plus size={17}/> Добавить компанию</button></div>{creating&&<form className="dw-card mb-5" onSubmit={e=>{e.preventDefault();void act(async()=>{const r=await programAction({action:'create',name,city});window.location.assign(`/crm/dealers/${r.id}`);});}}><h2>Новая компания</h2><div className="dw-form-grid mt-4"><Field label="Название" value={name} onChange={setName}/><Field label="Город" value={city} onChange={setCity}/></div><button disabled={busy||!name||!city} className="dw-primary mt-4">Создать кабинет</button></form>}
 <div className="dw-grid">{rows.map(d=><Link key={d.id} href={`/crm/dealers/${d.id}`} className="dw-card hover:border-red-400 transition-colors"><div className="flex items-center justify-between gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-red-500/10 text-red-500"><Building2 size={24}/></span><span className="dw-badge">{d.id==='dealer_topavto'?'Владелец платформы':statusLabel(d.status)}</span></div><h2 className="mt-5">{d.name}</h2><p className="dw-muted mt-1">{d.city||'Город не указан'}</p><div className="dw-row mt-3"><span className="text-sm">{d.id==='dealer_topavto'?'Все возможности без подписки':d.accessLabel}</span><ArrowUpRight size={19}/></div><p className="dw-muted">Страница · Автомобили · Доступ</p></Link>)}</div>{!rows.length&&<p className="dw-empty">Компании не найдены</p>}</>}
 {tab==='applications'&&<section className="dw-card"><h2>Заявки на сотрудничество</h2><p className="dw-muted mt-2">Дилеры и поставщики. Принятие заявки не открывает доступ к данным — создайте компанию и подтвердите её сотрудника отдельно.</p>{apps.length?apps.map(a=><article key={a.id} className="dw-row"><div className="min-w-0"><strong>{a.companyName}</strong><p className="dw-muted">{a.partnerType==='supplier'?'Поставщик':'Дилер'} · {[a.country,a.city].filter(Boolean).join(', ')} · {a.contactName}</p><p className="text-sm mt-1">{a.phone} {a.email} {a.telegram}</p><p className="dw-muted">{a.markets}</p></div><select disabled={busy} aria-label={`Статус заявки ${a.companyName}`} className={input+' !w-auto'} value={a.status} onChange={e=>void act(async()=>{const updated=await programAction({action:'application',id:a.id,status:e.target.value});setApps(rows=>rows.map(x=>x.id===a.id?updated:x));})}>{['new','contacted','approved','rejected'].map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></article>):<p className="dw-empty">Заявки появятся здесь после отправки заявки из каталога дилеров или страницы партнёров.</p>}</section>}
 {tab==='program'&&<div className="space-y-5"><section className="dw-card"><p className="dw-eyebrow">Полный доступ</p><h2 className="mt-2">Один набор возможностей. Три периода.</h2><p className="dw-muted mt-2">Первый пробный период начинается при подтверждении компании или сотрудника. Повторное подтверждение не запускает его заново. По окончании остаётся базовый каталог.</p><div className="dw-form-grid mt-5">{[['trialDays','Пробный период, дней'],['monthRub','1 месяц, ₽'],['halfYearRub','6 месяцев, ₽'],['yearRub','1 год, ₽'],['commissionPercent','Комиссия с продажи по заявке АвтоЦены, %']].map(([k,l])=><Field key={k} label={l} type="number" value={(p as any)[k]} onChange={v=>setP({...p,[k]:v})}/>)}<label>База комиссии<select className={input} value={p.commissionBasis} onChange={e=>setP({...p,commissionBasis:e.target.value as DealerProgram['commissionBasis']})}><option value="sale">Стоимость проданного автомобиля</option><option value="remuneration">Вознаграждение дилера по сделке</option></select><small>Этот выбор показывается в условиях партнёрам. Начисленные комиссии сохраняют прежние условия.</small></label></div><button disabled={busy} className="dw-primary mt-5" onClick={()=>void act(async()=>setP(await programAction({action:'program',value:p})))}>Сохранить условия</button></section><section className="dw-card"><h2>Что происходит после пробного месяца</h2><div className="dw-form-grid mt-4"><div><h3>Базовый доступ · без подписки</h3><p className="dw-muted mt-2">Общий каталог АвтоЦены, выбор направлений, информация компании и адреса. Комиссия по продажам из наших заявок сохраняется.</p></div><div><h3>Полный доступ</h3><p className="dw-muted mt-2">Собственные автомобили, фотографии выдач, расширенное оформление страницы и настройки расчёта своих предложений.</p></div></div><p className="dw-muted mt-5">Оплату подтверждает владелец в карточке компании. Автоматического списания денег нет. ТопАвто работает без подписки.</p></section></div>}
 </div>;
}
