'use client';
import {useState} from 'react';
import {Star} from 'lucide-react';
export function DealerReviewCard({review,dealerId,dealerName,canReply,canDelete,onChanged}:{review:any;dealerId:string;dealerName:string;canReply:boolean;canDelete:boolean;onChanged:()=>void}){
 const [editing,setEditing]=useState(false),[text,setText]=useState(review.reply?.text||''),[reply,setReply]=useState(review.reply),[busy,setBusy]=useState(false),[error,setError]=useState(''),[avatarFailed,setAvatarFailed]=useState(false),[deleted,setDeleted]=useState(false);
 if(deleted)return null;
 async function remove(){if(busy||!confirm('Удалить опубликованный отзыв и его оценку?'))return;setBusy(true);setError('');try{const response=await fetch('/api/account/review-moderation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',dealerId,reviewId:review.id})});if(!response.ok)throw Error('Не удалось удалить отзыв.');setDeleted(true);onChanged();}catch(e){setError(e instanceof Error?e.message:'Ошибка соединения.');}finally{setBusy(false);}}
 return <article className="dealer-welcome-review dealer-customer-review"><div className="dealer-review-author-row"><span className="dealer-review-avatar">{review.avatarUrl&&!avatarFailed?<img src={review.avatarUrl} alt="" onError={()=>setAvatarFailed(true)}/>:String(review.author||'П').slice(0,1).toUpperCase()}</span><strong>{review.author}</strong><span className="dealer-review-score" aria-label={`Оценка ${review.rating} из 5`}>{review.rating}<Star size={20}/></span></div><p className="dealer-review-text">{review.text}</p><div className="dealer-review-footer"><time dateTime={review.createdAt}>{new Date(review.createdAt).toLocaleDateString('ru-RU')}</time>{canReply&&<button type="button" disabled={busy} onClick={()=>{setEditing(v=>!v);setError('');}}>{editing?'Отмена':reply?'Изменить ответ':'Ответить'}</button>}{canDelete&&<button type="button" disabled={busy} onClick={()=>void remove()}>Удалить</button>}</div>
 {reply&&!editing&&<div className="dealer-review-reply"><strong>Ответ {dealerName}</strong><p className="dealer-review-text">{reply.text}</p><time dateTime={reply.createdAt}>{new Date(reply.createdAt).toLocaleDateString('ru-RU')}</time></div>}
 {editing&&canReply&&<form className="dealer-review-reply-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch(`/api/dealers/${encodeURIComponent(dealerId)}/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:review.id,text})});const data=await response.json();if(!response.ok)throw Error(data.error||'Не удалось сохранить ответ.');setReply(data.reply);setText(data.reply.text);setEditing(false);onChanged();}catch(e){setError(e instanceof Error?e.message:'Ошибка соединения.');}finally{setBusy(false);}}}><label>Ответ компании<textarea aria-label="Ответ компании" value={text} onChange={e=>setText(e.target.value)} required minLength={3} maxLength={3000} disabled={busy} placeholder="Напишите ответ клиенту…"/></label><button type="submit" disabled={busy}>{busy?'Сохраняем…':'Опубликовать ответ'}</button></form>}{error&&<p role="alert">{error}</p>}
 </article>;
}
