'use client';
import {useState} from 'react';
import {DealerAccessEditor} from './DealerAccessEditor';
import {Field,Toggle,input,button} from './DealerEditorFields';
import {DEALER_MAIL_PROVIDERS} from '@/lib/dealer-mail';
import {programAction} from './DealerPlatformManager';
import {dealerAccessLevel,type Membership,type DealerProgram} from '@/lib/dealers/program-model';
export function DealerCompanyControls({dealer,initialMembership,program,initialSales,completedLeads=[]}:{dealer:any;initialMembership:Membership;program:DealerProgram;initialSales:any[];completedLeads?:{id:string;label:string}[]}){
 const [m,setM]=useState(initialMembership),[status,setStatus]=useState(dealer.status),[channel,setChannel]=useState(dealer.telegramChannel||''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[months,setMonths]=useState(1),[amount,setAmount]=useState(program.monthRub),[note,setNote]=useState(''),[leadId,setLeadId]=useState(''),[saleAmount,setSaleAmount]=useState(0),[sales,setSales]=useState(initialSales),[mail,setMail]=useState(dealer.mail||{email:'',provider:'',ready:false});
 const level=dealerAccessLevel(dealer.id,m);
 async function act(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();setMessage('Сохранено');}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <div className="space-y-5"><section className="dealer-editor-panel"><h2 className="text-xl font-bold">Статус и подключение</h2><div className="dw-form-grid mt-5"><label>Статус компании<select className={input} disabled={dealer.id==='dealer_topavto'} value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Подключение</option><option value="verified">Подтверждена</option><option value="paused">Приостановлена</option></select></label><Field label="Telegram-канал компании" value={channel} onChange={setChannel}/></div><p className="dw-muted mt-3">Для фотоленты добавьте бота АвтоЦены администратором указанного канала без права публикации. Телефон и прямые контакты не выводятся в публичном профиле.</p><details className="mt-5"><summary className="cursor-pointer text-sm font-bold">Почта компании</summary><div className="dw-form-grid mt-4"><Field label="Адрес почты" value={mail.email} onChange={v=>setMail({...mail,email:v})}/><label>Почтовый сервис<select className={input} value={mail.provider} onChange={e=>setMail({...mail,provider:e.target.value})}><option value="">Не выбран</option>{Object.entries(DEALER_MAIL_PROVIDERS).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label></div><div className="mt-3"><Toggle label="Почтовый ящик подключён" value={mail.ready} onChange={v=>setMail({...mail,ready:v})}/></div><p className="dw-muted mt-2">Укажите уже созданный рабочий ящик. Пароль здесь не хранится.</p></details><button className={button+' mt-4'} disabled={busy} onClick={()=>void act(async()=>{await programAction({action:'company',dealerId:dealer.id,status,telegramChannel:channel,mail});})}>Сохранить подключение</button></section>
 {dealer.id!=='dealer_topavto'&&<section className="dealer-editor-panel"><h2 className="text-xl font-bold">Подписка компании</h2><p className="dw-muted mt-2">{level.full?`Полный доступ до ${new Date(level.until).toLocaleDateString('ru-RU')}`:'Базовый доступ'}</p>{!m.trialStartedAt&&<button className={button+' mt-3'} disabled={busy} onClick={()=>void act(async()=>setM(await programAction({action:'trial',dealerId:dealer.id})))}>Начать пробные {program.trialDays} дней</button>}<div className="dw-form-grid mt-5"><label>Оплаченный период<select className={input} value={months} onChange={e=>{const n=Number(e.target.value);setMonths(n);setAmount(n===1?program.monthRub:n===6?program.halfYearRub:program.yearRub);}}><option value={1}>1 месяц</option><option value={6}>6 месяцев</option><option value={12}>1 год</option></select></label><Field label="Полученная сумма, ₽" type="number" value={amount} onChange={setAmount}/><Field label="Основание: платёж, счёт или договор" value={note} onChange={setNote}/></div><button disabled={busy||!note} className="dw-primary mt-4" onClick={()=>{if(confirm('Подтвердить полученную оплату и продлить доступ компании?'))void act(async()=>{setM(await programAction({action:'membership',dealerId:dealer.id,version:m.version,months,amountRub:amount,note}));setNote('');});}}>Подтвердить оплату и продлить</button><p className="dw-muted mt-3">Период добавляется после текущего доступа. Это учёт уже полученной оплаты, без списания денег.</p>{m.history.map(h=><div className="dw-row text-sm" key={h.id}><span>{new Date(h.at).toLocaleDateString('ru-RU')} · {h.months} мес. · {h.note}</span><strong>{h.amountRub.toLocaleString('ru-RU')} ₽</strong></div>)}</section>}
 <section className="dealer-editor-panel"><h2 className="text-xl font-bold">Сотрудники и права</h2><DealerAccessEditor dealerId={dealer.id}/></section>
 {dealer.id!=='dealer_topavto'&&<section className="dealer-editor-panel"><h2 className="text-xl font-bold">Комиссии по продажам</h2><p className="dw-muted mt-2">{program.commissionPercent}% {program.commissionBasis==='sale'?'от цены проданного автомобиля':'от вознаграждения дилера'}. Начисление только по завершённой заявке АвтоЦены этой компании. Сумму подтверждает владелец.</p><div className="dw-form-grid mt-4"><label>Завершённая заявка<select className={input} value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">{completedLeads.length?"Выберите сделку":"Нет завершённых сделок для начисления"}</option>{completedLeads.filter(l=>!sales.some(s=>s.leadId===l.id)).map(l=><option key={l.id} value={l.id}>{l.label}</option>)}</select></label><Field label={program.commissionBasis==='sale'?'Цена продажи, ₽':'Вознаграждение дилера, ₽'} value={saleAmount} type="number" onChange={setSaleAmount}/></div><p className="dw-muted mt-3">К начислению: {Math.round(saleAmount*program.commissionPercent/100).toLocaleString('ru-RU')} ₽</p><button className={button+' mt-3'} disabled={busy||!leadId||saleAmount<=0} onClick={()=>void act(async()=>{await programAction({action:'sale',dealerId:dealer.id,leadId,amountRub:saleAmount});window.location.reload();})}>Подтвердить начисление</button>{sales.map(s=><div className="dw-row text-sm" key={s.id}><div><strong>{s.commissionRub.toLocaleString('ru-RU')} ₽</strong><p className="dw-muted">{s.leadId} · {s.percent}% · {s.status==='paid'?'Оплачено':'К оплате'}</p></div>{s.status!=='paid'&&<button className={button} disabled={busy} onClick={()=>{if(confirm('Подтвердить получение комиссии?'))void act(async()=>{await programAction({action:'settle',dealerId:dealer.id,saleId:s.id});setSales(rows=>rows.map(x=>x.id===s.id?{...x,status:'paid'}:x));});}}>Отметить оплату</button>}</div>)}</section>}
 {message&&<p role="status" className="dealer-editor-panel text-sm">{message}</p>}</div>;
}
