'use client';
import {useEffect,useState} from 'react';
import type {DealerTelegram} from '@/lib/dealers/telegram-settings';
export function DealerTelegramSettings({dealerId,demo=false}:{dealerId:string;demo?:boolean}){
 const [value,setValue]=useState<DealerTelegram|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(demo)return;let active=true;fetch(`/api/dealers/${dealerId}/telegram`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setValue(d);}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false};},[dealerId,demo]);
 async function save(enabled:boolean){if(!value)return;setBusy(true);setMessage('');try{const r=await fetch(`/api/dealers/${dealerId}/telegram`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...value,enabled})});const data=await r.json();if(!r.ok)throw Error(data.error);setValue(data);setMessage(enabled?'Группа проверена и подключена':'Уведомления в группе отключены');}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <section className="dealer-editor-panel space-y-5"><h2 className="text-2xl font-black">Telegram компании</h2><p className="text-sm text-[var(--ac-muted)]">В эту группу поступают заявки, адресованные вашей компании. Заявки сохраняются в кабинете, даже если группа не подключена.</p><ol className="list-decimal space-y-2 pl-5 text-sm"><li>Создайте закрытую группу и добавьте <a className="underline" href="https://t.me/avtocena_bot" target="_blank" rel="noreferrer">@avtocena_bot</a> с правом отправлять сообщения.</li><li>Укажите ID группы и её точное название.</li><li>Нажмите «Проверить и подключить». Проверка не отправляет сообщений в группу.</li></ol>{demo?<p>В демо подключение Telegram не выполняется.</p>:value?<><p className="font-bold">{value.enabled?'Уведомления включены':'Уведомления отключены'}</p><label className="grid gap-2 text-sm">ID группы<input className="soft-input rounded-xl p-3" placeholder="-100…" value={value.chatId} onChange={e=>setValue({...value,chatId:e.target.value})}/></label><label className="grid gap-2 text-sm">Название группы<input className="soft-input rounded-xl p-3" maxLength={128} value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label><div className="flex flex-wrap gap-3"><button disabled={busy} className="dw-primary" onClick={()=>void save(true)}>{busy?'Проверяем…':'Проверить и подключить'}</button>{value.enabled&&<button disabled={busy} className="dw-secondary" onClick={()=>void save(false)}>Отключить</button>}</div><p className="text-xs text-[var(--ac-muted)]">Кабинет компании и владелец платформы видят заявки. Копия в чужую группу не отправляется.</p></>:!message?<p>Загружаем настройки…</p>:null}<p role="status" className="text-sm">{message}</p></section>;
}
