"use client";
import {useEffect,useRef,useState} from 'react';
import {DealerLink as Link} from './DealerBrowsingContext';
import {CatalogMarketFlag} from '@/components/catalog/CatalogMarketFlag';
import {ChevronDown,ChevronUp,ArrowUpRight,ArrowRight} from 'lucide-react';
import type {PublicDealerProfile} from '@/lib/dealers/public-profile';
import {DEALER_MARKETS} from '@/lib/dealers/catalog-markets';
import type {SpecialRailItem} from './SpecialRail';
import {BuyerGallery} from '@/components/home/BuyerGallery';
import {DealerMap} from './DealerMap';
import {dealerProfileStyles} from './DealerProfileStyles';
import {yandexOfficeUrls} from '@/lib/dealers/yandex-map';
type Tab='cars'|'specials'|'about'|'photos';
function Icon({name}:{name:string}){
 const paths:Record<string,React.ReactNode>={home:<><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/></>,cars:<><path d="m5 6-2 7v6h3v-2h12v2h3v-6l-2-7Z"/><path d="M3 12h18M7 15h1m8 0h1"/></>,photos:<><rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8" cy="8" r="1"/><path d="m3 17 6-6 4 4 3-3 5 5"/></>,pin:<><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,message:<><path d="M21 11a8 8 0 0 1-8 8H7l-5 3 1.5-6A8 8 0 1 1 21 11Z"/><path d="M8 10h8m-8 4h5"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/></>,heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0l-1 1-1-1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>,share:<><path d="M12 16V3m-4 4 4-4 4 4M5 12v8h14v-8"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>};
 return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.info}</svg>;
}
export function DealerProfileContent({s,preview=false,items=[],catalog}:{s:PublicDealerProfile;preview?:boolean;items?:SpecialRailItem[];catalog?:React.ReactNode}){
 const [tab,setTab]=useState<Tab>('cars'),[expanded,setExpanded]=useState(false),[favorite,setFavorite]=useState(false),[shareStatus,setShareStatus]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),body=useRef<HTMLElement>(null),top=useRef<HTMLDivElement>(null);
 const [officeId,setOfficeId]=useState(s.offices[0]?.id||'');
 const office=s.offices.find(o=>o.id===officeId)||s.offices[0];
 const cities=[...new Set(s.offices.map(o=>o.city).filter(Boolean))];
 const photos=s.buyersEnabled?s.buyerPhotos:[];
 const request=`/request?dealer=${encodeURIComponent(s.dealerId)}`;
 useEffect(()=>{const navigate=()=>{if(location.hash==='#cars'||location.hash==='#photos'){setTab(location.hash==='#cars'?'cars':'photos');requestAnimationFrame(()=>body.current?.scrollIntoView({block:'start'}));}if(location.hash==='#offices')dialog.current?.showModal();};navigate();window.addEventListener('hashchange',navigate);return()=>window.removeEventListener('hashchange',navigate);},[]);
 useEffect(()=>{const openCatalog=()=>{setTab('cars');requestAnimationFrame(()=>body.current?.scrollIntoView({block:'start'}));};window.addEventListener('avtocena:dealer-section',openCatalog);return()=>window.removeEventListener('avtocena:dealer-section',openCatalog);},[]);
 useEffect(()=>{try{setFavorite(localStorage.getItem(`ac-dealer-favorite-${s.dealerId}`)==='1');}catch{}},[s.dealerId]);
 function toggleFavorite(){const value=!favorite;setFavorite(value);try{localStorage.setItem(`ac-dealer-favorite-${s.dealerId}`,value?'1':'0');}catch{}}
 function section(value:Tab){setTab(value);requestAnimationFrame(()=>body.current?.scrollIntoView({behavior:'smooth',block:'start'}));}
 function openOffice(){dialog.current?.showModal();}
 async function share(){try{const url=new URL(location.href);url.search='';url.hash='';if(navigator.share)await navigator.share({title:s.name,url:url.toString()});else{await navigator.clipboard.writeText(`${s.name}\n${url}`);setShareStatus('Ссылка скопирована');}}catch(e){if((e as Error).name!=='AbortError')setShareStatus('Не удалось поделиться ссылкой');}}
 return <div ref={top} className="dealer-profile mx-auto w-full max-w-[1500px] px-4 pt-4 md:px-8">
  {preview&&<p className="dealer-preview-note">Предпросмотр · {s.profileEnabled?'Страница опубликована':'Страница пока скрыта от посетителей'}</p>}
  <div className="dealer-profile-hero">{s.banner?<img src={s.banner} alt={`Обложка ${s.name}`} className="dealer-cover" fetchPriority="high"/>:<div className="dealer-cover dealer-cover-empty"/>}<span className="dealer-cover-label">На АвтоЦене</span><div className="dealer-cover-actions"><button type="button" aria-label="Поделиться страницей компании" onClick={()=>void share()}><Icon name="share"/></button><button type="button" aria-label={favorite?'Убрать компанию из избранного':'Сохранить компанию'} aria-pressed={favorite} onClick={toggleFavorite}><Icon name="heart"/></button></div>{shareStatus&&<p className="dealer-share-status" role="status">{shareStatus}</p>}</div>
  <section className="dealer-profile-identity dealer-sheet">
   <div className="dealer-identity-row"><div className="dealer-avatar">{s.logoLight||s.logoDark?<><img src={s.logoLight||s.logoDark} alt="" className="dealer-logo-light"/><img src={s.logoDark||s.logoLight} alt="" className="dealer-logo-dark"/></>:<span>{s.name.slice(0,2)}</span>}</div><div className="dealer-identity-title"><h1>{s.name}</h1><button type="button" className="dealer-address-link" onClick={openOffice}>{office?[office.city,office.address].filter(Boolean).join(', '):'Информация о компании'}</button>{office?.hours&&<button type="button" className="dealer-hours" onClick={openOffice}><Icon name="clock"/>{office.hours}<ChevronDown size={18}/></button>}</div><button type="button" className="dealer-info-button" aria-label="Информация о компании" onClick={openOffice}><Icon name="info"/></button><Link href={request} className="dealer-primary dealer-desktop-request">Подобрать автомобиль</Link></div>
   {photos.length>0&&<div className="dealer-stories"><BuyerGallery title="Наши покупатели" dealerName={s.name} images={photos.map(p=>p.url)} autoScroll={false}/></div>}
   {s.description&&<div className="dealer-intro-wrap"><p className={`dealer-intro ${expanded?'is-expanded':''}`}>{s.description}</p>{s.description.length>140&&<button type="button" className="dealer-expand" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Свернуть':'Подробнее'} {expanded?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>}</div>}
   <nav className="dealer-profile-tabs" aria-label="Разделы профиля">{([['cars','Каталог'],['specials','Предложения'],['photos','Фото'],['about','О компании']] as const).map(([id,label])=><button key={id} type="button" aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}{id==='specials'&&items.length>0&&<span>{items.length}</span>}</button>)}</nav>
  </section>
  <div className="dealer-profile-body"><section ref={body} className="dealer-tab-content" aria-label={tab==='cars'?'Каталог АвтоЦены':tab==='specials'?'Предложения дилера':tab==='photos'?'Фотографии компании':'О компании'}>
   <div hidden={tab!=='cars'}>{catalog}</div>
   {tab==='specials'&&<><div className="dealer-section-heading"><div><p className="dealer-eyebrow">От {s.name}</p><h2>Предложения компании</h2></div></div>{items.length?<>{(["order","stock"] as const).map(kind=>{const group=items.filter(o=>(o.availability||"order")===kind);return group.length?<section key={kind}><p className="dealer-muted">{group[0].heading|| (kind==="stock"?"Автомобили в наличии":s.specialHeading)}</p><div className="dealer-cars-grid">{group.map(o=><Link key={o.id} href={o.href} className="dealer-car"><img src={o.image} alt={o.title} loading="lazy"/><div><p className="dealer-muted">{o.availability==="stock"?`В наличии · ${o.condition==="used"?"С пробегом":"Новый"}`:"Под заказ"}</p><h3>{o.title}</h3><strong>{o.price===null?'Цена уточняется':`${o.price.toLocaleString('ru-RU')} ₽`}</strong><p>{[o.city,o.address].filter(Boolean).join(", ")}{o.daysFrom?` · ${o.daysFrom}–${o.daysTo} дней`:''}</p></div></Link>)}</div></section>:null;})}</>:<div className="dealer-empty"><Icon name="cars"/><h3>Подберём под ваши пожелания</h3><p>У компании пока нет отдельных предложений. Посмотрите автомобили по её направлениям доставки или оставьте заявку на подбор.</p><button type="button" className="dealer-primary" onClick={()=>setTab('cars')}>Перейти к каталогу</button></div>}</>}
   {tab==='about'&&<><p className="dealer-eyebrow">Знакомство</p><h2>{s.name}</h2><p className="dealer-about-text">{s.description||'Компания пока не добавила описание.'}</p>{s.catalogMarkets.length>0&&<><h3 className="dealer-small-heading">Направления доставки</h3><div className="dealer-city-chips">{DEALER_MARKETS.filter(m=>s.catalogMarkets.includes(m.id)).map(m=><span key={m.id}><CatalogMarketFlag market={m.id}/> {m.label}</span>)}</div></>}{cities.length>0&&<><h3 className="dealer-small-heading">Наши офисы</h3><div className="dealer-profile-offices">{s.offices.map(o=><button type="button" key={o.id} onClick={()=>{setOfficeId(o.id);openOffice();}}><Icon name="pin"/><span><strong>{o.city}</strong><span>{o.address}</span>{o.hours&&<small>{o.hours}</small>}</span><ArrowUpRight size={18}/></button>)}</div></>}</>}
   {tab==='photos'&&<><p className="dealer-eyebrow">Знакомство в фотографиях</p><h2>Жизнь компании</h2>{photos.length>0?<div className="dealer-photo-grid"><BuyerGallery title="Наши покупатели" dealerName={s.name} images={photos.map(p=>p.url)} autoScroll={false}/></div>:<p className="dealer-about-text dealer-muted">Фотографии покупателей появятся здесь после публикации компанией.</p>}{s.offices.some(o=>o.photos.length>0)&&<BuyerGallery title="Наши офисы" dealerName={s.name} images={s.offices.flatMap(o=>o.photos.map(p=>p.url))} autoScroll={false}/>}</>}
  </section></div>
  <nav className="dealer-dock" aria-label="Быстрое меню дилера"><button type="button" onClick={()=>top.current?.scrollIntoView({behavior:'smooth'})}><Icon name="home"/><span>Главная</span></button><button type="button" aria-pressed={tab==='cars'||tab==='specials'} onClick={()=>section('cars')}><Icon name="cars"/><span>Авто</span></button><button type="button" aria-pressed={tab==='photos'} onClick={()=>section('photos')}><Icon name="photos"/><span>Фото</span></button><button type="button" onClick={openOffice}><Icon name="pin"/><span>Адреса</span></button><Link href={request} className="dealer-dock-request"><Icon name="message"/><span>Заявка</span></Link></nav>
  <dialog ref={dialog} className="dealer-info-dialog" onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}>
   <div className="dealer-dialog-content"><div className="dealer-dialog-handle"/><header><div><p className="dealer-eyebrow">Информация о компании</p><h2>{s.name}</h2></div><button type="button" className="dealer-info-button" aria-label="Закрыть информацию" onClick={()=>dialog.current?.close()}><Icon name="close"/></button></header>
   {s.offices.length>0?<><div className="dealer-office-select"><Icon name="pin"/><label>Адрес офиса<select aria-label="Адрес офиса" value={office?.id} onChange={e=>setOfficeId(e.target.value)}>{s.offices.map(o=><option key={o.id} value={o.id}>{o.city}, {o.address}</option>)}</select></label></div>{office?.hours&&<div className="dealer-office-hours"><Icon name="clock"/><span><small>Режим работы</small>{office.hours}</span></div>}<DealerMap compact offices={s.offices} selectedId={office?.id} onSelect={setOfficeId}/>{office&&<a className="dealer-primary dealer-route-button" href={yandexOfficeUrls(office).full} target="_blank" rel="noreferrer">Построить маршрут <ArrowUpRight size={18}/></a>}</>:<p className="dealer-about-text">Компания пока не добавила адреса офисов.</p>}
   <p className="dealer-dialog-note">Для подбора автомобиля оставьте заявку через АвтоЦену.</p><Link className="dealer-dialog-request" href={request}>Оставить заявку <ArrowRight size={18}/></Link></div>
  </dialog>
  <style>{dealerProfileStyles}</style>
 </div>;
}
