"use client";
import {useEffect,useState} from 'react';
import {Heart} from 'lucide-react';
import {changeDealerSubscription,readDealerSubscriptions,saveDealerSubscription,type DealerSubscription} from '@/lib/dealers/subscriptions-client';
import type {PublicDealerProfile} from '@/lib/dealers/public-profile';
export function DealerSubscriptionButton({s,preview=false}:{s:PublicDealerProfile;preview?:boolean}){
 const [active,setActive]=useState(false),[count,setCount]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const value=():DealerSubscription=>({version:1,dealerId:s.dealerId,name:s.name,href:`/dealers/${encodeURIComponent(s.dealerId)}`,logoLight:s.logoLight,logoDark:s.logoDark,subscribedAt:readDealerSubscriptions().find(x=>x.dealerId===s.dealerId)?.subscribedAt||new Date().toISOString(),notifications:{company:false,application:false,vehicle:false}});
 useEffect(()=>{if(preview){setCount(0);return;}let alive=true;const sync=()=>{fetch(`/api/dealers/${encodeURIComponent(s.dealerId)}/subscription`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{if(!alive||typeof data.count!=='number')return;setActive(data.subscribed);setCount(data.count);if(data.subscribed)saveDealerSubscription(value(),true);}).catch(()=>{if(alive)setError('Не удалось загрузить подписку. Обновите страницу.');});};sync();window.addEventListener('storage',sync);return()=>{alive=false;window.removeEventListener('storage',sync);};},[s.dealerId,preview]);
 async function toggle(){if(preview){setError('Подписаться можно на странице компании.');return;}setBusy(true);setError('');try{const data=await changeDealerSubscription(value(),!active);setActive(data.subscribed);setCount(data.count);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="dealer-subscription-control"><button type="button" aria-label={active?'Отписаться от дилера':'Подписаться на дилера'} aria-pressed={active} disabled={busy||count===null} onClick={()=>void toggle()}><Heart size={20} fill={active?'currentColor':'none'}/><span>{active?'Вы подписаны':'Подписаться'}</span><strong aria-label="Подписчиков">{count===null?'—':count.toLocaleString('ru-RU')}</strong></button>{error&&<p role="status">{error}</p>}</div>;
}
export function SubscribedDealers(){const [items,setItems]=useState<DealerSubscription[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');useEffect(()=>{const sync=()=>setItems(readDealerSubscriptions());sync();window.addEventListener('avtocena:favorites-changed',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('avtocena:favorites-changed',sync);window.removeEventListener('storage',sync);};},[]);if(!items.length)return null;return <section className="ac-subscribed-dealers mt-8"><h2 className="text-2xl font-black">Подписки на дилеров</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(d=><article key={d.dealerId} className="flex items-center gap-3 rounded-2xl bg-[var(--ac-surface)] p-4"><a href={d.href} className="flex min-w-0 flex-1 items-center gap-3"><img src={d.logoLight||d.logoDark||'/logo/avtocena-mark-dark.svg'} alt="" className="h-12 w-12 rounded-xl object-contain"/><strong>{d.name}</strong></a><button type="button" disabled={!!busy} className="rounded-xl p-3 text-red-500" aria-label={`Отписаться от ${d.name}`} onClick={async()=>{setBusy(d.dealerId);try{await changeDealerSubscription(d,false);}catch(e){setError((e as Error).message);}finally{setBusy('');}}}><Heart size={20} fill="currentColor"/></button></article>)}</div>{error&&<p role="alert">{error}</p>}</section>;}
