'use client';
import {PARTNER_CONSENT_VERSION} from '@/lib/privacy-documents';
import Link from 'next/link';
import {useState} from 'react';
import {Building2,CheckCircle2,MapPin,Search} from 'lucide-react';
import {PublicHeader} from '@/components/layout/PublicHeader';
import {DealerLogo} from './DealerLogo';
export type DirectoryDealer={id:string;name:string;description:string;logoLight:string;logoDark:string;banner?:string;bannerMobile?:string;href:string;cities:string[];verified:boolean};
const normalize=(s:string)=>s.trim().toLocaleLowerCase('ru').replaceAll('ё','е');
export function DealerDirectory({dealers}:{dealers:DirectoryDealer[]}){
 const [city,setCity]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 const visible=dealers.filter(d=>!normalize(city)||d.cities.some(c=>normalize(c).includes(normalize(city))));
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const body=new FormData(e.currentTarget);body.set('source','dealer_directory');body.set('country','Россия');body.set('partnerType','dealer');try{const r=await fetch('/api/dealers/apply',{method:'POST',body,headers:{Accept:'application/json'}});if(!r.ok)throw Error();setSent(true);}catch{setError('Не удалось отправить заявку. Попробуйте ещё раз.');}finally{setBusy(false);}}
 return <main className="ac-page-copy min-h-screen bg-[var(--ac-page-bg)] text-[var(--ac-text)]"><PublicHeader backHref="/favorites" backLabel="В избранное"/><div className="mx-auto max-w-6xl px-4 py-10 md:px-8"><header className="flex flex-wrap items-start justify-between gap-6"><div><span className="rounded-full bg-red-500/10 px-3 py-1 text-xs font-bold text-red-500">Бета-версия</span><h1 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Автодилеры</h1><p className="mt-4 max-w-xl text-[var(--ac-muted)]">Найдите компанию в своём городе. Пока с нами Топ Авто — каталог постепенно пополняется.</p></div><a href="#dealer-apply" className="avto-button rounded-2xl px-5 py-4 font-bold">Подать заявку</a></header>
 <section className="mt-8" aria-label="Поиск дилеров"><label className="flex items-center gap-3 rounded-2xl border border-[var(--ac-border)] bg-[var(--ac-surface)] p-4"><Search size={20}/><input aria-label="Поиск по городу" placeholder="Поиск по городу" value={city} onChange={e=>setCity(e.target.value)} className="min-w-0 flex-1 bg-transparent outline-none"/>{city&&<button onClick={()=>setCity('')} type="button" className="text-sm font-bold">Сбросить</button>}</label><p className="my-5 text-sm text-[var(--ac-muted)]" role="status">Найдено компаний: {visible.length}</p><div className="grid gap-4 md:grid-cols-2">{visible.map(d=><Link key={d.id} href={d.href} className="dealer-directory-card overflow-hidden rounded-3xl border border-[var(--ac-border)] bg-[var(--ac-surface)]"><picture><source media="(max-width: 640px)" srcSet={d.bannerMobile||d.banner||'/dealers/topavto-banner-v3.webp'}/><img src={d.banner||'/dealers/topavto-banner-v3.webp'} alt="" className="aspect-[2.6/1] w-full object-cover"/></picture><div className="relative -mt-5 rounded-t-3xl bg-[var(--ac-surface)] px-5 pb-5 pt-4"><div className="flex items-center gap-3"><span className="h-12 w-12 shrink-0 md:h-16 md:w-16"><DealerLogo {...d}/></span><div className="min-w-0 flex-1"><h2 className="break-words text-xl font-black leading-tight md:text-2xl">{d.name}</h2>{d.verified&&<span className="mt-1 flex items-center gap-1 text-xs text-green-600"><CheckCircle2 size={14} className="shrink-0"/>Проверенный дилер</span>}</div></div>{d.description&&<p className="mt-4 line-clamp-2 text-sm text-[var(--ac-muted)]">{d.description}</p>}<p className="mt-4 flex items-start gap-2 text-sm"><MapPin size={16} className="shrink-0"/>{d.cities.join(' · ')||'Город уточняется'}</p><span className="mt-4 inline-block text-sm font-bold">Открыть профиль</span></div></Link>)}</div>{!visible.length&&<div className="rounded-3xl bg-[var(--ac-surface)] p-8 text-center"><Building2 className="mx-auto mb-3"/><h2 className="text-xl font-bold">В этом городе пока нет дилеров</h2><p className="mt-2 text-[var(--ac-muted)]">Попробуйте другой город или посмотрите все компании.</p><button type="button" onClick={()=>setCity('')} className="mt-4 font-bold text-red-500">Все компании</button></div>}</section>
 <section id="dealer-apply" className="mt-12 grid scroll-mt-24 gap-8 rounded-3xl border border-[var(--ac-border)] bg-[var(--ac-surface)] p-6 md:grid-cols-2 md:p-8"><div><Building2 size={30} className="text-red-500"/><h2 className="mt-4 text-3xl font-black">Ваша компания в АвтоЦене</h2><p className="mt-4 text-[var(--ac-muted)]">Оставьте заявку на подключение. Мы свяжемся с вами, расскажем о сервисе и поможем оформить профиль дилера.</p></div>{sent?<div role="status" className="self-center"><CheckCircle2 className="mb-4 text-green-500" size={36}/><h3 className="text-xl font-bold">Заявка отправлена</h3><p className="mt-2 text-[var(--ac-muted)]">Спасибо! Мы свяжемся с вами по указанному контакту.</p></div>:<form onSubmit={submit} className="grid gap-4">{[['companyName','Название компании','organization'],['city','Город','address-level2'],['contactName','Как к вам обращаться','name'],['contact','Телефон или электронная почта','']].map(([name,label,complete])=><label key={name} className="grid gap-2 text-sm font-bold">{label}<input name={name} required maxLength={180} autoComplete={complete||undefined} className="w-full rounded-xl border border-[var(--ac-border)] bg-[var(--ac-surface-2)] p-3"/></label>)}<div hidden><input name="website" tabIndex={-1} autoComplete="off"/></div><label className="flex items-start gap-3 text-xs text-[var(--ac-muted)]"><input type="hidden" name="consentVersion" value={PARTNER_CONSENT_VERSION}/><input type="checkbox" name="consent" value="yes" required className="mt-1"/><span>Даю <Link href="/consent/partner" target="_blank" className="underline">согласие на обработку заявки о сотрудничестве</Link>. <Link href="/privacy" target="_blank" className="underline">Политика</Link>.</span></label><button disabled={busy} className="avto-button rounded-2xl p-4 font-bold">{busy?'Отправляем…':'Подать заявку'}</button>{error&&<p role="alert" className="text-sm text-red-500">{error}</p>}</form>}</section><footer className="mt-10 flex flex-wrap justify-between gap-4 pb-8 text-sm text-[var(--ac-muted)]"><Link href="/cars">Каталог автомобилей</Link><Link href="/privacy">Конфиденциальность</Link></footer></div></main>;
}
