'use client';
import {MapPin,Navigation,Plus,Trash2} from 'lucide-react';
import {useState} from 'react';
import {DealerDeliveryCity} from './DealerDeliveryCity';
import {Field,Toggle,button} from './DealerEditorFields';
import {estimateDealerDelivery} from '@/lib/dealers/delivery-estimate';
import {normalizeCitySearch} from '@/lib/location/cities';
import type {DealerShowcase,DeliveryTariff} from '@/lib/dealers/showcase-model';
export function DealerDeliveryEditor({value,city,onCityChange,onChange,defaultDestination=false}:{value:DealerShowcase['pricing'];city:string;onCityChange:(city:string)=>void;onChange:(v:Partial<DealerShowcase['pricing']>)=>void;defaultDestination?:boolean}){
 const [draft,setDraft]=useState<{city:string;usd:number}|null>(null);
 const estimate=estimateDealerDelivery(value.originCity||'Бишкек',city,value.tariffs,value.distancePricing);
 const current=value.tariffs.find(t=>normalizeCitySearch(t.city)===normalizeCitySearch(city));
 const others=value.tariffs.filter(t=>t!==current);
 function edit(id:string,patch:Partial<DeliveryTariff>){onChange({tariffs:value.tariffs.map(t=>t.id===id?{...t,...patch}:t)});}
 function exact(usd:number){if(!city.trim())return;const next=current?{...current,usd}:{id:crypto.randomUUID(),city:city.trim(),usd,daysFrom:estimate?.daysFrom||5,daysTo:estimate?.daysTo||10};onChange({tariffs:current?value.tariffs.map(t=>t.id===current.id?next:t):[...value.tariffs,next]});}
 return <div className="dealer-delivery-editor">
  <div className="dealer-pricing-heading"><div><h4>Маршрут и доставка</h4><p className="dealer-pricing-note">Точный тариф в долларах · тот же курс, что и для автомобиля</p></div><button type="button" className="dealer-route-add" aria-label="Добавить город доставки" title="Добавить город с точным тарифом" onClick={()=>setDraft({city:'',usd:0})}><Plus size={19}/><span>Добавить город</span></button></div>
  <div className="dealer-route"><div className="dealer-route-point"><MapPin size={20}/><DealerDeliveryCity label="Откуда" value={value.originCity||'Бишкек'} onChange={originCity=>onChange({originCity})}/></div><div className="dealer-route-path" aria-hidden="true"><span/><Navigation size={17}/><span/></div><div className="dealer-route-point"><MapPin size={20}/><DealerDeliveryCity label={defaultDestination?'Куда по умолчанию':'Куда'} value={city} onChange={onCityChange}/></div><label className="dealer-route-price grid gap-1 text-sm">Доставка, $<input aria-label="Доставка, $" className="soft-input w-full min-w-0 rounded-xl px-3 py-2 text-sm" type="number" min="0" step="any" disabled={!city.trim()} value={estimate?.usd??current?.usd??''} placeholder="Точный тариф" onChange={e=>exact(Number(e.target.value))}/></label></div>
  <p className="dealer-pricing-note">{estimate?`${estimate.estimated?'Ориентировочно':'По тарифу'}: ${estimate.usd.toLocaleString('ru-RU')} $ · ${estimate.daysFrom}–${estimate.daysTo} дней`:'Укажите город и точный тариф доставки.'}{estimate?.estimated?' Чтобы закрепить точную цену, укажите стоимость выше.':''}</p>
  {current&&<div className="dealer-delivery-days"><Field label="От, дней" type="number" value={current.daysFrom} onChange={daysFrom=>edit(current.id,{daysFrom})}/><Field label="До, дней" type="number" value={current.daysTo} onChange={daysTo=>edit(current.id,{daysTo})}/></div>}
  {others.length>0&&<div className="dealer-delivery-anchors"><h5>Точные тарифы в другие города</h5>{others.map(t=><div className="dealer-delivery-anchor" key={t.id}><MapPin size={18}/><DealerDeliveryCity label="Город" value={t.city} onChange={city=>edit(t.id,{city})}/><Field label="Доставка, $" type="number" value={t.usd} onChange={usd=>edit(t.id,{usd})}/><Field label="От, дней" type="number" value={t.daysFrom} onChange={daysFrom=>edit(t.id,{daysFrom})}/><Field label="До, дней" type="number" value={t.daysTo} onChange={daysTo=>edit(t.id,{daysTo})}/><button type="button" className={button+' dealer-tariff-delete'} aria-label={`Удалить тариф ${t.city||'без города'}`} onClick={()=>onChange({tariffs:value.tariffs.filter(x=>x.id!==t.id)})}><Trash2 size={17}/></button></div>)}</div>}
  {draft&&<div className="dealer-tariff-draft"><DealerDeliveryCity label="Новый город доставки" value={draft.city} onChange={city=>setDraft({...draft,city})}/><Field label="Точный тариф, $" type="number" value={draft.usd} onChange={usd=>setDraft({...draft,usd})}/><button type="button" className={button} disabled={!draft.city.trim()||draft.usd<=0||!Number.isFinite(draft.usd)||value.tariffs.some(t=>normalizeCitySearch(t.city)===normalizeCitySearch(draft.city))} onClick={()=>{onChange({tariffs:[...value.tariffs,{id:crypto.randomUUID(),city:draft.city.trim(),usd:draft.usd,daysFrom:5,daysTo:10}]});setDraft(null);}}>Добавить тариф</button><button type="button" className={button} onClick={()=>setDraft(null)}>Отмена</button><p className="dealer-pricing-note">Укажите город и цену перевозчика. Срок по умолчанию 5–10 дней можно изменить после добавления.</p></div>}
  <Toggle label="Оценивать доставку в другие города по расстоянию" value={value.distancePricing===true} onChange={distancePricing=>onChange({distancePricing})}/>
  <p className="dealer-pricing-note">Тарифы сохраняются для всей компании. Два города с точными ценами дают ориентир для остальных направлений. Оценка по расстоянию между городами требует подтверждения перевозчика.</p>
 </div>;
}
