'use client';
import {useEffect,useState} from 'react';
import {DealerWorkspaceStyles} from './DealerWorkspaceStyles';
import {invoiceBalance,type BillingBook} from '@/lib/dealers/billing/model';
const money=(v:number)=>(v/100).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})+' ₽';
const blank={leadId:'',documentId:'',contractNumber:'',car:'',year:'',vin:'',total:'',deposit:'',commission:'',other:'',excluded:'',exclusionReason:'',dealerTax:'Не указан',version:0};
export function DealerBilling({initialDealer='',owner=false}:{initialDealer?:string;owner?:boolean}){
 const [dealer,setDealer]=useState(initialDealer),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[period,setPeriod]=useState(''),[status,setStatus]=useState('all'),[q,setQ]=useState(''),[form,setForm]=useState(blank),[email,setEmail]=useState(''),[months,setMonths]=useState(1),[preview,setPreview]=useState(''),[tax,setTax]=useState(''),[taxBasis,setTaxBasis]=useState(''),[bank,setBank]=useState({invoiceId:'',amount:'',reference:''});
 async function load(){const r=await fetch('/api/dealers/billing'+(owner&&!dealer?'?all=1':dealer?'?dealer='+encodeURIComponent(dealer):''),{cache:'no-store'});const b=await r.json();if(!r.ok)throw Error(b.error);setData(b);setTax(b.config?.tax===null?'':String(b.config?.tax??''));setTaxBasis(b.config?.taxBasis||'');}
 useEffect(()=>{setData(null);setForm(blank);setError('');void load().catch(e=>setError(e.message));},[dealer]);
 async function action(body:any){setBusy(true);setError('');try{const r=await fetch('/api/dealers/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,dealerId:dealer||data?.dealerId})});const b=await r.json();if(!r.ok)throw Error(b.error);if(b.url){location.assign(b.url);return;}await load();if(body.action==='spec')setForm(blank);if(body.action==='bank')setBank({invoiceId:'',amount:'',reference:''});if(b.status)setError(b.status==='paid'?'Оплата подтверждена':b.status==='test_succeeded'?'Тестовая оплата успешна; деньги и доступ не начислены':b.status==='canceled'?'Платёж отменён':'Платёж ещё не подтверждён');}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить операцию');}finally{setBusy(false);}}
 useEffect(()=>{if(!preview)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setPreview('');};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[preview]);
 const book:BillingBook|undefined=data?.book,charges=(book?.charges||[]).filter(c=>(!period||c.period===period)&&`${c.car} ${c.contractNumber} ${c.vin}`.toLowerCase().includes(q.toLowerCase())),invoices=(book?.invoices||[]).filter(i=>(!period||i.period===period)&&(status==='all'||(status==='paid'?invoiceBalance(book!,i)<=0:invoiceBalance(book!,i)>0)));
 const selectLead=(id:string)=>{const s=book?.specs.find(s=>s.leadId===id),l=data.candidates.find((l:any)=>l.id===id);setForm(s?{leadId:id,documentId:s.documentId,contractNumber:s.contractNumber,car:s.car,year:String(s.year),vin:s.vin,total:String(s.totalMinor/100),deposit:String(s.depositMinor/100),commission:String(s.commissionMinor/100),other:s.otherMinor?String(s.otherMinor/100):'',excluded:s.excludedMinor?String(s.excludedMinor/100):'',exclusionReason:s.exclusionReason,dealerTax:s.dealerTax,version:s.version}:{...blank,leadId:id,car:l?.title==='Автомобиль по заказу'?'':l?.title||'',commission:l?.suggestedCommission===undefined?'':String(l.suggestedCommission)});};
 return <div className="dealer-workspace"><DealerWorkspaceStyles/><div className="dw-header"><div><h1 className="dw-title">Взаиморасчёты</h1><p className="dw-muted">Тариф, договоры, комиссия АвтоЦены и документы</p></div></div>{error&&<p className="dw-card mb-4" role="status">{error}</p>}{!data?<p>Загружаем расчёты…</p>:<>
 {owner&&<label className="block mb-5">Компания<select className="dw-input" value={dealer} onChange={e=>setDealer(e.target.value)}><option value="">Все компании</option>{data.companies?.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
 <div className="dw-form-grid mb-5"><label>Месяц<input className="dw-input" type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><label>Автомобиль или договор<input className="dw-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Поиск"/></label><label>Счета<select className="dw-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Все</option><option value="due">К оплате</option><option value="paid">Оплачены / зачтены</option></select></label></div>
 {owner&&<details className="dw-card mb-5"><summary className="cursor-pointer font-bold">НДС АвтоЦены</summary><p className="dw-muted my-3">Настройка относится к услугам ИП Молодых А. В., а не к стоимости автомобилей и налогам дилеров. Уже выпущенные счета не пересчитываются.</p><div className="dw-form-grid"><select className="dw-input" aria-label="Ставка НДС" value={tax} onChange={e=>setTax(e.target.value)}><option value="">Не подтверждён</option><option value="none">Без НДС</option>{[0,5,7,10,22].map(n=><option key={n} value={n}>{n}%</option>)}</select><input className="dw-input" aria-label="Основание налогового режима" placeholder="Подтверждённое основание и дата применения" value={taxBasis} onChange={e=>setTaxBasis(e.target.value)}/></div><button className="dw-primary mt-3" disabled={busy||!tax||!taxBasis} onClick={()=>void action({action:'tax',version:data.config.version,tax:tax==='none'?tax:Number(tax),taxBasis})}>Подтвердить налоговые настройки</button></details>}
 {data.overview&&<div className="space-y-3">{data.overview.map((r:any)=>{const ch=r.charges.filter((c:any)=>(!period||c.period===period)&&`${c.car} ${c.contractNumber}`.toLowerCase().includes(q.toLowerCase())),iv=r.invoices.filter((i:any)=>(!period||i.period===period)&&(status==='all'||(status==='paid'?i.balance<=0:i.balance>0)));return <button key={r.id} className="dw-card w-full text-left" onClick={()=>setDealer(r.id)}><strong>{r.name}</strong><div className="dw-form-grid mt-2"><span>Договоров: {ch.filter((c:any)=>!c.reverses).length}</span><span>Начислено: {money(ch.reduce((a:number,c:any)=>a+c.amountMinor,0))}</span><span>Остаток по счетам: {money(iv.reduce((a:number,i:any)=>a+i.balance,0))}</span></div></button>;})}</div>}
 {book&&<>
 <div className="dw-grid mb-5">{[['Договоров',String(charges.filter(c=>!c.reverses).length)],['Начислено',money(charges.reduce((a,c)=>a+c.amountMinor,0))],['Остаток по счетам',money(invoices.reduce((a,i)=>a+invoiceBalance(book,i),0))]].map(([label,value])=><div key={label} className="dw-card"><p className="dw-muted">{label}</p><strong className="dw-stat">{value}</strong></div>)}</div>
 <details className="dw-card mb-5"><summary className="cursor-pointer font-bold">Оплатить тариф</summary><div className="dw-form-grid mt-4"><label>Период<select className="dw-input" value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={1}>1 месяц — 10 000 ₽</option><option value={6}>6 месяцев — 50 000 ₽</option><option value={12}>12 месяцев — 100 000 ₽</option></select></label><label>Email для чека<input className="dw-input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div><p className="dw-muted my-3">Комиссия по новым заявкам при подписке — 10%. Автоматических списаний нет. {data.paymentTest?'Включён тестовый режим: доступ за тестовый платёж не продлевается.':''}</p><button className="dw-primary" disabled={busy||!data.paymentReady||!email} onClick={()=>void action({action:'pay',kind:'subscription',months,email})}>{data.paymentReady?'Перейти к защищённой оплате':'Онлайн-оплата пока не подключена'}</button><a className="block underline mt-3" href="/dealer-cabinet/terms">Тариф и условия работы</a></details>
 <details className="dw-card mb-5"><summary className="cursor-pointer font-bold">Автомобиль и расчёт договора</summary><p className="dw-muted my-3">Подходит и для машины вне каталога. Сохраните расчёт до подтверждения договора клиентом. Не включайте одну сумму одновременно в обеспечительный взнос и комиссию.</p><form onSubmit={e=>{e.preventDefault();void action({action:'spec',...form,other:form.other||'0',excluded:form.excluded||'0'});}}><div className="dw-form-grid"><label>Заявка<select className="dw-input" required value={form.leadId} onChange={e=>selectLead(e.target.value)}><option value="">Выберите заявку</option>{data.candidates.map((l:any)=><option key={l.id} value={l.id}>{l.title} · {l.id}</option>)}</select></label><label>Прикреплённый договор<select required className="dw-input" value={form.documentId} onChange={e=>setForm({...form,documentId:e.target.value})}><option value="">Выберите документ</option>{data.candidates.find((l:any)=>l.id===form.leadId)?.documents.map((d:any)=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label>{[['contractNumber','Номер договора'],['car','Марка и модель'],['year','Год выпуска'],['vin','VIN / номер кузова, если известен'],['total','Итоговая стоимость договора, ₽'],['deposit','Обеспечительный взнос, ₽'],['commission','Комиссия дилера, ₽'],['other','Иные собственные вознаграждения, ₽'],['excluded','Исключить из базы, ₽'],['exclusionReason','Обоснование исключения и документы'],['dealerTax','Налоговый режим дилера (справочно)']].map(([k,label])=><label key={k}>{label}<input className="dw-input" required={['contractNumber','car','year','total','deposit','commission'].includes(k)} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="dw-primary mt-4" disabled={busy||!form.leadId}>Сохранить расчёт</button></form>{owner&&book.specs.filter(s=>s.excludedMinor&&!s.exclusionApprovedBy).map(s=><div className="dw-row" key={s.leadId}><span>{s.car}: исключение {money(s.excludedMinor)} · {s.exclusionReason}</span><button disabled={busy} onClick={()=>void action({action:'exclusion',leadId:s.leadId,version:s.version})}>Подтвердить исключение</button></div>)}</details>
 {data.errors?.length>0&&<p className="dw-card">Нужна проверка начислений по заявкам: {data.errors.join(', ')}. Ошибочные суммы не начислены.</p>}
 <section className="dw-card mb-5"><h2>Договоры и начисления</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Договор / автомобиль','Месяц','База','Ставка','АвтоЦена',...(owner?['Действия']:[])].map(h=><th className="p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{charges.map(c=><tr className="border-t border-[var(--ac-border)]" key={c.id}><td className="p-3">{c.contractNumber} · {c.car} {c.year}{c.reverses&&' · корректировка'}</td><td className="p-3">{c.period}</td><td className="p-3 whitespace-nowrap">{money(c.baseMinor)}</td><td className="p-3">{c.percent}%</td><td className="p-3 whitespace-nowrap">{money(c.amountMinor)}</td>{owner&&<td>{!c.reverses&&!book.charges.some(r=>r.reverses===c.id)&&<button disabled={busy} onClick={()=>{const reason=prompt('Основание подтверждённой отмены сделки:');if(reason)void action({action:'reverse',chargeId:c.id,reason});}}>Оформить отмену</button>}</td>}</tr>)}</tbody></table></div>{!charges.length&&<p className="dw-muted py-4">Подтверждённые договоры появятся здесь автоматически.</p>}</section>
 <section className="dw-card"><h2>Счета и документы</h2><p className="dw-muted my-3">Счёт за завершённый месяц — со сроком оплаты до конца 1-го числа следующего месяца. Проект акта требует подписания и не заменяет чек или УПД.</p>{invoices.map(i=><div className="dw-row flex-wrap gap-3" key={i.id}><div><strong>{i.period} · {money(i.amountMinor)}</strong><p>Остаток: {money(invoiceBalance(book,i))} · до {i.dueDate}{i.status==='draft'?' · ожидает настройки НДС':''}</p></div><div className="flex flex-wrap gap-3"><button onClick={()=>setPreview(`/api/dealers/billing/document?dealer=${data.dealerId}&invoice=${i.id}`)}>Счёт</button><button onClick={()=>setPreview(`/api/dealers/billing/document?dealer=${data.dealerId}&invoice=${i.id}&type=act`)}>Проект акта</button>{owner&&i.status==='draft'&&<button disabled={busy} onClick={()=>void action({action:'issue',invoiceId:i.id})}>Выпустить счёт</button>}{i.status==='issued'&&invoiceBalance(book,i)>0&&<button disabled={busy||!data.paymentReady||!email} onClick={()=>void action({action:'pay',kind:'invoice',invoiceId:i.id,email})}>Оплатить онлайн</button>}{owner&&invoiceBalance(book,i)>0&&<button onClick={()=>setBank({invoiceId:i.id,amount:String(invoiceBalance(book,i)/100),reference:''})}>Учесть банковский платёж</button>}</div></div>)}<label className="block mt-4">Email для чека при онлайн-оплате<input type="email" className="dw-input" value={email} onChange={e=>setEmail(e.target.value)}/></label>{owner&&bank.invoiceId&&<form className="dw-form-grid mt-4" onSubmit={e=>{e.preventDefault();void action({action:'bank',...bank});}}><input className="dw-input" aria-label="Сумма платежа" value={bank.amount} onChange={e=>setBank({...bank,amount:e.target.value})}/><input required className="dw-input" placeholder="Уникальный номер/дата банковского документа" value={bank.reference} onChange={e=>setBank({...bank,reference:e.target.value})}/><button className="dw-primary" disabled={busy}>Подтвердить поступление</button></form>}{book.receipts.map(r=><p className="mt-3 text-sm" key={r.id}>Получено {money(r.amountMinor)} · {r.reference} · {new Date(r.at).toLocaleDateString('ru-RU')}</p>)}</section>
 <details className="dw-card mt-5"><summary>Онлайн-платежи</summary>{book.orders.map(o=><div className="dw-row" key={o.id}><span>{o.description} · {money(o.amountMinor)} · {o.status==='test_paid'?'Тестовая оплата':o.status==='paid'?'Оплачен':o.status==='canceled'?'Отменён':'Ожидает оплаты'}</span>{o.providerId&&<button disabled={busy} onClick={()=>void action({action:'check',orderId:o.id})}>Проверить оплату</button>}</div>)}</details>
 </>}
 </>}{preview&&<div className="fixed inset-0 z-[2000] bg-black/60 p-3 md:p-8" role="dialog" aria-modal="true" aria-label="Документ"><div className="relative h-full rounded-2xl bg-[var(--ac-bg)] p-3 pt-14"><button autoFocus aria-label="Закрыть документ" className="absolute right-4 top-3 rounded-full border px-3 py-1 text-2xl" onClick={()=>setPreview('')}>×</button><iframe title="Документ АвтоЦены" src={preview} className="h-full w-full"/></div></div>}</div>;
}
