'use client';
import {useEffect,useState} from 'react';
import {ReviewDeleteButton} from '../account/ReviewDeleteButton';
export function DealerReviewsManager({dealerId,onCount}:{dealerId?:string;onCount?:(n:number)=>void}){
 const [selected,setSelected]=useState(dealerId||''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setError('');setData(null);fetch(`/api/crm/reviews?dealerId=${encodeURIComponent(selected)}&page=${page}`,{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Не удалось загрузить отзывы.');return r.json();}).then(d=>{setData(d);onCount?.(d.total);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[selected,page,revision,onCount]);
 return <section className="rounded-2xl border border-[var(--ac-border)] bg-[var(--ac-surface)] p-4 md:p-6"><h2 className="text-2xl font-bold">Отзывы{data?` · ${data.total}`:''}</h2><p className="mt-2 text-sm text-[var(--ac-muted)]">Отзывы доступны для чтения всем сотрудникам. Ответ и удаление — по выданным правам.</p>{!dealerId&&data?.platform&&<label className="mt-4 grid gap-2">Компания<select aria-label="Компания" className="soft-input rounded-xl p-3" value={selected} onChange={e=>{setSelected(e.target.value);setPage(1);}}><option value="">Все дилеры</option>{data.dealers.map((d:any)=><option key={d.id} value={d.id}>{d.name} · {d.count}</option>)}</select></label>}{error?<p role="alert" className="mt-4">{error}</p>:!data?<p role="status" className="mt-4">Загружаем отзывы…</p>:!data.items.length?<p className="mt-4">Опубликованных отзывов пока нет.</p>:data.items.map((r:any)=><ReviewRow key={`${r.dealerId}:${r.id}`} review={r} refresh={()=>setRevision(n=>n+1)}/>)}{data?.pages>1&&<nav className="mt-4 flex items-center gap-4" aria-label="Страницы отзывов"><button disabled={page<=1} onClick={()=>setPage(n=>n-1)}>Назад</button><span>{data.page} / {data.pages}</span><button disabled={page>=data.pages} onClick={()=>setPage(n=>n+1)}>Далее</button></nav>}</section>;
}
function ReviewRow({review:r,refresh}:{review:any;refresh:()=>void}){const [text,setText]=useState(r.reply?.text||''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <article className="mt-4 rounded-xl border border-[var(--ac-border)] bg-[var(--ac-surface-2)] p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{r.author} · {Number(r.rating).toFixed(1)} ★</strong><time>{new Date(r.createdAt).toLocaleDateString('ru-RU')}</time></div><a className="mt-1 block text-sm underline" href={`/dealers/${r.dealerId}#reviews`}>{r.dealerName}</a><p className="mt-3 whitespace-pre-wrap break-words">{r.text}</p>{r.reply&&<blockquote className="mt-3 border-l-2 pl-3"><strong>Ответ компании</strong><p className="whitespace-pre-wrap break-words">{r.reply.text}</p></blockquote>}{r.canReply&&<form className="mt-4 grid gap-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const response=await fetch(`/api/dealers/${r.dealerId}/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:r.id,text})});const d=await response.json();if(!response.ok)throw Error(d.error||'Не удалось сохранить ответ.');refresh();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить ответ.');}finally{setBusy(false);}}}><label>Ответ компании<textarea className="soft-input mt-2 block w-full rounded-xl p-3" minLength={3} maxLength={3000} required value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={busy} className="justify-self-start rounded-xl bg-[var(--ac-surface)] px-4 py-2">{busy?'Сохраняем…':r.reply?'Сохранить ответ':'Ответить'}</button></form>}{error&&<p role="alert">{error}</p>}<ReviewDeleteButton dealerId={r.dealerId} reviewId={r.id} allowed={r.canDelete} onDeleted={refresh}/></article>;}
