'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
export function DealerAccessEditor({dealerId}:{dealerId:string}){
 const [users,setUsers]=useState<{id:string;name:string;username:string;approved:boolean;status?:string}[]>([]),[username,setUsername]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch(`/api/crm/dealers/${dealerId}/access`);if(r.ok)setUsers((await r.json()).users);else setMessage('Не удалось загрузить список доступов');}
 useEffect(()=>{void load().catch(()=>setMessage('Не удалось загрузить список доступов'));},[dealerId]);
 async function save(name:string,approved:boolean){if(!confirm(approved?'Открыть сотруднику кабинет этой компании?':'Отключить доступ сотрудника к кабинету?'))return;setBusy(true);try{const r=await fetch(`/api/crm/dealers/${dealerId}/access`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,approved})});const body=await r.json();if(!r.ok)throw Error(body.error);await load();setMessage('Доступ сохранён. Сотруднику нужно войти заново.');setUsername('');}catch(e){setMessage(e instanceof Error?e.message:'Не удалось сохранить');}finally{setBusy(false);}}
 return <details className="mt-6 rounded-2xl border border-[var(--ac-border)] p-5"><summary className="cursor-pointer font-bold">Доступ сотрудников дилера</summary><p className="my-4 text-sm text-[var(--ac-muted)]">Сотрудник получает доступ только к этой компании после вашего подтверждения. Компания также должна иметь статус «Проверен АвтоЦена».</p><Link href={`/crm/managers/new?dealer=${encodeURIComponent(dealerId)}`} className="text-sm text-red-400 underline">Создать сотрудника с ролью «Дилер — только свой кабинет» →</Link><div className="my-4 flex flex-wrap gap-3"><input aria-label="Telegram username дилера" value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username" className="soft-input min-w-0 rounded-xl px-4 py-3"/><button disabled={busy||!username} className="rounded-xl bg-red-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-50" onClick={()=>void save(username,true)}>Подтвердить доступ</button></div>{users.map(u=><div key={u.id} className="my-2 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[var(--ac-bg)] p-3"><span>{u.name} · @{u.username}<small className="ml-2">{u.approved?'Подтверждён':'Ожидает подтверждения'}{u.status==='disabled'?' · аккаунт отключён':''}</small></span><button disabled={busy} className="text-sm text-red-400" onClick={()=>void save(u.username,!u.approved)}>{u.approved?'Отключить':'Подтвердить'}</button></div>)}<p role="status" className="mt-3 text-sm">{message}</p><p className="mt-3 text-xs text-[var(--ac-muted)]">Вход дилера: avtocena.com/dealer-cabinet. Аналитика платформы и другие компании ему недоступны.</p></details>;
}
