export const BILLING_POLICY='dealer-2026-10-07-v2';
export type TaxRate='none'|0|5|7|10|22;
export type BillingConfig={version:number;tax:TaxRate|null;taxBasis:string;confirmedBy:string;confirmedAt:string};
export const EMPTY_CONFIG:BillingConfig={version:0,tax:'none',taxBasis:'УСН. Без НДС. Подтверждено владельцем 07.10.2026.',confirmedBy:'owner_instruction_2026-10-07',confirmedAt:'2026-10-07T10:47:09.000Z'};
export type DealSpec={leadId:string;documentId:string;contractNumber:string;car:string;year:number;vin:string;totalMinor:number;depositMinor:number;commissionMinor:number;otherMinor:number;excludedMinor:number;exclusionReason:string;dealerTax:string;version:number;updatedAt:string;updatedBy:string;digest:string;lockedAt?:string;exclusionApprovedBy?:string;exclusionApprovedAt?:string};
export type Charge={id:string;leadId:string;documentId:string;contractNumber:string;car:string;year:number;vin:string;totalMinor:number;baseMinor:number;amountMinor:number;percent:number;period:string;serviceAt:string;createdAt:string;spec:DealSpec;agreementDigest:string;tax:TaxRate|null;taxBasis:string;reverses?:string;reason?:string};
export type Invoice={id:string;number:string;period:string;createdAt:string;dueDate:string;chargeIds:string[];amountMinor:number;tax:TaxRate|null;vatMinor:number|null;taxBasis:string;dealer:{name:string;inn:string;ogrn:string;address:string};issuer:{name:string;inn:string;ogrnip:string;correspondenceAddress:string;account:string;bank:string;bik:string;correspondent:string};status:'draft'|'issued';revision:number};
export type PaymentOrder={id:string;kind:'subscription'|'invoice';invoiceId?:string;months?:number;amountMinor:number;description:string;tax:TaxRate;vatMinor:number;email:string;createdAt:string;attemptAt?:string;providerId?:string;confirmationUrl?:string;status:'new'|'pending'|'paid'|'canceled'|'test_paid';paidAt?:string;appliedAt?:string;test?:boolean};
export type Receipt={id:string;invoiceId:string;amountMinor:number;at:string;reference:string;actorId:string;providerId?:string};
export type BillingBook={version:number;specs:DealSpec[];charges:Charge[];invoices:Invoice[];orders:PaymentOrder[];receipts:Receipt[];audit:{at:string;actorId:string;action:string;id:string}[]};
export const emptyBook=():BillingBook=>({version:0,specs:[],charges:[],invoices:[],orders:[],receipts:[],audit:[]});
export function minor(raw:unknown){const s=String(raw??'').replace(/[\s\u00a0]/g,'').replace(',','.');if(!/^\d{1,10}(\.\d{1,2})?$/.test(s))throw Error('Введите сумму в рублях, не более двух знаков после запятой');const [r,c='']=s.split('.');const n=Number(r)*100+Number(c.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n>100000000000)throw Error('Слишком большая сумма');return n;}
export const rub=(n:number)=>(n/100).toFixed(2);
export function monthKey(at:string|Date){const d=new Date(at);if(!Number.isFinite(d.getTime()))throw Error('Неверная дата');return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Krasnoyarsk',year:'numeric',month:'2-digit'}).format(d);}
export function dueDate(period:string){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(period))throw Error('Неверный период');const [y,m]=period.split('-').map(Number);return `${m===12?y+1:y}-${String(m===12?1:m+1).padStart(2,'0')}-01`;}
export function vatIncluded(amount:number,tax:TaxRate|null){if(tax===null)return null;return tax==='none'?0:Math.round(amount*tax/(100+tax));}
export function commissionMinor(base:number,percent:number){if(!Number.isSafeInteger(base)||base<0||![10,15].includes(percent))throw Error('Некорректная база или ставка комиссии');return Math.round(base*percent/100);}
export function basis(spec:DealSpec){const gross=spec.depositMinor+spec.commissionMinor+spec.otherMinor;if([spec.depositMinor,spec.commissionMinor,spec.otherMinor,spec.excludedMinor].some(n=>!Number.isSafeInteger(n)||n<0))throw Error('Некорректная сумма');if(spec.excludedMinor>gross)throw Error('Исключение превышает базу');if(spec.excludedMinor&&!spec.exclusionApprovedBy)throw Error('Исключение из базы ожидает проверки АвтоЦеной');return gross-spec.excludedMinor;}
export function invoiceBalance(book:BillingBook,invoice:Invoice){return invoice.amountMinor-book.receipts.filter(r=>r.invoiceId===invoice.id).reduce((a,r)=>a+r.amountMinor,0);}
export function eligibleProviderPayment(order:PaymentOrder,p:any,shopId:string,test:boolean){return !!order.providerId&&p?.id===order.providerId&&p.status==='succeeded'&&p.paid===true&&p.test===test&&p.amount?.currency==='RUB'&&p.amount?.value===rub(order.amountMinor)&&p.metadata?.orderId===order.id&&String(p.recipient?.account_id)===shopId;}
