import {mutateDataJson} from '../../data';
import {EMPTY_MEMBERSHIP,addMonths,type Membership} from '../program-model';
import {readBook,mutateBook} from './store';
import {eligibleProviderPayment,rub,type PaymentOrder} from './model';
export function paymentConfiguration(){const shop=process.env.DEALER_YOOKASSA_SHOP_ID,secret=process.env.DEALER_YOOKASSA_SECRET;return {shop,secret,test:process.env.DEALER_PAYMENTS_MODE!=='live',ready:process.env.DEALER_PAYMENTS_ENABLED==='1'&&!!shop&&!!secret&&process.env.DEALER_RECEIPTS_CONFIRMED==='1'&&(process.env.DEALER_PAYMENTS_MODE!=='live'||process.env.DEALER_FISCAL_FLOW_CONFIRMED==='1')};}
async function api(path:string,method='GET',body?:unknown,key?:string){const c=paymentConfiguration();if(!c.ready)throw Error('Онлайн-оплата ещё не подключена. Счёт доступен в кабинете');const response=await fetch(`https://api.yookassa.ru/v3/${path}`,{method,headers:{Authorization:`Basic ${Buffer.from(c.shop+':'+c.secret).toString('base64')}`,'Content-Type':'application/json',...(key?{'Idempotence-Key':key}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Провайдер не подтвердил операцию. Повторите проверку позже');return response.json();}
const vatCode=(tax:PaymentOrder['tax'])=>({'none':1,'0':2,'5':7,'7':8,'10':3,'22':11}[String(tax)]);
export async function startPayment(id:string,orderId:string){let order!:PaymentOrder;await mutateBook(id,b=>{const o=b.orders.find(o=>o.id===orderId);if(!o)throw Error('Платёж не найден');order=o;if(o.status==='paid'||o.status==='canceled'||o.status==='test_paid')throw Error('Платёж уже завершён');if(o.providerId)return b;if(o.attemptAt&&Date.now()-Date.parse(o.attemptAt)>23*3600000)throw Error('Нужна сверка незавершённой попытки с провайдером. Новый платёж не создаётся');order={...o,attemptAt:o.attemptAt||new Date().toISOString()};return {...b,orders:b.orders.map(x=>x.id===orderId?order:x)};});if(order.confirmationUrl)return order.confirmationUrl;if(order.providerId)throw Error('Платёж создан. Проверьте его статус перед повторной оплатой');
 const payment=await api('payments','POST',{amount:{value:rub(order.amountMinor),currency:'RUB'},capture:true,description:order.description,metadata:{dealerId:id,orderId},confirmation:{type:'redirect',return_url:`https://avtocena.com/dealer-cabinet/billing?payment=${orderId}`},receipt:{customer:{email:order.email},items:[{description:order.description,quantity:'1.00',amount:{value:rub(order.amountMinor),currency:'RUB'},vat_code:vatCode(order.tax),payment_subject:'service',payment_mode:order.kind==='subscription'?'full_prepayment':'full_payment'}]}},order.id);
 const url=String(payment.confirmation?.confirmation_url||'');if(!/^[a-f0-9-]{20,64}$/.test(payment.id)||payment.test!==paymentConfiguration().test)throw Error('Режим платежа не совпадает с настройками магазина');if(url){const u=new URL(url);if(u.protocol!=='https:'||!(u.hostname==='yoomoney.ru'||u.hostname.endsWith('.yoomoney.ru')||u.hostname==='yookassa.ru'||u.hostname.endsWith('.yookassa.ru')))throw Error('Неожиданный адрес платёжной страницы');}
 await mutateBook(id,b=>({...b,orders:b.orders.map(o=>o.id===orderId?{...o,providerId:payment.id,status:'pending',confirmationUrl:url,test:payment.test}:o)}));if(!url)throw Error('Платёж создан. Проверьте его статус перед повторной оплатой');return url;
}
async function applySubscription(id:string,o:PaymentOrder){await mutateDataJson<Membership>(`dealers/memberships/${id}.json`,EMPTY_MEMBERSHIP,m=>{if(m.history.some(h=>h.id===o.id))return m;if(![1,6,12].includes(o.months||0))throw Error('Неизвестный период');const start=new Date(Math.max(Date.now(),Date.parse(m.paidUntil)||0,Date.parse(m.trialEndsAt)||0));return {...m,version:m.version+1,plan:'subscription',paidUntil:addMonths(start,o.months!).toISOString(),history:[...m.history,{id:o.id,at:o.paidAt!,actorId:'payment_provider',months:o.months!,amountRub:o.amountMinor/100,note:`ЮKassa ${o.providerId}`} ]};});}
export async function checkPayment(id:string,orderId:string){const book=await readBook(id),o=book.orders.find(x=>x.id===orderId);if(!o?.providerId)throw Error('Платёж не найден');const p=await api(`payments/${encodeURIComponent(o.providerId)}`),c=paymentConfiguration();if(p.metadata?.dealerId!==id||p.metadata?.orderId!==orderId||p.id!==o.providerId)throw Error('Платёж не соответствует счёту');
 if(p.status==='canceled'){await mutateBook(id,b=>({...b,orders:b.orders.map(x=>x.id===o.id&&x.status!=='paid'?{...x,status:'canceled'}:x)}));return 'canceled';}
 if(p.status!=='succeeded')return 'pending';if(!eligibleProviderPayment(o,p,c.shop!,c.test))throw Error('Не совпадают сумма, валюта, магазин или режим платежа');
 // Test payments never activate production access or settle real invoices.
 if(c.test){await mutateBook(id,b=>({...b,orders:b.orders.map(x=>x.id===o.id?{...x,status:'test_paid',test:true}:x)}));return 'test_succeeded';}
 const paidAt=String(p.captured_at||new Date().toISOString());await mutateBook(id,b=>{const current=b.orders.find(x=>x.id===o.id)!;const receipts=current.invoiceId&&!b.receipts.some(r=>r.id===o.id)?[...b.receipts,{id:o.id,invoiceId:current.invoiceId,amountMinor:current.amountMinor,at:paidAt,reference:`ЮKassa ${p.id}`,providerId:p.id,actorId:'payment_provider'}]:b.receipts;return {...b,receipts,orders:b.orders.map(x=>x.id===o.id?{...x,status:'paid',paidAt:x.paidAt||paidAt}:x)};});
 if(o.kind==='subscription')await applySubscription(id,{...o,paidAt});await mutateBook(id,b=>({...b,orders:b.orders.map(x=>x.id===o.id?{...x,appliedAt:x.appliedAt||new Date().toISOString()}:x)}));return 'paid';
}
