import PDFDocument from 'pdfkit';
import {existsSync} from 'node:fs';
import path from 'node:path';
import type {BillingBook,Invoice} from './model';
const money=(n:number)=>(n/100).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})+' ₽';
export async function billingPdf(invoice:Invoice,book:BillingBook,act=false){const pub=existsSync(path.join(process.cwd(),'public/fonts/DejaVuSans.ttf'))?path.join(process.cwd(),'public'):path.join(process.cwd(),'apps/web/public');const doc=new PDFDocument({size:'A4',margins:{top:45,bottom:50,left:45,right:45},font:path.join(pub,'fonts/DejaVuSans.ttf')});const chunks:Buffer[]=[];const done=new Promise<Buffer>((resolve,reject)=>{doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);});
 const line=(text:string,bold=false)=>{doc.fontSize(bold?13:10).fillColor('#171717').text(text,{width:500,lineGap:3});doc.moveDown(.6);};
 line(act?'Проект акта оказанных услуг':invoice.status==='draft'?'Предварительный расчёт — НДС не подтверждён':'Счёт на оплату',true);line(`№ ${invoice.number} · ${new Date(invoice.createdAt).toLocaleDateString('ru-RU',{timeZone:'Asia/Krasnoyarsk'})}`);line(`Исполнитель: ${invoice.issuer.name}\nИНН ${invoice.issuer.inn}, ОГРНИП ${invoice.issuer.ogrnip}\n${invoice.issuer.correspondenceAddress}`);line(`Заказчик: ${invoice.dealer.name}\nИНН ${invoice.dealer.inn}, ОГРН/ОГРНИП ${invoice.dealer.ogrn}\n${invoice.dealer.address}`);line(`Услуги доступа и привлечения обращений с подтверждёнными договорами за ${invoice.period}. Срок оплаты: ${invoice.dueDate} включительно.`);
 for(const id of invoice.chargeIds){const c=book.charges.find(c=>c.id===id);if(!c)continue;line(`${c.reverses?'Корректировка':'Договор'} № ${c.contractNumber}: ${c.car}, ${c.year}${c.vin?', VIN / кузов '+c.vin:''}\nБаза ${money(c.baseMinor)} × ${c.percent}% = ${money(c.amountMinor)}${c.reason?'\nОснование: '+c.reason:''}`);}
 line(`Итого: ${money(invoice.amountMinor)}`,true);line(invoice.tax===null?'НДС: ожидает подтверждения':invoice.tax==='none'?`Без НДС. ${invoice.taxBasis}`:`В том числе НДС ${invoice.tax}%: ${money(invoice.vatMinor||0)}. ${invoice.taxBasis}`);
 if(!act)line(`Банк: ${invoice.issuer.bank}\nБИК ${invoice.issuer.bik}\nР/с ${invoice.issuer.account}\nК/с ${invoice.issuer.correspondent}\nНазначение: оплата услуг АвтоЦены по счёту ${invoice.number}`);
 else{line('Количество услуг: '+invoice.chargeIds.length+'; единица измерения — услуга по договору.');line('Исполнитель: ИП Молодых А. В. __________________\nЗаказчик: должность, ФИО уполномоченного лица __________________\nПодпись __________________');line('Проект сформирован автоматически. Требуется проверка и подписание сторонами. Не является подписанным актом, УПД, счётом-фактурой или кассовым чеком.');}doc.end();return done;}
