import {createHash,randomUUID} from 'node:crypto';
import {readDataJson,mutateDataJson,readChunkedDataJson} from '../../data';
import {validDealerId,readShowcase} from '../showcase-store';
import {readMembership} from '../program-store';
import {confirmedCustomerContract} from '../../account/access';
import {leadDealerId} from '../lead-routing';
import {OPERATOR} from '../../privacy-documents';
import {BILLING_POLICY,emptyBook,EMPTY_CONFIG,minor,monthKey,dueDate,basis,commissionMinor,vatIncluded,invoiceBalance,type BillingBook,type BillingConfig,type DealSpec,type Invoice,type PaymentOrder} from './model';
const key=(id:string)=>{if(!validDealerId(id))throw Error('Компания не найдена');return `dealers/billing/${id}.json`;};
export const readBook=(id:string)=>readDataJson<BillingBook>(key(id),emptyBook());
export const mutateBook=(id:string,fn:(b:BillingBook)=>BillingBook)=>mutateDataJson<BillingBook>(key(id),emptyBook(),b=>{const next=fn(b);if(next===b)return b;return {...next,version:b.version+1};});
export const readBillingConfig=()=>readDataJson<BillingConfig>('dealers/billing-config.json',EMPTY_CONFIG);
export async function saveBillingConfig(raw:any,actorId:string){if(!['none',0,5,7,10,22].includes(raw.tax)||!String(raw.taxBasis||'').trim())throw Error('Выберите подтверждённую ставку и основание');return mutateDataJson<BillingConfig>('dealers/billing-config.json',EMPTY_CONFIG,c=>{if(c.version!==raw.version)throw Error('Настройки изменились');return {version:c.version+1,tax:raw.tax,taxBasis:String(raw.taxBasis).trim().slice(0,500),confirmedBy:actorId,confirmedAt:new Date().toISOString()};});}
function audit(b:BillingBook,actorId:string,action:string,id:string){return [...b.audit,{actorId,action,id,at:new Date().toISOString()}];}
export async function saveSpec(dealerId:string,raw:any,actorId:string){
 const lead=(await readChunkedDataJson<any>('leads/leads.json',[])).find(l=>l.id===raw.leadId&&leadDealerId(l)===dealerId&&!l.archivedAt);if(!lead?.platformTerms?.agreementDigest||lead.platformTerms.agreementVersion!==BILLING_POLICY)throw Error('Заявка должна быть раскрыта по новой редакции условий взаиморасчётов');
 if(!lead.dealerContactResult)throw Error('Сначала сохраните результат общения');
 const client=(await readChunkedDataJson<any>(`dealers/${dealerId}/clients.json`,[])).find(c=>c.id===lead.clientId);const doc=client?.documents?.find((d:any)=>d.id===raw.documentId&&!d.deletedAt&&!d.purgeToken);if(!doc)throw Error('Прикрепите договор к клиенту и выберите его');
 if(confirmedCustomerContract(client,lead.id))throw Error('Подтверждённый договор нельзя переписать. Обратитесь в АвтоЦену для корректировки');
 const car=String(raw.car||'').trim(),contractNumber=String(raw.contractNumber||'').trim(),year=Number(raw.year),vin=String(raw.vin||'').trim();
 if(!car||car.length>200||!contractNumber||contractNumber.length>100||!Number.isInteger(year)||year<1950||year>new Date().getUTCFullYear()+1||vin.length>40)throw Error('Укажите автомобиль, год и номер договора');
 const values={totalMinor:minor(raw.total),depositMinor:minor(raw.deposit),commissionMinor:minor(raw.commission),otherMinor:minor(raw.other),excludedMinor:minor(raw.excluded)};
 if(!values.totalMinor||values.depositMinor+values.commissionMinor+values.otherMinor>values.totalMinor||values.excludedMinor>values.depositMinor+values.commissionMinor+values.otherMinor)throw Error('Проверьте итог договора и состав платежей');
 const exclusionReason=String(raw.exclusionReason||'').trim().slice(0,2000);if(values.excludedMinor&&!exclusionReason)throw Error('Обоснуйте исключение из базы и укажите подтверждающие документы');
 return mutateBook(dealerId,b=>{if(b.charges.some(c=>c.leadId===lead.id&&!c.reverses))throw Error('Начисление уже зафиксировано');const old=b.specs.find(s=>s.leadId===lead.id);if(old?.lockedAt)throw Error('Расчёт уже передан на подтверждение. Для исправления обратитесь в АвтоЦену');if(b.specs.some(s=>s.leadId!==lead.id&&(s.documentId===doc.id||s.contractNumber===contractNumber)))throw Error('Этот договор уже связан с другой заявкой');if((old?.version||0)!==raw.version)throw Error('Расчёт изменился. Обновите страницу');
 const s:DealSpec={leadId:lead.id,documentId:doc.id,contractNumber,car,year,vin,...values,exclusionReason,dealerTax:String(raw.dealerTax||'Не указан').slice(0,100),version:(old?.version||0)+1,updatedAt:new Date().toISOString(),updatedBy:actorId,digest:''};s.digest=createHash('sha256').update(JSON.stringify(s)).digest('hex');
 return {...b,specs:[...b.specs.filter(x=>x.leadId!==lead.id),s],audit:audit(b,actorId,'spec_saved',lead.id)};});
}
export async function approveExclusion(id:string,leadId:string,version:number,actorId:string){return mutateBook(id,b=>{const s=b.specs.find(x=>x.leadId===leadId);if(!s||s.version!==version||!s.excludedMinor||b.charges.some(c=>c.leadId===leadId))throw Error('Расчёт изменился или уже начислен');return {...b,specs:b.specs.map(x=>x===s?{...x,exclusionApprovedBy:actorId,exclusionApprovedAt:new Date().toISOString()}:x),audit:audit(b,actorId,'exclusion_approved',leadId)};});}
export async function requireSpec(id:string,lead:any,documentId:string,lock=false){if(lead.platformTerms?.agreementVersion!==BILLING_POLICY)return null;let saved!:DealSpec;await mutateBook(id,b=>{const s=b.specs.find(x=>x.leadId===lead.id&&x.documentId===documentId);if(!s)throw Error('Дилеру нужно заполнить автомобиль и расчёт договора в разделе «Взаиморасчёты»');basis(s);if(!lock){saved=s;return b;}saved={...s,lockedAt:s.lockedAt||new Date().toISOString()};return s.lockedAt?b:{...b,specs:b.specs.map(x=>x===s?saved:x)};});return saved;}
export async function captureSignedDeal(id:string,leadId:string){
 const [leads,clients,m,config]=await Promise.all([readChunkedDataJson<any>('leads/leads.json',[]),readChunkedDataJson<any>(`dealers/${id}/clients.json`,[]),readMembership(id),readBillingConfig()]);
 const lead=leads.find(l=>l.id===leadId&&leadDealerId(l)===id);if(lead?.platformTerms?.agreementVersion!==BILLING_POLICY)return;
 const client=clients.find(c=>c.id===lead.clientId),contract=confirmedCustomerContract(client,leadId);if(!contract?.customerConfirmedAt)return;
 const agreement=[m.agreement,...(m.agreementHistory||[])].find(a=>a?.digest===lead.platformTerms.agreementDigest&&a.approvedAt);if(!agreement)throw Error('Не найдены принятые условия заявки');
 return mutateBook(id,b=>{if(b.charges.some(c=>c.id===`deal_${leadId}`))return b;const s=b.specs.find(x=>x.leadId===leadId&&x.documentId===contract.documentId);if(!s||s.digest!==contract.financialDigest)throw Error('Расчёт договора изменился; требуется проверка');const base=basis(s),at=new Date().toISOString();let period=monthKey(contract.customerConfirmedAt);if(b.invoices.some(i=>i.period===period))period=monthKey(at);
 const charge={id:`deal_${leadId}`,leadId,documentId:s.documentId,contractNumber:s.contractNumber,car:s.car,year:s.year,vin:s.vin,totalMinor:s.totalMinor,baseMinor:base,percent:lead.platformTerms.percent,amountMinor:commissionMinor(base,lead.platformTerms.percent),period,serviceAt:contract.customerConfirmedAt,createdAt:at,spec:structuredClone(s),agreementDigest:agreement.digest,tax:config.tax,taxBasis:config.taxBasis};
 return {...b,charges:[...b.charges,charge],audit:audit(b,'system','signed_deal_accrued',leadId)};});
}
export async function reverseCharge(id:string,chargeId:string,reason:string,actorId:string){if(reason.trim().length<5)throw Error('Укажите основание отмены');return mutateBook(id,b=>{const c=b.charges.find(x=>x.id===chargeId&&!x.reverses);if(!c)throw Error('Начисление не найдено');if(b.charges.some(x=>x.reverses===c.id))return b;const at=new Date().toISOString();return {...b,charges:[...b.charges,{...c,id:`reverse_${c.id}`,reverses:c.id,period:monthKey(at),amountMinor:-c.amountMinor,baseMinor:-c.baseMinor,createdAt:at,reason:reason.trim().slice(0,2000)}],audit:audit(b,actorId,'charge_reversed',c.id)};});}
export async function closePeriods(id:string,now=new Date()){
 const m=await readMembership(id);if(!m.agreement)return readBook(id);
 return mutateBook(id,b=>{const billed=new Set(b.invoices.flatMap(i=>i.chargeIds));const pending=b.charges.filter(c=>c.period<monthKey(now)&&!billed.has(c.id));if(!pending.length)return b;
 const groups=new Map<string,typeof pending>();for(const c of pending){const group=`${c.period}_${c.tax??'unknown'}`;groups.set(group,[...(groups.get(group)||[]),c]);}
 const invoices=[...groups.entries()].map(([group,charges])=>{const period=charges[0].period,tax=charges[0].tax??null,amount=charges.reduce((a,c)=>a+c.amountMinor,0),a=m.agreement!,suffix=b.invoices.filter(i=>i.period===period).length+1;
 return {id:`month_${group}_${suffix}`,number:`AC-${id}-${group}-${suffix}`,period,createdAt:now.toISOString(),dueDate:dueDate(period),chargeIds:charges.map(c=>c.id),amountMinor:amount,tax,vatMinor:vatIncluded(amount,tax),taxBasis:[...new Set(charges.map(c=>c.taxBasis))].filter(Boolean).join('; '),dealer:{name:a.legalName,inn:a.inn,ogrn:a.ogrn,address:a.address},issuer:{...OPERATOR},status:tax===null?'draft':'issued',revision:1} as Invoice;});return {...b,invoices:[...b.invoices,...invoices]};});
}
export async function issueDraftInvoice(id:string,invoiceId:string,actorId:string){const c=await readBillingConfig();if(c.tax===null)throw Error('Сначала подтвердите НДС АвтоЦены');return mutateBook(id,b=>({...b,invoices:b.invoices.map(i=>i.id===invoiceId&&i.status==='draft'?{...i,status:'issued',tax:c.tax,vatMinor:vatIncluded(i.amountMinor,c.tax),taxBasis:c.taxBasis,revision:i.revision+1}:i),audit:audit(b,actorId,'invoice_issued',invoiceId)}));}
export async function recordBankPayment(id:string,invoiceId:string,raw:unknown,reference:string,actorId:string){const amount=minor(raw);if(!amount||reference.trim().length<3)throw Error('Укажите сумму и уникальный номер банковского платежа');return mutateBook(id,b=>{if(b.receipts.some(r=>r.reference===reference.trim()))throw Error('Такой банковский платёж уже учтён');const i=b.invoices.find(i=>i.id===invoiceId&&i.status==='issued');if(!i||amount>invoiceBalance(b,i))throw Error('Проверьте остаток счёта');if(b.orders.some(o=>o.invoiceId===i.id&&['new','pending'].includes(o.status)))throw Error('Сначала завершите проверку онлайн-платежа');return {...b,receipts:[...b.receipts,{id:randomUUID(),invoiceId,amountMinor:amount,reference:reference.trim().slice(0,200),actorId,at:new Date().toISOString()}],audit:audit(b,actorId,'bank_payment',invoiceId)};});}
export async function newOrder(id:string,raw:any){const [config,m]=await Promise.all([readBillingConfig(),readMembership(id)]);if(!m.agreement?.approvedAt)throw Error('Сначала подтвердите подключение');if(config.tax===null)throw Error('Налоговые настройки АвтоЦены ещё не подтверждены');const email=String(raw.email||'').trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>200)throw Error('Укажите email для чека');let saved!:PaymentOrder;
 await mutateBook(id,b=>{const pending=b.orders.find(o=>['new','pending'].includes(o.status)&&o.kind===raw.kind&&(o.kind==='subscription'||o.invoiceId===raw.invoiceId));if(pending){saved=pending;return b;}
 const months=Number(raw.months),i=b.invoices.find(i=>i.id===raw.invoiceId&&i.status==='issued');let amount:number;
 if(raw.kind==='subscription'){if(![1,6,12].includes(months))throw Error('Выберите срок тарифа');amount=(months===1?10000:months===6?50000:100000)*100;}
 else if(raw.kind==='invoice'&&i){amount=invoiceBalance(b,i);if(amount<=0)throw Error('Счёт уже оплачен или содержит кредит');}else throw Error('Счёт не найден');
 const tax=raw.kind==='invoice'?i!.tax:config.tax;if(tax===null)throw Error('НДС не подтверждён');saved={id:randomUUID(),kind:raw.kind,months:raw.kind==='subscription'?months:undefined,invoiceId:raw.kind==='invoice'?i!.id:undefined,amountMinor:amount,description:raw.kind==='subscription'?`Доступ к АвтоЦене на ${months} мес.`:`Услуги АвтоЦены за ${i!.period}`,tax,vatMinor:vatIncluded(amount,tax)!,email,createdAt:new Date().toISOString(),status:'new'};return {...b,orders:[...b.orders,saved]};});return saved;
}
