"use client";
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {ANALYTICS_EVENT,analyticsChoice,setAnalyticsChoice} from '@/lib/privacy-consent';
import {isPublicPagePath} from '@/lib/public-page-url';
export function AnalyticsChoiceNotice(){
 const pathname=usePathname(),[visible,setVisible]=useState(false),[settings,setSettings]=useState(false),[allowAnalytics,setAllowAnalytics]=useState(true);
 useEffect(()=>{const sync=()=>setVisible(analyticsChoice()===null);sync();window.addEventListener(ANALYTICS_EVENT,sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener(ANALYTICS_EVENT,sync);window.removeEventListener('storage',sync);};},[pathname]);
 if(!visible||!isPublicPagePath(pathname)||pathname.startsWith('/privacy/request'))return null;
 return createPortal(<div data-nosnippet="" role="complementary" className="ac-analytics-choice" aria-label="Выбор аналитики">
 <div className="ac-analytics-choice-row"><span className="ac-analytics-icon" aria-hidden="true">🛸</span><p>С вашего согласия используем <button className="ac-analytics-settings" type="button" aria-expanded={settings} aria-controls="ac-analytics-options" onClick={()=>setSettings(!settings)}>Настройки</button>{' '}<Link href="/cookies" target="_blank">cookie</Link><br />Яндекс Метрики, чтобы делать сайт удобнее.</p><button className="ac-analytics-accept" type="button" onClick={()=>setAnalyticsChoice(allowAnalytics)}>ХОРОШО</button></div>
 {settings&&<div id="ac-analytics-options"><p>Аналитика помогает оценить посещения и результаты заявок.</p><div className="ac-analytics-options-row"><button type="button" className="ac-analytics-decline" onClick={()=>setAnalyticsChoice(allowAnalytics)}>Продолжить</button><div className="ac-analytics-toggle"><span aria-hidden="true">Да</span><button type="button" role="switch" aria-label="Разрешить аналитику Яндекс Метрики" aria-checked={allowAnalytics} className="ac-analytics-switch" onClick={()=>setAllowAnalytics(value=>!value)}><span /></button><span aria-hidden="true">Нет</span></div></div></div>}
 <style>{`.ac-analytics-choice{position:fixed;z-index:65;left:10px;right:10px;bottom:calc(10px + env(safe-area-inset-bottom));border-radius:14px;padding:10px 12px;border:1px solid var(--ac-border);background:var(--ac-surface,#fff);color:var(--ac-text,#202633);box-shadow:0 -2px 14px #0001;font-size:12px;line-height:1.4}.ac-analytics-choice-row{display:flex;align-items:center;gap:12px}.ac-analytics-icon{flex-shrink:0;font-size:24px;line-height:1}.ac-analytics-choice p{margin:0;flex:1;min-width:0}.ac-analytics-choice a{text-decoration:underline}.ac-analytics-choice button{font:inherit;cursor:pointer}.ac-analytics-accept{flex-shrink:0;min-height:40px;padding:8px 16px;border:0;border-radius:12px;background:#83e05b;color:#142410;font-weight:700!important}.ac-analytics-settings{display:inline;padding:0;border:0;background:transparent;color:inherit;text-decoration:underline}.ac-analytics-choice button:focus-visible{outline:2px solid currentColor;outline-offset:2px}#ac-analytics-options{margin-top:10px;padding-top:8px;border-top:1px solid var(--ac-border)}.ac-analytics-options-row{display:flex;align-items:center;flex-wrap:wrap;gap:12px 24px;margin-top:8px}.ac-analytics-toggle{display:flex;align-items:center;gap:10px;font-weight:600}.ac-analytics-switch{display:inline-flex;align-items:center;width:54px;min-width:54px;height:32px;padding:4px;border:1px solid var(--ac-border);border-radius:999px;background:var(--ac-surface-2,#ccd5df);color:inherit}.ac-analytics-switch[aria-checked=true]{background:#83e05b;border-color:#6cbe48}.ac-analytics-switch span{display:block;width:24px;height:24px;flex-shrink:0;border-radius:50%;background:#fff;box-shadow:0 1px 3px #0004;transform:translateX(20px)}.ac-analytics-switch[aria-checked=true] span{transform:translateX(0)}.ac-analytics-decline{margin-top:0;min-height:40px;padding:8px 12px;border:1px solid var(--ac-border);border-radius:10px;background:var(--ac-surface-2);color:inherit}@media(min-width:768px){.ac-analytics-choice{left:12px;right:auto;bottom:12px;width:560px;max-width:calc(100vw - 24px);border:1px solid var(--ac-border);border-radius:16px;padding:12px}}`}</style>
 </div>,document.body);
}
